CREATE TABLE [rodis_wh].[birth_fact] (
    [id_birth_fact]                                                         INT          NOT NULL,
    [cd_birth_fact]                                                         VARCHAR (50) NOT NULL,
    [id_prsn_child]                                                         INT          NULL,
    [id_prsn_mother]                                                        INT          NULL,
    [id_calendar_dim_birth_child]                                           INT          NULL,
    [qt_child_weight]                                                       INT          NULL,
    [ms_maternal_bmi]                                                       FLOAT (53)   NULL,
    [qt_child_head_circum]                                                  INT          NULL,
    [qt_paternal_age]                                                       INT          NULL,
    [qt_child_age_est_gest]                                                 INT          NULL,
    [qt_child_age_gest]                                                     INT          NULL,
    [qt_maternal_age]                                                       INT          NULL,
    [qt_maternal_height]                                                    INT          NULL,
    [qt_preconception_maternal_weight]                                      INT          NULL,
    [qt_maternal_weight]                                                    INT          NULL,
    [ms_maternal_weight_gain]                                               INT          NULL,
    [am_median_income_tract]                                                INT          NULL,
    [id_birth_administration]                                               INT          NOT NULL,
    [birth_administration_id_birth_familial_child]                          INT          NOT NULL,
    [birth_administration_child_birth_familial_id_city_current]             INT          NOT NULL,
    [birth_administration_child_birth_familial_id_city_birth]               INT          NOT NULL,
    [birth_administration_child_birth_familial_id_education]                INT          NOT NULL,
    [birth_administration_id_birth_familial_maternal]                       INT          NOT NULL,
    [birth_administration_maternal_birth_familial_id_city_current]          INT          NOT NULL,
    [birth_administration_maternal_birth_familial_id_city_birth]            INT          NOT NULL,
    [birth_administration_maternal_birth_familial_id_education]             INT          NOT NULL,
    [birth_administration_id_birth_familial_paternal]                       INT          NOT NULL,
    [birth_administration_paternal_birth_familial_id_city_current]          INT          NOT NULL,
    [birth_administration_paternal_birth_familial_id_city_birth]            INT          NOT NULL,
    [birth_administration_paternal_birth_familial_id_education]             INT          NOT NULL,
    [birth_administration_id_hospital_admission_child]                      INT          NOT NULL,
    [birth_administration_child_hospital_admission_id_payment_primary]      INT          NOT NULL,
    [birth_administration_child_hospital_admission_id_payment_secondary]    INT          NOT NULL,
    [birth_administration_id_hospital_admission_maternal]                   INT          NOT NULL,
    [birth_administration_maternal_hospital_admission_id_payment_primary]   INT          NOT NULL,
    [birth_administration_maternal_hospital_admission_id_payment_secondary] INT          NOT NULL,
    [birth_administration_id_birth_child_condition]                         INT          NOT NULL,
    [birth_administration_id_birth_child_procedure]                         INT          NOT NULL,
    [birth_administration_id_maternal_behavior]                             INT          NOT NULL,
    [birth_administration_id_maternal_condition]                            INT          NOT NULL,
    [birth_administration_id_maternal_history]                              INT          NOT NULL,
    [birth_administration_id_maternal_procedure]                            INT          NOT NULL
);

