



CREATE VIEW [dbo].[Cube_WORKER_DIM]
AS

SELECT
	WD.ID_WORKER_DIM
	,WD.ID_PRSN
	,WD.ID_WORKER_DIM_SUPERVISOR
	,WD.ID_PRSN_SPRV
	,WD.ID_RMTS_GROUP_COORD	
	,WD.ID_LOCATION_DIM_WORKER
	,IIF(WD.ID_WORKER_DIM = -1, -999, WD.CD_JOB_CLS) [CD_JOB_CLS]
	,WD.TX_JOB_CLS
	,IIF(WD.ID_WORKER_DIM = -1, -999, IIF(WD.TX_RMTS_WRKR_TYP = '-', -99, WD.CD_RMTS_WRKR_TYP)) [CD_RMTS_WRKR_TYP]
	,WD.TX_RMTS_WRKR_TYP
	,IIF(WD.ID_WORKER_DIM = -1, 'F', WD.CD_STAT) [CD_STAT]
	,WD.TX_STAT
	,WD.CD_UNT
	,WD.QT_WRK_MEASURE
	,WD.DT_BRTH
	,WD.ID_CYCLE
FROM dbo.WORKER_DIM WD





