






CREATE VIEW [dbo].[Cube_PEOPLE_DIM]
AS

SELECT
	PD.ID_PEOPLE_DIM
	,PD.ID_PRSN
	,PD.ID_WORKER_DIM_SSI_SSA_UPDATE
	,PD.TX_BRAAM_RACE
	,IIF(PD.ID_PEOPLE_DIM = -1, -999, ISNULL(PD.CD_CMBN_ETHN, -99)) [CD_CMBN_ETHN]
	,PD.TX_CMBN_ETHN
	,IIF(PD.ID_PEOPLE_DIM = -1, -999, ISNULL(PD.CD_CTZN, -99)) [CD_CTZN]
	,PD.TX_CTZN
	,IIF(PD.ID_PEOPLE_DIM = -1, 'X', IIF(PD.TX_GNDR = '-', PD.TX_GNDR, PD.CD_GNDR)) [CD_GNDR]
	,PD.TX_GNDR
	,IIF(PD.ID_PEOPLE_DIM = -1, 'F', IIF(PD.TX_HSPNC = '-', PD.TX_HSPNC, PD.CD_HSPNC)) [CD_HSPNC]
	,PD.TX_HSPNC
	,IIF(PD.ID_PEOPLE_DIM = -1, -999, ISNULL(PD.CD_LICWAC, -99)) [CD_LICWAC]
	,PD.TX_LICWAC
	,IIF(PD.ID_PEOPLE_DIM = -1, -999, ISNULL(PD.CD_LNG_PRFR, -99)) [CD_LNG_PRFR]
	,PD.TX_LNG_PRFR
	,IIF(PD.ID_PEOPLE_DIM = -1, -999, ISNULL(PD.CD_LNG_SECONDARY, -99)) [CD_LNG_SECONDARY]
	,PD.TX_LNG_SECONDARY
	,IIF(PD.ID_PEOPLE_DIM = -1, -999, ISNULL(PD.CD_LTD_ENGLISH, -99)) [CD_LTD_ENGLISH]
	,PD.TX_LTD_ENGLISH
	,IIF(PD.ID_PEOPLE_DIM = -1, -999, ISNULL(PD.CD_MRTL_STAT, -99)) [CD_MRTL_STAT]
	,PD.TX_MRTL_STAT
	,PD.TX_MULTIRACE
	,IIF(PD.ID_PEOPLE_DIM = -1, -999, ISNULL(PD.CD_RACE, -99)) [CD_RACE]
	,PD.TX_RACE
	,IIF(PD.ID_PEOPLE_DIM = -1, -999, ISNULL(PD.CD_RACE_FIVE, -99)) [CD_RACE_FIVE]
	,PD.TX_RACE_FIVE
	,IIF(PD.ID_PEOPLE_DIM = -1, -999, ISNULL(PD.CD_RACE_FOUR, -99)) [CD_RACE_FOUR]
	,PD.TX_RACE_FOUR
	,IIF(PD.ID_PEOPLE_DIM = -1, -999, ISNULL(PD.CD_RACE_THREE, -99)) [CD_RACE_THREE]
	,PD.TX_RACE_THREE
	,IIF(PD.ID_PEOPLE_DIM = -1, -999, ISNULL(PD.CD_RACE_TWO, -99)) [CD_RACE_TWO]
	,PD.TX_RACE_TWO
	,IIF(PD.ID_PEOPLE_DIM = -1, -999, ISNULL(PD.CD_RLGN, -99)) [CD_RLGN]
	,PD.TX_RLGN
	,PD.TX_SSI_SSA_STATUS
	,IIF(PD.ID_PEOPLE_DIM = -1, 'F', IIF(PD.TX_STATE_RSDNT = '-', PD.TX_STATE_RSDNT, PD.CD_STATE_RSDNT)) [CD_STATE_RSDNT]
	,PD.TX_STATE_RSDNT
	,PD.FL_ADOPTION_MATCH
	,PD.FL_DANGER_TO_WORKER
	,PD.FL_DECEASED
	,IIF(PD.FL_DT_BIRTH_ESTIMATED = ' ', '-', PD.FL_DT_BIRTH_ESTIMATED) [FL_DT_BIRTH_ESTIMATED]
	,ISNULL(PD.FL_EMOTION_DSTRBD, '-') [FL_EMOTION_DSTRBD]
	,PD.FL_ICW_INVOLVEMENT
	,ISNULL(PD.FL_MNTAL_RETARDATN, '-') [FL_MNTAL_RETARDATN]
	,ISNULL(PD.FL_OTHR_SPC_CARE, '-') [FL_OTHR_SPC_CARE]
	,PD.FL_PHYS_DISABLED
	,ISNULL(PD.FL_PRSN_MALTREATER, '-') [FL_PRSN_MALTREATER]
	,PD.FL_SEX_AGGRESIVE_YOUTH
	,ISNULL(PD.FL_TEEN_PARENT, '-') [FL_TEEN_PARENT]
	,PD.FL_VIS_HEARING_IMPR
	,PD.DT_BIRTH
	,PD.DT_DEATH
	,PD.DT_LICWAC_DETERMINATION
	,PD.MULTI_RACE_MASK
	,PD.FL_DELETED
	,ISNULL(PD.FL_EXPUNGED, '-') [FL_EXPUNGED]
	,PD.cd_race_census
	,PD.tx_race_census
	,PD.census_Hispanic_Latino_Origin_cd
FROM dbo.PEOPLE_DIM PD







