CREATE TABLE [prtl].[cache_pbcw4_aggr] (
    [qry_type]               INT            NOT NULL,
    [date_type]              INT            NOT NULL,
    [cohort_entry_date]      DATETIME       NOT NULL,
    [int_param_key]          BIGINT         NOT NULL,
    [bin_dep_cd]             INT            NOT NULL,
    [bin_los_cd]             INT            NOT NULL,
    [bin_placement_cd]       INT            NOT NULL,
    [bin_ihs_svc_cd]         INT            NOT NULL,
    [cd_reporter_type]       INT            NOT NULL,
    [cd_access_type]         INT            NOT NULL,
    [cd_allegation]          INT            NOT NULL,
    [cd_finding]             INT            NOT NULL,
    [age_grouping_cd]        INT            NOT NULL,
    [cd_race]                INT            NOT NULL,
    [pk_gndr]                INT            NOT NULL,
    [init_cd_plcm_setng]     INT            NOT NULL,
    [long_cd_plcm_setng]     INT            NOT NULL,
    [county_cd]              INT            NOT NULL,
    [kincare]                INT            NOT NULL,
    [bin_sibling_group_size] INT            NOT NULL,
    [all_together]           DECIMAL (9, 2) NOT NULL,
    [some_together]          DECIMAL (9, 2) NOT NULL,
    [none_together]          DECIMAL (9, 2) NOT NULL,
    [min_start_date]         DATETIME       NOT NULL,
    [max_start_date]         DATETIME       NOT NULL,
    [x1]                     FLOAT (53)     NOT NULL,
    [x2]                     FLOAT (53)     NOT NULL,
    [insert_date]            DATETIME       NOT NULL,
    [qry_id]                 INT            NOT NULL,
    [cohort_begin_year]      INT            NULL,
    [int_hash_key]           DECIMAL (22)   NOT NULL,
    [cnt_cohort]             INT            NOT NULL
);

