CREATE TABLE [prtl].[cache_pbcw3_aggr] (
    [qry_type]                             INT            NOT NULL,
    [date_type]                            INT            NOT NULL,
    [cohort_entry_date]                    DATETIME       NOT NULL,
    [int_param_key]                        BIGINT         NOT NULL,
    [bin_dep_cd]                           INT            NOT NULL,
    [bin_los_cd]                           INT            NOT NULL,
    [bin_placement_cd]                     INT            NOT NULL,
    [bin_ihs_svc_cd]                       INT            NOT NULL,
    [cd_reporter_type]                     INT            NOT NULL,
    [cd_access_type]                       INT            NOT NULL,
    [cd_allegation]                        INT            NOT NULL,
    [cd_finding]                           INT            NOT NULL,
    [age_grouping_cd]                      INT            NOT NULL,
    [cd_race]                              INT            NOT NULL,
    [pk_gndr]                              INT            NOT NULL,
    [init_cd_plcm_setng]                   INT            NOT NULL,
    [long_cd_plcm_setng]                   INT            NOT NULL,
    [county_cd]                            INT            NOT NULL,
    [family_setting_dcfs_prcntg]           NUMERIC (9, 2) CONSTRAINT [DF__cache_pbc__famil__02091B31] DEFAULT (NULL) NULL,
    [family_setting_private_agency_prcntg] NUMERIC (9, 2) CONSTRAINT [DF__cache_pbc__famil__02FD3F6A] DEFAULT (NULL) NULL,
    [relative_prcntg]                      NUMERIC (9, 2) CONSTRAINT [DF__cache_pbc__relat__03F163A3] DEFAULT (NULL) NULL,
    [group_inst_care_prcntg]               NUMERIC (9, 2) CONSTRAINT [DF__cache_pbc__group__04E587DC] DEFAULT (NULL) NULL,
    [min_start_date]                       DATETIME       NOT NULL,
    [max_start_date]                       DATETIME       NOT NULL,
    [x1]                                   FLOAT (53)     NOT NULL,
    [x2]                                   FLOAT (53)     NOT NULL,
    [insert_date]                          DATETIME       NOT NULL,
    [qry_id]                               INT            NOT NULL,
    [cohort_begin_year]                    INT            CONSTRAINT [DF__cache_pbc__start__06CDD04E] DEFAULT (NULL) NULL,
    [int_hash_key]                         DECIMAL (22)   CONSTRAINT [DF__cache_pbc__int_h__07C1F487] DEFAULT ('0') NOT NULL
);

