CREATE TABLE [prtl].[prtl_poc1ab_exits] (
    [qry_type]                         INT      NOT NULL,
    [date_type]                        INT      NOT NULL,
    [start_date]                       DATETIME NOT NULL,
    [bin_dep_cd]                       INT      NOT NULL,
    [max_bin_los_cd]                   INT      NOT NULL,
    [bin_placement_cd]                 INT      NOT NULL,
    [bin_ihs_svc_cd]                   INT      NOT NULL,
    [cd_reporter_type]                 INT      NOT NULL,
    [age_grouping_cd]                  INT      NULL,
    [cd_race]                          INT      NULL,
    [census_hispanic_latino_origin_cd] INT      NOT NULL,
    [pk_gndr]                          INT      NOT NULL,
    [init_cd_plcm_setng]               INT      NULL,
    [long_cd_plcm_setng]               INT      NULL,
    [county_cd]                        INT      NULL,
    [int_match_param_key]              BIGINT   NOT NULL,
    [cd_discharge_type]                INT      NOT NULL,
    [cnt_exits]                        INT      NOT NULL,
    [filter_allegation]                INT      NOT NULL,
    [filter_finding]                   INT      NOT NULL,
    [filter_service_category]          INT      NOT NULL,
    [filter_service_budget]            INT      NOT NULL,
    [filter_access_type]               INT      NOT NULL,
    [start_year]                       INT      NULL,
    CONSTRAINT [prtl_ooh_exits_bin_dep_cd_FK] FOREIGN KEY ([bin_dep_cd]) REFERENCES [dbo].[ref_filter_dependency] ([bin_dep_cd]),
    CONSTRAINT [prtl_ooh_exits_bin_ihs_svc_cd_FK] FOREIGN KEY ([bin_ihs_svc_cd]) REFERENCES [dbo].[ref_filter_ihs_services] ([bin_ihs_svc_cd]),
    CONSTRAINT [prtl_ooh_exits_bin_placement_cd_FK] FOREIGN KEY ([bin_placement_cd]) REFERENCES [dbo].[ref_filter_nbr_placement] ([bin_placement_cd]),
    CONSTRAINT [prtl_ooh_exits_cd_race_FK] FOREIGN KEY ([cd_race]) REFERENCES [dbo].[ref_lookup_ethnicity_census] ([cd_race_census]),
    CONSTRAINT [prtl_ooh_exits_cd_reporter_type_FK] FOREIGN KEY ([cd_reporter_type]) REFERENCES [dbo].[ref_filter_reporter_type] ([cd_reporter_type]),
    CONSTRAINT [prtl_ooh_exits_county_cd_FK] FOREIGN KEY ([county_cd]) REFERENCES [dbo].[ref_lookup_county] ([county_cd]),
    CONSTRAINT [prtl_ooh_exits_filter_service_category_FK] FOREIGN KEY ([filter_service_category]) REFERENCES [dbo].[ref_service_category_flag_xwalk] ([int_filter_service_category]),
    CONSTRAINT [prtl_ooh_exits_init_cd_plcm_setng_FK] FOREIGN KEY ([init_cd_plcm_setng]) REFERENCES [dbo].[ref_lookup_plcmnt] ([cd_plcm_setng]),
    CONSTRAINT [prtl_ooh_exits_long_cd_plcm_setng_FK] FOREIGN KEY ([long_cd_plcm_setng]) REFERENCES [dbo].[ref_lookup_plcmnt] ([cd_plcm_setng]),
    CONSTRAINT [prtl_ooh_exits_max_bin_los_cd_FK] FOREIGN KEY ([max_bin_los_cd]) REFERENCES [dbo].[ref_filter_los] ([bin_los_cd]),
    CONSTRAINT [prtl_ooh_exits_origin_cd_FK] FOREIGN KEY ([census_hispanic_latino_origin_cd]) REFERENCES [dbo].[ref_lookup_hispanic_latino_census] ([census_hispanic_latino_origin_cd]),
    CONSTRAINT [prtl_ooh_exits_pk_gndr_FK] FOREIGN KEY ([pk_gndr]) REFERENCES [dbo].[ref_lookup_gender] ([pk_gndr])
);

