


CREATE VIEW [dbo].[Cube_PROVIDER_DIM]
AS

SELECT
	ID_PROVIDER_DIM
	,ID_BSNS
	,ID_PRVD_ORG
	,ID_SSPS
	,ID_CALENDAR_DIM_CREATED
	--,CD_MAIL_CITY -- not a unique code
	--,TX_MAIL_CITY -- mispellings, not standardized
	,IIF(ID_PROVIDER_DIM = -1, -999, ISNULL(CD_MAIL_COUNTY, -99)) [CD_MAIL_COUNTY]
	,ISNULL(TX_MAIL_COUNTY, '-') [TX_MAIL_COUNTY]
	,ISNULL(TX_MAIL_STATE, '-') [TX_MAIL_STATE]
	,TX_MAIL_ZIP
	--,CD_PHYS_CITY -- not a unique code
	--,TX_PHYS_CITY -- mispellings, not standardized
	,IIF(ID_PROVIDER_DIM = -1, -999, ISNULL(CD_PHYS_COUNTY, -99)) [CD_PHYS_COUNTY]
	,ISNULL(TX_PHYS_COUNTY, '-') [TX_PHYS_COUNTY]
	,ISNULL(TX_PHYS_STATE, '-') [TX_PHYS_STATE]
	,TX_PHYS_ZIP
	,phys_zip_5
	,IIF(ID_PROVIDER_DIM = -1, -999, IIF(TX_PROVIDER_TYPE = '*INVALID*', 22, CD_PROVIDER_TYPE)) [CD_PROVIDER_TYPE]
	,TX_PROVIDER_TYPE
	,IIF(ID_PROVIDER_DIM = -1, -999, IIF(TX_REGION = '*INVALID*', 13, ISNULL(CD_REGION, -99))) [CD_REGION]
	,TX_REGION
	,IIF(ID_PROVIDER_DIM = -1, -999, ISNULL(CD_SSPS_STATUS, -99)) [CD_SSPS_STATUS]
	,TX_SSPS_STATUS
	,CD_STAT
	,IIF(ID_PROVIDER_DIM = -1, -999, ISNULL(CD_TRIBAL_AFLTN, -99)) [CD_TRIBAL_AFLTN]
	,TX_TRIBAL_AFLTN
	,FL_24_HOUR_CARE
	,FL_ABUSES_ANIMALS
	,FL_ADA_NEEDS
	,FL_ADJUDICATED_CRIMINAL
	,FL_AFFILIATED_WITH_GANGS
	,FL_AUTISTIC
	,FL_BEFORE_AFTER_SCHOOL_ONLY
	,FL_DEVELOPMENTAL_DELAY
	,FL_DIABETIC
	,FL_DIAGNOSED_MENTAL_HEALTH_CONDITION
	,FL_DIAGNOSED_WITH_FETAL_ALCOHOL_SYNDROME
	,FL_DRUG_AFFECTED
	,FL_EATING_DISORDER
	,FL_ENCOPRETIC
	,FL_ENURESIS
	,FL_EVENING
	,FL_FEMALE
	,FL_FIRE_SETTER
	,FL_HEARING_IMPAIRED
	,FL_HIV_POSITIVE
	,FL_IV_DRUG_USER
	,FL_IVE_TRIBAL_AGREEMENT
	,ISNULL(FL_IVE_TRIBAL_AGRMT_IN_PLC, '-') [FL_IVE_TRIBAL_AGRMT_IN_PLC]
	,FL_LEARNING_DISABILITIES
	,FL_LIFE_SKILLS_TRAINING
	,FL_MALE
	,FL_MASTURBATES_IN_PUBLIC
	,FL_MEDICALLY_FRAGILE
	,FL_NAA_ACCREDITED
	,FL_NAEYC_ACCREDITED
	,FL_NAFCC_ACCREDITED
	,FL_OPEN
	,FL_PARENT_AGENCY
	,FL_PHYSICALLY_AGGRESSIVE_YOUTH
	,FL_PHYSICALLY_ASSAULTIVE_YOUTH_PAY
	,FL_PROPERTY_DESTRUCTION
	,FL_PSYCHIATRIC_HOSPITALIZATION_HISTORY
	,FL_RELATIVE_CAREGIVER
	,FL_REQUIRES_MEDICATION
	,FL_REQUIRES_SPECIAL_DIET
	,FL_RESIDENTIAL_TREATMENT_HISTORY
	,FL_RUNAWAY_HISTORY
	,FL_SELF_ABUSIVE
	,FL_SEXUALLY_ABUSED
	,FL_SEXUALLY_ACTIVE
	,FL_SEXUALLY_AGGRESSIVE_YOUTH
	,FL_SEXUALLY_AGGRESSIVE_YOUTH_SAY
	,FL_SEXUALLY_REACTIVE
	,FL_SIBLING_GROUP
	,FL_SIGNIFICANT_ASTHMA_OR_ALLERGIES
	,FL_SPECIAL_NEEDS_CHILDREN
	,FL_SPECIALIZED_MEDICAL_CERTIFICATION
	,FL_SUICIDAL_THREAT_ATTEMPT
	,FL_TREATMENT_FOSTER_HOME_TRAINING
	,FL_TUTORING
	,FL_VISUALLY_IMPAIRED
	,FL_WEEKEND_CARE
	,DT_ADDR_LAST_VERIFIED
	,DT_IVE_TRIBAL_AGREEMENT_EFFECTIVE
FROM dbo.PROVIDER_DIM PD






