create view dbo.vw_health_activity_entries_by_sfy
as 
  select cd.STATE_FISCAL_YEAR, TX_EVAL_RESULT,TX_EVAL_TYPE,TX_HLTH_ACTVTY,TX_IN_OUT_PATIENT
  -- ,ID_CALENDAR_DIM_ACTIVITY_START,ID_CALENDAR_DIM_ACTIVITY_END
  ,count(distinct ID_PRSN_CHILD) cnt_child
  ,count(*) cnt_activity
   from health_activity_fact haf
  left join HEALTH_ACTIVITY_TYPE_DIM hat on hat.ID_HEALTH_ACTIVITY_TYPE_DIM=haf.ID_HEALTH_ACTIVITY_TYPE_DIM
  left join MENTAL_HEALTH_EVAL_DIM mh on mh.ID_MENTAL_HEALTH_EVAL_DIM=haf.ID_MENTAL_HEALTH_EVAL_DIM
  left join CALENDAR_DIM cd on cd.ID_CALENDAR_DIM=haf.ID_CALENDAR_DIM_ACTIVITY_START
  where cd.STATE_FISCAL_YEAR >='2009-01-01'
  --(haf.ID_CALENDAR_DIM_ACTIVITY_END=0 or haf.ID_CALENDAR_DIM_ACTIVITY_END>=20120101)
  -- and haf.ID_CALENDAR_DIM_ACTIVITY_START<=20121231 

  group by  cd.STATE_FISCAL_YEAR, TX_EVAL_RESULT,TX_EVAL_TYPE,TX_HLTH_ACTVTY,TX_IN_OUT_PATIENT