CREATE TABLE [dbo].[ABUSE_TYPE_DIM] (
    [ID_ABUSE_TYPE_DIM] INT           NOT NULL,
    [CD_ALLEGATION]     INT           NULL,
    [TX_ALLEGATION]     VARCHAR (200) NULL,
    [DT_ROW_BEGIN]      DATETIME      NULL,
    [DT_ROW_END]        DATETIME      NULL,
    [ID_CYCLE]          INT           NULL,
    [IS_CURRENT]        CHAR (1)      NULL,
    CONSTRAINT [PK_ID_ABUSE_TYPE_DIM] PRIMARY KEY CLUSTERED ([ID_ABUSE_TYPE_DIM] ASC)
);

