CREATE TABLE [dbo].[ASSIGNMENT_FACT] (
    [ID_ASSIGNMENT_FACT]          INT      NOT NULL,
    [ID_ASGN]                     INT      NULL,
    [ID_INTAKE_FACT]              INT      NULL,
    [ID_ASSIGNMENT_ATTRIBUTE_DIM] INT      NULL,
    [ID_CALENDAR_DIM_BEGIN]       INT      NULL,
    [ID_CALENDAR_DIM_END]         INT      NULL,
    [ID_CASE_DIM]                 INT      NULL,
    [ID_LOCATION_DIM]             INT      NULL,
    [ID_PEOPLE_DIM]               INT      NULL,
    [ID_PROVIDER_DIM]             INT      NULL,
    [ID_WORKER_DIM]               INT      NULL,
    [FL_EXPUNGED]                 CHAR (1) NULL,
    [ID_CASE]                     INT      NULL,
    [ID_PRSN]                     INT      NULL,
    [ID_PRVD_ORG]                 INT      NULL,
    CONSTRAINT [PK_ID_ASSIGNMENT_FACT] PRIMARY KEY CLUSTERED ([ID_ASSIGNMENT_FACT] ASC),
    CONSTRAINT [fk_ASSIGNMENT_FACT_ID_ASSIGNMENT_ATTRIBUTE_DIM] FOREIGN KEY ([ID_ASSIGNMENT_ATTRIBUTE_DIM]) REFERENCES [dbo].[ASSIGNMENT_ATTRIBUTE_DIM] ([ID_ASSIGNMENT_ATTRIBUTE_DIM]),
    CONSTRAINT [fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_BEGIN] FOREIGN KEY ([ID_CALENDAR_DIM_BEGIN]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_END] FOREIGN KEY ([ID_CALENDAR_DIM_END]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_ASSIGNMENT_FACT_ID_CASE_DIM] FOREIGN KEY ([ID_CASE_DIM]) REFERENCES [dbo].[CASE_DIM] ([ID_CASE_DIM]),
    CONSTRAINT [fk_ASSIGNMENT_FACT_ID_LOCATION_DIM] FOREIGN KEY ([ID_LOCATION_DIM]) REFERENCES [dbo].[LOCATION_DIM] ([ID_LOCATION_DIM]),
    CONSTRAINT [fk_ASSIGNMENT_FACT_ID_PEOPLE_DIM] FOREIGN KEY ([ID_PEOPLE_DIM]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM]),
    CONSTRAINT [fk_ASSIGNMENT_FACT_ID_PROVIDER_DIM] FOREIGN KEY ([ID_PROVIDER_DIM]) REFERENCES [dbo].[PROVIDER_DIM] ([ID_PROVIDER_DIM]),
    CONSTRAINT [fk_ASSIGNMENT_FACT_ID_WORKER_DIM] FOREIGN KEY ([ID_WORKER_DIM]) REFERENCES [dbo].[WORKER_DIM] ([ID_WORKER_DIM])
);


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20140603-133409]
    ON [dbo].[ASSIGNMENT_FACT]([ID_CALENDAR_DIM_BEGIN] ASC, [ID_CASE] ASC);


GO
CREATE NONCLUSTERED INDEX [idx_id_case_id_calendar_dim_begin_aad]
    ON [dbo].[ASSIGNMENT_FACT]([ID_CASE] ASC)
    INCLUDE([ID_ASSIGNMENT_FACT], [ID_ASSIGNMENT_ATTRIBUTE_DIM], [ID_CALENDAR_DIM_BEGIN]);


GO
CREATE NONCLUSTERED INDEX [idx_asf_case_worker_begin_inc_fact_dim_end]
    ON [dbo].[ASSIGNMENT_FACT]([ID_WORKER_DIM] ASC, [ID_CASE] ASC, [ID_CALENDAR_DIM_BEGIN] ASC)
    INCLUDE([ID_ASSIGNMENT_FACT], [ID_ASSIGNMENT_ATTRIBUTE_DIM], [ID_CALENDAR_DIM_END]);


GO
CREATE NONCLUSTERED INDEX [idx_workder_dim_id_prsn_id_calendar_dim_begin]
    ON [dbo].[ASSIGNMENT_FACT]([ID_PRSN] ASC)
    INCLUDE([ID_CALENDAR_DIM_BEGIN], [ID_CALENDAR_DIM_END], [ID_WORKER_DIM]);

