CREATE TABLE [dbo].[CASE_PARTICIPANT_FACT] (
    [ID_CASE_PARTICIPANT_FACT]       INT NOT NULL,
    [ID_CASE]                        INT NULL,
    [ID_PRSN]                        INT NULL,
    [ID_CASE_DIM]                    INT NULL,
    [ID_PEOPLE_DIM]                  INT NULL,
    [ID_CASE_PARTICIPANT_STATUS_DIM] INT NULL,
    [FL_ACTIVE_PARTICIPANT]          INT NULL,
    CONSTRAINT [PK_ID_CASE_PARTICIPANT_FACT] PRIMARY KEY CLUSTERED ([ID_CASE_PARTICIPANT_FACT] ASC)
);

