CREATE TABLE [dbo].[dat_ref] (
	[Column 0] VARCHAR(50) NULL
	,[versionId] VARCHAR(50) NULL
	,[organizationId] VARCHAR(50) NULL
	,[updatedAt] VARCHAR(50) NULL
	,[updatedById] VARCHAR(50) NULL
	,[referralId] VARCHAR(50) NULL
	,[requestDate] VARCHAR(50) NULL
	,[resourceSpecialistLastName] VARCHAR(50) NULL
	,[resourceSpecialistFirstName] VARCHAR(50) NULL
	,[resourceSpecialistPhone] VARCHAR(50) NULL
	,[socialWorkerLastName] VARCHAR(50) NULL
	,[socialWorkerFirstName] VARCHAR(50) NULL
	,[socialWorkerPhone] VARCHAR(50) NULL
	,[socialWorkerEmail] VARCHAR(50) NULL
	,[dshsOffice] VARCHAR(50) NULL
	,[dshsOfficePhone] VARCHAR(50) NULL
	,[dcfsUnit] VARCHAR(50) NULL
	,[caseSupervisorLastName] VARCHAR(50) NULL
	,[caseSupervisorFirstName] VARCHAR(50) NULL
	,[caseSupervisorPhone] VARCHAR(50) NULL
	,[serviceType] VARCHAR(50) NULL
	,[levelOfSupervision] VARCHAR(50) NULL
	,[caseNumber] VARCHAR(50) NULL
	,[caseDetailsLastName] VARCHAR(50) NULL
	,[caseDetailsFirstName] VARCHAR(50) NULL
	,[fosterParents] VARCHAR(50) NULL
	,[relatives] VARCHAR(50) NULL
	,[caseAidesOrIntern] VARCHAR(50) NULL
	,[other] VARCHAR(50) NULL
	,[barriersToConsideredAlternatives] VARCHAR(50) NULL
	,[startDate] VARCHAR(50) NULL
	,[visitsPerWeek] VARCHAR(50) NULL
	,[hoursPerVisit] VARCHAR(50) NULL
	,[timeNegotiable] VARCHAR(50) NULL
	,[providerContactLastName] VARCHAR(50) NULL
	,[providerContactFirstName] VARCHAR(50) NULL
	,[providerContactPhone] VARCHAR(50) NULL
	,[restroomRules] VARCHAR(50) NULL
	,[languageRequirementNeed] VARCHAR(50) NULL
	,[language] VARCHAR(50) NULL
	,[languageSpecification] VARCHAR(50) NULL
	,[careSpecificInstructionsComment] VARCHAR(50) NULL
	,[relatedCases] VARCHAR(50) NULL
	,[emergencyNumbers] VARCHAR(50) NULL
	,[childDetails] VARCHAR(50) NULL
	,[parentVisitorDetails] VARCHAR(50) NULL
	,[visitLocations] VARCHAR(50) NULL
	,[visitSchedule] VARCHAR(50) NULL
	,[visitSupervisors] VARCHAR(50) NULL
	,[assignedDrivers] VARCHAR(50) NULL
	,[safetyIssues] VARCHAR(50) NULL
	,[childPlacements] VARCHAR(50) NULL
	,[pickupLocations] VARCHAR(50) NULL
	,[dropoffLocations] VARCHAR(50) NULL
	,[id] VARCHAR(50) NULL
	,[isCurrentVersion] VARCHAR(50) NULL
	,[deletedAt] VARCHAR(50) NULL
	,[inReviewReportsCount] VARCHAR(50) NULL
	,[inProgressReportsCount] VARCHAR(50) NULL
	)
