CREATE TABLE [dbo].[EDUCATION_PLAN_FACT] (
    [ID_EDUCATION_PLAN_FACT]    INT      NOT NULL,
    [ID_EDUC_PLAN]              INT      NULL,
    [ID_CALENDAR_DIM_PLAN_DATE] INT      NULL,
    [ID_EDUCATION_PLAN_DIM]     INT      NULL,
    [ID_PEOPLE_DIM_CHILD]       INT      NULL,
    [FL_APPLICATIONS]           INT      NULL,
    [FL_ASSISTANCE]             INT      NULL,
    [FL_COLLEGE_TOUR]           INT      NULL,
    [FL_OTHER]                  INT      NULL,
    [FL_POST_PLANNING]          INT      NULL,
    [FL_EXPUNGED]               CHAR (1) NULL,
    [ID_PRSN_CHILD]             INT      NULL,
    PRIMARY KEY CLUSTERED ([ID_EDUCATION_PLAN_FACT] ASC),
    CONSTRAINT [fk_EDUCATION_PLAN_FACT_ID_CALENDAR_DIM_PLAN_DATE] FOREIGN KEY ([ID_CALENDAR_DIM_PLAN_DATE]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_EDUCATION_PLAN_FACT_ID_EDUCATION_PLAN_DIM] FOREIGN KEY ([ID_EDUCATION_PLAN_DIM]) REFERENCES [dbo].[EDUCATION_PLAN_DIM] ([ID_EDUCATION_PLAN_DIM]),
    CONSTRAINT [fk_EDUCATION_PLAN_FACT_ID_PEOPLE_DIM_CHILD] FOREIGN KEY ([ID_PEOPLE_DIM_CHILD]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM])
);

