CREATE TABLE [dbo].[ELIGIBILITY_DIM] (
    [ID_ELIGIBILITY_DIM]     INT           NOT NULL,
    [CD_AGE]                 CHAR (1)      NULL,
    [TX_AGE]                 VARCHAR (200) NULL,
    [CD_CTZN]                CHAR (1)      NULL,
    [TX_CTZN]                VARCHAR (200) NULL,
    [CD_DPRV_TYPE]           INT           NULL,
    [TX_DPRV_TYPE]           VARCHAR (200) NULL,
    [CD_DPRVTN]              CHAR (1)      NULL,
    [TX_DPRVTN]              VARCHAR (200) NULL,
    [CD_LGL_RESP]            CHAR (1)      NULL,
    [TX_LGL_RESP]            VARCHAR (200) NULL,
    [CD_PRMNCY_PLAN]         CHAR (1)      NULL,
    [TX_PRMNCY_PLAN]         VARCHAR (200) NULL,
    [CD_RMVL]                CHAR (1)      NULL,
    [TX_RMVL]                VARCHAR (200) NULL,
    [CD_RMVL_RE]             CHAR (1)      NULL,
    [TX_RMVL_RE]             VARCHAR (200) NULL,
    [CD_SSI]                 CHAR (1)      NULL,
    [TX_SSI]                 VARCHAR (200) NULL,
    [CD_VPA_CTW]             CHAR (1)      NULL,
    [TX_VPA_CTW]             VARCHAR (200) NULL,
    [FL_ASSET_TEST]          CHAR (1)      NULL,
    [FL_INCOME_TEST]         CHAR (1)      NULL,
    [FL_INITIAL_ELIGIBILITY] CHAR (1)      NULL,
    [DT_ROW_BEGIN]           DATETIME      NULL,
    [DT_ROW_END]             DATETIME      NULL,
    [ID_CYCLE]               INT           NULL,
    [IS_CURRENT]             INT           NULL,
    CONSTRAINT [pk_ID_ELIGIBILITY_DIM] PRIMARY KEY CLUSTERED ([ID_ELIGIBILITY_DIM] ASC)
);

