CREATE TABLE [dbo].[HEALTH_CAT_ATTRIBUTE_BRIDGE_FACT] (
    [ID_HEALTH_CAT_ATTRIBUTE_BRIDGE_FACT] INT NOT NULL,
    [ID_HEALTH_ACTIVITY_FACT]             INT NULL,
    [ID_HEALTH_CAT_ATTRIBUTE_DIM]         INT NULL,
    CONSTRAINT [PK_HEALTH_CAT_ATTRIBUTE_BRIDGE_FACT] PRIMARY KEY CLUSTERED ([ID_HEALTH_CAT_ATTRIBUTE_BRIDGE_FACT] ASC),
    CONSTRAINT [fk_HEALTH_CAT_ATTRIBUTE_BRIDGE_FACT_ID_HEALTH_ACTIVITY_FACT] FOREIGN KEY ([ID_HEALTH_ACTIVITY_FACT]) REFERENCES [dbo].[HEALTH_ACTIVITY_FACT] ([ID_HEALTH_ACTIVITY_FACT])
);

