CREATE TABLE [dbo].[HEALTH_ACTIVITY_FACT] (
    [ID_HEALTH_ACTIVITY_FACT]        INT      NOT NULL,
    [ID_SOURCE_KEY]                  INT      NULL,
    [ID_CALENDAR_DIM_ACTIVITY_END]   INT      NULL,
    [ID_CALENDAR_DIM_ACTIVITY_START] INT      NULL,
    [ID_HEALTH_ACTIVITY_TYPE_DIM]    INT      NULL,
    [ID_MENTAL_HEALTH_EVAL_DIM]      INT      NULL,
    [ID_PEOPLE_DIM_CHILD]            INT      NULL,
    [FL_INACCURATE_DATA]             TINYINT  NULL,
    [QT_RECORDS_REQUEST]             INT      NULL,
    [CHILD_AGE]                      SMALLINT NULL,
    [FL_EXPUNGED]                    CHAR (1) NULL,
    [ID_PRSN_CHILD]                  INT      NULL,
    CONSTRAINT [PK_HEALTH_ACTIVITY_FACT] PRIMARY KEY CLUSTERED ([ID_HEALTH_ACTIVITY_FACT] ASC),
    CONSTRAINT [fk_HEALTH_ACTIVITY_FACT_ID_CALENDAR_DIM_ACTIVITY_END] FOREIGN KEY ([ID_CALENDAR_DIM_ACTIVITY_END]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_HEALTH_ACTIVITY_FACT_ID_CALENDAR_DIM_ACTIVITY_START] FOREIGN KEY ([ID_CALENDAR_DIM_ACTIVITY_START]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_HEALTH_ACTIVITY_FACT_ID_HEALTH_ACTIVITY_TYPE_DIM] FOREIGN KEY ([ID_HEALTH_ACTIVITY_TYPE_DIM]) REFERENCES [dbo].[HEALTH_ACTIVITY_TYPE_DIM] ([ID_HEALTH_ACTIVITY_TYPE_DIM]),
    CONSTRAINT [fk_HEALTH_ACTIVITY_FACT_ID_MENTAL_HEALTH_EVAL_DIM] FOREIGN KEY ([ID_MENTAL_HEALTH_EVAL_DIM]) REFERENCES [dbo].[MENTAL_HEALTH_EVAL_DIM] ([ID_MENTAL_HEALTH_EVAL_DIM]),
    CONSTRAINT [fk_HEALTH_ACTIVITY_FACT_ID_PEOPLE_DIM_CHILD] FOREIGN KEY ([ID_PEOPLE_DIM_CHILD]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM])
);

