CREATE TABLE [dbo].[IL_ANSELL_CASEY_ASSESSMENT_FACT] (
    [ID_IL_ANSELL_CASEY_ASSESSMENT_FACT] INT NOT NULL,
    [ID_IL_ANSELL_CASEY_ASSESSMENT]      INT NULL,
    [ID_INDEPENDENT_LIVING_FACT]         INT NULL,
    [CD_LEVEL]                           INT NULL,
    [FL_YOUTH_REFUSES]                   INT NULL,
    PRIMARY KEY CLUSTERED ([ID_IL_ANSELL_CASEY_ASSESSMENT_FACT] ASC),
    CONSTRAINT [fk_IL_ANSELL_CASEY_ASSESSMENT_FACT_ID_INDEPENDENT_LIVING_FACT] FOREIGN KEY ([ID_INDEPENDENT_LIVING_FACT]) REFERENCES [dbo].[INDEPENDENT_LIVING_FACT] ([ID_INDEPENDENT_LIVING_FACT])
);

