CREATE TABLE [dbo].[INDEPENDENT_LIVING_BRIDGE_FACT] (
    [ID_INDEPENDENT_LIVING_BRIDGE_FACT] INT NOT NULL,
    [ID_INDEPENDENT_LIVING_FACT]        INT NULL,
    [ID_IL_SERVICE_CATEGORY_TYPE_DIM]   INT NULL,
    CONSTRAINT [PK_INDEPENDENT_LIVING_BRIDGE_FACT] PRIMARY KEY CLUSTERED ([ID_INDEPENDENT_LIVING_BRIDGE_FACT] ASC)
);

