CREATE TABLE [dbo].[LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT] (
    [ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT] INT     NOT NULL,
    [ID_LEGAL_AGGRAVATED_CIRCUMSTANCES]      INT     NULL,
    [ID_CASE_DIM]                            INT     NULL,
    [ID_PEOPLE_DIM]                          INT     NULL,
    [ID_CALENDAR_DIM_FINDING]                INT     NULL,
    [FL_ADOPTION_NOT_APPROPRIATE]            TINYINT NULL,
    [FL_AGGRV_CIRCUMSTANCE_EXISTS]           TINYINT NULL,
    [FL_COMP_REASON_EXISTS]                  TINYINT NULL,
    [FL_NO_RSNBL_EFFORT_CT_FINDING]          TINYINT NULL,
    [FL_PROGRESS]                            TINYINT NULL,
    [FL_OTHER_TPR_REASON]                    TINYINT NULL,
    [ID_CASE]                                INT     NULL,
    CONSTRAINT [PK_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT] PRIMARY KEY CLUSTERED ([ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT] ASC),
    CONSTRAINT [fk_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT_ID_CALENDAR_DIM_FINDING] FOREIGN KEY ([ID_CALENDAR_DIM_FINDING]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT_ID_CASE_DIM] FOREIGN KEY ([ID_CASE_DIM]) REFERENCES [dbo].[CASE_DIM] ([ID_CASE_DIM]),
    CONSTRAINT [fk_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT_ID_PEOPLE_DIM] FOREIGN KEY ([ID_PEOPLE_DIM]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM])
);

