CREATE TABLE [dbo].[LEGAL_JURISDICTION_DIM] (
    [ID_LEGAL_JURISDICTION_DIM] INT           NOT NULL,
    [CD_JURISDICTION]           INT           NULL,
    [TX_JURISDICTION]           VARCHAR (200) NULL,
    [DT_ROW_BEGIN]              DATETIME      NULL,
    [DT_ROW_END]                DATETIME      NULL,
    [ID_CYCLE]                  INT           NULL,
    [IS_CURRENT]                INT           NULL,
    CONSTRAINT [PK_ID_LEGAL_JURISDICTION_DIM] PRIMARY KEY CLUSTERED ([ID_LEGAL_JURISDICTION_DIM] ASC)
);

