CREATE TABLE [dbo].[LICENSE_ACTION_FACT] (
    [ID_LICENSE_ACTION_FACT] INT           NOT NULL,
    [ID_LCNS]                INT           NULL,
    [ID_LCNS_ACTN]           INT           NULL,
    [ID_CALENDAR_DIM_ACTION] INT           NULL,
    [ID_LICENSE_ATTRIB_DIM]  INT           NULL,
    [ID_PROVIDER_DIM]        INT           NULL,
    [CD_ACTN]                VARCHAR (2)   NULL,
    [TX_ACTN]                VARCHAR (200) NULL,
    [CD_ACTN_RSN]            INT           NULL,
    [TX_ACTN_RSN]            VARCHAR (200) NULL,
    [CD_ACTN_RSN2]           INT           NULL,
    [TX_ACTN_RSN2]           VARCHAR (200) NULL,
    [ID_PRVD_ORG]            INT           NULL,
    CONSTRAINT [pk_ID_LICENSE_ACTION_FACT] PRIMARY KEY CLUSTERED ([ID_LICENSE_ACTION_FACT] ASC),
    CONSTRAINT [fk_LICENSE_ACTION_FACT_ID_CALENDAR_DIM_ACTION] FOREIGN KEY ([ID_CALENDAR_DIM_ACTION]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_LICENSE_ACTION_FACT_ID_LICENSE_ATTRIB_DIM] FOREIGN KEY ([ID_LICENSE_ATTRIB_DIM]) REFERENCES [dbo].[LICENSE_ATTRIB_DIM] ([ID_LICENSE_ATTRIB_DIM]),
    CONSTRAINT [fk_LICENSE_ACTION_FACT_ID_PROVIDER_DIM] FOREIGN KEY ([ID_PROVIDER_DIM]) REFERENCES [dbo].[PROVIDER_DIM] ([ID_PROVIDER_DIM])
);

