CREATE TABLE [dbo].[PAYMENT_DETAIL_FACT] (
    [ID_PAYMENT_DETAIL_FACT]    INT             NOT NULL,
    [ID_PMNT_HISTORY]           INT             NULL,
    [ID_PAYMENT_FACT]           INT             NULL,
    [ID_CALENDAR_DIM_EFFECTIVE] INT             NULL,
    [ID_CALENDAR_DIM_FROM]      INT             NULL,
    [ID_CALENDAR_DIM_TO]        INT             NULL,
    [ID_PAYMENT_DETAIL_DIM]     INT             NULL,
    [ID_SOURCE_FUNDS_DIM]       INT             NULL,
    [AM_PAID]                   NUMERIC (18, 2) NULL,
    [FL_ACTIVE]                 NUMERIC (18)    NULL,
    PRIMARY KEY CLUSTERED ([ID_PAYMENT_DETAIL_FACT] ASC),
    CONSTRAINT [fk_PAYMENT_DETAIL_FACT_ID_CALENDAR_DIM_EFFECTIVE] FOREIGN KEY ([ID_CALENDAR_DIM_EFFECTIVE]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_PAYMENT_DETAIL_FACT_ID_CALENDAR_DIM_FROM] FOREIGN KEY ([ID_CALENDAR_DIM_FROM]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_PAYMENT_DETAIL_FACT_ID_CALENDAR_DIM_TO] FOREIGN KEY ([ID_CALENDAR_DIM_TO]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_PAYMENT_DETAIL_FACT_ID_PAYMENT_DETAIL_DIM] FOREIGN KEY ([ID_PAYMENT_DETAIL_DIM]) REFERENCES [dbo].[PAYMENT_DETAIL_DIM] ([ID_PAYMENT_DETAIL_DIM]),
    CONSTRAINT [fk_PAYMENT_DETAIL_FACT_ID_PAYMENT_FACT] FOREIGN KEY ([ID_PAYMENT_FACT]) REFERENCES [dbo].[PAYMENT_FACT] ([ID_PAYMENT_FACT]),
    CONSTRAINT [fk_PAYMENT_DETAIL_FACT_ID_SOURCE_FUNDS_DIM] FOREIGN KEY ([ID_SOURCE_FUNDS_DIM]) REFERENCES [dbo].[SOURCE_FUNDS_DIM] ([ID_SOURCE_FUNDS_DIM])
);

