CREATE TABLE [dbo].[PAYMENT_FACT] (
    [ID_PAYMENT_FACT]                     INT        NOT NULL,
    [ID_PMNT]                             INT        NULL,
    [ID_SSPS_AUTH]                        INT        NULL,
    [ID_SSPS_PAYEE_ID]                    INT        NULL,
    [ID_SSPS_PRVD_ID]                     INT        NULL,
    [ID_AUTHORIZATION_FACT]               INT        NULL,
    [ID_CALENDAR_DIM_AUTHORIZATION_BEGIN] INT        NULL,
    [ID_CALENDAR_DIM_AUTHORIZATION_END]   INT        NULL,
    [ID_CALENDAR_DIM_PAYMENT_END]         INT        NULL,
    [ID_CALENDAR_DIM_PAYMENT_START]       INT        NULL,
    [ID_CALENDAR_DIM_SERVICE_BEGIN]       INT        NULL,
    [ID_CALENDAR_DIM_SERVICE_END]         INT        NULL,
    [ID_CALENDAR_DIM_WARRANT]             INT        NULL,
    [ID_CASE_DIM]                         INT        NULL,
    [ID_LOCATION_DIM]                     INT        NULL,
    [ID_PAYMENT_DIM]                      INT        NULL,
    [ID_PEOPLE_DIM_CHILD]                 INT        NULL,
    [ID_PEOPLE_DIM_CLIENT]                INT        NULL,
    [ID_PLACEMENT_CARE_AUTH_DIM]          INT        NULL,
    [ID_PLACEMENT_TYPE_DIM]               INT        NULL,
    [ID_PROVIDER_DIM_PAYEE]               INT        NULL,
    [ID_PROVIDER_DIM_SERVICE]             INT        NULL,
    [ID_SERVICE_TYPE_DIM]                 INT        NULL,
    [ID_WORKER_DIM]                       INT        NULL,
    [CD_SSPS_REGION_CODE]                 INT        NULL,
    [CD_SSPS_RPT_UNIT]                    INT        NULL,
    [AM_RATE]                             FLOAT (53) NULL,
    [AM_TOTAL_PAID]                       FLOAT (53) NULL,
    [AM_UNITS]                            FLOAT (53) NULL,
    [CHILD_AGE]                           INT        NULL,
    [ID_PRSN_CHILD]                       INT        NULL,
    [ID_PRSN_CLIENT]                      INT        NULL,
    [ID_PRVD_ORG_PAYEE]                   INT        NULL,
    [ID_PRVD_ORG_SERVICE]                 INT        NULL,
    [id_case]                             INT        NULL,
    CONSTRAINT [PK_ID_PAYMENT_FACT] PRIMARY KEY CLUSTERED ([ID_PAYMENT_FACT] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [fk_PAYMENT_FACT_ID_CALENDAR_DIM_AUTHORIZATION_BEGIN] FOREIGN KEY ([ID_CALENDAR_DIM_AUTHORIZATION_BEGIN]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_PAYMENT_FACT_ID_CALENDAR_DIM_AUTHORIZATION_END] FOREIGN KEY ([ID_CALENDAR_DIM_AUTHORIZATION_END]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_PAYMENT_FACT_ID_CALENDAR_DIM_PAYMENT_END] FOREIGN KEY ([ID_CALENDAR_DIM_PAYMENT_END]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_PAYMENT_FACT_ID_CALENDAR_DIM_PAYMENT_START] FOREIGN KEY ([ID_CALENDAR_DIM_PAYMENT_START]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_PAYMENT_FACT_ID_CALENDAR_DIM_SERVICE_BEGIN] FOREIGN KEY ([ID_CALENDAR_DIM_SERVICE_BEGIN]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_PAYMENT_FACT_ID_CALENDAR_DIM_SERVICE_END] FOREIGN KEY ([ID_CALENDAR_DIM_SERVICE_END]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_PAYMENT_FACT_ID_CALENDAR_DIM_WARRANT] FOREIGN KEY ([ID_CALENDAR_DIM_WARRANT]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_PAYMENT_FACT_ID_CASE_DIM] FOREIGN KEY ([ID_CASE_DIM]) REFERENCES [dbo].[CASE_DIM] ([ID_CASE_DIM]),
    CONSTRAINT [fk_PAYMENT_FACT_ID_LOCATION_DIM] FOREIGN KEY ([ID_LOCATION_DIM]) REFERENCES [dbo].[LOCATION_DIM] ([ID_LOCATION_DIM]),
    CONSTRAINT [fk_PAYMENT_FACT_ID_PAYMENT_DIM] FOREIGN KEY ([ID_PAYMENT_DIM]) REFERENCES [dbo].[PAYMENT_DIM] ([ID_PAYMENT_DIM]),
    CONSTRAINT [fk_PAYMENT_FACT_ID_PEOPLE_DIM_CHILD] FOREIGN KEY ([ID_PEOPLE_DIM_CHILD]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM]),
    CONSTRAINT [fk_PAYMENT_FACT_ID_PEOPLE_DIM_CLIENT] FOREIGN KEY ([ID_PEOPLE_DIM_CLIENT]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM]),
    CONSTRAINT [fk_PAYMENT_FACT_ID_PLACEMENT_CARE_AUTH_DIM] FOREIGN KEY ([ID_PLACEMENT_CARE_AUTH_DIM]) REFERENCES [dbo].[PLACEMENT_CARE_AUTH_DIM] ([ID_PLACEMENT_CARE_AUTH_DIM]),
    CONSTRAINT [fk_PAYMENT_FACT_ID_PLACEMENT_TYPE_DIM] FOREIGN KEY ([ID_PLACEMENT_TYPE_DIM]) REFERENCES [dbo].[PLACEMENT_TYPE_DIM] ([ID_PLACEMENT_TYPE_DIM]),
    CONSTRAINT [fk_PAYMENT_FACT_ID_PROVIDER_DIM_PAYEE] FOREIGN KEY ([ID_PROVIDER_DIM_PAYEE]) REFERENCES [dbo].[PROVIDER_DIM] ([ID_PROVIDER_DIM]),
    CONSTRAINT [fk_PAYMENT_FACT_ID_PROVIDER_DIM_SERVICE] FOREIGN KEY ([ID_PROVIDER_DIM_SERVICE]) REFERENCES [dbo].[PROVIDER_DIM] ([ID_PROVIDER_DIM]),
    CONSTRAINT [fk_PAYMENT_FACT_ID_SERVICE_TYPE_DIM] FOREIGN KEY ([ID_SERVICE_TYPE_DIM]) REFERENCES [dbo].[SERVICE_TYPE_DIM] ([ID_SERVICE_TYPE_DIM]),
    CONSTRAINT [fk_PAYMENT_FACT_ID_WORKER_DIM] FOREIGN KEY ([ID_WORKER_DIM]) REFERENCES [dbo].[WORKER_DIM] ([ID_WORKER_DIM])
);


GO
CREATE NONCLUSTERED INDEX [idx_payment_fact_am_total_paid_incl7]
    ON [dbo].[PAYMENT_FACT]([AM_TOTAL_PAID] ASC)
    INCLUDE([ID_PAYMENT_FACT], [ID_CALENDAR_DIM_SERVICE_BEGIN], [ID_CALENDAR_DIM_SERVICE_END], [ID_PROVIDER_DIM_SERVICE], [ID_SERVICE_TYPE_DIM], [ID_PRSN_CHILD]);


GO
CREATE NONCLUSTERED INDEX [idx_payment_fact_prov_svc_prsn_paid_incl3]
    ON [dbo].[PAYMENT_FACT]([ID_PROVIDER_DIM_SERVICE] ASC, [ID_SERVICE_TYPE_DIM] ASC, [ID_PRSN_CHILD] ASC, [AM_TOTAL_PAID] ASC)
    INCLUDE([ID_PAYMENT_FACT], [ID_CALENDAR_DIM_SERVICE_BEGIN], [ID_CALENDAR_DIM_SERVICE_END]);


GO
CREATE NONCLUSTERED INDEX [idx_provider_srvc_child_incl_srvc_dates]
    ON [dbo].[PAYMENT_FACT]([ID_PROVIDER_DIM_SERVICE] ASC, [ID_PRSN_CHILD] ASC)
    INCLUDE([ID_PAYMENT_FACT], [ID_CALENDAR_DIM_SERVICE_BEGIN], [ID_CALENDAR_DIM_SERVICE_END], [ID_SERVICE_TYPE_DIM], [AM_RATE], [AM_TOTAL_PAID], [AM_UNITS]);


GO
CREATE NONCLUSTERED INDEX [idx_am_total_paid]
    ON [dbo].[PAYMENT_FACT]([AM_TOTAL_PAID] ASC)
    INCLUDE([ID_PAYMENT_FACT], [ID_CALENDAR_DIM_SERVICE_BEGIN], [ID_CALENDAR_DIM_SERVICE_END], [ID_PROVIDER_DIM_SERVICE], [ID_SERVICE_TYPE_DIM], [AM_RATE], [AM_UNITS], [ID_PRSN_CHILD], [id_case]);


GO
CREATE NONCLUSTERED INDEX [idx_std_id_prsn_child_payment_fact]
    ON [dbo].[PAYMENT_FACT]([ID_SERVICE_TYPE_DIM] ASC)
    INCLUDE([ID_PRSN_CHILD]);

