CREATE TABLE [dbo].[PRE_ADOPTION_LEGAL_FACT] (
    [ID_PRE_ADOPTION_LEGAL_FACT] INT NOT NULL,
    [ID_CASE_NEW]                INT NULL,
    [ID_CALENDAR_DIM_ADOPTION]   INT NULL,
    [ID_LEGAL_JURISDICTION_DIM]  INT NULL,
    [ID_PEOPLE_DIM]              INT NULL,
    [ID_PLACEMENT_CARE_AUTH_DIM] INT NULL,
    [ID_PRSN]                    INT NULL,
    CONSTRAINT [PK_ID_PRE_ADOPTION_LEGAL_FACT] PRIMARY KEY CLUSTERED ([ID_PRE_ADOPTION_LEGAL_FACT] ASC),
    CONSTRAINT [fk_PRE_ADOPTION_LEGAL_FACT_ID_CALENDAR_DIM_ADOPTION] FOREIGN KEY ([ID_CALENDAR_DIM_ADOPTION]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_PRE_ADOPTION_LEGAL_FACT_ID_LEGAL_JURISDICTION_DIM] FOREIGN KEY ([ID_LEGAL_JURISDICTION_DIM]) REFERENCES [dbo].[LEGAL_JURISDICTION_DIM] ([ID_LEGAL_JURISDICTION_DIM]),
    CONSTRAINT [fk_PRE_ADOPTION_LEGAL_FACT_ID_PEOPLE_DIM] FOREIGN KEY ([ID_PEOPLE_DIM]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM]),
    CONSTRAINT [fk_PRE_ADOPTION_LEGAL_FACT_ID_PLACEMENT_CARE_AUTH_DIM] FOREIGN KEY ([ID_PLACEMENT_CARE_AUTH_DIM]) REFERENCES [dbo].[PLACEMENT_CARE_AUTH_DIM] ([ID_PLACEMENT_CARE_AUTH_DIM])
);

