CREATE TABLE [dbo].[PROVIDER_ACTIVITY_FACT] (
	[ID_PROVIDER_ACTIVITY_FACT] INT NULL
	,[ID_ACTION] INT NULL
	,[ID_PRVD_ACTIONS] INT NULL
	,[ID_PRVD_ACTIONS_ACTIVITIES] INT NULL
	,[ID_CALENDAR_DIM_BEGIN] INT NULL
	,[ID_CALENDAR_DIM_COMPLETED] INT NULL
	,[ID_CALENDAR_DIM_END] INT NULL
	,[ID_PROVIDER_ACTIVITY_DIM] INT NULL
	,[ID_PROVIDER_DIM] INT NULL
	,[FL_EXPUNGED] CHAR(1) NULL
	)
