CREATE TABLE [dbo].[PROVIDER_ACTIVITY_DIM] (
	[ID_PROVIDER_ACTIVITY_DIM] INT NULL
	,[CD_ACTION] INT NULL
	,[TX_ACTION] VARCHAR(200) NULL
	,[DT_ROW_BEGIN] DATETIME NULL
	,[DT_ROW_END] DATETIME NULL
	,[ID_CYCLE] INT NULL
	,[IS_CURRENT] INT NULL
	)
