CREATE TABLE [dbo].[SIBLING_RELATIONSHIP_FACT] (
    [ID_SIBLING_RELATIONSHIP_FACT] INT           NOT NULL,
    [ID_CALENDAR_DIM_BEGIN]        INT           NULL,
    [ID_CALENDAR_DIM_END]          INT           NULL,
    [ID_CASE_DIM_CHILD]            INT           NULL,
    [ID_PEOPLE_DIM_CHILD]          INT           NULL,
    [ID_PEOPLE_DIM_SIBLING]        INT           NULL,
    [ID_PLACEMENT_FACT]            INT           NULL,
    [TX_RELATIONSHIP_TYPE]         VARCHAR (200) NULL,
    [FL_SIBLING_IN_PLACEMENT]      INT           NULL,
    [FL_TOGETHER]                  INT           NULL,
    [CHILD_AGE]                    INT           NULL,
    [SIBLING_AGE]                  INT           NULL,
    [ID_PRSN_CHILD]                INT           NULL,
    [ID_PRSN_SIBLING]              INT           NULL,
    [ID_CASE_CHILD]                INT           NULL,
    CONSTRAINT [PK_ID_SIBLING_RELATIONSHIP_FACT] PRIMARY KEY CLUSTERED ([ID_SIBLING_RELATIONSHIP_FACT] ASC),
    CONSTRAINT [fk_SIBLING_RELATIONSHIP_FACT_ID_CALENDAR_DIM_BEGIN] FOREIGN KEY ([ID_CALENDAR_DIM_BEGIN]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_SIBLING_RELATIONSHIP_FACT_ID_CALENDAR_DIM_END] FOREIGN KEY ([ID_CALENDAR_DIM_END]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_SIBLING_RELATIONSHIP_FACT_ID_CASE_DIM_CHILD] FOREIGN KEY ([ID_CASE_DIM_CHILD]) REFERENCES [dbo].[CASE_DIM] ([ID_CASE_DIM]),
    CONSTRAINT [fk_SIBLING_RELATIONSHIP_FACT_ID_PEOPLE_DIM_CHILD] FOREIGN KEY ([ID_PEOPLE_DIM_CHILD]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM]),
    CONSTRAINT [fk_SIBLING_RELATIONSHIP_FACT_ID_PEOPLE_DIM_SIBLING] FOREIGN KEY ([ID_PEOPLE_DIM_SIBLING]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM])
);

