CREATE TABLE [dbo].[SUBSTANCE_ABUSE_WIZARD_FACT] (
    [ID_SUBSTANCE_ABUSE_WIZARD_FACT]   INT           NULL,
    [ID_SUBSTANCE_ABUSE]               INT           NULL,
    [ID_INVESTIGATION_ASSESSMENT_FACT] INT           NULL,
    [ID_PEOPLE_DIM_SUBJECT]            INT           NULL,
    [CD_DRUG_ALCOHOL_PROBLEM]          INT           NULL,
    [TX_DRUG_ALCOHOL_PROBLEM]          VARCHAR (200) NULL,
    [CD_REFER_CHEM_DEP_SRVS]           INT           NULL,
    [TX_REFER_CHEM_DEP_SRVS]           VARCHAR (200) NULL,
    [CD_SUBST_ABUSE_SRVS]              INT           NULL,
    [TX_SUBST_ABUSE_SRVS]              VARCHAR (200) NULL,
    [FL_ALCOHOL_DURING_TWELVE_MOS]     TINYINT       NULL,
    [FL_ALCOHOL_PRIOR_TWELVE_MOS]      TINYINT       NULL,
    [FL_DRUG_DURING_TWELVE_MOS]        TINYINT       NULL,
    [FL_DRUG_PRIOR_TWELVE_MOS]         TINYINT       NULL,
    [FL_EXPUNGED]                      CHAR (1)      NULL,
    [ID_PRSN_SUBJECT]                  INT           NULL,
    CONSTRAINT [fk_SUBSTANCE_ABUSE_WIZARD_FACT_ID_PEOPLE_DIM_SUBJECT] FOREIGN KEY ([ID_PEOPLE_DIM_SUBJECT]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM])
);

