CREATE TABLE [dbo].[TANF_FACT] (
    [ID_TANF_FACT]                INT NOT NULL,
    [ID_AUTH]                     INT NULL,
    [ID_TANF]                     INT NULL,
    [ID_CALENDAR_DIM_BEGIN]       INT NULL,
    [ID_CALENDAR_DIM_END]         INT NULL,
    [ID_CASE_DIM]                 INT NULL,
    [ID_PEOPLE_DIM]               INT NULL,
    [ID_TANF_DIM]                 INT NULL,
    [ID_WORKER_DIM_COMPLETED]     INT NULL,
    [ID_WORKER_DIM_DETERMINATION] INT NULL,
    [FL_VOID]                     INT NULL,
    [ID_PRSN]                     INT NULL,
    [ID_CASE]                     INT NULL,
    PRIMARY KEY CLUSTERED ([ID_TANF_FACT] ASC),
    CONSTRAINT [fk_TANF_FACT_ID_CALENDAR_DIM_BEGIN] FOREIGN KEY ([ID_CALENDAR_DIM_BEGIN]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_TANF_FACT_ID_CALENDAR_DIM_END] FOREIGN KEY ([ID_CALENDAR_DIM_END]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_TANF_FACT_ID_CASE_DIM] FOREIGN KEY ([ID_CASE_DIM]) REFERENCES [dbo].[CASE_DIM] ([ID_CASE_DIM]),
    CONSTRAINT [fk_TANF_FACT_ID_PEOPLE_DIM] FOREIGN KEY ([ID_PEOPLE_DIM]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM]),
    CONSTRAINT [fk_TANF_FACT_ID_TANF_DIM] FOREIGN KEY ([ID_TANF_DIM]) REFERENCES [dbo].[TANF_DIM] ([ID_TANF_DIM]),
    CONSTRAINT [fk_TANF_FACT_ID_WORKER_DIM_COMPLETED] FOREIGN KEY ([ID_WORKER_DIM_COMPLETED]) REFERENCES [dbo].[WORKER_DIM] ([ID_WORKER_DIM]),
    CONSTRAINT [fk_TANF_FACT_ID_WORKER_DIM_DETERMINATION] FOREIGN KEY ([ID_WORKER_DIM_DETERMINATION]) REFERENCES [dbo].[WORKER_DIM] ([ID_WORKER_DIM])
);

