CREATE TABLE [base].[rptPlacement] (
    [tablekey]                           INT            NULL,
    [id_removal_episode_fact]            INT            NOT NULL,
    [child]                              INT            NOT NULL,
    [id_case]                            INT            NULL,
    [cd_case_type]                       INT            NULL,
    [tx_case_type]                       VARCHAR (200)  NULL,
    [tx_region]                          VARCHAR (200)  NULL,
    [cd_region]                          INT            NULL,
    [tx_office]                          VARCHAR (200)  NULL,
    [cd_office]                          INT            NULL,
    [tx_county]                          VARCHAR (200)  NULL,
    [cd_county]                          INT            NULL,
    [primary_worker]                     INT            NULL,
    [worker_region]                      VARCHAR (200)  NULL,
    [cd_worker_region]                   INT            NULL,
    [worker_office]                      VARCHAR (200)  NULL,
    [cd_worker_office]                   INT            NULL,
    [worker_county]                      VARCHAR (200)  NULL,
    [cd_worker_county]                   INT            NULL,
    [worker_unit]                        VARCHAR (200)  NULL,
    [episode_los]                        INT            NULL,
    [episode_los_grp]                    VARCHAR (200)  NULL,
    [placement_los]                      INT            NULL,
    [placement_los_grp]                  VARCHAR (200)  NULL,
    [removal_dt]                         DATETIME       NOT NULL,
    [id_calendar_dim_begin]              INT            NULL,
    [id_epsd]                            INT            NULL,
    [id_placement_fact]                  INT            NULL,
    [latest_plcmnt_dt]                   DATETIME       NULL,
    [latest_plcmnt_end_dt]               DATETIME       NULL,
    [last_end_rsn]                       VARCHAR (200)  NULL,
    [id_prvd_org_caregiver]              INT            NULL,
    [discharge_dt]                       DATETIME       NULL,
    [id_calendar_dim_afcars_end]         INT            NULL,
    [tx_epsd_type]                       VARCHAR (200)  NULL,
    [cd_epsd_type]                       INT            NULL,
    [birthdate]                          DATETIME       NULL,
    [tx_gndr]                            VARCHAR (200)  NULL,
    [18bday]                             DATETIME       NULL,
    [child_age]                          INT            NULL,
    [tx_braam_race]                      VARCHAR (200)  NULL,
    [tx_multirace]                       VARCHAR (200)  NULL,
    [setting]                            VARCHAR (200)  NULL,
    [tx_subctgry]                        VARCHAR (200)  NULL,
    [relative]                           INT            NULL,
    [cd_rel]                             INT            NULL,
    [tx_rel]                             VARCHAR (200)  NULL,
    [current_setting]                    INT            NULL,
    [current_service]                    VARCHAR (200)  NULL,
    [removal]                            DATETIME       NULL,
    [exit]                               DATETIME       NULL,
    [exit_reason]                        VARCHAR (200)  NULL,
    [tx_placement_care_auth]             VARCHAR (200)  NULL,
    [tx_lgl_stat]                        VARCHAR (200)  NULL,
    [tx_plcm_dsch_rsn]                   VARCHAR (200)  NULL,
    [tx_dsch_rsn]                        VARCHAR (200)  NULL,
    [trh]                                VARCHAR (20)   NULL,
    [ts_up]                              NVARCHAR (50)  NULL,
    [runtime]                            DATETIME       NULL,
    [mom_id]                             INT            NULL,
    [dad_id]                             INT            NULL,
    [placement_worker_id]                INT            NULL,
    [placement_worker_region]            VARCHAR (200)  NULL,
    [placement_worker_region_cd]         INT            NULL,
    [placement_worker_office]            VARCHAR (200)  NULL,
    [placement_worker_office_cd]         INT            NULL,
    [placement_worker_county]            VARCHAR (200)  NULL,
    [placement_worker_county_cd]         INT            NULL,
    [placement_worker_unit]              INT            NULL,
    [placement_workerint_level]          INT            NULL,
    [placement_workerint_reason]         VARCHAR (200)  NULL,
    [town]                               VARCHAR (200)  NULL,
    [zip]                                NVARCHAR (50)  NULL,
    [cd_cnty]                            INT            NULL,
    [staddress_type]                     VARCHAR (200)  NULL,
    [town_type]                          VARCHAR (200)  NULL,
    [zip_type]                           VARCHAR (200)  NULL,
    [cnty_type]                          VARCHAR (200)  NULL,
    [state]                              VARCHAR (200)  NULL,
    [fl_abandonment]                     INT            NULL,
    [fl_caretaker_inability_cope]        INT            NULL,
    [fl_child_abuse_alcohol]             INT            NULL,
    [fl_child_abuses_drug]               INT            NULL,
    [fl_child_behavior_problems]         INT            NULL,
    [fl_inadequate_housng]               INT            NULL,
    [fl_neglect]                         INT            NULL,
    [fl_parent_abuse_alcohol]            INT            NULL,
    [fl_parent_death]                    INT            NULL,
    [fl_parent_drug_abuse]               INT            NULL,
    [fl_parent_incarceration]            INT            NULL,
    [fl_physical_abuse]                  INT            NULL,
    [fl_sex_abuse]                       INT            NULL,
    [fl_relinquishment]                  INT            NULL,
    [primary_ppln]                       VARCHAR (200)  NULL,
    [cd_primary_ppln]                    INT            NULL,
    [alt_ppln]                           VARCHAR (200)  NULL,
    [lf_dt]                              DATETIME       NULL,
    [cd_alt_ppln]                        INT            NULL,
    [multi_race_mask]                    INT            NULL,
    [cd_hspnc]                           CHAR (1)       NULL,
    [tx_hspnc]                           VARCHAR (20)   NULL,
    [tx_tribe_name]                      VARCHAR (200)  NULL,
    [re-entry]                           VARCHAR (1)    NULL,
    [fl_false]                           INT            NULL,
    [dt_case_cls]                        DATETIME       NULL,
    [h&s]                                NVARCHAR (200) NULL,
    [visit_span]                         NVARCHAR (200) NULL,
    [lls_dt]                             DATETIME       NULL,
    [vpa_lngth]                          INT            NULL,
    [cd_rmvl_mnr]                        INT            NULL,
    [tx_rmvl_mnr]                        VARCHAR (200)  NULL,
    [cd_placement_care_auth]             INT            NULL,
    [orig_cd_plcm_dsch_rsn]              INT            NULL,
    [orig_tx_plcm_dsch_rsn]              VARCHAR (200)  NULL,
    [fl_child_clinically_diagnosed]      INT            NULL,
    [CD_MULTI_RACE_ETHNICITY]            INT            NULL,
    [TX_MULTI_RACE_ETHNICITY]            VARCHAR (200)  NULL,
    [dependency_dt]                      DATETIME       NULL,
    [fl_dep_exist]                       INT            NULL,
    [id_intake_fact]                     INT            NULL,
    [age_at_removal_mos]                 INT            NULL,
    [first_removal_dt]                   DATETIME       NULL,
    [latest_removal_dt]                  DATETIME       NULL,
    [child_eps_rank]                     INT            NULL,
    [child_cnt_episodes]                 INT            NULL,
    [cd_race_census]                     INT            NULL,
    [census_hispanic_latino_origin_cd]   INT            NULL,
    [initial_id_placement_fact]          INT            NULL,
    [longest_id_placement_fact]          INT            NULL,
    [next_reentry_date]                  DATETIME       NULL,
    [days_to_reentry]                    INT            NULL,
    [cd_discharge_type]                  INT            NULL,
    [max_bin_los_cd]                     INT            NULL,
    [bin_dep_cd]                         INT            NULL,
    [bin_ihs_svc_cd]                     INT            NULL,
    [dur_days]                           INT            NULL,
    [exit_within_month_mult3]            INT            NULL,
    [nxt_reentry_within_min_month_mult3] INT            NULL,
    [int_filter_service_category]        INT            NULL,
    [filter_service_budget]              INT            NULL,
    [nbr_events]                         INT            NULL,
    [bin_placement_cd]                   INT            NULL,
    [nbr_ooh_events]                     INT            NULL,
    [init_cd_plcm_setng]                 INT            NULL,
    [long_cd_plcm_setng]                 INT            NULL,
    [pk_gndr]                            INT            NULL,
    [cd_gndr]                            VARCHAR (1)    NULL,
    [removal_county_cd]                  INT            NULL,
    [removal_qtr]                        DATETIME       NULL,
    [discharge_qtr]                      DATETIME       NULL,
    [first_setting]                      VARCHAR (200)  NULL,
    [first_relative]                     INT            NULL,
    [fl_extended_foster_care]            INT            NULL, 
    [tx_placement_care_auth_last]        VARCHAR(200)   NULL, 
    [cd_placement_care_auth_last]        INT            NULL, 
    [cd_multirace]                       INT            NULL, 
    [cd_setting_drvd]                    VARCHAR(50)    NULL, 
    [cd_subctgry]                        INT            NULL, 
    [cd_current_service]                 INT            NULL, 
    [cd_exit_reason]                     INT            NULL, 
    [cd_lgl_stat]                        INT            NULL, 
    [cd_plcm_dsch_rsn]                   INT            NULL, 
    [cd_tribe_name]                      INT            NULL, 
    [cd_dsch_rsn]                        INT            NULL, 
    CONSTRAINT [PK_rptPlacement] PRIMARY KEY CLUSTERED ([id_removal_episode_fact] ASC)
);

