CREATE TABLE [ospi].[fed_to_state_id_xwalk] (
	[SURVYEAR] FLOAT NULL
	,[NCESSCH] FLOAT NULL
	,[FIPST] FLOAT NULL
	,[LEAID] FLOAT NULL
	,[SCHNO] FLOAT NULL
	,[STID] FLOAT NULL
	,[SEASCH] FLOAT NULL
	,[LEANM] NVARCHAR(255) NULL
	,[SCHNAM] NVARCHAR(255) NULL
	,[LCITY] NVARCHAR(255) NULL
	,[LSTATE] NVARCHAR(255) NULL
	,[LZIP] FLOAT NULL
	,[LZIP4] FLOAT NULL
	)
