CREATE TABLE [ospi].[ospi_enrollment] (
    [researchID]                            VARCHAR (7)  NULL,
    [SchoolYear]                            VARCHAR (4)  NULL,
    [DistrictCode]                          VARCHAR (5)  NULL,
    [DistrictName]                          VARCHAR (55) NULL,
    [ResidentDistrictCode]                  VARCHAR (5)  NULL,
    [ResidentDistrictName]                  VARCHAR (55) NULL,
    [SchoolCode]                            VARCHAR (4)  NULL,
    [SchoolName]                            VARCHAR (55) NULL,
    [LocationID]                            VARCHAR (55) NULL,
    [PrimarySchoolFlag]                     VARCHAR (4)  NULL,
    [MonthYearOfBirth]                      VARCHAR (7)  NULL,
    [Gender]                                VARCHAR (1)  NULL,
    [GradeLevel]                            VARCHAR (3)  NULL,
    [DateEnrolledinDistrict]                DATETIME     NULL,
    [DateExitedDistrict]                    DATETIME     NULL,
    [DateEnrolledinSchool]                  DATETIME     NULL,
    [DateExitedSchool]                      DATETIME     NULL,
    [WithdrawalCode]                        VARCHAR (20) NULL,
    [WithdrawalType]                        VARCHAR (80) NULL,
    [BirthCountryCode]                      VARCHAR (3)  NULL,
    [BirthCountry]                          VARCHAR (78) NULL,
    [ZipCode]                               VARCHAR (10) NULL,
    [FederalEthRaceRollupCode]              VARCHAR (2)  NULL,
    [FederalEthRaceRollupName]              VARCHAR (55) NULL,
    [PrimaryLanguageCode]                   VARCHAR (4)  NULL,
    [PrimaryLanguage]                       VARCHAR (22) NULL,
    [LanguageSpokenatHomeCode]              VARCHAR (5)  NULL,
    [LanguageSpokenatHome]                  VARCHAR (22) NULL,
    [GradReqYear]                           VARCHAR (4)  NULL,
    [ExpectedGradYear]                      VARCHAR (4)  NULL,
    [CumulativeGPA]                         VARCHAR (10) NULL,
    [CumulativeCreditsAttempted]            FLOAT (53)   NULL,
    [CumulativeCreditsEarned]               VARCHAR (10) NULL,
    [NumDaysPresent]                        VARCHAR (3)  NULL,
    [NumUnexcusedAbsences]                  VARCHAR (3)  NULL,
    [DisabilityFlag]                        VARCHAR (1)  NULL,
    [ApprvdPrivateSchoolAttendPartTimeFlag] VARCHAR (1)  NULL,
    [HomeBasedAttendPartTimeFlag]           VARCHAR (1)  NULL,
    [F1VisaForeignExchgFlag]                VARCHAR (1)  NULL,
    [FreeReducedLunchFlag]                  VARCHAR (1)  NULL,
    [HomelessFlag]                          VARCHAR (1)  NULL,
    [FosterCareFlag]                        VARCHAR (1)  NULL,
    [v504Flag]                              VARCHAR (1)  NULL,
    [GiftedFlag]                            VARCHAR (1)  NULL,
    [MigrantFlag]                           VARCHAR (1)  NULL,
    [BilingualFlag]                         VARCHAR (1)  NULL,
    [SpecialEdFlag]                         VARCHAR (1)  NULL,
    [SubmitDate]                            VARCHAR (10) NULL,
    [ExtractDate]                           DATETIME     NULL
);

