CREATE TABLE [ospi].[ospi_episodes] (
    [researchid]                    NVARCHAR (14) NULL,
    [int_researchID]                INT           NOT NULL,
    [placeid]                       NVARCHAR (24) NULL,
    [placement_type]                NVARCHAR (4)  NULL,
    [epstrt_dte]                    DATETIME      NULL,
    [epend_dte]                     DATETIME      NULL,
    [strt_dte]                      DATETIME      NULL,
    [end_dte]                       DATETIME      NULL,
    [miss]                          NVARCHAR (2)  NULL,
    [mtch]                          NVARCHAR (6)  NULL,
    [temp_flag]                     NVARCHAR (2)  NULL,
    [disp]                          SMALLINT      NULL,
    [fosterkeep]                    SMALLINT      NULL,
    [region]                        NVARCHAR (2)  NULL,
    [custody]                       NVARCHAR (4)  NULL,
    [placement_result]              NVARCHAR (4)  NULL,
    [FL_SEX_ABUSE]                  SMALLINT      NULL,
    [FL_PHYSICAL_ABUSE]             SMALLINT      NULL,
    [FL_NEGLECT]                    SMALLINT      NULL,
    [FL_PARENT_ABUSE_ALCOHOL]       SMALLINT      NULL,
    [FL_PARENT_DRUG_ABUSE]          SMALLINT      NULL,
    [FL_CHILD_ABUSE_ALCOHOL]        SMALLINT      NULL,
    [FL_CHILD_ABUSE_DRUG]           SMALLINT      NULL,
    [FL_CHILD_CLINICALLY_DIAGNOSED] SMALLINT      NULL,
    [FL_CHILD_BEHAVIOR_PROBLEMS]    SMALLINT      NULL,
    [FL_PARENT_DEATH]               SMALLINT      NULL,
    [FL_PARENT_INCARCERATION]       SMALLINT      NULL,
    [FL_CARETAKER_INABILITY_COPE]   SMALLINT      NULL,
    [FL_ABANDONMENT]                SMALLINT      NULL,
    [FL_INADEQUATE_HOUSING]         SMALLINT      NULL,
    [FL_ABUSE]                      SMALLINT      NULL,
    [FL_REENTRY]                    SMALLINT      NULL,
    [FL_RELINQUISHMENT]             SMALLINT      NULL,
    [FL_AAFC]                       SMALLINT      NULL,
    [plcmnttime]                    SMALLINT      NULL,
    [shortep]                       SMALLINT      NULL,
    [brth_dte]                      DATETIME      NULL,
    [age_at_placement]              SMALLINT      NULL
);

