CREATE TABLE [prtl].[cache_ooh_wb_siblings_params]
(
    [qry_id] INT NOT NULL, 
    [age_grouping_cd] VARCHAR(20) NOT NULL, 
    [cd_race_census] VARCHAR(30) NOT NULL, 
    [pk_gndr] VARCHAR(10) NOT NULL, 
    [init_cd_plcm_setng] VARCHAR(50) NOT NULL, 
    [long_cd_plcm_setng] VARCHAR(50) NOT NULL, 
    [county_cd] VARCHAR(200) NOT NULL, 
    [bin_los_cd] VARCHAR(30) NOT NULL, 
    [bin_placement_cd] VARCHAR(30) NOT NULL, 
    [bin_ihs_svc_cd] VARCHAR(30) NOT NULL, 
    [cd_reporter_type] VARCHAR(100) NOT NULL, 
    [filter_access_type] VARCHAR(30) NOT NULL, 
    [filter_allegation] VARCHAR(30) NOT NULL, 
    [filter_finding] VARCHAR(30) NOT NULL, 
    [filter_service_type] VARCHAR(50) NOT NULL, 
    [filter_budget] VARCHAR(50) NOT NULL, 
    [bin_dep_cd] VARCHAR(20) NOT NULL, 
    [min_start_date] DATETIME NOT NULL, 
    [max_start_date] DATETIME NOT NULL, 
    [cnt_qry] INT NOT NULL, 
    [last_run_date] DATETIME NOT NULL, 
    PRIMARY KEY ([age_grouping_cd], [cd_race_census], [pk_gndr], [init_cd_plcm_setng], [long_cd_plcm_setng], [county_cd], [bin_los_cd], [bin_placement_cd], [bin_ihs_svc_cd], [cd_reporter_type], [filter_access_type], [filter_allegation], [filter_finding], [filter_service_type], [filter_budget], [bin_dep_cd])
)
