CREATE TABLE [prtl].[ooh_outcomes_params] (
    [qry_id] INT NOT NULL IDENTITY(1,1) 
        CONSTRAINT [pk_ooh_outcomes_params] PRIMARY KEY, 
    [age_grouping_cd] VARCHAR(20) NOT NULL, 
    [cd_race_census] VARCHAR(30) NOT NULL, 
    [pk_gender] VARCHAR(10) NOT NULL, 
    [initial_cd_placement_setting] VARCHAR(50) NOT NULL, 
    [longest_cd_placement_setting] VARCHAR(50) NOT NULL, 
    [cd_county] VARCHAR(200) NOT NULL, 
    [bin_los_cd] VARCHAR(30) NOT NULL, 
    [bin_placement_cd] VARCHAR(30) NOT NULL, 
    [bin_ihs_service_cd] VARCHAR(30) NOT NULL, 
    [cd_reporter_type] VARCHAR(100) NOT NULL, 
    [cd_access_type] VARCHAR(30) NOT NULL, 
    [cd_allegation] VARCHAR(30) NOT NULL, 
    [cd_finding] VARCHAR(30) NOT NULL, 
    [bin_dependency_cd] VARCHAR(20) NOT NULL, 
    [min_start_date] DATETIME NOT NULL, 
    [max_start_date] DATETIME NOT NULL, 
    [cnt_qry_outcomes] INT NOT NULL, 
    [cnt_qry_outcomes_3m] INT NOT NULL, 
    [cnt_qry_outcomes_12m] INT NOT NULL, 
    [cnt_qry_outcomes_24m] INT NOT NULL, 
    [last_run_date] DATETIME NOT NULL, 
    CONSTRAINT [idx_ooh_outcomes_params] UNIQUE NONCLUSTERED (
        [age_grouping_cd], 
        [cd_race_census], 
        [pk_gender], 
        [initial_cd_placement_setting], 
        [longest_cd_placement_setting], 
        [cd_county], 
        [bin_los_cd], 
        [bin_placement_cd], 
        [bin_ihs_service_cd], 
        [cd_reporter_type], 
        [cd_access_type], 
        [cd_allegation], 
        [cd_finding], 
        [bin_dependency_cd] 
		)
	)
