CREATE TABLE [prtl].[ooh_flow_entries_params] (
    [qry_id] INT NOT NULL IDENTITY(1,1) 
        CONSTRAINT [pk_ooh_flow_entries_params] PRIMARY KEY, 
    [age_grouping_cd] VARCHAR(20) NOT NULL, 
    [pk_gender] VARCHAR(10) NOT NULL, 
    [cd_race_census] VARCHAR(30) NOT NULL, 
    [initial_cd_placement_setting] VARCHAR(50) NOT NULL, 
    [longest_cd_placement_setting] VARCHAR(50) NOT NULL, 
    [cd_county] VARCHAR(200) NOT NULL, 
    [bin_los_cd] VARCHAR(30) NOT NULL, 
    [bin_placement_cd] VARCHAR(30) NOT NULL, 
    [bin_ihs_service_cd] VARCHAR(30) NOT NULL, 
    [cd_reporter_type] VARCHAR(100) NOT NULL, 
    [cd_access_type] VARCHAR(30) NOT NULL, 
    [cd_allegation] VARCHAR(30) NOT NULL, 
    [cd_finding] VARCHAR(30) NOT NULL, 
    [bin_dependency_cd] VARCHAR(20) NOT NULL, 
    [min_start_date] DATETIME NOT NULL, 
    [max_start_date] DATETIME NOT NULL, 
    [cnt_qry_counts] INT NOT NULL, 
	[cnt_qry_rates] INT NOT NULL, 
    [last_run_date] DATETIME NOT NULL, 
    CONSTRAINT [idx_ooh_flow_entries_params] UNIQUE NONCLUSTERED ( 
        [age_grouping_cd], 
        [pk_gender], 
        [cd_race_census], 
        [initial_cd_placement_setting], 
        [longest_cd_placement_setting], 
        [cd_county], 
        [bin_los_cd], 
        [bin_placement_cd], 
        [bin_ihs_service_cd], 
        [cd_reporter_type], 
        [cd_access_type], 
        [cd_allegation], 
        [cd_finding], 
        [bin_dependency_cd] 
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
