CREATE TABLE [oliver].[VISITATION_REFERRAL_FACT] (
	[ID_VISITATION_REFERRAL_FACT] VARCHAR(50) NULL
	,[ID_PROVIDER_DIM] VARCHAR(50) NULL
	,[ID_CASE_DIM] VARCHAR(50) NULL
	,[ID_CALENDAR_DIM_RCVD] VARCHAR(50) NULL
	)
