CREATE TABLE [poc_survey].[derived_tbl_burnout_study] (
    [r_respondent_id]         FLOAT (53)      NULL,
    [rda_start_date]          DATETIME        NULL,
    [closest_id_prsn]         INT             NULL,
    [closest_id_worker_dim]   INT             NULL,
    [cd_office]               INT             NULL,
    [cd_unit]                 INT             NULL,
    [tx_unit]                 VARCHAR (200)   NULL,
    [id_prsn_sprv]            INT             NULL,
    [newest_derived_start_dt] DATETIME        NULL,
    [unit_new_ooh_cases]      INT             NULL,
    [unit_new_cps_cases]      INT             NULL,
    [cnt_respodents_srv]      INT             NULL,
    [cnt_respodents_wd]       INT             NULL,
    [office_number]           FLOAT (53)      NULL,
    [unit_id]                 NVARCHAR (5)    NULL,
    [derived_unit_id]         INT             NULL,
    [derived_cnt_respondents] INT             NULL,
    [any_fvs]                 INT             NULL,
    [any_cfws]                INT             NULL,
    [any_frs]                 INT             NULL,
    [any_cps]                 INT             NULL,
    [any_dlr_cps]             INT             NULL,
    [any_dlr_lic]             INT             NULL,
    [any_intk]                INT             NULL,
    [any_adtp]                INT             NULL,
    [program_area_sum]        INT             NULL,
    [tenure_at_survey]        NUMERIC (18, 6) NULL,
    [years_position]          FLOAT (53)      NULL,
    [female]                  INT             NULL,
    [deg_any_BA]              INT             NULL,
    [deg_any_GRAD]            INT             NULL,
    [MSW]                     INT             NULL,
    [BSW]                     INT             NULL,
    [degree_year]             FLOAT (53)      NULL,
    [spc_training]            INT             NULL,
    [worker_age]              FLOAT (53)      NULL,
    [race_any_cauc]           INT             NULL,
    [race_any_afra]           INT             NULL,
    [race_any_aian]           INT             NULL,
    [race_any_aapi]           INT             NULL,
    [race_any_hisp]           INT             NULL,
    [race_any_other]          INT             NULL,
    [q3a]                     FLOAT (53)      NULL,
    [q3b]                     FLOAT (53)      NULL,
    [q3c]                     FLOAT (53)      NULL,
    [q3e]                     FLOAT (53)      NULL,
    [q3f]                     FLOAT (53)      NULL,
    [q3g]                     FLOAT (53)      NULL,
    [q3h]                     FLOAT (53)      NULL,
    [q3i]                     FLOAT (53)      NULL,
    [q3j]                     FLOAT (53)      NULL,
    [q3k]                     FLOAT (53)      NULL,
    [q3l]                     FLOAT (53)      NULL,
    [q3m]                     FLOAT (53)      NULL,
    [q3n]                     FLOAT (53)      NULL,
    [q3o]                     FLOAT (53)      NULL,
    [q3p]                     FLOAT (53)      NULL,
    [q3q]                     FLOAT (53)      NULL,
    [q5b]                     FLOAT (53)      NULL,
    [q6a]                     FLOAT (53)      NULL,
    [q6j]                     FLOAT (53)      NULL,
    [q6k]                     FLOAT (53)      NULL,
    [q6l]                     FLOAT (53)      NULL,
    [q6m]                     FLOAT (53)      NULL,
    [q6o]                     FLOAT (53)      NULL,
    [q6p]                     FLOAT (53)      NULL,
    [q6q]                     FLOAT (53)      NULL,
    [Rq7a]                    FLOAT (53)      NULL,
    [q7b]                     FLOAT (53)      NULL,
    [Rq7c]                    FLOAT (53)      NULL,
    [q7d]                     FLOAT (53)      NULL,
    [Rq7e]                    FLOAT (53)      NULL,
    [q7f]                     FLOAT (53)      NULL,
    [q7g]                     FLOAT (53)      NULL,
    [q7h]                     FLOAT (53)      NULL,
    [q7i]                     FLOAT (53)      NULL,
    [q7j]                     FLOAT (53)      NULL,
    [q7k]                     FLOAT (53)      NULL,
    [q7l]                     FLOAT (53)      NULL,
    [q7m]                     FLOAT (53)      NULL,
    [q7n]                     FLOAT (53)      NULL,
    [q8a]                     FLOAT (53)      NULL,
    [Rq8b]                    FLOAT (53)      NULL,
    [q8c]                     FLOAT (53)      NULL,
    [q8d]                     FLOAT (53)      NULL,
    [q8e]                     FLOAT (53)      NULL,
    [q8f]                     FLOAT (53)      NULL,
    [q8g]                     FLOAT (53)      NULL,
    [q9a]                     FLOAT (53)      NULL,
    [q9b]                     FLOAT (53)      NULL,
    [q9c]                     FLOAT (53)      NULL,
    [q9d]                     FLOAT (53)      NULL,
    [Rq9d]                    FLOAT (53)      NULL,
    [q9e]                     FLOAT (53)      NULL,
    [q9f]                     FLOAT (53)      NULL,
    [q9g]                     FLOAT (53)      NULL,
    [q9h]                     FLOAT (53)      NULL,
    [q10a]                    FLOAT (53)      NULL,
    [q10c]                    FLOAT (53)      NULL,
    [q10e]                    FLOAT (53)      NULL,
    [q10h]                    FLOAT (53)      NULL,
    [q10i]                    FLOAT (53)      NULL,
    [q10p]                    FLOAT (53)      NULL,
    [q10q]                    FLOAT (53)      NULL,
    [q10b]                    FLOAT (53)      NULL,
    [q10d]                    FLOAT (53)      NULL,
    [q10g]                    FLOAT (53)      NULL,
    [q10o]                    FLOAT (53)      NULL,
    [q10r]                    FLOAT (53)      NULL,
    [q10s]                    FLOAT (53)      NULL,
    [q6h]                     FLOAT (53)      NULL,
    [q6i]                     FLOAT (53)      NULL,
    [q6f]                     FLOAT (53)      NULL,
    [q6g]                     FLOAT (53)      NULL,
    [q6u]                     FLOAT (53)      NULL,
    [q6v]                     FLOAT (53)      NULL
);

