CREATE TABLE [poc_survey].[ps_Original_Openwithplacements_BA_added] (
    [STUDY_ID]                  FLOAT (53)   NULL,
    [PLCMNT_ID]                 FLOAT (53)   NULL,
    [PLCMNT_TYPE_CODE_6_08]     VARCHAR (2)  NULL,
    [PLCMNT_TYPE_CODE_6_08_num] FLOAT (53)   NULL,
    [OFF_CASE6]                 FLOAT (53)   NULL,
    [BA_match]                  FLOAT (53)   NULL,
    [BA_prev_plcmnt_type]       VARCHAR (2)  NULL,
    [BA_prev_reslt]             VARCHAR (2)  NULL,
    [BA_prev_days]              FLOAT (53)   NULL,
    [BA_with_end_date]          FLOAT (53)   NULL,
    [BA_catch_result]           VARCHAR (2)  NULL,
    [Person_Id]                 FLOAT (53)   NULL,
    [Case_Number]               VARCHAR (10) NULL,
    [Placement_Type]            VARCHAR (2)  NULL,
    [Placement_Type_num]        FLOAT (53)   NULL,
    [Placement_Date]            DATETIME     NULL,
    [Placement_Episode_End]     DATETIME     NULL,
    [Placement_Result]          VARCHAR (2)  NULL,
    [Gender]                    VARCHAR (1)  NULL,
    [DOB]                       DATETIME     NULL,
    [age_at_placement]          FLOAT (53)   NULL,
    [los]                       FLOAT (53)   NULL,
    [ethnc1]                    FLOAT (53)   NULL,
    [ethnc2]                    FLOAT (53)   NULL,
    [ethnc3]                    FLOAT (53)   NULL,
    [ethnc4]                    FLOAT (53)   NULL,
    [ethnc5]                    FLOAT (53)   NULL,
    [ethnc6]                    FLOAT (53)   NULL,
    [Hispanic]                  FLOAT (53)   NULL,
    [singlrac]                  FLOAT (53)   NULL,
    [nreason1]                  FLOAT (53)   NULL,
    [nreason2]                  FLOAT (53)   NULL,
    [nreason3]                  FLOAT (53)   NULL,
    [nreason4]                  FLOAT (53)   NULL,
    [rmvsexab]                  FLOAT (53)   NULL,
    [rmvphyab]                  FLOAT (53)   NULL,
    [rmvnegl]                   FLOAT (53)   NULL,
    [rmvalabp]                  FLOAT (53)   NULL,
    [rmvdrabp]                  FLOAT (53)   NULL,
    [rmvalabc]                  FLOAT (53)   NULL,
    [rmvdrabc]                  FLOAT (53)   NULL,
    [rmvddc]                    FLOAT (53)   NULL,
    [rmvbvprc]                  FLOAT (53)   NULL,
    [rmvdeath]                  FLOAT (53)   NULL,
    [rmvjail]                   FLOAT (53)   NULL,
    [rmvddp]                    FLOAT (53)   NULL,
    [rmvaband]                  FLOAT (53)   NULL,
    [rmvihous]                  FLOAT (53)   NULL,
    [rmvmajab]                  FLOAT (53)   NULL,
    [rmvcan]                    FLOAT (53)   NULL,
    [rmvpsa]                    FLOAT (53)   NULL,
    [rmvcsa]                    FLOAT (53)   NULL
);

