CREATE TABLE [poc_survey].[tbl_burnout_study] (
	[r_respondent_id] FLOAT NULL
	,[rda_start_date] DATETIME NULL
	,[closest_id_prsn] INT NULL
	,[closest_id_worker_dim] INT NULL
	,[cd_office] INT NULL
	,[cd_unit] INT NULL
	,[tx_unit] VARCHAR(200) NULL
	,[id_prsn_sprv] INT NULL
	,[newest_derived_start_dt] DATETIME NULL
	,[unit_new_ooh_cases] INT NULL
	,[unit_new_cps_cases] INT NULL
	,[cnt_respodents_srv] INT NULL
	,[cnt_respodents_wd] INT NULL
	,[office_number] FLOAT NULL
	,[unit_id] [nvarchar](5) NULL
	,[derived_unit_id] INT NULL
	,[derived_cnt_respondents] INT NULL
	,[any_fvs] INT NULL
	,[any_cfws] INT NULL
	,[any_frs] INT NULL
	,[any_cps] INT NULL
	,[any_dlr_cps] INT NULL
	,[any_dlr_lic] INT NULL
	,[any_intk] INT NULL
	,[any_adtp] INT NULL
	,[program_area_sum] INT NULL
	,[tenure_at_survey] NUMERIC(18, 6) NULL
	,[years_position] FLOAT NULL
	,[female] INT NULL
	,[deg_any_BA] INT NULL
	,[deg_any_GRAD] INT NULL
	,[MSW] INT NULL
	,[BSW] INT NULL
	,[degree_year] FLOAT NULL
	,[spc_training] INT NULL
	,[worker_age] FLOAT NULL
	,[race_any_cauc] INT NULL
	,[race_any_afra] INT NULL
	,[race_any_aian] INT NULL
	,[race_any_aapi] INT NULL
	,[race_any_hisp] INT NULL
	,[race_any_other] INT NULL
	,[q5b] FLOAT NULL
	,[q6a] FLOAT NULL
	,[q6j] FLOAT NULL
	,[q6k] FLOAT NULL
	,[q6l] FLOAT NULL
	,[q6m] FLOAT NULL
	,[q6o] FLOAT NULL
	,[q6p] FLOAT NULL
	,[q6q] FLOAT NULL
	,[Rq7a] FLOAT NULL
	,[q7b] FLOAT NULL
	,[Rq7c] FLOAT NULL
	,[q7d] FLOAT NULL
	,[Rq7e] FLOAT NULL
	,[q7f] FLOAT NULL
	,[q7g] FLOAT NULL
	,[q7h] FLOAT NULL
	,[q7i] FLOAT NULL
	,[q7j] FLOAT NULL
	,[q7k] FLOAT NULL
	,[q7l] FLOAT NULL
	,[q7m] FLOAT NULL
	,[q7n] FLOAT NULL
	,[q8a] FLOAT NULL
	,[Rq8b] FLOAT NULL
	,[q8c] FLOAT NULL
	,[q8d] FLOAT NULL
	,[q8e] FLOAT NULL
	,[q8f] FLOAT NULL
	,[q8g] FLOAT NULL
	,[q9a] FLOAT NULL
	,[q9b] FLOAT NULL
	,[q9c] FLOAT NULL
	,[q9d] FLOAT NULL
	,[Rq9d] FLOAT NULL
	,[q9e] FLOAT NULL
	,[q9f] FLOAT NULL
	,[q9g] FLOAT NULL
	,[q9h] FLOAT NULL
	,[q10a] FLOAT NULL
	,[q10c] FLOAT NULL
	,[q10e] FLOAT NULL
	,[q10h] FLOAT NULL
	,[q10i] FLOAT NULL
	,[q10p] FLOAT NULL
	,[q10q] FLOAT NULL
	,[q10b] FLOAT NULL
	,[q10d] FLOAT NULL
	,[q10g] FLOAT NULL
	,[q10o] FLOAT NULL
	,[q10r] FLOAT NULL
	,[q10s] FLOAT NULL
	,[q6h] FLOAT NULL
	,[q6i] FLOAT NULL
	,[q6f] FLOAT NULL
	,[q6g] FLOAT NULL
	,[q6u] FLOAT NULL
	,[q6v] FLOAT NULL
	)
