CREATE TABLE [ndacan].[afcars_foster_care_00_13_spss] (
	[datayear] FLOAT NULL
	,[version] FLOAT NULL
	,[state] FLOAT NULL
	,[st] VARCHAR(255) NULL
	,[repdatyr] FLOAT NULL
	,[repdatmo] FLOAT NULL
	,[fipscode] FLOAT NULL
	,[recnumbr] VARCHAR(255) NULL
	,[sex] FLOAT NULL
	,[amiakn] FLOAT NULL
	,[asian] FLOAT NULL
	,[blkafram] FLOAT NULL
	,[hawaiipi] FLOAT NULL
	,[white] FLOAT NULL
	,[untodetm] FLOAT NULL
	,[hisorgin] FLOAT NULL
	,[clindis] FLOAT NULL
	,[mr] FLOAT NULL
	,[vishear] FLOAT NULL
	,[phydis] FLOAT NULL
	,[dsmiii] FLOAT NULL
	,[othermed] FLOAT NULL
	,[everadpt] FLOAT NULL
	,[ageadopt] FLOAT NULL
	,[totalrem] FLOAT NULL
	,[numplep] FLOAT NULL
	,[manrem] FLOAT NULL
	,[phyabuse] FLOAT NULL
	,[sexabuse] FLOAT NULL
	,[neglect] FLOAT NULL
	,[aaparent] FLOAT NULL
	,[daparent] FLOAT NULL
	,[aachild] FLOAT NULL
	,[dachild] FLOAT NULL
	,[childis] FLOAT NULL
	,[chbehprb] FLOAT NULL
	,[prtsdied] FLOAT NULL
	,[prtsjail] FLOAT NULL
	,[nocope] FLOAT NULL
	,[abandmnt] FLOAT NULL
	,[relinqsh] FLOAT NULL
	,[housing] FLOAT NULL
	,[curplset] FLOAT NULL
	,[placeout] FLOAT NULL
	,[casegoal] FLOAT NULL
	,[ctkfamst] FLOAT NULL
	,[ctk1yr] FLOAT NULL
	,[ctk2yr] FLOAT NULL
	,[fosfamst] FLOAT NULL
	,[fcctk1yr] FLOAT NULL
	,[fcctk2yr] FLOAT NULL
	,[rf1amakn] FLOAT NULL
	,[rf1asian] FLOAT NULL
	,[rf1blkaa] FLOAT NULL
	,[rf1nhopi] FLOAT NULL
	,[rf1white] FLOAT NULL
	,[rf1utod] FLOAT NULL
	,[hofcctk1] FLOAT NULL
	,[rf2amakn] FLOAT NULL
	,[rf2asian] FLOAT NULL
	,[rf2blkaa] FLOAT NULL
	,[rf2nhopi] FLOAT NULL
	,[rf2white] FLOAT NULL
	,[rf2utod] FLOAT NULL
	,[hofcctk2] FLOAT NULL
	,[disreasn] FLOAT NULL
	,[ivefc] FLOAT NULL
	,[iveaa] FLOAT NULL
	,[ivaafdc] FLOAT NULL
	,[ivdchsup] FLOAT NULL
	,[xixmedcd] FLOAT NULL
	,[ssiother] FLOAT NULL
	,[noa] FLOAT NULL
	,[fcmntpay] FLOAT NULL
	,[dob] FLOAT NULL
	,[rem1dt] FLOAT NULL
	,[dlstfcdt] FLOAT NULL
	,[latremdt] FLOAT NULL
	,[cursetdt] FLOAT NULL
	,[dodfcdt] FLOAT NULL
	,[tprmomdt] FLOAT NULL
	,[tprdaddt] FLOAT NULL
	,[tprdate] FLOAT NULL
	,[pedrevdt] FLOAT NULL
	,[remtrndt] FLOAT NULL
	,[dodtrndt] FLOAT NULL
	,[latremlos] FLOAT NULL
	,[settinglos] FLOAT NULL
	,[previouslos] FLOAT NULL
	,[lifelos] FLOAT NULL
	,[ageatstart] FLOAT NULL
	,[ageatlatrem] FLOAT NULL
	,[ageatend] FLOAT NULL
	,[inatstart] FLOAT NULL
	,[inatend] FLOAT NULL
	,[entered] FLOAT NULL
	,[exited] FLOAT NULL
	,[served] FLOAT NULL
	,[iswaiting] FLOAT NULL
	,[istpr] FLOAT NULL
	,[agedout] FLOAT NULL
	,[raceethn] FLOAT NULL
	)
