CREATE TABLE [ndacan].[afcars_foster_care_00_13] (
    [datayear]    INT           NULL,
    [version]     INT           NULL,
    [state]       VARCHAR (255) NULL,
    [st]          VARCHAR (255) NULL,
    [repdatyr]    INT           NULL,
    [repdatmo]    INT           NULL,
    [fipscode]    VARCHAR (255) NULL,
    [recnumbr]    VARCHAR (255) NULL,
    [sex]         VARCHAR (255) NULL,
    [amiakn]      VARCHAR (255) NULL,
    [asian]       VARCHAR (255) NULL,
    [blkafram]    VARCHAR (255) NULL,
    [hawaiipi]    VARCHAR (255) NULL,
    [white]       VARCHAR (255) NULL,
    [untodetm]    VARCHAR (255) NULL,
    [hisorgin]    VARCHAR (255) NULL,
    [clindis]     VARCHAR (255) NULL,
    [mr]          VARCHAR (255) NULL,
    [vishear]     VARCHAR (255) NULL,
    [phydis]      VARCHAR (255) NULL,
    [dsmiii]      VARCHAR (255) NULL,
    [othermed]    VARCHAR (255) NULL,
    [everadpt]    VARCHAR (255) NULL,
    [ageadopt]    VARCHAR (255) NULL,
    [totalrem]    INT           NULL,
    [numplep]     INT           NULL,
    [manrem]      VARCHAR (255) NULL,
    [phyabuse]    VARCHAR (255) NULL,
    [sexabuse]    VARCHAR (255) NULL,
    [neglect]     VARCHAR (255) NULL,
    [aaparent]    VARCHAR (255) NULL,
    [daparent]    VARCHAR (255) NULL,
    [aachild]     VARCHAR (255) NULL,
    [dachild]     VARCHAR (255) NULL,
    [childis]     VARCHAR (255) NULL,
    [chbehprb]    VARCHAR (255) NULL,
    [prtsdied]    VARCHAR (255) NULL,
    [prtsjail]    VARCHAR (255) NULL,
    [nocope]      VARCHAR (255) NULL,
    [abandmnt]    VARCHAR (255) NULL,
    [relinqsh]    VARCHAR (255) NULL,
    [housing]     VARCHAR (255) NULL,
    [curplset]    VARCHAR (255) NULL,
    [placeout]    VARCHAR (255) NULL,
    [casegoal]    VARCHAR (255) NULL,
    [ctkfamst]    VARCHAR (255) NULL,
    [ctk1yr]      INT           NULL,
    [ctk2yr]      INT           NULL,
    [fosfamst]    VARCHAR (255) NULL,
    [fcctk1yr]    INT           NULL,
    [fcctk2yr]    INT           NULL,
    [rf1amakn]    VARCHAR (255) NULL,
    [rf1asian]    VARCHAR (255) NULL,
    [rf1blkaa]    VARCHAR (255) NULL,
    [rf1nhopi]    VARCHAR (255) NULL,
    [rf1white]    VARCHAR (255) NULL,
    [rf1utod]     VARCHAR (255) NULL,
    [hofcctk1]    VARCHAR (255) NULL,
    [rf2amakn]    VARCHAR (255) NULL,
    [rf2asian]    VARCHAR (255) NULL,
    [rf2blkaa]    VARCHAR (255) NULL,
    [rf2nhopi]    VARCHAR (255) NULL,
    [rf2white]    VARCHAR (255) NULL,
    [rf2utod]     VARCHAR (255) NULL,
    [hofcctk2]    VARCHAR (255) NULL,
    [disreasn]    VARCHAR (255) NULL,
    [ivefc]       VARCHAR (255) NULL,
    [iveaa]       VARCHAR (255) NULL,
    [ivaafdc]     VARCHAR (255) NULL,
    [ivdchsup]    VARCHAR (255) NULL,
    [xixmedcd]    VARCHAR (255) NULL,
    [ssiother]    VARCHAR (255) NULL,
    [noa]         VARCHAR (255) NULL,
    [fcmntpay]    INT           NULL,
    [dob]         VARCHAR (255) NULL,
    [rem1dt]      VARCHAR (255) NULL,
    [dlstfcdt]    VARCHAR (255) NULL,
    [latremdt]    VARCHAR (255) NULL,
    [cursetdt]    VARCHAR (255) NULL,
    [dodfcdt]     VARCHAR (255) NULL,
    [tprmomdt]    VARCHAR (255) NULL,
    [tprdaddt]    VARCHAR (255) NULL,
    [tprdate]     VARCHAR (255) NULL,
    [pedrevdt]    VARCHAR (255) NULL,
    [remtrndt]    VARCHAR (255) NULL,
    [dodtrndt]    VARCHAR (255) NULL,
    [latremlos]   INT           NULL,
    [settinglos]  INT           NULL,
    [previouslos] INT           NULL,
    [lifelos]     INT           NULL,
    [ageatstart]  INT           NULL,
    [ageatlatrem] INT           NULL,
    [ageatend]    INT           NULL,
    [inatstart]   VARCHAR (255) NULL,
    [inatend]     VARCHAR (255) NULL,
    [entered]     VARCHAR (255) NULL,
    [exited]      VARCHAR (255) NULL,
    [served]      VARCHAR (255) NULL,
    [iswaiting]   VARCHAR (255) NULL,
    [istpr]       VARCHAR (255) NULL,
    [agedout]     VARCHAR (255) NULL,
    [raceethn]    VARCHAR (255) NULL,
    [ru13]        VARCHAR (255) NULL,
    [multi]       INT           NULL
);

