CREATE TABLE [ndacan].[afcars_adoption_00_13] (
    [state]       VARCHAR (255) NULL,
    [st]          VARCHAR (255) NULL,
    [repdatyr]    INT           NULL,
    [repdatmo]    INT           NULL,
    [recnum]      VARCHAR (255) NULL,
    [agnyinvl]    VARCHAR (255) NULL,
    [dob]         VARCHAR (255) NULL,
    [sex]         VARCHAR (255) NULL,
    [amiakn]      VARCHAR (255) NULL,
    [asian]       VARCHAR (255) NULL,
    [blkafram]    VARCHAR (255) NULL,
    [hawaiipi]    VARCHAR (255) NULL,
    [white]       VARCHAR (255) NULL,
    [untodetm]    VARCHAR (255) NULL,
    [hisorgin]    VARCHAR (255) NULL,
    [agyspnds]    VARCHAR (255) NULL,
    [basspnds]    VARCHAR (255) NULL,
    [mr]          VARCHAR (255) NULL,
    [vishear]     VARCHAR (255) NULL,
    [phydis]      VARCHAR (255) NULL,
    [dsmiii]      VARCHAR (255) NULL,
    [othrmed]     VARCHAR (255) NULL,
    [dobyrmom]    INT           NULL,
    [dobyrdad]    INT           NULL,
    [momarrd]     VARCHAR (255) NULL,
    [tprmomdate]  VARCHAR (255) NULL,
    [tprdaddate]  VARCHAR (255) NULL,
    [adpfamst]    VARCHAR (255) NULL,
    [admomyr]     INT           NULL,
    [adoptdate]   VARCHAR (255) NULL,
    [addadyr]     INT           NULL,
    [amiaknm]     VARCHAR (255) NULL,
    [asianm]      VARCHAR (255) NULL,
    [blaframm]    VARCHAR (255) NULL,
    [hawiipim]    VARCHAR (255) NULL,
    [whitem]      VARCHAR (255) NULL,
    [untodemm]    VARCHAR (255) NULL,
    [homom]       VARCHAR (255) NULL,
    [amiaknd]     VARCHAR (255) NULL,
    [asiand]      VARCHAR (255) NULL,
    [blaframd]    VARCHAR (255) NULL,
    [hawiipid]    VARCHAR (255) NULL,
    [whited]      VARCHAR (255) NULL,
    [untodemd]    VARCHAR (255) NULL,
    [hodad]       VARCHAR (255) NULL,
    [stparent]    VARCHAR (255) NULL,
    [otherel]     VARCHAR (255) NULL,
    [fosparch]    VARCHAR (255) NULL,
    [nonrel]      VARCHAR (255) NULL,
    [chpldfrm]    VARCHAR (255) NULL,
    [chpldby]     VARCHAR (255) NULL,
    [monsubsy]    VARCHAR (255) NULL,
    [monamnt]     INT           NULL,
    [iveaa]       VARCHAR (255) NULL,
    [ageatadopt]  INT           NULL,
    [childrace]   INT           NULL,
    [momrace]     INT           NULL,
    [dadrace]     INT           NULL,
    [transracial] VARCHAR (255) NULL,
    [datayear]    INT           NULL
);

