CREATE TABLE [ndacan].[NYTD_Services_2011_2012_2013] (
    [repdate]    INT           NULL,
    [stchid]     VARCHAR (255) NULL,
    [stfips]     VARCHAR (255) NULL,
    [st]         VARCHAR (255) NULL,
    [recnumbr]   VARCHAR (255) NULL,
    [dob]        VARCHAR (255) NULL,
    [sex]        VARCHAR (255) NULL,
    [amiakn]     VARCHAR(255)  NULL,
    [asian]      VARCHAR(255)  NULL,
    [blkafram]   VARCHAR(255)  NULL,
    [hawaiipi]   VARCHAR(255)  NULL,
    [white]      VARCHAR(255)  NULL,
    [raceunkn]   VARCHAR(255)  NULL,
    [racedcln]   VARCHAR(255)  NULL,
    [hisorgin]   VARCHAR(255)  NULL,
    [fcstatsv]   INT           NULL,
    [lclfipssv]  INT           NULL,
    [tribesv]    VARCHAR(255)  NULL,
    [delinqntsv] VARCHAR(255)  NULL,
    [edlevlsv]   VARCHAR (255) NULL,
    [specedsv]   VARCHAR(255)  NULL,
    [ilnasv]     VARCHAR(255)  NULL,
    [acsuppsv]   VARCHAR(255)  NULL,
    [psedsuppsv] VARCHAR(255)  NULL,
    [careersv]   VARCHAR(255)  NULL,
    [emplytrsv]  VARCHAR(255)  NULL,
    [budgetsv]   VARCHAR(255)  NULL,
    [housedsv]   VARCHAR(255)  NULL,
    [hlthedsv]   VARCHAR(255)  NULL,
    [famsuppsv]  VARCHAR(255)  NULL,
    [mentorsv]   VARCHAR(255)  NULL,
    [silsv]      VARCHAR(255)  NULL,
    [rmbrdfasv]  VARCHAR(255)  NULL,
    [educfinasv] VARCHAR(255)  NULL,
    [othrfinasv] VARCHAR(255)  NULL,
    [raceethn]   VARCHAR (255) NULL
);

