CREATE TABLE [ndacan].[NYTD_Outcomes_Waves_1_2] (
    [wave]        VARCHAR (255) NULL,
    [cd_wave]     FLOAT (53)    NULL,
    [stchid]      VARCHAR (255) NULL,
    [stfips]      VARCHAR (255) NULL,
    [st]          VARCHAR (255) NULL,
    [recnumbr]    VARCHAR (255) NULL,
    [repdate]     VARCHAR (255) NULL,
    [dob]         VARCHAR (255) NULL,
    [sex]         VARCHAR (255) NULL,
    [amiakn]      INT           NULL,
    [asian]       INT           NULL,
    [blkafram]    INT           NULL,
    [hawaiipi]    INT           NULL,
    [white]       INT           NULL,
    [raceunkn]    VARCHAR(255)  NULL,
    [racedcln]    VARCHAR(255)  NULL,
    [hisorgin]    VARCHAR(255)  NULL,
    [outcmrpt]    VARCHAR (255) NULL,
    [outcmdte]    VARCHAR (255) NULL,
    [outcmfcs]    VARCHAR(255)  NULL,
    [currfte]     VARCHAR(255)  NULL,
    [currpte]     VARCHAR(255)  NULL,
    [emplysklls]  VARCHAR(255)  NULL,
    [socsecrty]   VARCHAR(255)  NULL,
    [educaid]     VARCHAR(255)  NULL,
    [pubfinas]    VARCHAR(255)  NULL,
    [pubfoodas]   VARCHAR(255)  NULL,
    [pubhousas]   VARCHAR(255)  NULL,
    [othrfinas]   VARCHAR(255)  NULL,
    [highedcert]  INT           NULL,
    [currenroll]  INT           NULL,
    [cnctadult]   VARCHAR(255)  NULL,
    [homeless]    VARCHAR(255)  NULL,
    [subabuse]    VARCHAR(255)  NULL,
    [incarc]      VARCHAR(255)  NULL,
    [children]    VARCHAR(255)  NULL,
    [marriage]    VARCHAR(255)  NULL,
    [medicaid]    VARCHAR(255)  NULL,
    [othrhlthin]  INT           NULL,
    [medicalin]   VARCHAR(255)  NULL,
    [mentlhlthin] VARCHAR(255)  NULL,
    [prescripin]  VARCHAR(255)  NULL,
    [samplestate] VARCHAR(255)  NULL,
    [insample]    VARCHAR(255)  NULL,
    [baseline]    VARCHAR(255)  NULL,
    [fy11cohort]  VARCHAR(255)  NULL,
    [elig19]      VARCHAR(255)  NULL,
    [weight]      FLOAT (53)    NULL,
    [responded]   VARCHAR (255) NULL
);

