CREATE TABLE [ndacan].[NYTD_Services_2011_2012_2013] (
    [repdate]    INT           NULL,
    [stchid]     VARCHAR (255) NULL,
    [stfips]     VARCHAR (255) NULL,
    [st]         VARCHAR (255) NULL,
    [recnumbr]   VARCHAR (255) NULL,
    [dob]        VARCHAR (255) NULL,
    [sex]        VARCHAR (255) NULL,
    [amiakn]     INT           NULL,
    [asian]      INT           NULL,
    [blkafram]   INT           NULL,
    [hawaiipi]   INT           NULL,
    [white]      INT           NULL,
    [raceunkn]   INT           NULL,
    [racedcln]   INT           NULL,
    [hisorgin]   INT           NULL,
    [fcstatsv]   INT           NULL,
    [lclfipssv]  INT           NULL,
    [tribesv]    INT           NULL,
    [delinqntsv] INT           NULL,
    [edlevlsv]   VARCHAR (255) NULL,
    [specedsv]   INT           NULL,
    [ilnasv]     INT           NULL,
    [acsuppsv]   INT           NULL,
    [psedsuppsv] INT           NULL,
    [careersv]   INT           NULL,
    [emplytrsv]  INT           NULL,
    [budgetsv]   INT           NULL,
    [housedsv]   INT           NULL,
    [hlthedsv]   INT           NULL,
    [famsuppsv]  INT           NULL,
    [mentorsv]   INT           NULL,
    [silsv]      INT           NULL,
    [rmbrdfasv]  INT           NULL,
    [educfinasv] INT           NULL,
    [othrfinasv] INT           NULL,
    [raceethn]   VARCHAR (255) NULL
);

