CREATE TABLE [ndacan].[NYTD_Outcomes_Waves_1_2] (
    [wave]        VARCHAR (255) NULL,
    [cd_wave]     FLOAT (53)    NULL,
    [stchid]      VARCHAR (255) NULL,
    [stfips]      VARCHAR (255) NULL,
    [st]          VARCHAR (255) NULL,
    [recnumbr]    VARCHAR (255) NULL,
    [repdate]     VARCHAR (255) NULL,
    [dob]         VARCHAR (255) NULL,
    [sex]         VARCHAR (255) NULL,
    [amiakn]      INT           NULL,
    [asian]       INT           NULL,
    [blkafram]    INT           NULL,
    [hawaiipi]    INT           NULL,
    [white]       INT           NULL,
    [raceunkn]    INT           NULL,
    [racedcln]    INT           NULL,
    [hisorgin]    INT           NULL,
    [outcmrpt]    VARCHAR (255) NULL,
    [outcmdte]    VARCHAR (255) NULL,
    [outcmfcs]    INT           NULL,
    [currfte]     INT           NULL,
    [currpte]     INT           NULL,
    [emplysklls]  INT           NULL,
    [socsecrty]   INT           NULL,
    [educaid]     INT           NULL,
    [pubfinas]    INT           NULL,
    [pubfoodas]   INT           NULL,
    [pubhousas]   INT           NULL,
    [othrfinas]   INT           NULL,
    [highedcert]  INT           NULL,
    [currenroll]  INT           NULL,
    [cnctadult]   INT           NULL,
    [homeless]    INT           NULL,
    [subabuse]    INT           NULL,
    [incarc]      INT           NULL,
    [children]    INT           NULL,
    [marriage]    INT           NULL,
    [medicaid]    INT           NULL,
    [othrhlthin]  INT           NULL,
    [medicalin]   INT           NULL,
    [mentlhlthin] INT           NULL,
    [prescripin]  INT           NULL,
    [samplestate] INT           NULL,
    [insample]    INT           NULL,
    [baseline]    INT           NULL,
    [fy11cohort]  INT           NULL,
    [elig19]      INT           NULL,
    [weight]      FLOAT (53)    NULL,
    [responded]   VARCHAR (255) NULL
);

