
CREATE procedure [dbo].[prod_ca_load_add_foreign_keys]
as
ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_id_calendar_dim_founded] FOREIGN KEY([ID_CALENDAR_DIM_FOUNDED])
REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM])


ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_id_calendar_dim_founded]


ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_CALENDAR_DIM_INCIDENT] FOREIGN KEY([ID_CALENDAR_DIM_INCIDENT])
REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM])


ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_CALENDAR_DIM_INCIDENT]


ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_CALENDAR_DIM_REFERRED] FOREIGN KEY([ID_CALENDAR_DIM_REFERRED])
REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM])


ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_CALENDAR_DIM_REFERRED]


ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_CASE_DIM] FOREIGN KEY([ID_CASE_DIM])
REFERENCES [dbo].[CASE_DIM] ([ID_CASE_DIM])


ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_CASE_DIM]


ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_LOCATION_DIM_INCIDENT] FOREIGN KEY([ID_LOCATION_DIM_INCIDENT])
REFERENCES [dbo].[LOCATION_DIM] ([ID_LOCATION_DIM])


ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_LOCATION_DIM_INCIDENT]


ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_LOCATION_DIM_INTAKE_WORKER] FOREIGN KEY([ID_LOCATION_DIM_INTAKE_WORKER])
REFERENCES [dbo].[LOCATION_DIM] ([ID_LOCATION_DIM])


ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_LOCATION_DIM_INTAKE_WORKER]


ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_LOCATION_DIM_PRIMARY_WORKER] FOREIGN KEY([ID_LOCATION_DIM_PRIMARY_WORKER])
REFERENCES [dbo].[LOCATION_DIM] ([ID_LOCATION_DIM])


ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_LOCATION_DIM_PRIMARY_WORKER]


ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_PEOPLE_DIM_VICTIM] FOREIGN KEY([ID_PEOPLE_DIM_VICTIM])
REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM])


ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_PEOPLE_DIM_VICTIM]


ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_PLACEMENT_TYPE_DIM] FOREIGN KEY([ID_PLACEMENT_TYPE_DIM])
REFERENCES [dbo].[PLACEMENT_TYPE_DIM] ([ID_PLACEMENT_TYPE_DIM])


ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_PLACEMENT_TYPE_DIM]


ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_PROVIDER_DIM] FOREIGN KEY([ID_PROVIDER_DIM])
REFERENCES [dbo].[PROVIDER_DIM] ([ID_PROVIDER_DIM])


ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_PROVIDER_DIM]


ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_WORKER_DIM_PRIMARY] FOREIGN KEY([ID_WORKER_DIM_PRIMARY])
REFERENCES [dbo].[WORKER_DIM] ([ID_WORKER_DIM])


ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_WORKER_DIM_PRIMARY]




ALTER TABLE [dbo].[ADOPTION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_af_ID_CASE_DIM] FOREIGN KEY([ID_CASE_DIM])
REFERENCES [dbo].[CASE_DIM] ([ID_CASE_DIM])


ALTER TABLE [dbo].[ADOPTION_FACT] CHECK CONSTRAINT [fk_af_ID_CASE_DIM]


ALTER TABLE [dbo].[ADOPTION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_af_ID_PEOPLE_DIM_CHILD] FOREIGN KEY([ID_PEOPLE_DIM_CHILD])
REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM])


ALTER TABLE [dbo].[ADOPTION_FACT] CHECK CONSTRAINT [fk_af_ID_PEOPLE_DIM_CHILD]


ALTER TABLE [dbo].[ADOPTION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_ADOPTION_STATUS_DIM] FOREIGN KEY([ID_ADOPTION_STATUS_DIM])
REFERENCES [dbo].[ADOPTION_STATUS_DIM] ([ID_ADOPTION_STATUS_DIM])


ALTER TABLE [dbo].[ADOPTION_FACT] CHECK CONSTRAINT [fk_ID_ADOPTION_STATUS_DIM]


ALTER TABLE [dbo].[ADOPTION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_CALENDAR_DIM_COMPLETE] FOREIGN KEY([ID_CALENDAR_DIM_COMPLETE])
REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM])


ALTER TABLE [dbo].[ADOPTION_FACT] CHECK CONSTRAINT [fk_ID_CALENDAR_DIM_COMPLETE]


ALTER TABLE [dbo].[ADOPTION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_CALENDAR_DIM_EFFECTIVE_ELIGIBLE] FOREIGN KEY([ID_CALENDAR_DIM_EFFECTIVE_ELIGIBLE])
REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM])


ALTER TABLE [dbo].[ADOPTION_FACT] CHECK CONSTRAINT [fk_ID_CALENDAR_DIM_EFFECTIVE_ELIGIBLE]


ALTER TABLE [dbo].[ADOPTION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_CALENDAR_DIM_TERMINATED] FOREIGN KEY([ID_CALENDAR_DIM_TERMINATED])
REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM])


ALTER TABLE [dbo].[ADOPTION_FACT] CHECK CONSTRAINT [fk_ID_CALENDAR_DIM_TERMINATED]


ALTER TABLE [dbo].[ALLEGATION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ALLEGATION_FACT_ID_ABUSE_TYPE_DIM] FOREIGN KEY([ID_ABUSE_TYPE_DIM])
REFERENCES [dbo].[ABUSE_TYPE_DIM] ([ID_ABUSE_TYPE_DIM])


ALTER TABLE [dbo].[ALLEGATION_FACT] CHECK CONSTRAINT [fk_ALLEGATION_FACT_ID_ABUSE_TYPE_DIM]


ALTER TABLE [dbo].[ALLEGATION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ALLEGATION_FACT_ID_CASE_DIM] FOREIGN KEY([ID_CASE_DIM])
REFERENCES [dbo].[CASE_DIM] ([ID_CASE_DIM])


ALTER TABLE [dbo].[ALLEGATION_FACT] CHECK CONSTRAINT [fk_ALLEGATION_FACT_ID_CASE_DIM]


ALTER TABLE [dbo].[ALLEGATION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ALLEGATION_FACT_ID_FINDINGS_DIM] FOREIGN KEY([ID_FINDINGS_DIM])
REFERENCES [dbo].[FINDINGS_DIM] ([ID_FINDINGS_DIM])


ALTER TABLE [dbo].[ALLEGATION_FACT] CHECK CONSTRAINT [fk_ALLEGATION_FACT_ID_FINDINGS_DIM]


ALTER TABLE [dbo].[ALLEGATION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ALLEGATION_FACT_ID_INTAKE_FACT] FOREIGN KEY([ID_INTAKE_FACT])
REFERENCES [dbo].[INTAKE_FACT] ([ID_INTAKE_FACT])


ALTER TABLE [dbo].[ALLEGATION_FACT] CHECK CONSTRAINT [fk_ALLEGATION_FACT_ID_INTAKE_FACT]


ALTER TABLE [dbo].[ALLEGATION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ALLEGATION_FACT_ID_INVESTIGATION_ASSESSMENT_FACT] FOREIGN KEY([ID_INVESTIGATION_ASSESSMENT_FACT])
REFERENCES [dbo].[INVESTIGATION_ASSESSMENT_FACT] ([ID_INVESTIGATION_ASSESSMENT_FACT])


ALTER TABLE [dbo].[ALLEGATION_FACT] CHECK CONSTRAINT [fk_ALLEGATION_FACT_ID_INVESTIGATION_ASSESSMENT_FACT]


ALTER TABLE [dbo].[ALLEGATION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ALLEGATION_FACT_ID_PEOPLE_DIM_SUBJECT] FOREIGN KEY([ID_PEOPLE_DIM_SUBJECT])
REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM])


ALTER TABLE [dbo].[ALLEGATION_FACT] CHECK CONSTRAINT [fk_ALLEGATION_FACT_ID_PEOPLE_DIM_SUBJECT]


ALTER TABLE [dbo].[ALLEGATION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ALLEGATION_FACT_ID_RELATIONSHIP_DIM] FOREIGN KEY([ID_RELATIONSHIP_DIM])
REFERENCES [dbo].[RELATIONSHIP_DIM] ([ID_RELATIONSHIP_DIM])


ALTER TABLE [dbo].[ALLEGATION_FACT] CHECK CONSTRAINT [fk_ALLEGATION_FACT_ID_RELATIONSHIP_DIM]


ALTER TABLE [dbo].[ASSIGNMENT_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ASSIGNMENT_FACT_ID_ASSIGNMENT_ATTRIBUTE_DIM] FOREIGN KEY([ID_ASSIGNMENT_ATTRIBUTE_DIM])
REFERENCES [dbo].[ASSIGNMENT_ATTRIBUTE_DIM] ([ID_ASSIGNMENT_ATTRIBUTE_DIM])


ALTER TABLE [dbo].[ASSIGNMENT_FACT] CHECK CONSTRAINT [fk_ASSIGNMENT_FACT_ID_ASSIGNMENT_ATTRIBUTE_DIM]


ALTER TABLE [dbo].[ASSIGNMENT_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_BEGIN] FOREIGN KEY([ID_CALENDAR_DIM_BEGIN])
REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM])


ALTER TABLE [dbo].[ASSIGNMENT_FACT] CHECK CONSTRAINT [fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_BEGIN]


ALTER TABLE [dbo].[ASSIGNMENT_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_END] FOREIGN KEY([ID_CALENDAR_DIM_END])
REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM])


ALTER TABLE [dbo].[ASSIGNMENT_FACT] CHECK CONSTRAINT [fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_END]


ALTER TABLE [dbo].[ASSIGNMENT_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ASSIGNMENT_FACT_ID_CASE_DIM] FOREIGN KEY([ID_CASE_DIM])
REFERENCES [dbo].[CASE_DIM] ([ID_CASE_DIM])


ALTER TABLE [dbo].[ASSIGNMENT_FACT] CHECK CONSTRAINT [fk_ASSIGNMENT_FACT_ID_CASE_DIM]


ALTER TABLE [dbo].[ASSIGNMENT_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ASSIGNMENT_FACT_ID_LOCATION_DIM] FOREIGN KEY([ID_LOCATION_DIM])
REFERENCES [dbo].[LOCATION_DIM] ([ID_LOCATION_DIM])


ALTER TABLE [dbo].[ASSIGNMENT_FACT] CHECK CONSTRAINT [fk_ASSIGNMENT_FACT_ID_LOCATION_DIM]


ALTER TABLE [dbo].[ASSIGNMENT_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ASSIGNMENT_FACT_ID_PEOPLE_DIM] FOREIGN KEY([ID_PEOPLE_DIM])
REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM])


ALTER TABLE [dbo].[ASSIGNMENT_FACT] CHECK CONSTRAINT [fk_ASSIGNMENT_FACT_ID_PEOPLE_DIM]


ALTER TABLE [dbo].[ASSIGNMENT_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ASSIGNMENT_FACT_ID_PROVIDER_DIM] FOREIGN KEY([ID_PROVIDER_DIM])
REFERENCES [dbo].[PROVIDER_DIM] ([ID_PROVIDER_DIM])


ALTER TABLE [dbo].[ASSIGNMENT_FACT] CHECK CONSTRAINT [fk_ASSIGNMENT_FACT_ID_PROVIDER_DIM]


ALTER TABLE [dbo].[ASSIGNMENT_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ASSIGNMENT_FACT_ID_WORKER_DIM] FOREIGN KEY([ID_WORKER_DIM])
REFERENCES [dbo].[WORKER_DIM] ([ID_WORKER_DIM])


ALTER TABLE [dbo].[ASSIGNMENT_FACT] CHECK CONSTRAINT [fk_ASSIGNMENT_FACT_ID_WORKER_DIM]




alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_AUTHORIZATION_DIM FOREIGN KEY ( ID_AUTHORIZATION_DIM )
references dbo.AUTHORIZATION_DIM(ID_AUTHORIZATION_DIM)

alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_AUTH_BEGIN FOREIGN KEY ( ID_CALENDAR_DIM_AUTH_BEGIN )
references dbo.calendar_dim(ID_CALENDAR_DIM)


alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_AUTH_END FOREIGN KEY ( ID_CALENDAR_DIM_AUTH_END )
references dbo.calendar_dim(ID_CALENDAR_DIM)


alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_SERVICE_BEGIN FOREIGN KEY ( ID_CALENDAR_DIM_SERVICE_BEGIN )
references dbo.calendar_dim(ID_CALENDAR_DIM)

alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_SERVICE_END FOREIGN KEY ( ID_CALENDAR_DIM_SERVICE_END )
references dbo.calendar_dim(ID_CALENDAR_DIM)

alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_CASE_DIM FOREIGN KEY ( ID_CASE_DIM )
references dbo.case_dim(ID_CASE_DIM)

alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_CHART_OF_ACCOUNTS_DIM FOREIGN KEY ( ID_CHART_OF_ACCOUNTS_DIM )
references dbo.CHART_OF_ACCOUNTS_DIM(ID_CHART_OF_ACCOUNTS_DIM)

alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_LOCATION_DIM FOREIGN KEY ( ID_LOCATION_DIM )
references dbo.LOCATION_DIM(ID_LOCATION_DIM)

alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY ( ID_PEOPLE_DIM_CHILD )
references dbo.people_dim(id_people_dim)


alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_PEOPLE_DIM_CLIENT FOREIGN KEY ( ID_PEOPLE_DIM_CLIENT )
references dbo.people_dim(id_people_dim)

alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_PLACEMENT_CARE_AUTH_DIM FOREIGN KEY ( ID_PLACEMENT_CARE_AUTH_DIM )
references dbo.PLACEMENT_CARE_AUTH_DIM(ID_PLACEMENT_CARE_AUTH_DIM)


alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_IID_PLACEMENT_TYPE_DIM FOREIGN KEY ( ID_PLACEMENT_TYPE_DIM )
references dbo.PLACEMENT_TYPE_DIM(ID_PLACEMENT_TYPE_DIM)

alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_PROVIDER_DIM_PAYEE FOREIGN KEY ( ID_PROVIDER_DIM_PAYEE )
references dbo.PROVIDER_DIM(ID_PROVIDER_DIM)

alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_PROVIDER_DIM_SERVICE FOREIGN KEY ( ID_PROVIDER_DIM_SERVICE )
references dbo.PROVIDER_DIM(ID_PROVIDER_DIM)

alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_SERVICE_TYPE_DIME FOREIGN KEY ( ID_SERVICE_TYPE_DIM )
references dbo.SERVICE_TYPE_DIM(ID_SERVICE_TYPE_DIM)

alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_SOURCE_FUNDS_DIM FOREIGN KEY ( ID_SOURCE_FUNDS_DIM )
references dbo.SOURCE_FUNDS_DIM(ID_SOURCE_FUNDS_DIM)

alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_WORKER_DIM FOREIGN KEY ( ID_WORKER_DIM )
references dbo.worker_dim(ID_WORKER_DIM)

-- case_dim
alter table CASE_DIM
add constraint fk_CASE_DIM_ID_LOCATION_DIM FOREIGN KEY ( ID_LOCATION_DIM )
references dbo.LOCATION_DIM(ID_LOCATION_DIM)

alter table CASE_DIM
add constraint fk_CASE_DIM_ID_CALENDAR_DIM_LAST_ACTIVITY FOREIGN KEY ( ID_CALENDAR_DIM_LAST_ACTIVITY )
references dbo.calendar_dim(ID_CALENDAR_DIM)


alter table CASE_NOTE_FACT
add constraint fk_CASE_NOTE_FACT_ID_LEGAL_STATUS_DIM FOREIGN KEY ( ID_LEGAL_STATUS_DIM )
references dbo.LEGAL_STATUS_DIM(ID_LEGAL_STATUS_DIM)

alter table CASE_NOTE_FACT
add constraint fk_CASE_NOTE_FACT_ID_PEOPLE_DIM FOREIGN KEY ( ID_PEOPLE_DIM )
references dbo.PEOPLE_DIM(ID_PEOPLE_DIM)

alter table CASE_NOTE_FACT
add constraint fk_CASE_NOTE_FACT_ID_WORKER_DIM FOREIGN KEY ( ID_WORKER_DIM )
references dbo.WORKER_DIM(ID_WORKER_DIM)

alter table CASE_NOTE_FACT
add constraint fk_CASE_NOTE_FACT_ID_CASE_NOTE_TYPE_DIM FOREIGN KEY ( ID_CASE_NOTE_TYPE_DIM )
references dbo.CASE_NOTE_TYPE_DIM(ID_CASE_NOTE_TYPE_DIM)

alter table CASE_NOTE_FACT
add constraint fk_CASE_NOTE_FACT_ID_CASE_DIM FOREIGN KEY ( ID_CASE_DIM )
references dbo.case_dim(ID_CASE_DIM)

alter table CASE_NOTE_FACT
add constraint fk_CASE_NOTE_FACT_ID_LOCATION_DIM FOREIGN KEY ( ID_LOCATION_DIM )
references dbo.LOCATION_DIM(ID_LOCATION_DIM)

alter table CASE_NOTE_FACT
add constraint fk_CASE_NOTE_FACT_ID_CALENDAR_DIM_OCCURRED FOREIGN KEY ( ID_CALENDAR_DIM_OCCURRED )
references dbo.calendar_dim(ID_CALENDAR_DIM)

alter table CASE_NOTE_FACT
add constraint fk_CASE_NOTE_FACT_ID_CALENDAR_DIM_PRIOR_VISIT FOREIGN KEY ( ID_CALENDAR_DIM_PRIOR_VISIT )
references dbo.calendar_dim(ID_CALENDAR_DIM)


alter table DLR_RISK_ASSESSMENT_FACT
add constraint fk_DLR_RISK_ASSESSMENT_FACT_ID_CALENDAR_DIM_COMPLETED FOREIGN KEY ( ID_CALENDAR_DIM_COMPLETED )
references dbo.calendar_dim(ID_CALENDAR_DIM)


alter table DLR_RISK_ASSESSMENT_FACT
add constraint fk_DLR_RISK_ASSESSMENT_FACT_ID_PROVIDER_DIM FOREIGN KEY ( ID_PROVIDER_DIM )
references dbo.PROVIDER_DIM(ID_PROVIDER_DIM)



alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_EDUCATION_DIM FOREIGN KEY ( ID_EDUCATION_DIM )
references dbo.EDUCATION_DIM(ID_EDUCATION_DIM)

alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_CALENDAR_DIM_CREATED FOREIGN KEY ( ID_CALENDAR_DIM_CREATED )
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)

alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_CALENDAR_DIM_EARNED_DIPLOMA FOREIGN KEY (ID_CALENDAR_DIM_EARNED_DIPLOMA )
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)

alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_CALENDAR_DIM_ENROLLED FOREIGN KEY (ID_CALENDAR_DIM_ENROLLED )
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)

alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_CALENDAR_DIM_ENROLLMENT_END FOREIGN KEY (ID_CALENDAR_DIM_ENROLLMENT_END )
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)

alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_LOCATION_DIM_CASE FOREIGN KEY (ID_LOCATION_DIM_CASE )
references dbo.LOCATION_DIM(ID_LOCATION_DIM)

alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_LOCATION_DIM_CHILD FOREIGN KEY (ID_LOCATION_DIM_CHILD )
references dbo.LOCATION_DIM(ID_LOCATION_DIM)

alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY (ID_PEOPLE_DIM_CHILD )
references dbo.PEOPLE_DIM(ID_PEOPLE_DIM)

alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_SCHOOL_DIM FOREIGN KEY (ID_SCHOOL_DIM )
references dbo.school_dim(ID_SCHOOL_DIM)

alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_WORKER_DIM_CASE FOREIGN KEY (ID_WORKER_DIM_CASE )
references dbo.worker_dim(ID_WORKER_DIM)

alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_WORKER_DIM_CHILD FOREIGN KEY (ID_WORKER_DIM_CHILD )
references dbo.worker_dim(ID_WORKER_DIM)

alter table EDUCATION_PLAN_FACT
add constraint fk_EDUCATION_PLAN_FACT_ID_EDUCATION_PLAN_DIM FOREIGN KEY ( ID_EDUCATION_PLAN_DIM )
references dbo.EDUCATION_PLAN_DIM(ID_EDUCATION_PLAN_DIM)


alter table EDUCATION_PLAN_FACT
add constraint fk_EDUCATION_PLAN_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY ( ID_PEOPLE_DIM_CHILD )
references dbo.PEOPLE_DIM(ID_PEOPLE_DIM)


alter table EDUCATION_PLAN_FACT
add constraint fk_EDUCATION_PLAN_FACT_ID_CALENDAR_DIM_PLAN_DATE FOREIGN KEY ( ID_CALENDAR_DIM_PLAN_DATE )
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)





alter table EDUCATION_RECORDS_REQUEST_REFERRAL_FACT
add constraint fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_EDUCATION_RECORDS_REQUEST_REFERRAL_DIM
FOREIGN KEY ( ID_EDUCATION_RECORDS_REQUEST_REFERRAL_DIM )
references dbo.EDUCATION_RECORDS_REQUEST_REFERRAL_DIM(ID_EDUCATION_RECORDS_REQUEST_REFERRAL_DIM)

alter table EDUCATION_RECORDS_REQUEST_REFERRAL_FACT
add constraint fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_CALENDAR_DIM_REQUESTED FOREIGN KEY ( ID_CALENDAR_DIM_REQUESTED )
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)

alter table EDUCATION_RECORDS_REQUEST_REFERRAL_FACT
add constraint fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_CALENDAR_DIM_RECEIVED FOREIGN KEY ( ID_CALENDAR_DIM_RECEIVED )
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)

alter table EDUCATION_RECORDS_REQUEST_REFERRAL_FACT
add constraint fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_CALENDAR_DIM_REFERRAL FOREIGN KEY ( ID_CALENDAR_DIM_REFERRAL )
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)

alter table ELIG_EPISODE_FACT
add constraint fk_ELIG_EPISODE_FACT_ID_CALENDAR_DIM_END FOREIGN KEY(ID_CALENDAR_DIM_END)
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)

alter table ELIG_EPISODE_FACT
add constraint fk_ELIG_EPISODE_FACT_ID_CALENDAR_DIM_BEGIN FOREIGN KEY(ID_CALENDAR_DIM_BEGIN)
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)

alter table ELIG_EPISODE_FACT
add constraint fk_ELIG_EPISODE_FACT_ID_CASE_DIM FOREIGN KEY(ID_CASE_DIM)
references dbo.CASE_DIM(ID_CASE_DIM)

alter table ELIG_EPISODE_FACT
add constraint fk_ELIG_EPISODE_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY(ID_PEOPLE_DIM_CHILD)
references dbo.PEOPLE_DIM(ID_PEOPLE_DIM)


alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_COMPLETE FOREIGN KEY (ID_CALENDAR_DIM_COMPLETE )
references dbo.calendar_dim(ID_CALENDAR_DIM)

alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_COMPLETE FOREIGN KEY (ID_CALENDAR_DIM_ELIGIBILITY_COMPLETE )
references dbo.calendar_dim(ID_CALENDAR_DIM)

alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_EFFECTIVE FOREIGN KEY (ID_CALENDAR_DIM_ELIGIBILITY_EFFECTIVE)
references dbo.calendar_dim(ID_CALENDAR_DIM)

alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_END FOREIGN KEY (ID_CALENDAR_DIM_ELIGIBILITY_END)
references dbo.calendar_dim(ID_CALENDAR_DIM)

alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_VPA_CTW FOREIGN KEY (ID_CALENDAR_DIM_ELIGIBILITY_VPA_CTW)
references dbo.calendar_dim(ID_CALENDAR_DIM)



alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY (ID_PEOPLE_DIM_CHILD)
references dbo.PEOPLE_DIM(ID_PEOPLE_DIM)

alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_WORKER_DIM FOREIGN KEY (ID_WORKER_DIM)
references dbo.WORKER_DIM(ID_WORKER_DIM)



alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_ELIGIBILITY_REMOVAL_HOME_DIM FOREIGN KEY (ID_ELIGIBILITY_REMOVAL_HOME_DIM)
references dbo.ELIGIBILITY_REMOVAL_HOME_DIM(ID_ELIGIBILITY_REMOVAL_HOME_DIM)

alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_ELIGIBILITY_STATUS_DIM FOREIGN KEY (ID_ELIGIBILITY_STATUS_DIM)
references dbo.ELIGIBILITY_STATUS_DIM(ID_ELIGIBILITY_STATUS_DIM)

alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_ELIGIBILITY_DIM FOREIGN KEY (ID_ELIGIBILITY_DIM)
references dbo.ELIGIBILITY_DIM(ID_ELIGIBILITY_DIM)


alter table HEALTH_ACTIVITY_FACT
add constraint fk_HEALTH_ACTIVITY_FACT_ID_CALENDAR_DIM_ACTIVITY_END foreign key (ID_CALENDAR_DIM_ACTIVITY_END)
references dbo.calendar_dim(id_calendar_dim)

alter table HEALTH_ACTIVITY_FACT
add constraint fk_HEALTH_ACTIVITY_FACT_ID_CALENDAR_DIM_ACTIVITY_START foreign key (ID_CALENDAR_DIM_ACTIVITY_START)
references dbo.calendar_dim(id_calendar_dim)

alter table HEALTH_ACTIVITY_FACT
add constraint fk_HEALTH_ACTIVITY_FACT_ID_HEALTH_ACTIVITY_TYPE_DIM foreign key (ID_HEALTH_ACTIVITY_TYPE_DIM)
references dbo.HEALTH_ACTIVITY_TYPE_DIM(ID_HEALTH_ACTIVITY_TYPE_DIM)

alter table HEALTH_ACTIVITY_FACT
add constraint fk_HEALTH_ACTIVITY_FACT_ID_MENTAL_HEALTH_EVAL_DIM foreign key (ID_MENTAL_HEALTH_EVAL_DIM)
references dbo.MENTAL_HEALTH_EVAL_DIM(ID_MENTAL_HEALTH_EVAL_DIM)

alter table HEALTH_ACTIVITY_FACT
add constraint fk_HEALTH_ACTIVITY_FACT_ID_PEOPLE_DIM_CHILD foreign key (ID_PEOPLE_DIM_CHILD)
references dbo.PEOPLE_DIM(ID_PEOPLE_DIM)

alter table HEALTH_CAT_ATTRIBUTE_BRIDGE_FACT
add constraint fk_HEALTH_CAT_ATTRIBUTE_BRIDGE_FACT_ID_HEALTH_ACTIVITY_FACT foreign key (ID_HEALTH_ACTIVITY_FACT)
references dbo.HEALTH_ACTIVITY_FACT(ID_HEALTH_ACTIVITY_FACT)


alter table IL_ANSELL_CASEY_ASSESSMENT_FACT
add constraint fk_IL_ANSELL_CASEY_ASSESSMENT_FACT_ID_INDEPENDENT_LIVING_FACT foreign key(ID_INDEPENDENT_LIVING_FACT)
references dbo.independent_living_fact(ID_INDEPENDENT_LIVING_FACT);


alter table IL_NYTD_QUESTIONS_FACT
add constraint fk_IL_NYTD_QUESTIONS_FACT_ID_INDEPENDENT_LIVING_FACT foreign key(ID_INDEPENDENT_LIVING_FACT)
references dbo.INDEPENDENT_LIVING_FACT(ID_INDEPENDENT_LIVING_FACT)

alter table IL_NYTD_QUESTIONS_FACT
add constraint fk_IL_NYTD_QUESTIONS_FACT_ID_IL_NYTD_QUESTIONS_ATTRIBUTE_DIM foreign key(ID_IL_NYTD_QUESTIONS_ATTRIBUTE_DIM)
references dbo.IL_NYTD_QUESTIONS_ATTRIBUTE_DIM(ID_IL_NYTD_QUESTIONS_ATTRIBUTE_DIM)

alter table IL_NYTD_QUESTIONS_FACT
add constraint fk_IL_NYTD_QUESTIONS_FACT_ID_CALENDAR_DIM_SURVEY_COMPLETED foreign key(ID_CALENDAR_DIM_SURVEY_COMPLETED)
references dbo.calendar_dim(id_calendar_dim)

alter table INDEPENDENT_LIVING_FACT
add constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_ANTICIPATED_OUT_CARE foreign key(ID_CALENDAR_DIM_ANTICIPATED_OUT_CARE)
references dbo.calendar_dim(id_calendar_dim)

alter table INDEPENDENT_LIVING_FACT
add constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_BEGAN foreign key(ID_CALENDAR_DIM_BEGAN)
references dbo.calendar_dim(id_calendar_dim)

alter table INDEPENDENT_LIVING_FACT
add constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_IL_PLAN_COMPLETED foreign key(ID_CALENDAR_DIM_IL_PLAN_COMPLETED)
references dbo.calendar_dim(id_calendar_dim)

alter table INDEPENDENT_LIVING_FACT
add constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_INITIAL_IL_REFERRAL foreign key(ID_CALENDAR_DIM_INITIAL_IL_REFERRAL)
references dbo.calendar_dim(id_calendar_dim)

alter table INDEPENDENT_LIVING_FACT
add constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_REFERRED foreign key(ID_CALENDAR_DIM_REFERRED)
references dbo.calendar_dim(id_calendar_dim)

alter table INDEPENDENT_LIVING_FACT
add constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_YOUTH_NOT_PARTICIPATING foreign key(ID_CALENDAR_DIM_YOUTH_NOT_PARTICIPATING)
references dbo.calendar_dim(id_calendar_dim)

alter table INDEPENDENT_LIVING_FACT
add constraint fk_INDEPENDENT_LIVING_FACT_ID_PEOPLE_DIM foreign key(ID_PEOPLE_DIM)
references dbo.PEOPLE_DIM(ID_PEOPLE_DIM)

alter table intake_fact
add constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_ACCESS_RCVD foreign key (ID_CALENDAR_DIM_ACCESS_RCVD)
references calendar_dim(id_calendar_dim);

alter table intake_fact
add constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_CPS_SPVR_DSCN foreign key (ID_CALENDAR_DIM_CPS_SPVR_DSCN)
references calendar_dim(id_calendar_dim);

alter table intake_fact
add constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_INCD foreign key (ID_CALENDAR_DIM_INCD)
references calendar_dim(id_calendar_dim);

alter table intake_fact
add constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_SPVR_DSCN foreign key (ID_CALENDAR_DIM_SPVR_DSCN)
references calendar_dim(id_calendar_dim);

alter table intake_fact
add constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_WRKR_DSCN foreign key (ID_CALENDAR_DIM_WRKR_DSCN)
references calendar_dim(id_calendar_dim);

alter table intake_fact
add constraint fk_INTAKE_FACT_ID_CASE_DIM foreign key (ID_CASE_DIM)
references case_dim(id_case_dim);

alter table intake_fact
add constraint fk_INTAKE_FACT_ID_INTAKE_ATTRIBUTE_DIM foreign key (ID_INTAKE_ATTRIBUTE_DIM)
references INTAKE_ATTRIBUTE_DIM(ID_INTAKE_ATTRIBUTE_DIM);

alter table intake_fact
add constraint fk_INTAKE_FACT_ID_INTAKE_TYPE_DIM foreign key (ID_INTAKE_TYPE_DIM)
references INTAKE_TYPE_DIM(ID_INTAKE_TYPE_DIM);

alter table intake_fact
add constraint fk_INTAKE_FACT_ID_LOCATION_DIM_INTAKE_WORKER foreign key (ID_LOCATION_DIM_INTAKE_WORKER)
references location_dim(id_location_dim);


alter table intake_fact
add constraint fk_INTAKE_FACT_ID_PROVIDER_DIM_INTAKE foreign key(ID_PROVIDER_DIM_INTAKE)
references provider_dim(ID_PROVIDER_DIM)


alter table intake_fact
add constraint fk_INTAKE_FACT_ID_RESPONSE_TIME_EXP_DIM foreign key(ID_RESPONSE_TIME_EXP_DIM)
references  RESPONSE_TIME_EXP_DIM(ID_RESPONSE_TIME_EXP_DIM)


alter table intake_fact
add constraint fk_INTAKE_FACT_ID_WORKER_DIM_CPS_SUPERVISOR  foreign key(ID_WORKER_DIM_CPS_SUPERVISOR)
references worker_dim(id_worker_dim);

alter table intake_fact
add constraint fk_INTAKE_FACT_ID_WORKER_DIM_INTAKE  foreign key(ID_WORKER_DIM_INTAKE)
references worker_dim(ID_WORKER_DIM);

alter table intake_fact
add constraint fk_INTAKE_FACT_ID_WORKER_DIM_INTAKE_SUPERVISOR  foreign key(ID_WORKER_DIM_INTAKE_SUPERVISOR)
references worker_dim(ID_WORKER_DIM);

alter table INTAKE_PARTICIPANT_FACT
add constraint fk_INTAKE_PARTICIPANT_FACT_ID_INTAKE_PARTICIPANT_ROLES_DIM foreign key (ID_INTAKE_PARTICIPANT_ROLES_DIM)
references INTAKE_PARTICIPANT_ROLES_DIM(ID_INTAKE_PARTICIPANT_ROLES_DIM)

alter table INTAKE_PARTICIPANT_FACT
add constraint fk_INTAKE_PARTICIPANT_FACT_ID_PEOPLE_DIM_CHILD foreign key (ID_PEOPLE_DIM_CHILD)
references PEOPLE_DIM(ID_PEOPLE_DIM)

alter table INTAKE_SERVICE_BRIDGE_FACT
add constraint fk_INTAKE_SERVICE_BRIDGE_FACT_ID_INTAKE_FACT foreign key (ID_INTAKE_FACT)
references intake_fact(id_intake_fact);

alter table INTAKE_SERVICE_BRIDGE_FACT
add constraint fk_INTAKE_SERVICE_BRIDGE_FACT_ID_SERVICE_REFERRAL_DIM foreign key (ID_SERVICE_REFERRAL_DIM)
references SERVICE_REFERRAL_DIM(ID_SERVICE_REFERRAL_DIM);

alter table INTAKE_VICTIM_FACT
add constraint fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_IFF_RESPONSE_ATTEMPT
 foreign key (ID_CALENDAR_DIM_IFF_RESPONSE_ATTEMPT
)references calendar_dim(id_calendar_dim);

alter table INTAKE_VICTIM_FACT
add constraint fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_IFF_RESPONSE_COMPLETED
 foreign key (ID_CALENDAR_DIM_IFF_RESPONSE_COMPLETED
)references calendar_dim(id_calendar_dim);

alter table INTAKE_VICTIM_FACT
add constraint fk_INTAKE_VICTIM_FACT_IID_CALENDAR_DIM_VICTIM_ADDED
 foreign key (ID_CALENDAR_DIM_VICTIM_ADDED
)references calendar_dim(id_calendar_dim);

alter table INTAKE_VICTIM_FACT
add constraint fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_DUE_ORIGINAL
 foreign key (ID_CALENDAR_DIM_DUE_ORIGINAL
)references calendar_dim(id_calendar_dim);

alter table INTAKE_VICTIM_FACT
add constraint fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_DUE
 foreign key (ID_CALENDAR_DIM_DUE
)references calendar_dim(id_calendar_dim);

alter table INTAKE_VICTIM_FACT
add constraint fk_INTAKE_VICTIM_FACT_ID_RESPONSE_TIME_EXP_DIM
foreign key(ID_RESPONSE_TIME_EXP_DIM) references RESPONSE_TIME_EXP_DIM(ID_RESPONSE_TIME_EXP_DIM)


alter table INVESTIGATION_ASSESSMENT_FACT	
add constraint fk_INVESTIGATION_ASSESSMENT_FACT_ID_CALENDAR_DIM_LEVEL1_APPROVED
foreign key(ID_CALENDAR_DIM_LEVEL1_APPROVED) references calendar_dim(id_calendar_dim);

alter table INVESTIGATION_ASSESSMENT_FACT	
add constraint fk_INVESTIGATION_ASSESSMENT_FACT_ID_CALENDAR_DIM_LEVEL2_APPROVED
foreign key(ID_CALENDAR_DIM_LEVEL2_APPROVED) references calendar_dim(id_calendar_dim);



alter table INVESTIGATION_ASSESSMENT_FACT	
add constraint fk_INVESTIGATION_ASSESSMENT_FACT_ID_CASE_DIM foreign key (ID_CASE_DIM) references case_dim(id_case_dim);

alter table INVESTIGATION_ASSESSMENT_FACT	
add constraint fk_INVESTIGATION_ASSESSMENT_FACT_ID_DISPOSITION_DIM foreign key (ID_DISPOSITION_DIM) references DISPOSITION_DIM(ID_DISPOSITION_DIM)

alter table INVESTIGATION_ASSESSMENT_FACT	
add constraint fk_INVESTIGATION_ASSESSMENT_FACT_ID_INVESTIGATION_TYPE_DIM foreign key (ID_INVESTIGATION_TYPE_DIM) references  INVESTIGATION_TYPE_DIM(ID_INVESTIGATION_TYPE_DIM)

alter table INVESTIGATION_ASSESSMENT_FACT	
add constraint fk_INVESTIGATION_ASSESSMENT_FACT_ID_LOCATION_DIM foreign key (ID_LOCATION_DIM) references location_dim(id_location_dim)

alter table INVESTIGATION_ASSESSMENT_FACT	
add constraint fk_INVESTIGATION_ASSESSMENT_FACT_ID_PROVIDER_DIM foreign key (ID_PROVIDER_DIM) references provider_dim(id_provider_dim)

alter table INVESTIGATION_ASSESSMENT_FACT	
add constraint fk_INVESTIGATION_ASSESSMENT_FACT_ID_WORKER_DIM foreign key (ID_WORKER_DIM) references worker_dim(id_worker_dim)

------------------------------------------------
alter table LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT
add constraint fk_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT_ID_CASE_DIM foreign key (ID_CASE_DIM  ) references case_dim(ID_CASE_DIM)


alter table LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT
add constraint fk_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT_ID_PEOPLE_DIM foreign key (ID_PEOPLE_DIM  ) references PEOPLE_DIM (ID_PEOPLE_DIM )


alter table LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT
add constraint fk_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT_ID_CALENDAR_DIM_FINDING 
foreign key (ID_CALENDAR_DIM_FINDING  ) references CALENDAR_DIM(ID_CALENDAR_DIM)



alter table LEGAL_FACT
add constraint fk_LEGAL_FACT_ID_CALENDAR_DIM_EFFECTIVE 
foreign key (ID_CALENDAR_DIM_EFFECTIVE  ) references CALENDAR_DIM(ID_CALENDAR_DIM)


alter table LEGAL_FACT
add constraint fk_LEGAL_FACT_ID_CALENDAR_DIM_HEARING 
foreign key (ID_CALENDAR_DIM_HEARING  ) references CALENDAR_DIM(ID_CALENDAR_DIM)


alter table LEGAL_FACT
add constraint fk_LEGAL_FACT_ID_CASE_DIM foreign key (ID_CASE_DIM  ) references dbo.case_dim(ID_CASE_DIM)


alter table LEGAL_FACT
add constraint fk_LEGAL_FACT_ID_LEGAL_ACTION_DIM foreign key (ID_LEGAL_ACTION_DIM  ) references LEGAL_ACTION_DIM(ID_LEGAL_ACTION_DIM)



alter table LEGAL_FACT
add constraint fk_LEGAL_FACT_ID_LEGAL_JURISDICTION_DIM foreign key (ID_LEGAL_JURISDICTION_DIM  ) references LEGAL_JURISDICTION_DIM(ID_LEGAL_JURISDICTION_DIM)


alter table LEGAL_FACT
add constraint fk_LEGAL_FACT_ID_LEGAL_RESULT_DIM foreign key (ID_LEGAL_RESULT_DIM  ) references LEGAL_RESULT_DIM (ID_LEGAL_RESULT_DIM)


alter table LEGAL_FACT
add constraint fk_LEGAL_FACT_ID_LEGAL_STATUS_DIM foreign key (ID_LEGAL_STATUS_DIM  ) references LEGAL_STATUS_DIM(ID_LEGAL_STATUS_DIM)


alter table LEGAL_FACT
add constraint fk_LEGAL_FACT_ID_PEOPLE_DIM foreign key (ID_PEOPLE_DIM  ) references dbo.people_dim(ID_PEOPLE_DIM)



alter table LEGAL_FACT
add constraint fk_LEGAL_FACT_ID_WORKER_DIM foreign key (ID_WORKER_DIM  ) references WORKER_DIM(ID_WORKER_DIM)



alter table LEGAL_TPR_REFERRAL_FACT
add constraint fk_LEGAL_TPR_REFERRAL_FACT_ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT 
foreign key (ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT  ) references  LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT(ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT)


alter table LEGAL_TPR_REFERRAL_FACT
add constraint fk_LEGAL_TPR_REFERRAL_FACT_ID_CALENDAR_DIM_TPR_REFERRAL 
foreign key (ID_CALENDAR_DIM_TPR_REFERRAL  ) references calendar_dim(ID_CALENDAR_DIM)



alter table LEGAL_TPR_REFERRAL_FACT
add constraint fk_LEGAL_TPR_REFERRAL_FACT_ID_RELATIONSHIP_DIM_TPR 
foreign key (ID_RELATIONSHIP_DIM_TPR  ) references relationship_dim(ID_RELATIONSHIP_DIM)



alter table LEGAL_TPR_REFERRAL_FACT
add constraint fk_LEGAL_TPR_REFERRAL_FACT_ID_PEOPLE_DIM_TPR_PARENT foreign key (ID_PEOPLE_DIM_TPR_PARENT  ) 
references people_dim(id_people_dim)

---
alter table LICENSE_ACTION_FACT
add constraint fk_LICENSE_ACTION_FACT_ID_CALENDAR_DIM_ACTION foreign key (ID_CALENDAR_DIM_ACTION  ) 
references calendar_dim(ID_CALENDAR_DIM)


alter table LICENSE_ACTION_FACT
add constraint fk_LICENSE_ACTION_FACT_ID_LICENSE_ATTRIB_DIM 
foreign key (ID_LICENSE_ATTRIB_DIM  ) references  LICENSE_ATTRIB_DIM(ID_LICENSE_ATTRIB_DIM)


alter table LICENSE_ACTION_FACT
add constraint fk_LICENSE_ACTION_FACT_ID_PROVIDER_DIM 
foreign key (ID_PROVIDER_DIM  ) references PROVIDER_DIM (ID_PROVIDER_DIM)


alter table LICENSE_FACT
add constraint fk_LICENSE_FACT_ID_CALENDAR_DIM_APPLICATION foreign key (ID_CALENDAR_DIM_APPLICATION  ) 
references calendar_dim(ID_CALENDAR_DIM)
 


alter table LICENSE_FACT
add constraint fk_LICENSE_FACT_ID_CALENDAR_DIM_CLOSED foreign key (ID_CALENDAR_DIM_CLOSED  ) 
references calendar_dim(ID_CALENDAR_DIM)
 


alter table LICENSE_FACT
add constraint fk_LICENSE_FACT_ID_CALENDAR_DIM_EXPIRATION 
foreign key (ID_CALENDAR_DIM_EXPIRATION  ) references calendar_dim(ID_CALENDAR_DIM) 


alter table LICENSE_FACT
add constraint fk_LICENSE_FACT_ID_CALENDAR_DIM_ISSUE foreign key (ID_CALENDAR_DIM_ISSUE  ) references calendar_dim(ID_CALENDAR_DIM) 


alter table LICENSE_FACT
add constraint fk_LICENSE_FACT_ID_LICENSE_ATTRIB_DIM foreign key (ID_LICENSE_ATTRIB_DIM  ) references license_attrib_dim(ID_LICENSE_ATTRIB_DIM)



alter table LICENSE_FACT
add constraint fk_LICENSE_FACT_ID_LOCATION_DIM foreign key (ID_LOCATION_DIM  ) references LOCATION_DIM(ID_LOCATION_DIM)



alter table LICENSE_FACT
add constraint fk_LICENSE_FACT_ID_PROVIDER_DIM foreign key (ID_PROVIDER_DIM  ) references PROVIDER_DIM(ID_PROVIDER_DIM)
 


alter table LICENSE_FACT
add constraint fk_LICENSE_FACT_ID_WORKER_DIM foreign key (ID_WORKER_DIM  ) references WORKER_DIM(ID_WORKER_DIM)



--alter table MEETING_FACT
--add constraint fk_MEETING_FACT_ID_CALENDAR_DIM_CANCEL foreign key (ID_CALENDAR_DIM_CANCEL  ) references calendar_dim(id_calendar_dim)
--

--alter table MEETING_FACT
--add constraint fk_MEETING_FACT_ID_CALENDAR_DIM_MTNG foreign key (ID_CALENDAR_DIM_MTNG  ) references calendar_dim(id_calendar_dim) 
--

--alter table MEETING_FACT
--add constraint fk_MEETING_FACT_ID_CALENDAR_DIM_SETUP foreign key (ID_CALENDAR_DIM_SETUP  ) references calendar_dim(id_calendar_dim) 
--

--alter table MEETING_FACT
--add constraint fk_MEETING_FACT_ID_CASE_DIM foreign key (ID_CASE_DIM  ) references case_dim(id_case_dim)
--


--alter table MEETING_FACT
--add constraint fk_MEETING_FACT_ID_LOCATION_DIM_CASE foreign key (ID_LOCATION_DIM_CASE  ) references LOCATION_DIM(ID_LOCATION_DIM)
--


--alter table MEETING_FACT
--add constraint fk_MEETING_FACT_ID_LOCATION_DIM_MEETING_LEADER foreign key (ID_LOCATION_DIM_MEETING_LEADER  ) references LOCATION_DIM(ID_LOCATION_DIM)
--

--alter table MEETING_FACT
--add constraint fk_MEETING_FACT_ID_MEETING_TYPE_DIM foreign key (ID_MEETING_TYPE_DIM  ) references MEETING_TYPE_DIM(ID_MEETING_TYPE_DIM)
--


--alter table MEETING_FACT
--add constraint fk_MEETING_FACT_ID_OUTCOME_DIM foreign key (ID_OUTCOME_DIM  ) references OUTCOME_DIM (ID_OUTCOME_DIM)
--


--alter table MEETING_FACT
--add constraint fk_MEETING_FACT_ID_PEOPLE_DIM_CHILD foreign key (ID_PEOPLE_DIM_CHILD  ) references PEOPLE_DIM(ID_PEOPLE_DIM)
--


--alter table MEETING_FACT
--add constraint fk_MEETING_FACT_ID_WORKER_DIM foreign key (ID_WORKER_DIM  ) references WORKER_DIM(ID_WORKER_DIM)
--


alter table PAYMENT_DETAIL_FACT
add constraint fk_PAYMENT_DETAIL_FACT_ID_PAYMENT_FACT foreign key (ID_PAYMENT_FACT  ) references PAYMENT_FACT  (ID_PAYMENT_FACT  )



alter table PAYMENT_DETAIL_FACT
add constraint fk_PAYMENT_DETAIL_FACT_ID_CALENDAR_DIM_EFFECTIVE foreign key (ID_CALENDAR_DIM_EFFECTIVE  ) references   calendar_dim(id_calendar_dim) 


alter table PAYMENT_DETAIL_FACT
add constraint fk_PAYMENT_DETAIL_FACT_ID_CALENDAR_DIM_FROM foreign key (ID_CALENDAR_DIM_FROM  )  references calendar_dim(id_calendar_dim)  


alter table PAYMENT_DETAIL_FACT
add constraint fk_PAYMENT_DETAIL_FACT_ID_CALENDAR_DIM_TO foreign key (ID_CALENDAR_DIM_TO  )references calendar_dim(id_calendar_dim)  



alter table PAYMENT_DETAIL_FACT
add constraint fk_PAYMENT_DETAIL_FACT_ID_PAYMENT_DETAIL_DIM foreign key (ID_PAYMENT_DETAIL_DIM  ) references PAYMENT_DETAIL_DIM (ID_PAYMENT_DETAIL_DIM )



alter table PAYMENT_DETAIL_FACT
add constraint fk_PAYMENT_DETAIL_FACT_ID_SOURCE_FUNDS_DIM foreign key (ID_SOURCE_FUNDS_DIM  ) references SOURCE_FUNDS_DIM(ID_SOURCE_FUNDS_DIM)



alter table PAYMENT_FACT
add constraint fk_PAYMENT_FACT_ID_CALENDAR_DIM_AUTHORIZATION_BEGIN foreign key (ID_CALENDAR_DIM_AUTHORIZATION_BEGIN  )  references   calendar_dim(id_calendar_dim)  


alter table PAYMENT_FACT
add constraint fk_PAYMENT_FACT_ID_CALENDAR_DIM_AUTHORIZATION_END foreign key (ID_CALENDAR_DIM_AUTHORIZATION_END  )  references   calendar_dim(id_calendar_dim)  


alter table PAYMENT_FACT
add constraint fk_PAYMENT_FACT_ID_CALENDAR_DIM_PAYMENT_END foreign key (ID_CALENDAR_DIM_PAYMENT_END  )  references   calendar_dim(id_calendar_dim)  


alter table PAYMENT_FACT
add constraint fk_PAYMENT_FACT_ID_CALENDAR_DIM_PAYMENT_START foreign key (ID_CALENDAR_DIM_PAYMENT_START  )  references   calendar_dim(id_calendar_dim)  


alter table PAYMENT_FACT
add constraint fk_PAYMENT_FACT_ID_CALENDAR_DIM_SERVICE_BEGIN foreign key (ID_CALENDAR_DIM_SERVICE_BEGIN  )  references   calendar_dim(id_calendar_dim)  


alter table PAYMENT_FACT
add constraint fk_PAYMENT_FACT_ID_CALENDAR_DIM_SERVICE_END foreign key (ID_CALENDAR_DIM_SERVICE_END  )  references   calendar_dim(id_calendar_dim)  


alter table PAYMENT_FACT
add constraint fk_PAYMENT_FACT_ID_CALENDAR_DIM_WARRANT foreign key (ID_CALENDAR_DIM_WARRANT  )  references   calendar_dim(id_calendar_dim)  


alter table PAYMENT_FACT
add constraint fk_PAYMENT_FACT_ID_CASE_DIM foreign key (ID_CASE_DIM  ) references case_dim(ID_CASE_DIM)



alter table PAYMENT_FACT
add constraint fk_PAYMENT_FACT_ID_LOCATION_DIM foreign key (ID_LOCATION_DIM  ) references LOCATION_DIM(ID_LOCATION_DIM)



alter table PAYMENT_FACT
add constraint fk_PAYMENT_FACT_ID_PAYMENT_DIM foreign key (ID_PAYMENT_DIM  ) references PAYMENT_DIM(ID_PAYMENT_DIM)



alter table PAYMENT_FACT
add constraint fk_PAYMENT_FACT_ID_PEOPLE_DIM_CHILD foreign key (ID_PEOPLE_DIM_CHILD  ) references PEOPLE_DIM(ID_PEOPLE_DIM)



alter table PAYMENT_FACT
add constraint fk_PAYMENT_FACT_ID_PEOPLE_DIM_CLIENT foreign key (ID_PEOPLE_DIM_CLIENT  ) references PEOPLE_DIM(ID_PEOPLE_DIM) 


alter table PAYMENT_FACT
add constraint fk_PAYMENT_FACT_ID_PLACEMENT_CARE_AUTH_DIM foreign key (ID_PLACEMENT_CARE_AUTH_DIM  ) references PLACEMENT_CARE_AUTH_DIM (ID_PLACEMENT_CARE_AUTH_DIM )



alter table PAYMENT_FACT
add constraint fk_PAYMENT_FACT_ID_PLACEMENT_TYPE_DIM foreign key (ID_PLACEMENT_TYPE_DIM  ) references PLACEMENT_TYPE_DIM(ID_PLACEMENT_TYPE_DIM)


alter table PAYMENT_FACT
add constraint fk_PAYMENT_FACT_ID_PROVIDER_DIM_PAYEE foreign key (ID_PROVIDER_DIM_PAYEE  ) references PROVIDER_DIM(ID_PROVIDER_DIM)



alter table PAYMENT_FACT
add constraint fk_PAYMENT_FACT_ID_PROVIDER_DIM_SERVICE foreign key (ID_PROVIDER_DIM_SERVICE  ) references PROVIDER_DIM(ID_PROVIDER_DIM) 


alter table PAYMENT_FACT
add constraint fk_PAYMENT_FACT_ID_SERVICE_TYPE_DIM foreign key (ID_SERVICE_TYPE_DIM  ) references SERVICE_TYPE_DIM(ID_SERVICE_TYPE_DIM)



alter table PAYMENT_FACT
add constraint fk_PAYMENT_FACT_ID_WORKER_DIM foreign key (ID_WORKER_DIM  ) references WORKER_DIM (ID_WORKER_DIM )



alter table PEOPLE_DIM
add constraint fk_PEOPLE_DIM_ID_WORKER_DIM_SSI_SSA_UPDATE foreign key (ID_WORKER_DIM_SSI_SSA_UPDATE  ) references WORKER_DIM (ID_WORKER_DIM ) 


alter table PERMANENCY_FACT
add constraint fk_PERMANENCY_FACT_ID_CALENDAR_DIM_HEARING foreign key (ID_CALENDAR_DIM_HEARING  ) references  calendar_dim(id_calendar_dim)


alter table PERMANENCY_FACT
add constraint fk_PERMANENCY_FACT_ID_CALENDAR_DIM_ORDER_ENTERED foreign key (ID_CALENDAR_DIM_ORDER_ENTERED  ) references  calendar_dim(id_calendar_dim) 


alter table PERMANENCY_FACT
add constraint fk_PERMANENCY_FACT_ID_CASE_DIM foreign key (ID_CASE_DIM  ) references case_dim(id_case_dim)



alter table PERMANENCY_FACT
add constraint fk_PERMANENCY_FACT_ID_LEGAL_JURISDICTION_DIM foreign key (ID_LEGAL_JURISDICTION_DIM  ) references LEGAL_JURISDICTION_DIM(ID_LEGAL_JURISDICTION_DIM)



alter table PERMANENCY_FACT
add constraint fk_PERMANENCY_FACT_ID_LEGAL_STATUS_DIM foreign key (ID_LEGAL_STATUS_DIM  ) references LEGAL_STATUS_DIM(ID_LEGAL_STATUS_DIM)



alter table PERMANENCY_FACT
add constraint fk_PERMANENCY_FACT_ID_PEOPLE_DIM foreign key (ID_PEOPLE_DIM  ) references people_dim(ID_PEOPLE_DIM)


alter table PERMANENCY_FACT
add constraint fk_PERMANENCY_FACT_ID_PERMANENCY_PLAN_DIM foreign key (ID_PERMANENCY_PLAN_DIM  ) references PERMANENCY_PLAN_DIM(ID_PERMANENCY_PLAN_DIM)



alter table PLACEMENT_CARE_AUTH_FACT
add constraint fk_PLACEMENT_CARE_AUTH_FACT_ID_CALENDAR_DIM_BEGIN foreign key (ID_CALENDAR_DIM_BEGIN  ) references calendar_dim(ID_CALENDAR_DIM) 


alter table PLACEMENT_CARE_AUTH_FACT
add constraint fk_PLACEMENT_CARE_AUTH_FACT_ID_CALENDAR_DIM_END foreign key (ID_CALENDAR_DIM_END  ) references calendar_dim(ID_CALENDAR_DIM)



alter table PLACEMENT_CARE_AUTH_FACT
add constraint fk_PLACEMENT_CARE_AUTH_FACT_ID_PEOPLE_DIM foreign key (ID_PEOPLE_DIM  ) references people_dim(ID_PEOPLE_DIM) 


alter table PLACEMENT_CARE_AUTH_FACT
add constraint fk_PLACEMENT_CARE_AUTH_FACT_ID_PLACEMENT_CARE_AUTH_DIM foreign key (ID_PLACEMENT_CARE_AUTH_DIM  ) references PLACEMENT_CARE_AUTH_DIM(ID_PLACEMENT_CARE_AUTH_DIM)



alter table PLACEMENT_FACT
add constraint fk_PLACEMENT_FACT_ID_REMOVAL_EPISODE_FACT foreign key (ID_REMOVAL_EPISODE_FACT  ) references REMOVAL_EPISODE_FACT (ID_REMOVAL_EPISODE_FACT )



alter table PLACEMENT_FACT
add constraint fk_PLACEMENT_FACT_ID_CALENDAR_DIM_BEGIN foreign key (ID_CALENDAR_DIM_BEGIN  )  references calendar_dim(ID_CALENDAR_DIM) 


alter table PLACEMENT_FACT
add constraint fk_PLACEMENT_FACT_ID_CALENDAR_DIM_END foreign key (ID_CALENDAR_DIM_END  )  references calendar_dim(ID_CALENDAR_DIM) 


alter table PLACEMENT_FACT
add constraint fk_PLACEMENT_FACT_ID_CALENDAR_DIM_RMVL foreign key (ID_CALENDAR_DIM_RMVL  )  references calendar_dim(ID_CALENDAR_DIM)
 


alter table PLACEMENT_FACT
add constraint fk_PLACEMENT_FACT_ID_CASE_DIM foreign key (ID_CASE_DIM  ) references dbo.case_dim(id_case_dim)



alter table PLACEMENT_FACT
add constraint fk_PLACEMENT_FACT_ID_LOCATION_DIM_PLACEMENT foreign key (ID_LOCATION_DIM_PLACEMENT  ) references LOCATION_DIM(ID_LOCATION_DIM)



alter table PLACEMENT_FACT
add constraint fk_PLACEMENT_FACT_ID_LOCATION_DIM_REMOVAL foreign key (ID_LOCATION_DIM_REMOVAL  ) references LOCATION_DIM(ID_LOCATION_DIM) 


alter table PLACEMENT_FACT
add constraint fk_PLACEMENT_FACT_ID_LOCATION_DIM_WORKER foreign key (ID_LOCATION_DIM_WORKER  ) references LOCATION_DIM(ID_LOCATION_DIM) 


alter table PLACEMENT_FACT
add constraint fk_PLACEMENT_FACT_ID_PEOPLE_DIM_CHILD foreign key (ID_PEOPLE_DIM_CHILD  ) references PEOPLE_DIM(ID_PEOPLE_DIM)



alter table PLACEMENT_FACT
add constraint fk_PLACEMENT_FACT_ID_PLACEMENT_CARE_AUTH_DIM foreign key (ID_PLACEMENT_CARE_AUTH_DIM  ) references PLACEMENT_CARE_AUTH_DIM(ID_PLACEMENT_CARE_AUTH_DIM)



alter table PLACEMENT_FACT
add constraint fk_PLACEMENT_FACT_ID_PLACEMENT_DISCHARGE_REASON_DIM foreign key (ID_PLACEMENT_DISCHARGE_REASON_DIM  ) 
references DISCHARGE_REASON_DIM(ID_DISCHARGE_REASON_DIM)



alter table PLACEMENT_FACT
add constraint fk_PLACEMENT_FACT_ID_PLACEMENT_RESULT_DIM foreign key (ID_PLACEMENT_RESULT_DIM  ) references PLACEMENT_RESULT_DIM(ID_PLACEMENT_RESULT_DIM)




alter table PLACEMENT_FACT
add constraint fk_PLACEMENT_FACT_ID_PLACEMENT_TYPE_DIM foreign key (ID_PLACEMENT_TYPE_DIM  ) references PLACEMENT_TYPE_DIM(ID_PLACEMENT_TYPE_DIM)



alter table PLACEMENT_FACT
add constraint fk_PLACEMENT_FACT_ID_PROVIDER_DIM_CAREGIVER foreign key (ID_PROVIDER_DIM_CAREGIVER  ) references PROVIDER_DIM(ID_PROVIDER_DIM)



alter table PLACEMENT_FACT
add constraint fk_PLACEMENT_FACT_ID_SERVICE_TYPE_DIM foreign key (ID_SERVICE_TYPE_DIM  ) references SERVICE_TYPE_DIM(ID_SERVICE_TYPE_DIM)



alter table PLACEMENT_FACT
add constraint fk_PLACEMENT_FACT_ID_LEGAL_STATUS_DIM foreign key (ID_LEGAL_STATUS_DIM  ) references LEGAL_STATUS_DIM(ID_LEGAL_STATUS_DIM)



alter table PRE_ADOPTION_LEGAL_FACT
add constraint fk_PRE_ADOPTION_LEGAL_FACT_ID_CALENDAR_DIM_ADOPTION foreign key (ID_CALENDAR_DIM_ADOPTION  ) references CALENDAR_DIM(ID_CALENDAR_DIM)



alter table PRE_ADOPTION_LEGAL_FACT
add constraint fk_PRE_ADOPTION_LEGAL_FACT_ID_LEGAL_JURISDICTION_DIM foreign key (ID_LEGAL_JURISDICTION_DIM  ) references LEGAL_JURISDICTION_DIM(ID_LEGAL_JURISDICTION_DIM)



alter table PRE_ADOPTION_LEGAL_FACT
add constraint fk_PRE_ADOPTION_LEGAL_FACT_ID_PEOPLE_DIM foreign key (ID_PEOPLE_DIM  ) references PEOPLE_DIM(ID_PEOPLE_DIM)



alter table PRE_ADOPTION_LEGAL_FACT
add constraint fk_PRE_ADOPTION_LEGAL_FACT_ID_PLACEMENT_CARE_AUTH_DIM foreign key (ID_PLACEMENT_CARE_AUTH_DIM  ) 
references PLACEMENT_CARE_AUTH_DIM (ID_PLACEMENT_CARE_AUTH_DIM )



alter table PRIMARY_ASSIGNMENT_FACT
add constraint fk_PRIMARY_ASSIGNMENT_FACT_ID_CALENDAR_DIM_BEGIN foreign key (ID_CALENDAR_DIM_BEGIN  ) references dbo.calendar_dim(ID_CALENDAR_DIM)



alter table PRIMARY_ASSIGNMENT_FACT
add constraint fk_PRIMARY_ASSIGNMENT_FACT_ID_CALENDAR_DIM_END foreign key (ID_CALENDAR_DIM_END  )  references dbo.calendar_dim(ID_CALENDAR_DIM) 


alter table PRIMARY_ASSIGNMENT_FACT
add constraint fk_PRIMARY_ASSIGNMENT_FACT_ID_CASE_DIM foreign key (ID_CASE_DIM  ) references case_dim(id_case_dim)



alter table PRIMARY_ASSIGNMENT_FACT
add constraint fk_PRIMARY_ASSIGNMENT_FACT_ID_LOCATION_DIM foreign key (ID_LOCATION_DIM  ) references LOCATION_DIM(ID_LOCATION_DIM)



alter table PRIMARY_ASSIGNMENT_FACT
add constraint fk_PRIMARY_ASSIGNMENT_FACT_ID_WORKER_DIM foreign key (ID_WORKER_DIM  ) references WORKER_DIM(ID_WORKER_DIM)



alter table PRIMARY_ASSIGNMENT_FACT
add constraint fk_PRIMARY_ASSIGNMENT_FACT_ID_WORKER_DIM_CURRENT foreign key (ID_WORKER_DIM_CURRENT  )  references WORKER_DIM(ID_WORKER_DIM) 


--alter table PROVIDER_ACTIVITY_FACT
--add constraint fk_PROVIDER_ACTIVITY_FACT_ID_CALENDAR_DIM_BEGIN foreign key (ID_CALENDAR_DIM_BEGIN  ) references dbo.calendar_dim(ID_CALENDAR_DIM)  
--

--alter table PROVIDER_ACTIVITY_FACT
--add constraint fk_PROVIDER_ACTIVITY_FACT_ID_CALENDAR_DIM_COMPLETED foreign key (ID_CALENDAR_DIM_COMPLETED  ) references dbo.calendar_dim(ID_CALENDAR_DIM)  
--

--alter table PROVIDER_ACTIVITY_FACT
--add constraint fk_PROVIDER_ACTIVITY_FACT_ID_CALENDAR_DIM_END foreign key (ID_CALENDAR_DIM_END  ) references dbo.calendar_dim(ID_CALENDAR_DIM)  
--

--alter table PROVIDER_ACTIVITY_FACT
--add constraint fk_PROVIDER_ACTIVITY_FACT_ID_PROVIDER_ACTIVITY_DIM foreign key (ID_PROVIDER_ACTIVITY_DIM  ) references PROVIDER_ACTIVITY_DIM(ID_PROVIDER_ACTIVITY_DIM)
--

--alter table PROVIDER_ACTIVITY_FACT
--add constraint fk_PROVIDER_ACTIVITY_FACT_ID_PROVIDER_DIM foreign key (ID_PROVIDER_DIM  ) references PROVIDER_DIM(ID_PROVIDER_DIM)
--


alter table PROVIDER_DIM
add constraint fk_PROVIDER_DIM_ID_CALENDAR_DIM_CREATED foreign key (ID_CALENDAR_DIM_CREATED  ) references dbo.calendar_dim(ID_CALENDAR_DIM)   


--alter table PROVIDER_NOTES_FACT
--add constraint fk_PROVIDER_NOTES_FACT_ID_CALENDAR_DIM foreign key (ID_CALENDAR_DIM  ) references dbo.calendar_dim(ID_CALENDAR_DIM)   
--

--alter table PROVIDER_NOTES_FACT
--add constraint fk_PROVIDER_NOTES_FACT_ID_PROVIDER_DIM foreign key (ID_PROVIDER_DIM  ) references PROVIDER_DIM(ID_PROVIDER_DIM) 
--

--alter table PROVIDER_NOTES_FACT
--add constraint fk_PROVIDER_NOTES_FACT_ID_PROVIDER_NOTES_TYPE_DIM foreign key (ID_PROVIDER_NOTES_TYPE_DIM  ) references dbo.PROVIDER_NOTES_TYPE_DIM(ID_PROVIDER_NOTES_TYPE_DIM)
--


alter table PROVIDER_PART_FACT
add constraint fk_PROVIDER_PART_FACT_ID_CALENDAR_DIM_END foreign key (ID_CALENDAR_DIM_END  ) references dbo.calendar_dim(ID_CALENDAR_DIM)    


alter table PROVIDER_PART_FACT
add constraint fk_PROVIDER_PART_FACT_ID_CALENDAR_DIM_START foreign key (ID_CALENDAR_DIM_START  ) references dbo.calendar_dim(ID_CALENDAR_DIM)    


alter table PROVIDER_PART_FACT
add constraint fk_PROVIDER_PART_FACT_ID_PEOPLE_DIM foreign key (ID_PEOPLE_DIM  ) references PEOPLE_DIM(ID_PEOPLE_DIM)



alter table PROVIDER_PART_FACT
add constraint fk_PROVIDER_PART_FACT_ID_PROVIDER_DIM_CAREGIVER foreign key (ID_PROVIDER_DIM_CAREGIVER  ) references PROVIDER_DIM(ID_PROVIDER_DIM)



alter table PROVIDER_SERVICE_LICENSE_FACT
add constraint fk_PROVIDER_SERVICE_LICENSE_FACT_ID_LICENSE_FACT foreign key (ID_LICENSE_FACT  ) references LICENSE_FACT(ID_LICENSE_FACT)



alter table PROVIDER_SERVICE_LICENSE_FACT
add constraint fk_PROVIDER_SERVICE_LICENSE_FACT_ID_PROVIDER_DIM foreign key (ID_PROVIDER_DIM  ) references PROVIDER_DIM(ID_PROVIDER_DIM) 


alter table PROVIDER_SERVICE_LICENSE_FACT
add constraint fk_PROVIDER_SERVICE_LICENSE_FACT_ID_SERVICE_TYPE_DIM foreign key (ID_SERVICE_TYPE_DIM  ) references SERVICE_TYPE_DIM (ID_SERVICE_TYPE_DIM)



--alter table REMOVAL_EPISODE_FACT
--add constraint fk_REMOVAL_EPISODE_FACT_ID_CALENDAR_DIM_AFCARS_BEGIN foreign key (ID_CALENDAR_DIM_AFCARS_BEGIN  ) references dbo.calendar_dim(ID_CALENDAR_DIM)     
--

alter table REMOVAL_EPISODE_FACT
add constraint fk_REMOVAL_EPISODE_FACT_ID_CALENDAR_DIM_AFCARS_END foreign key (ID_CALENDAR_DIM_AFCARS_END  ) references dbo.calendar_dim(ID_CALENDAR_DIM)     


alter table REMOVAL_EPISODE_FACT
add constraint fk_REMOVAL_EPISODE_FACT_ID_CALENDAR_DIM_BEGIN foreign key (ID_CALENDAR_DIM_BEGIN  ) references dbo.calendar_dim(ID_CALENDAR_DIM)     


alter table REMOVAL_EPISODE_FACT
add constraint fk_REMOVAL_EPISODE_FACT_ID_CALENDAR_DIM_END foreign key (ID_CALENDAR_DIM_END  ) references dbo.calendar_dim(ID_CALENDAR_DIM)     


alter table REMOVAL_EPISODE_FACT
add constraint fk_REMOVAL_EPISODE_FACT_ID_CALENDAR_DIM_FIRST_HEALTH_SAFETY_VISIT 
foreign key (ID_CALENDAR_DIM_FIRST_HEALTH_SAFETY_VISIT  ) references  dbo.calendar_dim(ID_CALENDAR_DIM)    



alter table REMOVAL_EPISODE_FACT
add constraint fk_REMOVAL_EPISODE_FACT_ID_CASE_DIM foreign key (ID_CASE_DIM  ) references dbo.case_dim(id_case_dim)



alter table REMOVAL_EPISODE_FACT
add constraint fk_REMOVAL_EPISODE_FACT_ID_DISCHARGE_REASON_DIM foreign key (ID_DISCHARGE_REASON_DIM  ) references DISCHARGE_REASON_DIM(ID_DISCHARGE_REASON_DIM)



alter table REMOVAL_EPISODE_FACT
add constraint fk_REMOVAL_EPISODE_FACT_ID_FAMILY_STRUCTURE_DIM foreign key (ID_FAMILY_STRUCTURE_DIM  ) references FAMILY_STRUCTURE_DIM (ID_FAMILY_STRUCTURE_DIM  ) 



alter table REMOVAL_EPISODE_FACT
add constraint fk_REMOVAL_EPISODE_FACT_ID_LOCATION_DIM_REMOVAL foreign key (ID_LOCATION_DIM_REMOVAL  ) references LOCATION_DIM(ID_LOCATION_DIM)



alter table REMOVAL_EPISODE_FACT
add constraint fk_REMOVAL_EPISODE_FACT_ID_LOCATION_DIM_WORKER foreign key (ID_LOCATION_DIM_WORKER  ) references LOCATION_DIM(ID_LOCATION_DIM) 


alter table REMOVAL_EPISODE_FACT
add constraint fk_REMOVAL_EPISODE_FACT_ID_PEOPLE_DIM_CHILD foreign key (ID_PEOPLE_DIM_CHILD  ) references PEOPLE_DIM(ID_PEOPLE_DIM)



alter table REMOVAL_EPISODE_FACT
add constraint fk_REMOVAL_EPISODE_FACT_ID_PEOPLE_DIM_PARENT_PRIMARY foreign key (ID_PEOPLE_DIM_PARENT_PRIMARY  ) references PEOPLE_DIM(ID_PEOPLE_DIM) 


alter table REMOVAL_EPISODE_FACT
add constraint fk_REMOVAL_EPISODE_FACT_ID_PEOPLE_DIM_PARENT_SECONDARY foreign key (ID_PEOPLE_DIM_PARENT_SECONDARY  ) references PEOPLE_DIM(ID_PEOPLE_DIM)
 


alter table REMOVAL_EPISODE_FACT
add constraint fk_REMOVAL_EPISODE_FACT_ID_PLACEMENT_CARE_AUTH_DIM foreign key (ID_PLACEMENT_CARE_AUTH_DIM  ) references PLACEMENT_CARE_AUTH_DIM(ID_PLACEMENT_CARE_AUTH_DIM)



alter table REMOVAL_EPISODE_FACT
add constraint fk_REMOVAL_EPISODE_FACT_ID_REMOVAL_DIM foreign key (ID_REMOVAL_DIM  ) references REMOVAL_DIM(ID_REMOVAL_DIM)



alter table REMOVAL_EPISODE_FACT
add constraint fk_REMOVAL_EPISODE_FACT_ID_WORKER_DIM_CURRENT foreign key (ID_WORKER_DIM_CURRENT  ) references WORKER_DIM(ID_WORKER_DIM)


alter table REMOVAL_EPISODE_FACT
add constraint fk_REMOVAL_EPISODE_FACT_ID_WORKER_DIM_ORIGINAL foreign key (ID_WORKER_DIM_ORIGINAL  )  references WORKER_DIM(ID_WORKER_DIM) 


alter table REMOVAL_EPISODE_FACT
add constraint fk_REMOVAL_EPISODE_FACT_ID_LEGAL_STATUS_DIM foreign key (ID_LEGAL_STATUS_DIM  ) references LEGAL_STATUS_DIM(ID_LEGAL_STATUS_DIM)



alter table REMOVAL_EPISODE_FACT
add constraint fk_REMOVAL_EPISODE_FACT_ID_PLACEMENT_RESULT_DIM_LATEST foreign key (ID_PLACEMENT_RESULT_DIM_LATEST  ) 
references PLACEMENT_RESULT_DIM(ID_PLACEMENT_RESULT_DIM)


alter table REPEAT_MALTREATMENT_FACT
add constraint fk_REPEAT_MALTREATMENT_FACT_ID_CALENDAR_DIM_PRIOR foreign key (ID_CALENDAR_DIM_PRIOR  ) 
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)



alter table REPEAT_MALTREATMENT_FACT
add constraint fk_REPEAT_MALTREATMENT_FACT_ID_CALENDAR_DIM_REPEAT foreign key (ID_CALENDAR_DIM_REPEAT  ) references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)
 


alter table REPEAT_MALTREATMENT_FACT
add constraint fk_REPEAT_MALTREATMENT_FACT_ID_CASE_DIM foreign key (ID_CASE_DIM  ) references dbo.case_dim(id_case_dim)



alter table REPEAT_MALTREATMENT_FACT
add constraint fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_INCIDENT foreign key (ID_LOCATION_DIM_INCIDENT  ) references LOCATION_DIM(ID_LOCATION_DIM)



alter table REPEAT_MALTREATMENT_FACT
add constraint fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_INTAKE_WORKER foreign key (ID_LOCATION_DIM_INTAKE_WORKER  )  references LOCATION_DIM(ID_LOCATION_DIM) 


alter table REPEAT_MALTREATMENT_FACT
add constraint fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_INVESTIGATION_WORKER foreign key (ID_LOCATION_DIM_INVESTIGATION_WORKER  )  references LOCATION_DIM(ID_LOCATION_DIM) 


alter table REPEAT_MALTREATMENT_FACT
add constraint fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_PRIMARY_WORKER foreign key (ID_LOCATION_DIM_PRIMARY_WORKER  )  references LOCATION_DIM(ID_LOCATION_DIM)


alter table REPEAT_MALTREATMENT_FACT
add constraint fk_REPEAT_MALTREATMENT_FACT_ID_PEOPLE_DIM_VICTIM foreign key (ID_PEOPLE_DIM_VICTIM  ) references PEOPLE_DIM(ID_PEOPLE_DIM)



alter table REPEAT_MALTREATMENT_FACT
add constraint fk_REPEAT_MALTREATMENT_FACT_ID_PLACEMENT_TYPE_DIM foreign key (ID_PLACEMENT_TYPE_DIM  ) references PLACEMENT_TYPE_DIM(ID_PLACEMENT_TYPE_DIM)



alter table RGAP_AGREEMENT_FACT
add constraint fk_RGAP_AGREEMENT_FACT_ID_CASE_DIM foreign key (ID_CASE_DIM  ) references case_dim(id_case_dim)



alter table RGAP_AGREEMENT_FACT
add constraint fk_RGAP_AGREEMENT_FACT_ID_PEOPLE_DIM foreign key (ID_PEOPLE_DIM  ) references PEOPLE_DIM(ID_PEOPLE_DIM)



alter table RGAP_AGREEMENT_FACT
add constraint fk_RGAP_AGREEMENT_FACT_ID_PROVIDER_DIM foreign key (ID_PROVIDER_DIM  ) references PROVIDER_DIM(ID_PROVIDER_DIM)



alter table RGAP_AGREEMENT_FACT
add constraint fk_RGAP_AGREEMENT_FACT_ID_RGAP_AGREEMENT_ATTRIBUTE_DIM foreign key (ID_RGAP_AGREEMENT_ATTRIBUTE_DIM  ) 
references RGAP_AGREEMENT_ATTRIBUTE_DIM(ID_RGAP_AGREEMENT_ATTRIBUTE_DIM)



alter table RGAP_AGREEMENT_FACT
add constraint fk_RGAP_AGREEMENT_FACT_ID_CALENDAR_DIM_RGAP_EFFECTIVE foreign key (ID_CALENDAR_DIM_RGAP_EFFECTIVE  )
 references CALENDAR_DIM(ID_CALENDAR_DIM)
 


alter table RGAP_AGREEMENT_FACT
add constraint fk_RGAP_AGREEMENT_FACT_ID_CALENDAR_DIM_RGAP_END foreign key (ID_CALENDAR_DIM_RGAP_END  )  references CALENDAR_DIM(ID_CALENDAR_DIM)
  


alter table RGAP_AGREEMENT_FACT
add constraint fk_RGAP_AGREEMENT_FACT_ID_WORKER_DIM_RESPONSIBLE foreign key (ID_WORKER_DIM_RESPONSIBLE  ) references worker_dim(id_worker_dim)


alter table RGAP_ELIGIBILITY_FACT
add constraint fk_RGAP_ELIGIBILITY_FACT_ID_CASE_DIM foreign key (ID_CASE_DIM  ) references case_dim(id_case_dim)



alter table RGAP_ELIGIBILITY_FACT
add constraint fk_RGAP_ELIGIBILITY_FACT_ID_PEOPLE_DIM foreign key (ID_PEOPLE_DIM  ) references PEOPLE_DIM(ID_PEOPLE_DIM)



alter table RGAP_ELIGIBILITY_FACT
add constraint fk_RGAP_ELIGIBILITY_FACT_ID_PROVIDER_DIM foreign key (ID_PROVIDER_DIM  ) references PROVIDER_DIM (ID_PROVIDER_DIM )



alter table RGAP_ELIGIBILITY_FACT
add constraint fk_RGAP_ELIGIBILITY_FACT_ID_RGAP_ELIGIBILITY_STATUS_DIM foreign key (ID_RGAP_ELIGIBILITY_STATUS_DIM  ) references RGAP_ELIGIBILITY_STATUS_DIM(ID_RGAP_ELIGIBILITY_STATUS_DIM)



alter table RGAP_ELIGIBILITY_FACT
add constraint fk_RGAP_ELIGIBILITY_FACT_ID_CALENDAR_DIM_DETERMINATION_EFFECTIVE 
foreign key (ID_CALENDAR_DIM_DETERMINATION_EFFECTIVE  ) references calendar_dim(id_calendar_dim)



alter table RGAP_ELIGIBILITY_FACT
add constraint fk_RGAP_ELIGIBILITY_FACT_ID_CALENDAR_DIM_DETERMINATION_END 
foreign key (ID_CALENDAR_DIM_DETERMINATION_END  )  references calendar_dim(id_calendar_dim)
 


alter table RGAP_ELIGIBILITY_FACT
add constraint fk_RGAP_ELIGIBILITY_FACT_ID_CALENDAR_DIM_DETERMINATION_COMPLETED 
foreign key (ID_CALENDAR_DIM_DETERMINATION_COMPLETED  )  references calendar_dim(id_calendar_dim)
 


alter table RGAP_ELIGIBILITY_FACT
add constraint fk_RGAP_ELIGIBILITY_FACT_ID_WORKER_DIM_DETERMINATION_COMPLETED 
foreign key (ID_WORKER_DIM_DETERMINATION_COMPLETED  ) references WORKER_DIM(ID_WORKER_DIM)



alter table SAFETY_ASSESSMENT_FACT
add constraint fk_SAFETY_ASSESSMENT_FACT_ID_INTAKE_FACT foreign key (ID_INTAKE_FACT  ) references intake_fact(id_intake_fact)



alter table SAFETY_ASSESSMENT_FACT
add constraint fk_SAFETY_ASSESSMENT_FACT_ID_CALENDAR_DIM_APPROVAL foreign key (ID_CALENDAR_DIM_APPROVAL  ) references calendar_dim(id_calendar_dim) 


alter table SAFETY_ASSESSMENT_FACT
add constraint fk_SAFETY_ASSESSMENT_FACT_ID_CALENDAR_DIM_INVESTIGATION_BEGIN foreign key (ID_CALENDAR_DIM_INVESTIGATION_BEGIN  ) references calendar_dim(id_calendar_dim) 


alter table SAFETY_ASSESSMENT_FACT
add constraint fk_SAFETY_ASSESSMENT_FACT_ID_CALENDAR_DIM_INVESTIGATION_END foreign key (ID_CALENDAR_DIM_INVESTIGATION_END  ) references calendar_dim(id_calendar_dim)  


alter table SAFETY_ASSESSMENT_FACT
add constraint fk_SAFETY_ASSESSMENT_FACT_ID_CASE_DIM foreign key (ID_CASE_DIM  ) references case_dim(id_case_dim)



alter table SAFETY_ASSESSMENT_FACT
add constraint fk_SAFETY_ASSESSMENT_FACT_ID_LOCATION_DIM foreign key (ID_LOCATION_DIM  ) references LOCATION_DIM(ID_LOCATION_DIM)



alter table SAFETY_ASSESSMENT_FACT
add constraint fk_SAFETY_ASSESSMENT_FACT_ID_PEOPLE_DIM_CHILD foreign key (ID_PEOPLE_DIM_CHILD  ) references PEOPLE_DIM(ID_PEOPLE_DIM)



alter table SAFETY_ASSESSMENT_FACT
add constraint fk_SAFETY_ASSESSMENT_FACT_ID_WORKER_DIM foreign key (ID_WORKER_DIM  ) references WORKER_DIM(ID_WORKER_DIM)



alter table SERVICE_FACT
add constraint fk_SERVICE_FACT_ID_REMOVAL_EPISODE_FACT foreign key (ID_REMOVAL_EPISODE_FACT  ) references REMOVAL_EPISODE_FACT(ID_REMOVAL_EPISODE_FACT)



alter table SERVICE_FACT
add constraint fk_SERVICE_FACT_ID_CALENDAR_DIM_END foreign key (ID_CALENDAR_DIM_END  ) references CALENDAR_DIM(ID_CALENDAR_DIM)



alter table SERVICE_FACT
add constraint fk_SERVICE_FACT_ID_CALENDAR_DIM_START foreign key (ID_CALENDAR_DIM_START  ) references CALENDAR_DIM(ID_CALENDAR_DIM)
 


alter table SERVICE_FACT
add constraint fk_SERVICE_FACT_ID_CASE_DIM foreign key (ID_CASE_DIM  ) references case_dim(id_case_dim)



alter table SERVICE_FACT
add constraint fk_SERVICE_FACT_ID_LOCATION_DIM_TIME_OF_APPROVAL foreign key (ID_LOCATION_DIM_TIME_OF_APPROVAL  )
 references LOCATION_DIM(ID_LOCATION_DIM)
 


alter table SERVICE_FACT
add constraint fk_SERVICE_FACT_ID_PEOPLE_DIM_CHILD foreign key (ID_PEOPLE_DIM_CHILD  ) references PEOPLE_DIM(ID_PEOPLE_DIM)



alter table SERVICE_FACT
add constraint fk_SERVICE_FACT_ID_PEOPLE_DIM_SERVICE_RECIPIENT foreign key (ID_PEOPLE_DIM_SERVICE_RECIPIENT  )  references PEOPLE_DIM(ID_PEOPLE_DIM) 


alter table SERVICE_FACT
add constraint fk_SERVICE_FACT_ID_PLACEMENT_CARE_AUTH_DIM foreign key (ID_PLACEMENT_CARE_AUTH_DIM  ) references PLACEMENT_CARE_AUTH_DIM(ID_PLACEMENT_CARE_AUTH_DIM)



alter table SERVICE_FACT
add constraint fk_SERVICE_FACT_ID_PLACEMENT_RESULT_DIM foreign key (ID_PLACEMENT_RESULT_DIM  ) references PLACEMENT_RESULT_DIM(ID_PLACEMENT_RESULT_DIM)



alter table SERVICE_FACT
add constraint fk_SERVICE_FACT_ID_PLACEMENT_TYPE_DIM foreign key (ID_PLACEMENT_TYPE_DIM  ) references PLACEMENT_TYPE_DIM(ID_PLACEMENT_TYPE_DIM)



alter table SERVICE_FACT
add constraint fk_SERVICE_FACT_ID_PROVIDER_DIM foreign key (ID_PROVIDER_DIM  ) references PROVIDER_DIM (ID_PROVIDER_DIM   ) 


alter table SERVICE_FACT
add constraint fk_SERVICE_FACT_ID_SERVICE_TYPE_DIM foreign key (ID_SERVICE_TYPE_DIM  ) references SERVICE_TYPE_DIM(ID_SERVICE_TYPE_DIM)



alter table SIBLING_RELATIONSHIP_FACT
add constraint fk_SIBLING_RELATIONSHIP_FACT_ID_CALENDAR_DIM_BEGIN foreign key (ID_CALENDAR_DIM_BEGIN  ) references CALENDAR_DIM(ID_CALENDAR_DIM)



alter table SIBLING_RELATIONSHIP_FACT
add constraint fk_SIBLING_RELATIONSHIP_FACT_ID_CALENDAR_DIM_END foreign key (ID_CALENDAR_DIM_END  ) references CALENDAR_DIM(ID_CALENDAR_DIM)
 


alter table SIBLING_RELATIONSHIP_FACT
add constraint fk_SIBLING_RELATIONSHIP_FACT_ID_CASE_DIM_CHILD foreign key (ID_CASE_DIM_CHILD  ) references case_dim(id_case_dim)



alter table SIBLING_RELATIONSHIP_FACT
add constraint fk_SIBLING_RELATIONSHIP_FACT_ID_PEOPLE_DIM_CHILD foreign key (ID_PEOPLE_DIM_CHILD  ) references  people_dim(id_people_dim)



alter table SIBLING_RELATIONSHIP_FACT
add constraint fk_SIBLING_RELATIONSHIP_FACT_ID_PEOPLE_DIM_SIBLING foreign key (ID_PEOPLE_DIM_SIBLING  )  references  people_dim(id_people_dim) 


--alter table SUBSTANCE_ABUSE_WIZARD_FACT
--add constraint fk_SUBSTANCE_ABUSE_WIZARD_FACT_ID_INVESTIGATION_ASSESSMENT_FACT foreign key (ID_INVESTIGATION_ASSESSMENT_FACT  )
--references INVESTIGATION_ASSESSMENT_FACT(ID_INVESTIGATION_ASSESSMENT_FACT)
--



alter table SUBSTANCE_ABUSE_WIZARD_FACT
add constraint fk_SUBSTANCE_ABUSE_WIZARD_FACT_ID_PEOPLE_DIM_SUBJECT foreign key (ID_PEOPLE_DIM_SUBJECT  )  references  people_dim(id_people_dim) 
 


alter table TANF_FACT
add constraint fk_TANF_FACT_ID_CALENDAR_DIM_BEGIN foreign key (ID_CALENDAR_DIM_BEGIN  )  references CALENDAR_DIM(ID_CALENDAR_DIM) 


alter table TANF_FACT
add constraint fk_TANF_FACT_ID_CALENDAR_DIM_END foreign key (ID_CALENDAR_DIM_END  )  references CALENDAR_DIM(ID_CALENDAR_DIM) 


alter table TANF_FACT
add constraint fk_TANF_FACT_ID_CASE_DIM foreign key (ID_CASE_DIM  ) references CASE_DIM(ID_CASE_DIM)



alter table TANF_FACT
add constraint fk_TANF_FACT_ID_PEOPLE_DIM foreign key (ID_PEOPLE_DIM  ) references PEOPLE_DIM (ID_PEOPLE_DIM)


alter table TANF_FACT
add constraint fk_TANF_FACT_ID_TANF_DIM foreign key (ID_TANF_DIM  ) references TANF_DIM(ID_TANF_DIM)


alter table TANF_FACT
add constraint fk_TANF_FACT_ID_WORKER_DIM_COMPLETED foreign key (ID_WORKER_DIM_COMPLETED  ) references WORKER_DIM(ID_WORKER_DIM)



alter table TANF_FACT
add constraint fk_TANF_FACT_ID_WORKER_DIM_DETERMINATION foreign key (ID_WORKER_DIM_DETERMINATION  ) references WORKER_DIM(ID_WORKER_DIM) 


alter table TRAINING_FACT
add constraint fk_TRAINING_FACT_ID_CALENDAR_DIM_COMPLETION foreign key (ID_CALENDAR_DIM_COMPLETION  ) references CALENDAR_DIM(ID_CALENDAR_DIM)  


alter table TRAINING_FACT
add constraint fk_TRAINING_FACT_ID_CALENDAR_DIM_EXPIRATION foreign key (ID_CALENDAR_DIM_EXPIRATION  ) references CALENDAR_DIM(ID_CALENDAR_DIM)  


alter table TRAINING_FACT
add constraint fk_TRAINING_FACT_ID_PEOPLE_DIM_TRAINING_PARTICIPANT foreign key (ID_PEOPLE_DIM_TRAINING_PARTICIPANT  ) references PEOPLE_DIM(ID_PEOPLE_DIM)



alter table TRAINING_FACT
add constraint fk_TRAINING_FACT_ID_TRAINING_TYPE_DIM foreign key (ID_TRAINING_TYPE_DIM  ) references TRAINING_TYPE_DIM(ID_TRAINING_TYPE_DIM)



alter table TRIBE_FACT
add constraint fk_TRIBE_FACT_ID_CALENDAR_DIM_ENTERED foreign key (ID_CALENDAR_DIM_ENTERED  ) references CALENDAR_DIM(ID_CALENDAR_DIM)   


alter table TRIBE_FACT
add constraint fk_TRIBE_FACT_ID_PEOPLE_DIM foreign key (ID_PEOPLE_DIM  )  references PEOPLE_DIM(ID_PEOPLE_DIM) 


alter table TRIBE_FACT
add constraint fk_TRIBE_FACT_ID_TRIBE_ATTRIBUTE_DIM foreign key (ID_TRIBE_ATTRIBUTE_DIM  ) references TRIBE_ATTRIBUTE_DIM(ID_TRIBE_ATTRIBUTE_DIM)


alter table TRIBE_FACT
add constraint fk_TRIBE_FACT_ID_TRIBE_DIM foreign key (ID_TRIBE_DIM  ) references TRIBE_DIM (ID_TRIBE_DIM  )




alter table WORKER_DIM
add constraint fk_WORKER_DIM_ID_LOCATION_DIM_WORKER foreign key (ID_LOCATION_DIM_WORKER  ) references LOCATION_DIM(ID_LOCATION_DIM)



alter table WORKER_DIM
add constraint fk_WORKER_DIM_ID_WORKER_DIM_SUPERVISOR foreign key (ID_WORKER_DIM_SUPERVISOR  ) references  WORKER_DIM(ID_WORKER_DIM)




alter table  [dbo].[INTAKE_VICTIM_FACT]  
add constraint [fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_VICTIM_ADDED] FOREIGN KEY([ID_CALENDAR_DIM_VICTIM_ADDED])
references [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM])




ALTER TABLE [dbo].[INTAKE_VICTIM_FACT]  
ADD  CONSTRAINT [FK_INTAKE_VICTIM_FACT_INTAKE_FACT] FOREIGN KEY([ID_INTAKE_FACT])
REFERENCES [dbo].[INTAKE_FACT] ([ID_INTAKE_FACT])








