CREATE  procedure [dbo].[prod_ca_load_drop_foreign_keys]
as
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_WORKER_DIM_PRIMARY]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_WORKER_DIM_PRIMARY]

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_PROVIDER_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_PROVIDER_DIM]

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_PLACEMENT_TYPE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_PLACEMENT_TYPE_DIM]

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_PEOPLE_DIM_VICTIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_PEOPLE_DIM_VICTIM]

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_LOCATION_DIM_PRIMARY_WORKER]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_LOCATION_DIM_PRIMARY_WORKER]

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_LOCATION_DIM_INTAKE_WORKER]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_LOCATION_DIM_INTAKE_WORKER]

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_LOCATION_DIM_INCIDENT]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_LOCATION_DIM_INCIDENT]

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_CASE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_CASE_DIM]

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_CALENDAR_DIM_REFERRED]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_CALENDAR_DIM_REFERRED]

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_CALENDAR_DIM_INCIDENT]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_CALENDAR_DIM_INCIDENT]

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_id_calendar_dim_founded]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_id_calendar_dim_founded]


IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_CALENDAR_DIM_TERMINATED]')
   AND parent_object_id = OBJECT_ID(N'dbo.adoption_fact')
)
ALTER TABLE dbo.ADOPTION_FACT DROP CONSTRAINT fk_ID_CALENDAR_DIM_TERMINATED

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_CALENDAR_DIM_EFFECTIVE_ELIGIBLE]')
   AND parent_object_id = OBJECT_ID(N'dbo.adoption_fact')
)
ALTER TABLE dbo.ADOPTION_FACT DROP CONSTRAINT fk_ID_CALENDAR_DIM_EFFECTIVE_ELIGIBLE

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_CALENDAR_DIM_COMPLETE]')
   AND parent_object_id = OBJECT_ID(N'dbo.adoption_fact')
)
ALTER TABLE dbo.ADOPTION_FACT DROP CONSTRAINT fk_ID_CALENDAR_DIM_COMPLETE

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_ADOPTION_STATUS_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.adoption_fact')
)
ALTER TABLE dbo.ADOPTION_FACT DROP CONSTRAINT fk_ID_ADOPTION_STATUS_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_af_ID_PEOPLE_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.adoption_fact')
)
ALTER TABLE dbo.ADOPTION_FACT DROP CONSTRAINT fk_af_ID_PEOPLE_DIM_CHILD

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_af_ID_CASE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.adoption_fact')
)
ALTER TABLE dbo.ADOPTION_FACT DROP CONSTRAINT fk_af_ID_CASE_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ALLEGATION_FACT_ID_RELATIONSHIP_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ALLEGATION_FACT')
)
ALTER TABLE dbo.ALLEGATION_FACT DROP CONSTRAINT fk_ALLEGATION_FACT_ID_RELATIONSHIP_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ALLEGATION_FACT_ID_PEOPLE_DIM_SUBJECT]')
   AND parent_object_id = OBJECT_ID(N'dbo.ALLEGATION_FACT')
)
ALTER TABLE dbo.ALLEGATION_FACT DROP CONSTRAINT fk_ALLEGATION_FACT_ID_PEOPLE_DIM_SUBJECT

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ALLEGATION_FACT_ID_INVESTIGATION_ASSESSMENT_FACT]')
   AND parent_object_id = OBJECT_ID(N'dbo.ALLEGATION_FACT')
)
ALTER TABLE dbo.ALLEGATION_FACT DROP CONSTRAINT fk_ALLEGATION_FACT_ID_INVESTIGATION_ASSESSMENT_FACT

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ALLEGATION_FACT_ID_INTAKE_FACT]')
   AND parent_object_id = OBJECT_ID(N'dbo.ALLEGATION_FACT')
)
ALTER TABLE dbo.ALLEGATION_FACT DROP CONSTRAINT fk_ALLEGATION_FACT_ID_INTAKE_FACT

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ALLEGATION_FACT_ID_FINDINGS_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ALLEGATION_FACT')
)
ALTER TABLE dbo.ALLEGATION_FACT DROP CONSTRAINT fk_ALLEGATION_FACT_ID_FINDINGS_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ALLEGATION_FACT_ID_CASE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ALLEGATION_FACT')
)
ALTER TABLE dbo.ALLEGATION_FACT DROP CONSTRAINT fk_ALLEGATION_FACT_ID_CASE_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ALLEGATION_FACT_ID_ABUSE_TYPE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ALLEGATION_FACT')
)
ALTER TABLE dbo.ALLEGATION_FACT DROP CONSTRAINT fk_ALLEGATION_FACT_ID_ABUSE_TYPE_DIM


IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ASSIGNMENT_FACT_ID_WORKER_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ASSIGNMENT_FACT')
)
ALTER TABLE dbo.ASSIGNMENT_FACT DROP CONSTRAINT fk_ASSIGNMENT_FACT_ID_WORKER_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ASSIGNMENT_FACT_ID_PROVIDER_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ASSIGNMENT_FACT')
)
ALTER TABLE dbo.ASSIGNMENT_FACT DROP CONSTRAINT fk_ASSIGNMENT_FACT_ID_PROVIDER_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ASSIGNMENT_FACT_ID_PEOPLE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ASSIGNMENT_FACT')
)
ALTER TABLE dbo.ASSIGNMENT_FACT DROP CONSTRAINT fk_ASSIGNMENT_FACT_ID_PEOPLE_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ASSIGNMENT_FACT_ID_LOCATION_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ASSIGNMENT_FACT')
)
ALTER TABLE dbo.ASSIGNMENT_FACT DROP CONSTRAINT fk_ASSIGNMENT_FACT_ID_LOCATION_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ASSIGNMENT_FACT_ID_CASE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ASSIGNMENT_FACT')
)
ALTER TABLE dbo.ASSIGNMENT_FACT DROP CONSTRAINT fk_ASSIGNMENT_FACT_ID_CASE_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_END]')
   AND parent_object_id = OBJECT_ID(N'dbo.ASSIGNMENT_FACT')
)
ALTER TABLE dbo.ASSIGNMENT_FACT DROP CONSTRAINT fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_END

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_BEGIN]')
   AND parent_object_id = OBJECT_ID(N'dbo.ASSIGNMENT_FACT')
)
ALTER TABLE dbo.ASSIGNMENT_FACT DROP CONSTRAINT fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_BEGIN

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ASSIGNMENT_FACT_ID_ASSIGNMENT_ATTRIBUTE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ASSIGNMENT_FACT')
)
ALTER TABLE dbo.ASSIGNMENT_FACT DROP CONSTRAINT fk_ASSIGNMENT_FACT_ID_ASSIGNMENT_ATTRIBUTE_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_IID_PLACEMENT_TYPE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
 ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_IID_PLACEMENT_TYPE_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_WORKER_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_WORKER_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_SOURCE_FUNDS_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_SOURCE_FUNDS_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_SERVICE_TYPE_DIME]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_SERVICE_TYPE_DIME

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_PROVIDER_DIM_SERVICE]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_PROVIDER_DIM_SERVICE

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_PROVIDER_DIM_PAYEE]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_PROVIDER_DIM_PAYEE

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_PLACEMENT_CARE_AUTH_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_PLACEMENT_CARE_AUTH_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_PEOPLE_DIM_CLIENT]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_PEOPLE_DIM_CLIENT

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_PEOPLE_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_PEOPLE_DIM_CHILD

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_LOCATION_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_LOCATION_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_CHART_OF_ACCOUNTS_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_CHART_OF_ACCOUNTS_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_CASE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_CASE_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_SERVICE_END]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_SERVICE_END

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_SERVICE_BEGIN]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_SERVICE_BEGIN

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_AUTH_END]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_AUTH_END

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_AUTH_BEGIN]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_AUTH_BEGIN

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_AUTHORIZATION_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_AUTHORIZATION_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_DIM_ID_LOCATION_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_DIM')
)
ALTER TABLE dbo.CASE_DIM DROP CONSTRAINT fk_CASE_DIM_ID_LOCATION_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_DIM_ID_CALENDAR_DIM_LAST_ACTIVITY]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_DIM')
)
ALTER TABLE dbo.CASE_DIM DROP CONSTRAINT fk_CASE_DIM_ID_CALENDAR_DIM_LAST_ACTIVITY


IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_NOTE_FACT_ID_WORKER_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_NOTE_FACT')
)
ALTER TABLE dbo.CASE_NOTE_FACT DROP CONSTRAINT fk_CASE_NOTE_FACT_ID_WORKER_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_NOTE_FACT_ID_PEOPLE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_NOTE_FACT')
)
ALTER TABLE dbo.CASE_NOTE_FACT DROP CONSTRAINT fk_CASE_NOTE_FACT_ID_PEOPLE_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_NOTE_FACT_ID_LOCATION_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_NOTE_FACT')
)
ALTER TABLE dbo.CASE_NOTE_FACT DROP CONSTRAINT fk_CASE_NOTE_FACT_ID_LOCATION_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_NOTE_FACT_ID_LEGAL_STATUS_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_NOTE_FACT')
)
ALTER TABLE dbo.CASE_NOTE_FACT DROP CONSTRAINT fk_CASE_NOTE_FACT_ID_LEGAL_STATUS_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_NOTE_FACT_ID_CASE_NOTE_TYPE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_NOTE_FACT')
)
ALTER TABLE dbo.CASE_NOTE_FACT DROP CONSTRAINT fk_CASE_NOTE_FACT_ID_CASE_NOTE_TYPE_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_NOTE_FACT_ID_CASE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_NOTE_FACT')
)
ALTER TABLE dbo.CASE_NOTE_FACT DROP CONSTRAINT fk_CASE_NOTE_FACT_ID_CASE_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_NOTE_FACT_ID_CALENDAR_DIM_PRIOR_VISIT]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_NOTE_FACT')
)
ALTER TABLE dbo.CASE_NOTE_FACT DROP CONSTRAINT fk_CASE_NOTE_FACT_ID_CALENDAR_DIM_PRIOR_VISIT

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_NOTE_FACT_ID_CALENDAR_DIM_OCCURRED]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_NOTE_FACT')
)
ALTER TABLE dbo.CASE_NOTE_FACT DROP CONSTRAINT fk_CASE_NOTE_FACT_ID_CALENDAR_DIM_OCCURRED

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_DLR_RISK_ASSESSMENT_FACT_ID_PROVIDER_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.DLR_RISK_ASSESSMENT_FACT')
)
alter table DLR_RISK_ASSESSMENT_FACT
drop constraint fk_DLR_RISK_ASSESSMENT_FACT_ID_PROVIDER_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_DLR_RISK_ASSESSMENT_FACT_ID_CALENDAR_DIM_COMPLETED]')
   AND parent_object_id = OBJECT_ID(N'dbo.DLR_RISK_ASSESSMENT_FACT')
)
alter table DLR_RISK_ASSESSMENT_FACT
drop constraint fk_DLR_RISK_ASSESSMENT_FACT_ID_CALENDAR_DIM_COMPLETED

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_WORKER_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_WORKER_DIM_CHILD

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_WORKER_DIM_CASE]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_WORKER_DIM_CASE

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_SCHOOL_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_SCHOOL_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_PEOPLE_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_PEOPLE_DIM_CHILD

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_LOCATION_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_LOCATION_DIM_CHILD

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_LOCATION_DIM_CASE]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_LOCATION_DIM_CASE

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_EDUCATION_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_EDUCATION_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_CALENDAR_DIM_ENROLLMENT_END]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_CALENDAR_DIM_ENROLLMENT_END

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_CALENDAR_DIM_ENROLLED]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_CALENDAR_DIM_ENROLLED

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_CALENDAR_DIM_EARNED_DIPLOMA]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_CALENDAR_DIM_EARNED_DIPLOMA

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_CALENDAR_DIM_CREATED]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_CALENDAR_DIM_CREATED


IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_PLAN_FACT_ID_PEOPLE_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_PLAN_FACT')
)
ALTER TABLE [dbo].[EDUCATION_PLAN_FACT] DROP CONSTRAINT [fk_EDUCATION_PLAN_FACT_ID_PEOPLE_DIM_CHILD]

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_PLAN_FACT_ID_EDUCATION_PLAN_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_PLAN_FACT')
)
ALTER TABLE [dbo].[EDUCATION_PLAN_FACT] DROP CONSTRAINT [fk_EDUCATION_PLAN_FACT_ID_EDUCATION_PLAN_DIM]

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_PLAN_FACT_ID_CALENDAR_DIM_PLAN_DATE]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_PLAN_FACT')
)
ALTER TABLE [dbo].[EDUCATION_PLAN_FACT] DROP CONSTRAINT fk_EDUCATION_PLAN_FACT_ID_CALENDAR_DIM_PLAN_DATE


IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_EDUCATION_RECORDS_REQUEST_REFERRAL_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_RECORDS_REQUEST_REFERRAL_FACT')
)
ALTER TABLE dbo.EDUCATION_RECORDS_REQUEST_REFERRAL_FACT 
DROP CONSTRAINT fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_EDUCATION_RECORDS_REQUEST_REFERRAL_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_CALENDAR_DIM_REQUESTED]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_RECORDS_REQUEST_REFERRAL_FACT')
)
ALTER TABLE dbo.EDUCATION_RECORDS_REQUEST_REFERRAL_FACT DROP CONSTRAINT fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_CALENDAR_DIM_REQUESTED

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_CALENDAR_DIM_REFERRAL]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_RECORDS_REQUEST_REFERRAL_FACT')
)
ALTER TABLE dbo.EDUCATION_RECORDS_REQUEST_REFERRAL_FACT DROP CONSTRAINT fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_CALENDAR_DIM_REFERRAL

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_CALENDAR_DIM_RECEIVED]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_RECORDS_REQUEST_REFERRAL_FACT')
)
ALTER TABLE dbo.EDUCATION_RECORDS_REQUEST_REFERRAL_FACT DROP CONSTRAINT fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_CALENDAR_DIM_RECEIVED

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIG_EPISODE_FACT_ID_CALENDAR_DIM_END]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIG_EPISODE_FACT')
)
alter table ELIG_EPISODE_FACT
drop constraint fk_ELIG_EPISODE_FACT_ID_CALENDAR_DIM_END 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIG_EPISODE_FACT_ID_CALENDAR_DIM_BEGIN]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIG_EPISODE_FACT')
)
alter table ELIG_EPISODE_FACT
drop constraint fk_ELIG_EPISODE_FACT_ID_CALENDAR_DIM_BEGIN 


IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIG_EPISODE_FACT_ID_CASE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIG_EPISODE_FACT')
)
alter table ELIG_EPISODE_FACT
drop constraint fk_ELIG_EPISODE_FACT_ID_CASE_DIM 


IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIG_EPISODE_FACT_ID_PEOPLE_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIG_EPISODE_FACT')
)
alter table ELIG_EPISODE_FACT
drop constraint fk_ELIG_EPISODE_FACT_ID_PEOPLE_DIM_CHILD

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_COMPLETE]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_COMPLETE 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_COMPLETE]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_COMPLETE 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_EFFECTIVE]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_EFFECTIVE 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_END]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_END 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_VPA_CTW]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_VPA_CTW 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_PEOPLE_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_PEOPLE_DIM_CHILD 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_WORKER_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_WORKER_DIM 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_ELIGIBILITY_REMOVAL_HOME_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_ELIGIBILITY_REMOVAL_HOME_DIM 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_ELIGIBILITY_STATUS_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_ELIGIBILITY_STATUS_DIM 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_ELIGIBILITY_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_ELIGIBILITY_DIM 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_HEALTH_ACTIVITY_FACT_ID_CALENDAR_DIM_ACTIVITY_END]')
   AND parent_object_id = OBJECT_ID(N'dbo.HEALTH_ACTIVITY_FACT')
)
alter table HEALTH_ACTIVITY_FACT
drop constraint fk_HEALTH_ACTIVITY_FACT_ID_CALENDAR_DIM_ACTIVITY_END 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_HEALTH_ACTIVITY_FACT_ID_CALENDAR_DIM_ACTIVITY_START]')
   AND parent_object_id = OBJECT_ID(N'dbo.HEALTH_ACTIVITY_FACT')
)
alter table HEALTH_ACTIVITY_FACT
drop constraint fk_HEALTH_ACTIVITY_FACT_ID_CALENDAR_DIM_ACTIVITY_START

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_HEALTH_ACTIVITY_FACT_ID_HEALTH_ACTIVITY_TYPE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.HEALTH_ACTIVITY_FACT')
)
alter table HEALTH_ACTIVITY_FACT
drop constraint fk_HEALTH_ACTIVITY_FACT_ID_HEALTH_ACTIVITY_TYPE_DIM 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_HEALTH_ACTIVITY_FACT_ID_MENTAL_HEALTH_EVAL_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.HEALTH_ACTIVITY_FACT')
)
alter table HEALTH_ACTIVITY_FACT
drop constraint fk_HEALTH_ACTIVITY_FACT_ID_MENTAL_HEALTH_EVAL_DIM 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_HEALTH_ACTIVITY_FACT_ID_PEOPLE_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.HEALTH_ACTIVITY_FACT')
)
alter table HEALTH_ACTIVITY_FACT
drop constraint fk_HEALTH_ACTIVITY_FACT_ID_PEOPLE_DIM_CHILD 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_HEALTH_CAT_ATTRIBUTE_BRIDGE_FACT_ID_HEALTH_ACTIVITY_FACT]')
   AND parent_object_id = OBJECT_ID(N'dbo.HEALTH_CAT_ATTRIBUTE_BRIDGE_FACT')
)
alter table HEALTH_CAT_ATTRIBUTE_BRIDGE_FACT
drop constraint fk_HEALTH_CAT_ATTRIBUTE_BRIDGE_FACT_ID_HEALTH_ACTIVITY_FACT

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_IL_ANSELL_CASEY_ASSESSMENT_FACT_ID_INDEPENDENT_LIVING_FACT]')
   AND parent_object_id = OBJECT_ID(N'dbo.IL_ANSELL_CASEY_ASSESSMENT_FACT')
)
alter table IL_ANSELL_CASEY_ASSESSMENT_FACT
drop constraint fk_IL_ANSELL_CASEY_ASSESSMENT_FACT_ID_INDEPENDENT_LIVING_FACT 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_IL_NYTD_QUESTIONS_FACT_ID_INDEPENDENT_LIVING_FACT]')
   AND parent_object_id = OBJECT_ID(N'dbo.IL_NYTD_QUESTIONS_FACT')
)
alter table IL_NYTD_QUESTIONS_FACT
drop constraint fk_IL_NYTD_QUESTIONS_FACT_ID_INDEPENDENT_LIVING_FACT 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_IL_NYTD_QUESTIONS_FACT_ID_IL_NYTD_QUESTIONS_ATTRIBUTE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.IL_NYTD_QUESTIONS_FACT')
)
alter table IL_NYTD_QUESTIONS_FACT
drop constraint fk_IL_NYTD_QUESTIONS_FACT_ID_IL_NYTD_QUESTIONS_ATTRIBUTE_DIM 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_IL_NYTD_QUESTIONS_FACT_ID_CALENDAR_DIM_SURVEY_COMPLETED]')
   AND parent_object_id = OBJECT_ID(N'dbo.IL_NYTD_QUESTIONS_FACT')
)
alter table IL_NYTD_QUESTIONS_FACT
drop constraint fk_IL_NYTD_QUESTIONS_FACT_ID_CALENDAR_DIM_SURVEY_COMPLETED 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_ANTICIPATED_OUT_CARE]')
   AND parent_object_id = OBJECT_ID(N'dbo.INDEPENDENT_LIVING_FACT')
)
alter table INDEPENDENT_LIVING_FACT
drop constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_ANTICIPATED_OUT_CARE 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_BEGAN]')
   AND parent_object_id = OBJECT_ID(N'dbo.INDEPENDENT_LIVING_FACT')
)
alter table INDEPENDENT_LIVING_FACT
drop constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_BEGAN 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_IL_PLAN_COMPLETED]')
   AND parent_object_id = OBJECT_ID(N'dbo.INDEPENDENT_LIVING_FACT')
)
alter table INDEPENDENT_LIVING_FACT
drop constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_IL_PLAN_COMPLETED 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_INITIAL_IL_REFERRAL]')
   AND parent_object_id = OBJECT_ID(N'dbo.INDEPENDENT_LIVING_FACT')
)
alter table INDEPENDENT_LIVING_FACT
drop constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_INITIAL_IL_REFERRAL

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_REFERRED]')
   AND parent_object_id = OBJECT_ID(N'dbo.INDEPENDENT_LIVING_FACT')
)
alter table INDEPENDENT_LIVING_FACT
drop constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_REFERRED

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_YOUTH_NOT_PARTICIPATING]')
   AND parent_object_id = OBJECT_ID(N'dbo.INDEPENDENT_LIVING_FACT')
)
alter table INDEPENDENT_LIVING_FACT
drop constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_YOUTH_NOT_PARTICIPATING 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INDEPENDENT_LIVING_FACT_ID_PEOPLE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.INDEPENDENT_LIVING_FACT')
)
alter table INDEPENDENT_LIVING_FACT
drop constraint fk_INDEPENDENT_LIVING_FACT_ID_PEOPLE_DIM 


IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_CALENDAR_DIM_ACCESS_RCVD]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_ACCESS_RCVD 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_CALENDAR_DIM_CPS_SPVR_DSCN]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_CPS_SPVR_DSCN 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_CALENDAR_DIM_INCD]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_INCD

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_CALENDAR_DIM_SPVR_DSCN]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_SPVR_DSCN 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_CALENDAR_DIM_WRKR_DSCN]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_WRKR_DSCN 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_CASE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_CASE_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_INTAKE_ATTRIBUTE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_INTAKE_ATTRIBUTE_DIM 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_INTAKE_TYPE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_INTAKE_TYPE_DIM 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_LOCATION_DIM_INTAKE_WORKER]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_LOCATION_DIM_INTAKE_WORKER 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_PROVIDER_DIM_INTAKE]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_PROVIDER_DIM_INTAKE

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_RESPONSE_TIME_EXP_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_RESPONSE_TIME_EXP_DIM 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_WORKER_DIM_CPS_SUPERVISOR]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_WORKER_DIM_CPS_SUPERVISOR 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_WORKER_DIM_INTAKE]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_WORKER_DIM_INTAKE 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_WORKER_DIM_INTAKE_SUPERVISOR]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_WORKER_DIM_INTAKE_SUPERVISOR  

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_PARTICIPANT_FACT_ID_INTAKE_PARTICIPANT_ROLES_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.INTAKE_PARTICIPANT_FACT')
)
alter table INTAKE_PARTICIPANT_FACT
drop constraint fk_INTAKE_PARTICIPANT_FACT_ID_INTAKE_PARTICIPANT_ROLES_DIM 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_PARTICIPANT_FACT_ID_PEOPLE_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.INTAKE_PARTICIPANT_FACT')
)
alter table INTAKE_PARTICIPANT_FACT
drop constraint fk_INTAKE_PARTICIPANT_FACT_ID_PEOPLE_DIM_CHILD 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_SERVICE_BRIDGE_FACT_ID_INTAKE_FACT]')
   AND parent_object_id = OBJECT_ID(N'dbo.INTAKE_SERVICE_BRIDGE_FACT')
)
alter table INTAKE_SERVICE_BRIDGE_FACT
drop constraint fk_INTAKE_SERVICE_BRIDGE_FACT_ID_INTAKE_FACT ;

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_SERVICE_BRIDGE_FACT_ID_SERVICE_REFERRAL_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.INTAKE_SERVICE_BRIDGE_FACT')
)
alter table INTAKE_SERVICE_BRIDGE_FACT
drop constraint fk_INTAKE_SERVICE_BRIDGE_FACT_ID_SERVICE_REFERRAL_DIM ;


--  intake victim fact
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_IFF_RESPONSE_ATTEMPT')
   AND parent_object_id = OBJECT_ID(N'dbo.INTAKE_VICTIM_FACT')
)
alter table INTAKE_VICTIM_FACT
drop constraint fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_IFF_RESPONSE_ATTEMPT


IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_IFF_RESPONSE_COMPLETED')
   AND parent_object_id = OBJECT_ID(N'dbo.INTAKE_VICTIM_FACT')
)
alter table INTAKE_VICTIM_FACT
drop constraint fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_IFF_RESPONSE_COMPLETED


IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.fk_INTAKE_VICTIM_FACT_IID_CALENDAR_DIM_VICTIM_ADDED')
   AND parent_object_id = OBJECT_ID(N'dbo.INTAKE_VICTIM_FACT')
)
alter table INTAKE_VICTIM_FACT
drop constraint fk_INTAKE_VICTIM_FACT_IID_CALENDAR_DIM_VICTIM_ADDED


IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_DUE_ORIGINAL')
   AND parent_object_id = OBJECT_ID(N'dbo.INTAKE_VICTIM_FACT')
)
alter table INTAKE_VICTIM_FACT
drop constraint fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_DUE_ORIGINAL

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_DUE')
   AND parent_object_id = OBJECT_ID(N'dbo.INTAKE_VICTIM_FACT')
)
alter table INTAKE_VICTIM_FACT
drop constraint fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_DUE

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.fk_INTAKE_VICTIM_FACT_ID_RESPONSE_TIME_EXP_DIM')
   AND parent_object_id = OBJECT_ID(N'dbo.INTAKE_VICTIM_FACT')
)
alter table INTAKE_VICTIM_FACT
drop constraint fk_INTAKE_VICTIM_FACT_ID_RESPONSE_TIME_EXP_DIM

---
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.fk_INVESTIGATION_ASSESSMENT_FACT_ID_CALENDAR_DIM_LEVEL1_APPROVED')
   AND parent_object_id = OBJECT_ID(N'dbo.INVESTIGATION_ASSESSMENT_FACT')
)
alter table INVESTIGATION_ASSESSMENT_FACT	
drop constraint fk_INVESTIGATION_ASSESSMENT_FACT_ID_CALENDAR_DIM_LEVEL1_APPROVED

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.fk_INVESTIGATION_ASSESSMENT_FACT_ID_CALENDAR_DIM_LEVEL2_APPROVED')
   AND parent_object_id = OBJECT_ID(N'dbo.INVESTIGATION_ASSESSMENT_FACT')
)
alter table INVESTIGATION_ASSESSMENT_FACT	
drop constraint fk_INVESTIGATION_ASSESSMENT_FACT_ID_CALENDAR_DIM_LEVEL2_APPROVED


IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.fk_INVESTIGATION_ASSESSMENT_FACT_ID_CASE_DIM')
   AND parent_object_id = OBJECT_ID(N'dbo.INVESTIGATION_ASSESSMENT_FACT')
)
alter table INVESTIGATION_ASSESSMENT_FACT	
drop constraint fk_INVESTIGATION_ASSESSMENT_FACT_ID_CASE_DIM 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.fk_INVESTIGATION_ASSESSMENT_FACT_ID_DISPOSITION_DIM')
   AND parent_object_id = OBJECT_ID(N'dbo.INVESTIGATION_ASSESSMENT_FACT')
)
alter table INVESTIGATION_ASSESSMENT_FACT	
drop constraint fk_INVESTIGATION_ASSESSMENT_FACT_ID_DISPOSITION_DIM 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.fk_INVESTIGATION_ASSESSMENT_FACT_ID_INVESTIGATION_TYPE_DIM')
   AND parent_object_id = OBJECT_ID(N'dbo.INVESTIGATION_ASSESSMENT_FACT')
)
alter table INVESTIGATION_ASSESSMENT_FACT	
drop constraint fk_INVESTIGATION_ASSESSMENT_FACT_ID_INVESTIGATION_TYPE_DIM 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.fk_INVESTIGATION_ASSESSMENT_FACT_ID_LOCATION_DIM')
   AND parent_object_id = OBJECT_ID(N'dbo.INVESTIGATION_ASSESSMENT_FACT')
)
alter table INVESTIGATION_ASSESSMENT_FACT	
drop constraint fk_INVESTIGATION_ASSESSMENT_FACT_ID_LOCATION_DIM

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.fk_INVESTIGATION_ASSESSMENT_FACT_ID_PROVIDER_DIM')
   AND parent_object_id = OBJECT_ID(N'dbo.INVESTIGATION_ASSESSMENT_FACT')
)
alter table INVESTIGATION_ASSESSMENT_FACT	
drop constraint fk_INVESTIGATION_ASSESSMENT_FACT_ID_PROVIDER_DIM 

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.fk_INVESTIGATION_ASSESSMENT_FACT_ID_WORKER_DIM')
   AND parent_object_id = OBJECT_ID(N'dbo.INVESTIGATION_ASSESSMENT_FACT')
)
alter table INVESTIGATION_ASSESSMENT_FACT	
drop constraint fk_INVESTIGATION_ASSESSMENT_FACT_ID_WORKER_DIM


--------
IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT_ID_CASE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT'))
alter table LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT
drop constraint fk_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT_ID_CASE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT_ID_PEOPLE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT'))
alter table LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT
drop constraint fk_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT_ID_PEOPLE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT_ID_CALENDAR_DIM_FINDING')  AND parent_object_id=OBJECT_ID(N'dbo.LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT'))
alter table LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT
drop constraint fk_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT_ID_CALENDAR_DIM_FINDING


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LEGAL_FACT_ID_CALENDAR_DIM_EFFECTIVE')  AND parent_object_id=OBJECT_ID(N'dbo.LEGAL_FACT'))
alter table LEGAL_FACT
drop constraint fk_LEGAL_FACT_ID_CALENDAR_DIM_EFFECTIVE


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LEGAL_FACT_ID_CALENDAR_DIM_HEARING')  AND parent_object_id=OBJECT_ID(N'dbo.LEGAL_FACT'))
alter table LEGAL_FACT
drop constraint fk_LEGAL_FACT_ID_CALENDAR_DIM_HEARING


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LEGAL_FACT_ID_CASE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.LEGAL_FACT'))
alter table LEGAL_FACT
drop constraint fk_LEGAL_FACT_ID_CASE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LEGAL_FACT_ID_LEGAL_ACTION_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.LEGAL_FACT'))
alter table LEGAL_FACT
drop constraint fk_LEGAL_FACT_ID_LEGAL_ACTION_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LEGAL_FACT_ID_LEGAL_JURISDICTION_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.LEGAL_FACT'))
alter table LEGAL_FACT
drop constraint fk_LEGAL_FACT_ID_LEGAL_JURISDICTION_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LEGAL_FACT_ID_LEGAL_RESULT_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.LEGAL_FACT'))
alter table LEGAL_FACT
drop constraint fk_LEGAL_FACT_ID_LEGAL_RESULT_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LEGAL_FACT_ID_LEGAL_STATUS_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.LEGAL_FACT'))
alter table LEGAL_FACT
drop constraint fk_LEGAL_FACT_ID_LEGAL_STATUS_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LEGAL_FACT_ID_PEOPLE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.LEGAL_FACT'))
alter table LEGAL_FACT
drop constraint fk_LEGAL_FACT_ID_PEOPLE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LEGAL_FACT_ID_WORKER_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.LEGAL_FACT'))
alter table LEGAL_FACT
drop constraint fk_LEGAL_FACT_ID_WORKER_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LEGAL_TPR_REFERRAL_FACT_ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT')  AND parent_object_id=OBJECT_ID(N'dbo.LEGAL_TPR_REFERRAL_FACT'))
alter table LEGAL_TPR_REFERRAL_FACT
drop constraint fk_LEGAL_TPR_REFERRAL_FACT_ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LEGAL_TPR_REFERRAL_FACT_ID_CALENDAR_DIM_TPR_REFERRAL')  AND parent_object_id=OBJECT_ID(N'dbo.LEGAL_TPR_REFERRAL_FACT'))
alter table LEGAL_TPR_REFERRAL_FACT
drop constraint fk_LEGAL_TPR_REFERRAL_FACT_ID_CALENDAR_DIM_TPR_REFERRAL


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LEGAL_TPR_REFERRAL_FACT_ID_RELATIONSHIP_DIM_TPR')  AND parent_object_id=OBJECT_ID(N'dbo.LEGAL_TPR_REFERRAL_FACT'))
alter table LEGAL_TPR_REFERRAL_FACT
drop constraint fk_LEGAL_TPR_REFERRAL_FACT_ID_RELATIONSHIP_DIM_TPR


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LEGAL_TPR_REFERRAL_FACT_ID_PEOPLE_DIM_TPR_PARENT')  AND parent_object_id=OBJECT_ID(N'dbo.LEGAL_TPR_REFERRAL_FACT'))
alter table LEGAL_TPR_REFERRAL_FACT
drop constraint fk_LEGAL_TPR_REFERRAL_FACT_ID_PEOPLE_DIM_TPR_PARENT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LICENSE_ACTION_FACT_ID_CALENDAR_DIM_ACTION')  AND parent_object_id=OBJECT_ID(N'dbo.LICENSE_ACTION_FACT'))
alter table LICENSE_ACTION_FACT
drop constraint fk_LICENSE_ACTION_FACT_ID_CALENDAR_DIM_ACTION


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LICENSE_ACTION_FACT_ID_LICENSE_ATTRIB_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.LICENSE_ACTION_FACT'))
alter table LICENSE_ACTION_FACT
drop constraint fk_LICENSE_ACTION_FACT_ID_LICENSE_ATTRIB_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LICENSE_ACTION_FACT_ID_PROVIDER_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.LICENSE_ACTION_FACT'))
alter table LICENSE_ACTION_FACT
drop constraint fk_LICENSE_ACTION_FACT_ID_PROVIDER_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LICENSE_FACT_ID_CALENDAR_DIM_APPLICATION')  AND parent_object_id=OBJECT_ID(N'dbo.LICENSE_FACT'))
alter table LICENSE_FACT
drop constraint fk_LICENSE_FACT_ID_CALENDAR_DIM_APPLICATION


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LICENSE_FACT_ID_CALENDAR_DIM_CLOSED')  AND parent_object_id=OBJECT_ID(N'dbo.LICENSE_FACT'))
alter table LICENSE_FACT
drop constraint fk_LICENSE_FACT_ID_CALENDAR_DIM_CLOSED


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LICENSE_FACT_ID_CALENDAR_DIM_EXPIRATION')  AND parent_object_id=OBJECT_ID(N'dbo.LICENSE_FACT'))
alter table LICENSE_FACT
drop constraint fk_LICENSE_FACT_ID_CALENDAR_DIM_EXPIRATION


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LICENSE_FACT_ID_CALENDAR_DIM_ISSUE')  AND parent_object_id=OBJECT_ID(N'dbo.LICENSE_FACT'))
alter table LICENSE_FACT
drop constraint fk_LICENSE_FACT_ID_CALENDAR_DIM_ISSUE


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LICENSE_FACT_ID_LICENSE_ATTRIB_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.LICENSE_FACT'))
alter table LICENSE_FACT
drop constraint fk_LICENSE_FACT_ID_LICENSE_ATTRIB_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LICENSE_FACT_ID_LOCATION_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.LICENSE_FACT'))
alter table LICENSE_FACT
drop constraint fk_LICENSE_FACT_ID_LOCATION_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LICENSE_FACT_ID_PROVIDER_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.LICENSE_FACT'))
alter table LICENSE_FACT
drop constraint fk_LICENSE_FACT_ID_PROVIDER_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_LICENSE_FACT_ID_WORKER_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.LICENSE_FACT'))
alter table LICENSE_FACT
drop constraint fk_LICENSE_FACT_ID_WORKER_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_MEETING_FACT_ID_CALENDAR_DIM_CANCEL')  AND parent_object_id=OBJECT_ID(N'dbo.MEETING_FACT'))
alter table MEETING_FACT
drop constraint fk_MEETING_FACT_ID_CALENDAR_DIM_CANCEL


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_MEETING_FACT_ID_CALENDAR_DIM_MTNG')  AND parent_object_id=OBJECT_ID(N'dbo.MEETING_FACT'))
alter table MEETING_FACT
drop constraint fk_MEETING_FACT_ID_CALENDAR_DIM_MTNG


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_MEETING_FACT_ID_CALENDAR_DIM_SETUP')  AND parent_object_id=OBJECT_ID(N'dbo.MEETING_FACT'))
alter table MEETING_FACT
drop constraint fk_MEETING_FACT_ID_CALENDAR_DIM_SETUP


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_MEETING_FACT_ID_CASE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.MEETING_FACT'))
alter table MEETING_FACT
drop constraint fk_MEETING_FACT_ID_CASE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_MEETING_FACT_ID_LOCATION_DIM_CASE')  AND parent_object_id=OBJECT_ID(N'dbo.MEETING_FACT'))
alter table MEETING_FACT
drop constraint fk_MEETING_FACT_ID_LOCATION_DIM_CASE


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_MEETING_FACT_ID_LOCATION_DIM_MEETING_LEADER')  AND parent_object_id=OBJECT_ID(N'dbo.MEETING_FACT'))
alter table MEETING_FACT
drop constraint fk_MEETING_FACT_ID_LOCATION_DIM_MEETING_LEADER


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_MEETING_FACT_ID_MEETING_TYPE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.MEETING_FACT'))
alter table MEETING_FACT
drop constraint fk_MEETING_FACT_ID_MEETING_TYPE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_MEETING_FACT_ID_OUTCOME_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.MEETING_FACT'))
alter table MEETING_FACT
drop constraint fk_MEETING_FACT_ID_OUTCOME_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_MEETING_FACT_ID_PEOPLE_DIM_CHILD')  AND parent_object_id=OBJECT_ID(N'dbo.MEETING_FACT'))
alter table MEETING_FACT
drop constraint fk_MEETING_FACT_ID_PEOPLE_DIM_CHILD


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_MEETING_FACT_ID_WORKER_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.MEETING_FACT'))
alter table MEETING_FACT
drop constraint fk_MEETING_FACT_ID_WORKER_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_DETAIL_FACT_ID_PAYMENT_FACT')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_DETAIL_FACT'))
alter table PAYMENT_DETAIL_FACT
drop constraint fk_PAYMENT_DETAIL_FACT_ID_PAYMENT_FACT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_DETAIL_FACT_ID_CALENDAR_DIM_EFFECTIVE')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_DETAIL_FACT'))
alter table PAYMENT_DETAIL_FACT
drop constraint fk_PAYMENT_DETAIL_FACT_ID_CALENDAR_DIM_EFFECTIVE


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_DETAIL_FACT_ID_CALENDAR_DIM_FROM')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_DETAIL_FACT'))
alter table PAYMENT_DETAIL_FACT
drop constraint fk_PAYMENT_DETAIL_FACT_ID_CALENDAR_DIM_FROM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_DETAIL_FACT_ID_CALENDAR_DIM_TO')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_DETAIL_FACT'))
alter table PAYMENT_DETAIL_FACT
drop constraint fk_PAYMENT_DETAIL_FACT_ID_CALENDAR_DIM_TO


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_DETAIL_FACT_ID_PAYMENT_DETAIL_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_DETAIL_FACT'))
alter table PAYMENT_DETAIL_FACT
drop constraint fk_PAYMENT_DETAIL_FACT_ID_PAYMENT_DETAIL_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_DETAIL_FACT_ID_SOURCE_FUNDS_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_DETAIL_FACT'))
alter table PAYMENT_DETAIL_FACT
drop constraint fk_PAYMENT_DETAIL_FACT_ID_SOURCE_FUNDS_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_FACT_ID_CALENDAR_DIM_AUTHORIZATION_BEGIN')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_FACT'))
alter table PAYMENT_FACT
drop constraint fk_PAYMENT_FACT_ID_CALENDAR_DIM_AUTHORIZATION_BEGIN


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_FACT_ID_CALENDAR_DIM_AUTHORIZATION_END')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_FACT'))
alter table PAYMENT_FACT
drop constraint fk_PAYMENT_FACT_ID_CALENDAR_DIM_AUTHORIZATION_END


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_FACT_ID_CALENDAR_DIM_PAYMENT_END')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_FACT'))
alter table PAYMENT_FACT
drop constraint fk_PAYMENT_FACT_ID_CALENDAR_DIM_PAYMENT_END


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_FACT_ID_CALENDAR_DIM_PAYMENT_START')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_FACT'))
alter table PAYMENT_FACT
drop constraint fk_PAYMENT_FACT_ID_CALENDAR_DIM_PAYMENT_START


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_FACT_ID_CALENDAR_DIM_SERVICE_BEGIN')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_FACT'))
alter table PAYMENT_FACT
drop constraint fk_PAYMENT_FACT_ID_CALENDAR_DIM_SERVICE_BEGIN


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_FACT_ID_CALENDAR_DIM_SERVICE_END')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_FACT'))
alter table PAYMENT_FACT
drop constraint fk_PAYMENT_FACT_ID_CALENDAR_DIM_SERVICE_END


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_FACT_ID_CALENDAR_DIM_WARRANT')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_FACT'))
alter table PAYMENT_FACT
drop constraint fk_PAYMENT_FACT_ID_CALENDAR_DIM_WARRANT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_FACT_ID_CASE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_FACT'))
alter table PAYMENT_FACT
drop constraint fk_PAYMENT_FACT_ID_CASE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_FACT_ID_LOCATION_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_FACT'))
alter table PAYMENT_FACT
drop constraint fk_PAYMENT_FACT_ID_LOCATION_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_FACT_ID_PAYMENT_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_FACT'))
alter table PAYMENT_FACT
drop constraint fk_PAYMENT_FACT_ID_PAYMENT_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_FACT_ID_PAYMENT_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_FACT'))
alter table PAYMENT_FACT
drop constraint fk_PAYMENT_FACT_ID_PAYMENT_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_FACT_ID_PEOPLE_DIM_CHILD')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_FACT'))
alter table PAYMENT_FACT
drop constraint fk_PAYMENT_FACT_ID_PEOPLE_DIM_CHILD


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_FACT_ID_PEOPLE_DIM_CLIENT')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_FACT'))
alter table PAYMENT_FACT
drop constraint fk_PAYMENT_FACT_ID_PEOPLE_DIM_CLIENT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_FACT_ID_PLACEMENT_CARE_AUTH_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_FACT'))
alter table PAYMENT_FACT
drop constraint fk_PAYMENT_FACT_ID_PLACEMENT_CARE_AUTH_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_FACT_ID_PLACEMENT_TYPE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_FACT'))
alter table PAYMENT_FACT
drop constraint fk_PAYMENT_FACT_ID_PLACEMENT_TYPE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_FACT_ID_PROVIDER_DIM_PAYEE')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_FACT'))
alter table PAYMENT_FACT
drop constraint fk_PAYMENT_FACT_ID_PROVIDER_DIM_PAYEE


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_FACT_ID_PROVIDER_DIM_SERVICE')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_FACT'))
alter table PAYMENT_FACT
drop constraint fk_PAYMENT_FACT_ID_PROVIDER_DIM_SERVICE


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_FACT_ID_SERVICE_TYPE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_FACT'))
alter table PAYMENT_FACT
drop constraint fk_PAYMENT_FACT_ID_SERVICE_TYPE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PAYMENT_FACT_ID_WORKER_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PAYMENT_FACT'))
alter table PAYMENT_FACT
drop constraint fk_PAYMENT_FACT_ID_WORKER_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PEOPLE_DIM_ID_WORKER_DIM_SSI_SSA_UPDATE')  AND parent_object_id=OBJECT_ID(N'dbo.PEOPLE_DIM'))
alter table PEOPLE_DIM
drop constraint fk_PEOPLE_DIM_ID_WORKER_DIM_SSI_SSA_UPDATE


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PERMANENCY_FACT_ID_CALENDAR_DIM_HEARING')  AND parent_object_id=OBJECT_ID(N'dbo.PERMANENCY_FACT'))
alter table PERMANENCY_FACT
drop constraint fk_PERMANENCY_FACT_ID_CALENDAR_DIM_HEARING


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PERMANENCY_FACT_ID_CALENDAR_DIM_ORDER_ENTERED')  AND parent_object_id=OBJECT_ID(N'dbo.PERMANENCY_FACT'))
alter table PERMANENCY_FACT
drop constraint fk_PERMANENCY_FACT_ID_CALENDAR_DIM_ORDER_ENTERED


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PERMANENCY_FACT_ID_CASE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PERMANENCY_FACT'))
alter table PERMANENCY_FACT
drop constraint fk_PERMANENCY_FACT_ID_CASE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PERMANENCY_FACT_ID_LEGAL_JURISDICTION_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PERMANENCY_FACT'))
alter table PERMANENCY_FACT
drop constraint fk_PERMANENCY_FACT_ID_LEGAL_JURISDICTION_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PERMANENCY_FACT_ID_LEGAL_STATUS_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PERMANENCY_FACT'))
alter table PERMANENCY_FACT
drop constraint fk_PERMANENCY_FACT_ID_LEGAL_STATUS_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PERMANENCY_FACT_ID_PEOPLE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PERMANENCY_FACT'))
alter table PERMANENCY_FACT
drop constraint fk_PERMANENCY_FACT_ID_PEOPLE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PERMANENCY_FACT_ID_PERMANENCY_PLAN_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PERMANENCY_FACT'))
alter table PERMANENCY_FACT
drop constraint fk_PERMANENCY_FACT_ID_PERMANENCY_PLAN_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_CARE_AUTH_FACT_ID_CALENDAR_DIM_BEGIN')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_CARE_AUTH_FACT'))
alter table PLACEMENT_CARE_AUTH_FACT
drop constraint fk_PLACEMENT_CARE_AUTH_FACT_ID_CALENDAR_DIM_BEGIN


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_CARE_AUTH_FACT_ID_CALENDAR_DIM_END')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_CARE_AUTH_FACT'))
alter table PLACEMENT_CARE_AUTH_FACT
drop constraint fk_PLACEMENT_CARE_AUTH_FACT_ID_CALENDAR_DIM_END


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_CARE_AUTH_FACT_ID_PEOPLE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_CARE_AUTH_FACT'))
alter table PLACEMENT_CARE_AUTH_FACT
drop constraint fk_PLACEMENT_CARE_AUTH_FACT_ID_PEOPLE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_CARE_AUTH_FACT_ID_PLACEMENT_CARE_AUTH_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_CARE_AUTH_FACT'))
alter table PLACEMENT_CARE_AUTH_FACT
drop constraint fk_PLACEMENT_CARE_AUTH_FACT_ID_PLACEMENT_CARE_AUTH_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_FACT_ID_REMOVAL_EPISODE_FACT')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_FACT'))
alter table PLACEMENT_FACT
drop constraint fk_PLACEMENT_FACT_ID_REMOVAL_EPISODE_FACT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_FACT_ID_CALENDAR_DIM_BEGIN')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_FACT'))
alter table PLACEMENT_FACT
drop constraint fk_PLACEMENT_FACT_ID_CALENDAR_DIM_BEGIN


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_FACT_ID_CALENDAR_DIM_END')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_FACT'))
alter table PLACEMENT_FACT
drop constraint fk_PLACEMENT_FACT_ID_CALENDAR_DIM_END


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_FACT_ID_CALENDAR_DIM_RMVL')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_FACT'))
alter table PLACEMENT_FACT
drop constraint fk_PLACEMENT_FACT_ID_CALENDAR_DIM_RMVL


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_FACT_ID_CASE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_FACT'))
alter table PLACEMENT_FACT
drop constraint fk_PLACEMENT_FACT_ID_CASE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_FACT_ID_LOCATION_DIM_PLACEMENT')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_FACT'))
alter table PLACEMENT_FACT
drop constraint fk_PLACEMENT_FACT_ID_LOCATION_DIM_PLACEMENT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_FACT_ID_LOCATION_DIM_REMOVAL')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_FACT'))
alter table PLACEMENT_FACT
drop constraint fk_PLACEMENT_FACT_ID_LOCATION_DIM_REMOVAL


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_FACT_ID_LOCATION_DIM_WORKER')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_FACT'))
alter table PLACEMENT_FACT
drop constraint fk_PLACEMENT_FACT_ID_LOCATION_DIM_WORKER


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_FACT_ID_PEOPLE_DIM_CHILD')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_FACT'))
alter table PLACEMENT_FACT
drop constraint fk_PLACEMENT_FACT_ID_PEOPLE_DIM_CHILD


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_FACT_ID_PLACEMENT_CARE_AUTH_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_FACT'))
alter table PLACEMENT_FACT
drop constraint fk_PLACEMENT_FACT_ID_PLACEMENT_CARE_AUTH_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_FACT_ID_PLACEMENT_DISCHARGE_REASON_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_FACT'))
alter table PLACEMENT_FACT
drop constraint fk_PLACEMENT_FACT_ID_PLACEMENT_DISCHARGE_REASON_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_FACT_ID_PLACEMENT_RESULT_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_FACT'))
alter table PLACEMENT_FACT
drop constraint fk_PLACEMENT_FACT_ID_PLACEMENT_RESULT_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_FACT_ID_PLACEMENT_TYPE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_FACT'))
alter table PLACEMENT_FACT
drop constraint fk_PLACEMENT_FACT_ID_PLACEMENT_TYPE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_FACT_ID_PROVIDER_DIM_CAREGIVER')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_FACT'))
alter table PLACEMENT_FACT
drop constraint fk_PLACEMENT_FACT_ID_PROVIDER_DIM_CAREGIVER


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_FACT_ID_SERVICE_TYPE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_FACT'))
alter table PLACEMENT_FACT
drop constraint fk_PLACEMENT_FACT_ID_SERVICE_TYPE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PLACEMENT_FACT_ID_LEGAL_STATUS_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PLACEMENT_FACT'))
alter table PLACEMENT_FACT
drop constraint fk_PLACEMENT_FACT_ID_LEGAL_STATUS_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PRE_ADOPTION_LEGAL_FACT_ID_CALENDAR_DIM_ADOPTION')  AND parent_object_id=OBJECT_ID(N'dbo.PRE_ADOPTION_LEGAL_FACT'))
alter table PRE_ADOPTION_LEGAL_FACT
drop constraint fk_PRE_ADOPTION_LEGAL_FACT_ID_CALENDAR_DIM_ADOPTION


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PRE_ADOPTION_LEGAL_FACT_ID_LEGAL_JURISDICTION_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PRE_ADOPTION_LEGAL_FACT'))
alter table PRE_ADOPTION_LEGAL_FACT
drop constraint fk_PRE_ADOPTION_LEGAL_FACT_ID_LEGAL_JURISDICTION_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PRE_ADOPTION_LEGAL_FACT_ID_PEOPLE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PRE_ADOPTION_LEGAL_FACT'))
alter table PRE_ADOPTION_LEGAL_FACT
drop constraint fk_PRE_ADOPTION_LEGAL_FACT_ID_PEOPLE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PRE_ADOPTION_LEGAL_FACT_ID_PLACEMENT_CARE_AUTH_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PRE_ADOPTION_LEGAL_FACT'))
alter table PRE_ADOPTION_LEGAL_FACT
drop constraint fk_PRE_ADOPTION_LEGAL_FACT_ID_PLACEMENT_CARE_AUTH_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PRE_ADOPTION_LEGAL_FACT_ID_PEOPLE_DIM_OLD')  AND parent_object_id=OBJECT_ID(N'dbo.PRE_ADOPTION_LEGAL_FACT'))
alter table PRE_ADOPTION_LEGAL_FACT
drop constraint fk_PRE_ADOPTION_LEGAL_FACT_ID_PEOPLE_DIM_OLD


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PRIMARY_ASSIGNMENT_FACT_ID_CALENDAR_DIM_BEGIN')  AND parent_object_id=OBJECT_ID(N'dbo.PRIMARY_ASSIGNMENT_FACT'))
alter table PRIMARY_ASSIGNMENT_FACT
drop constraint fk_PRIMARY_ASSIGNMENT_FACT_ID_CALENDAR_DIM_BEGIN


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PRIMARY_ASSIGNMENT_FACT_ID_CALENDAR_DIM_END')  AND parent_object_id=OBJECT_ID(N'dbo.PRIMARY_ASSIGNMENT_FACT'))
alter table PRIMARY_ASSIGNMENT_FACT
drop constraint fk_PRIMARY_ASSIGNMENT_FACT_ID_CALENDAR_DIM_END


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PRIMARY_ASSIGNMENT_FACT_ID_CASE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PRIMARY_ASSIGNMENT_FACT'))
alter table PRIMARY_ASSIGNMENT_FACT
drop constraint fk_PRIMARY_ASSIGNMENT_FACT_ID_CASE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PRIMARY_ASSIGNMENT_FACT_ID_LOCATION_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PRIMARY_ASSIGNMENT_FACT'))
alter table PRIMARY_ASSIGNMENT_FACT
drop constraint fk_PRIMARY_ASSIGNMENT_FACT_ID_LOCATION_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PRIMARY_ASSIGNMENT_FACT_ID_WORKER_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PRIMARY_ASSIGNMENT_FACT'))
alter table PRIMARY_ASSIGNMENT_FACT
drop constraint fk_PRIMARY_ASSIGNMENT_FACT_ID_WORKER_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PRIMARY_ASSIGNMENT_FACT_ID_WORKER_DIM_CURRENT')  AND parent_object_id=OBJECT_ID(N'dbo.PRIMARY_ASSIGNMENT_FACT'))
alter table PRIMARY_ASSIGNMENT_FACT
drop constraint fk_PRIMARY_ASSIGNMENT_FACT_ID_WORKER_DIM_CURRENT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PROVIDER_ACTIVITY_FACT_ID_CALENDAR_DIM_BEGIN')  AND parent_object_id=OBJECT_ID(N'dbo.PROVIDER_ACTIVITY_FACT'))
alter table PROVIDER_ACTIVITY_FACT
drop constraint fk_PROVIDER_ACTIVITY_FACT_ID_CALENDAR_DIM_BEGIN


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PROVIDER_ACTIVITY_FACT_ID_CALENDAR_DIM_COMPLETED')  AND parent_object_id=OBJECT_ID(N'dbo.PROVIDER_ACTIVITY_FACT'))
alter table PROVIDER_ACTIVITY_FACT
drop constraint fk_PROVIDER_ACTIVITY_FACT_ID_CALENDAR_DIM_COMPLETED


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PROVIDER_ACTIVITY_FACT_ID_CALENDAR_DIM_END')  AND parent_object_id=OBJECT_ID(N'dbo.PROVIDER_ACTIVITY_FACT'))
alter table PROVIDER_ACTIVITY_FACT
drop constraint fk_PROVIDER_ACTIVITY_FACT_ID_CALENDAR_DIM_END


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PROVIDER_ACTIVITY_FACT_ID_PROVIDER_ACTIVITY_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PROVIDER_ACTIVITY_FACT'))
alter table PROVIDER_ACTIVITY_FACT
drop constraint fk_PROVIDER_ACTIVITY_FACT_ID_PROVIDER_ACTIVITY_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PROVIDER_ACTIVITY_FACT_ID_PROVIDER_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PROVIDER_ACTIVITY_FACT'))
alter table PROVIDER_ACTIVITY_FACT
drop constraint fk_PROVIDER_ACTIVITY_FACT_ID_PROVIDER_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PROVIDER_DIM_ID_CALENDAR_DIM_CREATED')  AND parent_object_id=OBJECT_ID(N'dbo.PROVIDER_DIM'))
alter table PROVIDER_DIM
drop constraint fk_PROVIDER_DIM_ID_CALENDAR_DIM_CREATED


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PROVIDER_NOTES_FACT_ID_CALENDAR_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PROVIDER_NOTES_FACT'))
alter table PROVIDER_NOTES_FACT
drop constraint fk_PROVIDER_NOTES_FACT_ID_CALENDAR_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PROVIDER_NOTES_FACT_ID_PROVIDER_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PROVIDER_NOTES_FACT'))
alter table PROVIDER_NOTES_FACT
drop constraint fk_PROVIDER_NOTES_FACT_ID_PROVIDER_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PROVIDER_NOTES_FACT_ID_PROVIDER_NOTES_TYPE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PROVIDER_NOTES_FACT'))
alter table PROVIDER_NOTES_FACT
drop constraint fk_PROVIDER_NOTES_FACT_ID_PROVIDER_NOTES_TYPE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PROVIDER_PART_FACT_ID_CALENDAR_DIM_END')  AND parent_object_id=OBJECT_ID(N'dbo.PROVIDER_PART_FACT'))
alter table PROVIDER_PART_FACT
drop constraint fk_PROVIDER_PART_FACT_ID_CALENDAR_DIM_END


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PROVIDER_PART_FACT_ID_CALENDAR_DIM_START')  AND parent_object_id=OBJECT_ID(N'dbo.PROVIDER_PART_FACT'))
alter table PROVIDER_PART_FACT
drop constraint fk_PROVIDER_PART_FACT_ID_CALENDAR_DIM_START


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PROVIDER_PART_FACT_ID_PEOPLE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PROVIDER_PART_FACT'))
alter table PROVIDER_PART_FACT
drop constraint fk_PROVIDER_PART_FACT_ID_PEOPLE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PROVIDER_PART_FACT_ID_PROVIDER_DIM_CAREGIVER')  AND parent_object_id=OBJECT_ID(N'dbo.PROVIDER_PART_FACT'))
alter table PROVIDER_PART_FACT
drop constraint fk_PROVIDER_PART_FACT_ID_PROVIDER_DIM_CAREGIVER


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PROVIDER_SERVICE_LICENSE_FACT_ID_LICENSE_FACT')  AND parent_object_id=OBJECT_ID(N'dbo.PROVIDER_SERVICE_LICENSE_FACT'))
alter table PROVIDER_SERVICE_LICENSE_FACT
drop constraint fk_PROVIDER_SERVICE_LICENSE_FACT_ID_LICENSE_FACT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PROVIDER_SERVICE_LICENSE_FACT_ID_PROVIDER_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PROVIDER_SERVICE_LICENSE_FACT'))
alter table PROVIDER_SERVICE_LICENSE_FACT
drop constraint fk_PROVIDER_SERVICE_LICENSE_FACT_ID_PROVIDER_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_PROVIDER_SERVICE_LICENSE_FACT_ID_SERVICE_TYPE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.PROVIDER_SERVICE_LICENSE_FACT'))
alter table PROVIDER_SERVICE_LICENSE_FACT
drop constraint fk_PROVIDER_SERVICE_LICENSE_FACT_ID_SERVICE_TYPE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REMOVAL_EPISODE_FACT_ID_CALENDAR_DIM_AFCARS_BEGIN')  AND parent_object_id=OBJECT_ID(N'dbo.REMOVAL_EPISODE_FACT'))
alter table REMOVAL_EPISODE_FACT
drop constraint fk_REMOVAL_EPISODE_FACT_ID_CALENDAR_DIM_AFCARS_BEGIN


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REMOVAL_EPISODE_FACT_ID_CALENDAR_DIM_AFCARS_END')  AND parent_object_id=OBJECT_ID(N'dbo.REMOVAL_EPISODE_FACT'))
alter table REMOVAL_EPISODE_FACT
drop constraint fk_REMOVAL_EPISODE_FACT_ID_CALENDAR_DIM_AFCARS_END


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REMOVAL_EPISODE_FACT_ID_CALENDAR_DIM_BEGIN')  AND parent_object_id=OBJECT_ID(N'dbo.REMOVAL_EPISODE_FACT'))
alter table REMOVAL_EPISODE_FACT
drop constraint fk_REMOVAL_EPISODE_FACT_ID_CALENDAR_DIM_BEGIN


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REMOVAL_EPISODE_FACT_ID_CALENDAR_DIM_END')  AND parent_object_id=OBJECT_ID(N'dbo.REMOVAL_EPISODE_FACT'))
alter table REMOVAL_EPISODE_FACT
drop constraint fk_REMOVAL_EPISODE_FACT_ID_CALENDAR_DIM_END


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REMOVAL_EPISODE_FACT_ID_CALENDAR_DIM_FIRST_HEALTH_SAFETY_VISIT')  AND parent_object_id=OBJECT_ID(N'dbo.REMOVAL_EPISODE_FACT'))
alter table REMOVAL_EPISODE_FACT
drop constraint fk_REMOVAL_EPISODE_FACT_ID_CALENDAR_DIM_FIRST_HEALTH_SAFETY_VISIT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REMOVAL_EPISODE_FACT_ID_CASE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.REMOVAL_EPISODE_FACT'))
alter table REMOVAL_EPISODE_FACT
drop constraint fk_REMOVAL_EPISODE_FACT_ID_CASE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REMOVAL_EPISODE_FACT_ID_DISCHARGE_REASON_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.REMOVAL_EPISODE_FACT'))
alter table REMOVAL_EPISODE_FACT
drop constraint fk_REMOVAL_EPISODE_FACT_ID_DISCHARGE_REASON_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REMOVAL_EPISODE_FACT_ID_FAMILY_STRUCTURE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.REMOVAL_EPISODE_FACT'))
alter table REMOVAL_EPISODE_FACT
drop constraint fk_REMOVAL_EPISODE_FACT_ID_FAMILY_STRUCTURE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REMOVAL_EPISODE_FACT_ID_LOCATION_DIM_REMOVAL')  AND parent_object_id=OBJECT_ID(N'dbo.REMOVAL_EPISODE_FACT'))
alter table REMOVAL_EPISODE_FACT
drop constraint fk_REMOVAL_EPISODE_FACT_ID_LOCATION_DIM_REMOVAL


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REMOVAL_EPISODE_FACT_ID_LOCATION_DIM_WORKER')  AND parent_object_id=OBJECT_ID(N'dbo.REMOVAL_EPISODE_FACT'))
alter table REMOVAL_EPISODE_FACT
drop constraint fk_REMOVAL_EPISODE_FACT_ID_LOCATION_DIM_WORKER


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REMOVAL_EPISODE_FACT_ID_PEOPLE_DIM_CHILD')  AND parent_object_id=OBJECT_ID(N'dbo.REMOVAL_EPISODE_FACT'))
alter table REMOVAL_EPISODE_FACT
drop constraint fk_REMOVAL_EPISODE_FACT_ID_PEOPLE_DIM_CHILD


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REMOVAL_EPISODE_FACT_ID_PEOPLE_DIM_PARENT_PRIMARY')  AND parent_object_id=OBJECT_ID(N'dbo.REMOVAL_EPISODE_FACT'))
alter table REMOVAL_EPISODE_FACT
drop constraint fk_REMOVAL_EPISODE_FACT_ID_PEOPLE_DIM_PARENT_PRIMARY


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REMOVAL_EPISODE_FACT_ID_PEOPLE_DIM_PARENT_SECONDARY')  AND parent_object_id=OBJECT_ID(N'dbo.REMOVAL_EPISODE_FACT'))
alter table REMOVAL_EPISODE_FACT
drop constraint fk_REMOVAL_EPISODE_FACT_ID_PEOPLE_DIM_PARENT_SECONDARY


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REMOVAL_EPISODE_FACT_ID_PLACEMENT_CARE_AUTH_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.REMOVAL_EPISODE_FACT'))
alter table REMOVAL_EPISODE_FACT
drop constraint fk_REMOVAL_EPISODE_FACT_ID_PLACEMENT_CARE_AUTH_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REMOVAL_EPISODE_FACT_ID_REMOVAL_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.REMOVAL_EPISODE_FACT'))
alter table REMOVAL_EPISODE_FACT
drop constraint fk_REMOVAL_EPISODE_FACT_ID_REMOVAL_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REMOVAL_EPISODE_FACT_ID_WORKER_DIM_CURRENT')  AND parent_object_id=OBJECT_ID(N'dbo.REMOVAL_EPISODE_FACT'))
alter table REMOVAL_EPISODE_FACT
drop constraint fk_REMOVAL_EPISODE_FACT_ID_WORKER_DIM_CURRENT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REMOVAL_EPISODE_FACT_ID_WORKER_DIM_ORIGINAL')  AND parent_object_id=OBJECT_ID(N'dbo.REMOVAL_EPISODE_FACT'))
alter table REMOVAL_EPISODE_FACT
drop constraint fk_REMOVAL_EPISODE_FACT_ID_WORKER_DIM_ORIGINAL


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REMOVAL_EPISODE_FACT_ID_LEGAL_STATUS_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.REMOVAL_EPISODE_FACT'))
alter table REMOVAL_EPISODE_FACT
drop constraint fk_REMOVAL_EPISODE_FACT_ID_LEGAL_STATUS_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REMOVAL_EPISODE_FACT_ID_PLACEMENT_RESULT_DIM_LATEST')  AND parent_object_id=OBJECT_ID(N'dbo.REMOVAL_EPISODE_FACT'))
alter table REMOVAL_EPISODE_FACT
drop constraint fk_REMOVAL_EPISODE_FACT_ID_PLACEMENT_RESULT_DIM_LATEST


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REPEAT_MALTREATMENT_FACT_ID_CALENDAR_DIM_PRIOR')  AND parent_object_id=OBJECT_ID(N'dbo.REPEAT_MALTREATMENT_FACT'))
alter table REPEAT_MALTREATMENT_FACT
drop constraint fk_REPEAT_MALTREATMENT_FACT_ID_CALENDAR_DIM_PRIOR


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REPEAT_MALTREATMENT_FACT_ID_CALENDAR_DIM_REPEAT')  AND parent_object_id=OBJECT_ID(N'dbo.REPEAT_MALTREATMENT_FACT'))
alter table REPEAT_MALTREATMENT_FACT
drop constraint fk_REPEAT_MALTREATMENT_FACT_ID_CALENDAR_DIM_REPEAT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REPEAT_MALTREATMENT_FACT_ID_CASE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.REPEAT_MALTREATMENT_FACT'))
alter table REPEAT_MALTREATMENT_FACT
drop constraint fk_REPEAT_MALTREATMENT_FACT_ID_CASE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_INCIDENT')  AND parent_object_id=OBJECT_ID(N'dbo.REPEAT_MALTREATMENT_FACT'))
alter table REPEAT_MALTREATMENT_FACT
drop constraint fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_INCIDENT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_INTAKE_WORKER')  AND parent_object_id=OBJECT_ID(N'dbo.REPEAT_MALTREATMENT_FACT'))
alter table REPEAT_MALTREATMENT_FACT
drop constraint fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_INTAKE_WORKER


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_INVESTIGATION_WORKER')  AND parent_object_id=OBJECT_ID(N'dbo.REPEAT_MALTREATMENT_FACT'))
alter table REPEAT_MALTREATMENT_FACT
drop constraint fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_INVESTIGATION_WORKER


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_PRIMARY_WORKER')  AND parent_object_id=OBJECT_ID(N'dbo.REPEAT_MALTREATMENT_FACT'))
alter table REPEAT_MALTREATMENT_FACT
drop constraint fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_PRIMARY_WORKER


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REPEAT_MALTREATMENT_FACT_ID_PEOPLE_DIM_VICTIM')  AND parent_object_id=OBJECT_ID(N'dbo.REPEAT_MALTREATMENT_FACT'))
alter table REPEAT_MALTREATMENT_FACT
drop constraint fk_REPEAT_MALTREATMENT_FACT_ID_PEOPLE_DIM_VICTIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_REPEAT_MALTREATMENT_FACT_ID_PLACEMENT_TYPE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.REPEAT_MALTREATMENT_FACT'))
alter table REPEAT_MALTREATMENT_FACT
drop constraint fk_REPEAT_MALTREATMENT_FACT_ID_PLACEMENT_TYPE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_RGAP_AGREEMENT_FACT_ID_CASE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.RGAP_AGREEMENT_FACT'))
alter table RGAP_AGREEMENT_FACT
drop constraint fk_RGAP_AGREEMENT_FACT_ID_CASE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_RGAP_AGREEMENT_FACT_ID_PEOPLE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.RGAP_AGREEMENT_FACT'))
alter table RGAP_AGREEMENT_FACT
drop constraint fk_RGAP_AGREEMENT_FACT_ID_PEOPLE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_RGAP_AGREEMENT_FACT_ID_PROVIDER_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.RGAP_AGREEMENT_FACT'))
alter table RGAP_AGREEMENT_FACT
drop constraint fk_RGAP_AGREEMENT_FACT_ID_PROVIDER_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_RGAP_AGREEMENT_FACT_ID_RGAP_AGREEMENT_ATTRIBUTE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.RGAP_AGREEMENT_FACT'))
alter table RGAP_AGREEMENT_FACT
drop constraint fk_RGAP_AGREEMENT_FACT_ID_RGAP_AGREEMENT_ATTRIBUTE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_RGAP_AGREEMENT_FACT_ID_CALENDAR_DIM_RGAP_EFFECTIVE')  AND parent_object_id=OBJECT_ID(N'dbo.RGAP_AGREEMENT_FACT'))
alter table RGAP_AGREEMENT_FACT
drop constraint fk_RGAP_AGREEMENT_FACT_ID_CALENDAR_DIM_RGAP_EFFECTIVE


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_RGAP_AGREEMENT_FACT_ID_CALENDAR_DIM_RGAP_END')  AND parent_object_id=OBJECT_ID(N'dbo.RGAP_AGREEMENT_FACT'))
alter table RGAP_AGREEMENT_FACT
drop constraint fk_RGAP_AGREEMENT_FACT_ID_CALENDAR_DIM_RGAP_END


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_RGAP_AGREEMENT_FACT_ID_WORKER_DIM_RESPONSIBLE')  AND parent_object_id=OBJECT_ID(N'dbo.RGAP_AGREEMENT_FACT'))
alter table RGAP_AGREEMENT_FACT
drop constraint fk_RGAP_AGREEMENT_FACT_ID_WORKER_DIM_RESPONSIBLE


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_RGAP_ELIGIBILITY_FACT_ID_CASE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.RGAP_ELIGIBILITY_FACT'))
alter table RGAP_ELIGIBILITY_FACT
drop constraint fk_RGAP_ELIGIBILITY_FACT_ID_CASE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_RGAP_ELIGIBILITY_FACT_ID_PEOPLE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.RGAP_ELIGIBILITY_FACT'))
alter table RGAP_ELIGIBILITY_FACT
drop constraint fk_RGAP_ELIGIBILITY_FACT_ID_PEOPLE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_RGAP_ELIGIBILITY_FACT_ID_PROVIDER_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.RGAP_ELIGIBILITY_FACT'))
alter table RGAP_ELIGIBILITY_FACT
drop constraint fk_RGAP_ELIGIBILITY_FACT_ID_PROVIDER_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_RGAP_ELIGIBILITY_FACT_ID_RGAP_ELIGIBILITY_STATUS_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.RGAP_ELIGIBILITY_FACT'))
alter table RGAP_ELIGIBILITY_FACT
drop constraint fk_RGAP_ELIGIBILITY_FACT_ID_RGAP_ELIGIBILITY_STATUS_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_RGAP_ELIGIBILITY_FACT_ID_CALENDAR_DIM_DETERMINATION_EFFECTIVE')  AND parent_object_id=OBJECT_ID(N'dbo.RGAP_ELIGIBILITY_FACT'))
alter table RGAP_ELIGIBILITY_FACT
drop constraint fk_RGAP_ELIGIBILITY_FACT_ID_CALENDAR_DIM_DETERMINATION_EFFECTIVE


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_RGAP_ELIGIBILITY_FACT_ID_CALENDAR_DIM_DETERMINATION_END')  AND parent_object_id=OBJECT_ID(N'dbo.RGAP_ELIGIBILITY_FACT'))
alter table RGAP_ELIGIBILITY_FACT
drop constraint fk_RGAP_ELIGIBILITY_FACT_ID_CALENDAR_DIM_DETERMINATION_END


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_RGAP_ELIGIBILITY_FACT_ID_CALENDAR_DIM_DETERMINATION_COMPLETED')  AND parent_object_id=OBJECT_ID(N'dbo.RGAP_ELIGIBILITY_FACT'))
alter table RGAP_ELIGIBILITY_FACT
drop constraint fk_RGAP_ELIGIBILITY_FACT_ID_CALENDAR_DIM_DETERMINATION_COMPLETED


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_RGAP_ELIGIBILITY_FACT_ID_WORKER_DIM_DETERMINATION_COMPLETED')  AND parent_object_id=OBJECT_ID(N'dbo.RGAP_ELIGIBILITY_FACT'))
alter table RGAP_ELIGIBILITY_FACT
drop constraint fk_RGAP_ELIGIBILITY_FACT_ID_WORKER_DIM_DETERMINATION_COMPLETED


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SAFETY_ASSESSMENT_FACT_ID_INTAKE_FACT')  AND parent_object_id=OBJECT_ID(N'dbo.SAFETY_ASSESSMENT_FACT'))
alter table SAFETY_ASSESSMENT_FACT
drop constraint fk_SAFETY_ASSESSMENT_FACT_ID_INTAKE_FACT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SAFETY_ASSESSMENT_FACT_ID_CALENDAR_DIM_APPROVAL')  AND parent_object_id=OBJECT_ID(N'dbo.SAFETY_ASSESSMENT_FACT'))
alter table SAFETY_ASSESSMENT_FACT
drop constraint fk_SAFETY_ASSESSMENT_FACT_ID_CALENDAR_DIM_APPROVAL


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SAFETY_ASSESSMENT_FACT_ID_CALENDAR_DIM_INVESTIGATION_BEGIN')  AND parent_object_id=OBJECT_ID(N'dbo.SAFETY_ASSESSMENT_FACT'))
alter table SAFETY_ASSESSMENT_FACT
drop constraint fk_SAFETY_ASSESSMENT_FACT_ID_CALENDAR_DIM_INVESTIGATION_BEGIN


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SAFETY_ASSESSMENT_FACT_ID_CALENDAR_DIM_INVESTIGATION_END')  AND parent_object_id=OBJECT_ID(N'dbo.SAFETY_ASSESSMENT_FACT'))
alter table SAFETY_ASSESSMENT_FACT
drop constraint fk_SAFETY_ASSESSMENT_FACT_ID_CALENDAR_DIM_INVESTIGATION_END


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SAFETY_ASSESSMENT_FACT_ID_CASE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.SAFETY_ASSESSMENT_FACT'))
alter table SAFETY_ASSESSMENT_FACT
drop constraint fk_SAFETY_ASSESSMENT_FACT_ID_CASE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SAFETY_ASSESSMENT_FACT_ID_LOCATION_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.SAFETY_ASSESSMENT_FACT'))
alter table SAFETY_ASSESSMENT_FACT
drop constraint fk_SAFETY_ASSESSMENT_FACT_ID_LOCATION_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SAFETY_ASSESSMENT_FACT_ID_PEOPLE_DIM_CHILD')  AND parent_object_id=OBJECT_ID(N'dbo.SAFETY_ASSESSMENT_FACT'))
alter table SAFETY_ASSESSMENT_FACT
drop constraint fk_SAFETY_ASSESSMENT_FACT_ID_PEOPLE_DIM_CHILD


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SAFETY_ASSESSMENT_FACT_ID_WORKER_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.SAFETY_ASSESSMENT_FACT'))
alter table SAFETY_ASSESSMENT_FACT
drop constraint fk_SAFETY_ASSESSMENT_FACT_ID_WORKER_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SERVICE_FACT_ID_REMOVAL_EPISODE_FACT')  AND parent_object_id=OBJECT_ID(N'dbo.SERVICE_FACT'))
alter table SERVICE_FACT
drop constraint fk_SERVICE_FACT_ID_REMOVAL_EPISODE_FACT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SERVICE_FACT_ID_CALENDAR_DIM_END')  AND parent_object_id=OBJECT_ID(N'dbo.SERVICE_FACT'))
alter table SERVICE_FACT
drop constraint fk_SERVICE_FACT_ID_CALENDAR_DIM_END


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SERVICE_FACT_ID_CALENDAR_DIM_START')  AND parent_object_id=OBJECT_ID(N'dbo.SERVICE_FACT'))
alter table SERVICE_FACT
drop constraint fk_SERVICE_FACT_ID_CALENDAR_DIM_START


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SERVICE_FACT_ID_CASE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.SERVICE_FACT'))
alter table SERVICE_FACT
drop constraint fk_SERVICE_FACT_ID_CASE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SERVICE_FACT_ID_LOCATION_DIM_TIME_OF_APPROVAL')  AND parent_object_id=OBJECT_ID(N'dbo.SERVICE_FACT'))
alter table SERVICE_FACT
drop constraint fk_SERVICE_FACT_ID_LOCATION_DIM_TIME_OF_APPROVAL


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SERVICE_FACT_ID_PEOPLE_DIM_CHILD')  AND parent_object_id=OBJECT_ID(N'dbo.SERVICE_FACT'))
alter table SERVICE_FACT
drop constraint fk_SERVICE_FACT_ID_PEOPLE_DIM_CHILD


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SERVICE_FACT_ID_PEOPLE_DIM_SERVICE_RECIPIENT')  AND parent_object_id=OBJECT_ID(N'dbo.SERVICE_FACT'))
alter table SERVICE_FACT
drop constraint fk_SERVICE_FACT_ID_PEOPLE_DIM_SERVICE_RECIPIENT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SERVICE_FACT_ID_PLACEMENT_CARE_AUTH_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.SERVICE_FACT'))
alter table SERVICE_FACT
drop constraint fk_SERVICE_FACT_ID_PLACEMENT_CARE_AUTH_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SERVICE_FACT_ID_PLACEMENT_RESULT_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.SERVICE_FACT'))
alter table SERVICE_FACT
drop constraint fk_SERVICE_FACT_ID_PLACEMENT_RESULT_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SERVICE_FACT_ID_PLACEMENT_TYPE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.SERVICE_FACT'))
alter table SERVICE_FACT
drop constraint fk_SERVICE_FACT_ID_PLACEMENT_TYPE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SERVICE_FACT_ID_PROVIDER_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.SERVICE_FACT'))
alter table SERVICE_FACT
drop constraint fk_SERVICE_FACT_ID_PROVIDER_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SERVICE_FACT_ID_SERVICE_TYPE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.SERVICE_FACT'))
alter table SERVICE_FACT
drop constraint fk_SERVICE_FACT_ID_SERVICE_TYPE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SIBLING_RELATIONSHIP_FACT_ID_CALENDAR_DIM_BEGIN')  AND parent_object_id=OBJECT_ID(N'dbo.SIBLING_RELATIONSHIP_FACT'))
alter table SIBLING_RELATIONSHIP_FACT
drop constraint fk_SIBLING_RELATIONSHIP_FACT_ID_CALENDAR_DIM_BEGIN


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SIBLING_RELATIONSHIP_FACT_ID_CALENDAR_DIM_END')  AND parent_object_id=OBJECT_ID(N'dbo.SIBLING_RELATIONSHIP_FACT'))
alter table SIBLING_RELATIONSHIP_FACT
drop constraint fk_SIBLING_RELATIONSHIP_FACT_ID_CALENDAR_DIM_END


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SIBLING_RELATIONSHIP_FACT_ID_CASE_DIM_CHILD')  AND parent_object_id=OBJECT_ID(N'dbo.SIBLING_RELATIONSHIP_FACT'))
alter table SIBLING_RELATIONSHIP_FACT
drop constraint fk_SIBLING_RELATIONSHIP_FACT_ID_CASE_DIM_CHILD


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SIBLING_RELATIONSHIP_FACT_ID_PEOPLE_DIM_CHILD')  AND parent_object_id=OBJECT_ID(N'dbo.SIBLING_RELATIONSHIP_FACT'))
alter table SIBLING_RELATIONSHIP_FACT
drop constraint fk_SIBLING_RELATIONSHIP_FACT_ID_PEOPLE_DIM_CHILD


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SIBLING_RELATIONSHIP_FACT_ID_PEOPLE_DIM_SIBLING')  AND parent_object_id=OBJECT_ID(N'dbo.SIBLING_RELATIONSHIP_FACT'))
alter table SIBLING_RELATIONSHIP_FACT
drop constraint fk_SIBLING_RELATIONSHIP_FACT_ID_PEOPLE_DIM_SIBLING


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SUBSTANCE_ABUSE_WIZARD_FACT_ID_INVESTIGATION_ASSESSMENT_FACT')  AND parent_object_id=OBJECT_ID(N'dbo.SUBSTANCE_ABUSE_WIZARD_FACT'))
alter table SUBSTANCE_ABUSE_WIZARD_FACT
drop constraint fk_SUBSTANCE_ABUSE_WIZARD_FACT_ID_INVESTIGATION_ASSESSMENT_FACT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_SUBSTANCE_ABUSE_WIZARD_FACT_ID_PEOPLE_DIM_SUBJECT')  AND parent_object_id=OBJECT_ID(N'dbo.SUBSTANCE_ABUSE_WIZARD_FACT'))
alter table SUBSTANCE_ABUSE_WIZARD_FACT
drop constraint fk_SUBSTANCE_ABUSE_WIZARD_FACT_ID_PEOPLE_DIM_SUBJECT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_TANF_FACT_ID_CALENDAR_DIM_BEGIN')  AND parent_object_id=OBJECT_ID(N'dbo.TANF_FACT'))
alter table TANF_FACT
drop constraint fk_TANF_FACT_ID_CALENDAR_DIM_BEGIN


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_TANF_FACT_ID_CALENDAR_DIM_END')  AND parent_object_id=OBJECT_ID(N'dbo.TANF_FACT'))
alter table TANF_FACT
drop constraint fk_TANF_FACT_ID_CALENDAR_DIM_END


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_TANF_FACT_ID_CASE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.TANF_FACT'))
alter table TANF_FACT
drop constraint fk_TANF_FACT_ID_CASE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_TANF_FACT_ID_PEOPLE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.TANF_FACT'))
alter table TANF_FACT
drop constraint fk_TANF_FACT_ID_PEOPLE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_TANF_FACT_ID_TANF_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.TANF_FACT'))
alter table TANF_FACT
drop constraint fk_TANF_FACT_ID_TANF_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_TANF_FACT_ID_WORKER_DIM_COMPLETED')  AND parent_object_id=OBJECT_ID(N'dbo.TANF_FACT'))
alter table TANF_FACT
drop constraint fk_TANF_FACT_ID_WORKER_DIM_COMPLETED


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_TANF_FACT_ID_WORKER_DIM_DETERMINATION')  AND parent_object_id=OBJECT_ID(N'dbo.TANF_FACT'))
alter table TANF_FACT
drop constraint fk_TANF_FACT_ID_WORKER_DIM_DETERMINATION


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_TRAINING_FACT_ID_CALENDAR_DIM_COMPLETION')  AND parent_object_id=OBJECT_ID(N'dbo.TRAINING_FACT'))
alter table TRAINING_FACT
drop constraint fk_TRAINING_FACT_ID_CALENDAR_DIM_COMPLETION


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_TRAINING_FACT_ID_CALENDAR_DIM_EXPIRATION')  AND parent_object_id=OBJECT_ID(N'dbo.TRAINING_FACT'))
alter table TRAINING_FACT
drop constraint fk_TRAINING_FACT_ID_CALENDAR_DIM_EXPIRATION


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_TRAINING_FACT_ID_PEOPLE_DIM_TRAINING_PARTICIPANT')  AND parent_object_id=OBJECT_ID(N'dbo.TRAINING_FACT'))
alter table TRAINING_FACT
drop constraint fk_TRAINING_FACT_ID_PEOPLE_DIM_TRAINING_PARTICIPANT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_TRAINING_FACT_ID_TRAINING_TYPE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.TRAINING_FACT'))
alter table TRAINING_FACT
drop constraint fk_TRAINING_FACT_ID_TRAINING_TYPE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_TRIBE_FACT_ID_CALENDAR_DIM_ENTERED')  AND parent_object_id=OBJECT_ID(N'dbo.TRIBE_FACT'))
alter table TRIBE_FACT
drop constraint fk_TRIBE_FACT_ID_CALENDAR_DIM_ENTERED


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_TRIBE_FACT_ID_PEOPLE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.TRIBE_FACT'))
alter table TRIBE_FACT
drop constraint fk_TRIBE_FACT_ID_PEOPLE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_TRIBE_FACT_ID_TRIBE_ATTRIBUTE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.TRIBE_FACT'))
alter table TRIBE_FACT
drop constraint fk_TRIBE_FACT_ID_TRIBE_ATTRIBUTE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_TRIBE_FACT_ID_TRIBE_DIM')  AND parent_object_id=OBJECT_ID(N'dbo.TRIBE_FACT'))
alter table TRIBE_FACT
drop constraint fk_TRIBE_FACT_ID_TRIBE_DIM


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_WORKER_DIM_ID_LOCATION_DIM_WORKER')  AND parent_object_id=OBJECT_ID(N'dbo.WORKER_DIM'))
alter table WORKER_DIM
drop constraint fk_WORKER_DIM_ID_LOCATION_DIM_WORKER


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_WORKER_DIM_ID_WORKER_DIM_SUPERVISOR')  AND parent_object_id=OBJECT_ID(N'dbo.WORKER_DIM'))
alter table WORKER_DIM
drop constraint fk_WORKER_DIM_ID_WORKER_DIM_SUPERVISOR

IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_VICTIM_ADDED')  
AND parent_object_id=OBJECT_ID(N'dbo.INTAKE_VICTIM_FACT'))
alter table intake_victim_fact
drop constraint  fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_VICTIM_ADDED


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_VICTIM_ADDED')  
AND parent_object_id=OBJECT_ID(N'dbo.INTAKE_VICTIM_FACT'))
alter table intake_victim_fact
drop constraint  fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_VICTIM_ADDED

IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_INTAKE_VICTIM_FACT_ID_INTAKE_FACT')  
AND parent_object_id=OBJECT_ID(N'dbo.INTAKE_VICTIM_FACT'))
alter table intake_victim_fact
drop constraint  fk_INTAKE_VICTIM_FACT_ID_INTAKE_FACT


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.FK_INTAKE_VICTIM_FACT_INTAKE_FACT')  
AND parent_object_id=OBJECT_ID(N'dbo.INTAKE_VICTIM_FACT'))
alter table intake_victim_fact
drop constraint  FK_INTAKE_VICTIM_FACT_INTAKE_FACT

IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_WORKER_DIM_HISTORY_ID_LOCATION_DIM_WORKER')  
AND parent_object_id=OBJECT_ID(N'dbo.WORKER_DIM_HISTORY'))
ALTER TABLE [dbo].[WORKER_DIM_HISTORY] DROP CONSTRAINT [fk_WORKER_DIM_HISTORY_ID_LOCATION_DIM_WORKER]


IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_WORKER_DIM_HISTORY_ID_WORKER_DIM')  
AND parent_object_id=OBJECT_ID(N'dbo.WORKER_DIM_HISTORY'))
ALTER TABLE [dbo].[WORKER_DIM_HISTORY] DROP CONSTRAINT [fk_WORKER_DIM_HISTORY_ID_WORKER_DIM]

IF EXISTS (SELECT *   FROM sys.foreign_keys    WHERE object_id = OBJECT_ID(N'dbo.fk_WORKER_DIM_HISTORY_ID_WORKER_DIM_HISTORY_SUPERVISOR')  
AND parent_object_id=OBJECT_ID(N'dbo.WORKER_DIM_HISTORY'))
ALTER TABLE [dbo].[WORKER_DIM_HISTORY] DROP CONSTRAINT [fk_WORKER_DIM_HISTORY_ID_WORKER_DIM_HISTORY_SUPERVISOR]
