CREATE TABLE [camis].[JM_CPSAcceptRefs] (
    [STUDY_ID]            FLOAT (53)     NULL,
    [DCFREF_ID]           FLOAT (53)     NULL,
    [PRSN_DCFS_ROLE_CODE] NVARCHAR (255) NULL,
    [recdate]             DATETIME       NULL,
    [recmnthC]            NVARCHAR (255) NULL,
    [recmnthF]            NVARCHAR (255) NULL,
    [weekday]             NVARCHAR (255) NULL,
    [region]              FLOAT (53)     NULL,
    [county]              NVARCHAR (255) NULL,
    [zipcombine]          FLOAT (53)     NULL,
    [wrkoff]              FLOAT (53)     NULL,
    [unit]                FLOAT (53)     NULL,
    [referer_type]        NVARCHAR (255) NULL,
    [risktag]             NVARCHAR (255) NULL,
    [invstand]            NVARCHAR (255) NULL,
    [intakdec]            NVARCHAR (255) NULL,
    [resptime]            NVARCHAR (255) NULL,
    [abusetype]           NVARCHAR (255) NULL,
    [invstfnd]            NVARCHAR (255) NULL,
    [viccount]            FLOAT (53)     NULL,
    [licflag]             NVARCHAR (255) NULL,
    [CY]                  FLOAT (53)     NULL,
    [FY]                  FLOAT (53)     NULL,
    [ncomdate_old]        DATETIME       NULL,
    [IRA_compdate]        DATETIME       NULL,
    [dispcode]            NVARCHAR (255) NULL,
    [dispdet]             NVARCHAR (255) NULL,
    [overallr]            FLOAT (53)     NULL,
    [sa_appr_date]        DATETIME       NULL,
    [sacompdt]            DATETIME       NULL,
    [unable_locate]       NVARCHAR (255) NULL,
    [SUBREL#1]            NVARCHAR (255) NULL,
    [SUBREL#2]            NVARCHAR (255) NULL,
    [SUBREL#3]            NVARCHAR (255) NULL,
    [SUBREL#4]            NVARCHAR (255) NULL,
    [SUBREL#5]            NVARCHAR (255) NULL,
    [SUBREL#6]            NVARCHAR (255) NULL,
    [SUBREL#7]            NVARCHAR (255) NULL,
    [SUBREL#8]            NVARCHAR (255) NULL,
    [SUBREL#9]            NVARCHAR (255) NULL
);

