CREATE TABLE [camis].[JM_ira_sdm_camis] (
    [DCFREF_ID]                 INT           NULL,
    [ASSESS_ID]                 INT           NULL,
    [ASSESS_DATE]               DATETIME      NULL,
    [REC_CREAT_DATE]            DATETIME      NULL,
    [ASSESS_BASELINE_RSK_RATE]  NVARCHAR (1)  NULL,
    [ASSESS_OVRALL_RSK_RATE]    NVARCHAR (1)  NULL,
    [ASSESS_CMPLT_DATE]         DATETIME      NULL,
    [dispcode]                  NVARCHAR (17) NULL,
    [dispdet]                   NVARCHAR (57) NULL,
    [rate_max_20_30]            SMALLINT      NULL,
    [rate_max_20_40]            SMALLINT      NULL,
    [rate_max_40_20]            SMALLINT      NULL,
    [rate_max_40_30]            SMALLINT      NULL,
    [rate_max_40_40]            SMALLINT      NULL,
    [rate_max_40_50]            SMALLINT      NULL,
    [rate_max_40_60]            SMALLINT      NULL,
    [rate_max_40_70]            SMALLINT      NULL,
    [rate_max_40_80]            SMALLINT      NULL,
    [rate_max_40_90]            SMALLINT      NULL,
    [rate_max_40_100]           SMALLINT      NULL,
    [rate_max_60_10]            SMALLINT      NULL,
    [rate_max_60_30]            SMALLINT      NULL,
    [rate_max_60_40]            SMALLINT      NULL,
    [rate_max_60_50]            SMALLINT      NULL,
    [SDM1_A]                    SMALLINT      NULL,
    [SDM2_N]                    SMALLINT      NULL,
    [SDM3_N]                    SMALLINT      NULL,
    [SDM3_A]                    SMALLINT      NULL,
    [SDM4_N]                    SMALLINT      NULL,
    [SDM4_A]                    SMALLINT      NULL,
    [SDM5_N]                    SMALLINT      NULL,
    [SDM5_A]                    SMALLINT      NULL,
    [SDM6_N]                    SMALLINT      NULL,
    [SDM6_A]                    SMALLINT      NULL,
    [SDM7_N]                    SMALLINT      NULL,
    [SDM7_A]                    SMALLINT      NULL,
    [SDMQ2_N]                   SMALLINT      NULL,
    [SDMQ2_A]                   SMALLINT      NULL,
    [SDM8_N]                    SMALLINT      NULL,
    [SDM8_A]                    SMALLINT      NULL,
    [SDM9_N]                    SMALLINT      NULL,
    [SDM9_A]                    SMALLINT      NULL,
    [SDM10_N]                   SMALLINT      NULL,
    [SDM11_N]                   SMALLINT      NULL,
    [SDM12_A]                   SMALLINT      NULL,
    [SDM13_A]                   SMALLINT      NULL,
    [SDM14_N]                   SMALLINT      NULL,
    [SDM15_N]                   SMALLINT      NULL,
    [SDM16_N]                   SMALLINT      NULL,
    [SDM16_A]                   SMALLINT      NULL,
    [SDM17_N]                   SMALLINT      NULL,
    [SDM17_A]                   SMALLINT      NULL,
    [SDM18_N]                   SMALLINT      NULL,
    [SDM18_A]                   SMALLINT      NULL,
    [SDM19_N]                   SMALLINT      NULL,
    [SDM19_A]                   SMALLINT      NULL,
    [SDM20_N]                   SMALLINT      NULL,
    [SDM20_A]                   SMALLINT      NULL,
    [SDM21_N]                   SMALLINT      NULL,
    [SDM21_A]                   SMALLINT      NULL,
    [SDM22_N]                   SMALLINT      NULL,
    [SDM22_A]                   SMALLINT      NULL,
    [SDM18_19_N]                SMALLINT      NULL,
    [SDMQ7_N]                   SMALLINT      NULL,
    [SDMQ7_A]                   SMALLINT      NULL,
    [SDM23]                     SMALLINT      NULL,
    [SDM24]                     SMALLINT      NULL,
    [SDM25]                     SMALLINT      NULL,
    [SDM26]                     SMALLINT      NULL,
    [SDM27]                     SMALLINT      NULL,
    [SDM28_A]                   SMALLINT      NULL,
    [SDM29_A]                   SMALLINT      NULL,
    [SDM30_A]                   SMALLINT      NULL,
    [SDMQ9_A]                   SMALLINT      NULL,
    [SDM31_N]                   SMALLINT      NULL,
    [SDM32_N]                   SMALLINT      NULL,
    [SDM33_A]                   SMALLINT      NULL,
    [SDM34_A]                   SMALLINT      NULL,
    [SDM35_A]                   SMALLINT      NULL,
    [SDM36_A]                   SMALLINT      NULL,
    [SDM37_A]                   SMALLINT      NULL,
    [SDM38_A]                   SMALLINT      NULL,
    [SDM39_A]                   SMALLINT      NULL,
    [SDM40]                     SMALLINT      NULL,
    [SDM41]                     SMALLINT      NULL,
    [SDM42]                     SMALLINT      NULL,
    [SDM43]                     SMALLINT      NULL,
    [SDM44]                     SMALLINT      NULL,
    [SDM45]                     SMALLINT      NULL,
    [SDM46]                     SMALLINT      NULL,
    [SDMQ11_A]                  SMALLINT      NULL,
    [SDM47_N]                   SMALLINT      NULL,
    [SDM48_N]                   SMALLINT      NULL,
    [SDM49_N]                   SMALLINT      NULL,
    [SDM50]                     SMALLINT      NULL,
    [SDM51]                     SMALLINT      NULL,
    [SDM52]                     SMALLINT      NULL,
    [SDMQ12_N]                  SMALLINT      NULL,
    [SDM53_N]                   SMALLINT      NULL,
    [SDM54_N]                   SMALLINT      NULL,
    [SDM55_N]                   SMALLINT      NULL,
    [SDM56_N]                   SMALLINT      NULL,
    [SDM57_N]                   SMALLINT      NULL,
    [SDM58_A]                   SMALLINT      NULL,
    [SDM59_A]                   SMALLINT      NULL,
    [SDM60_A]                   SMALLINT      NULL,
    [SDM61_A]                   SMALLINT      NULL,
    [SDM62_A]                   SMALLINT      NULL,
    [SDM54_55_N]                SMALLINT      NULL,
    [SDM56_57_N]                SMALLINT      NULL,
    [SDMQ13_N]                  SMALLINT      NULL,
    [SDMQ13_A]                  SMALLINT      NULL,
    [SDM63_A]                   SMALLINT      NULL,
    [SDM64_A]                   SMALLINT      NULL,
    [SDM65]                     SMALLINT      NULL,
    [SDM66]                     SMALLINT      NULL,
    [SDM67_A]                   SMALLINT      NULL,
    [SDM68_A]                   SMALLINT      NULL,
    [SDM69_A]                   SMALLINT      NULL,
    [SDM70_N]                   SMALLINT      NULL,
    [SDM71_N]                   SMALLINT      NULL,
    [SDM72_N]                   SMALLINT      NULL,
    [SDMQ16_N]                  SMALLINT      NULL,
    [SDM73]                     SMALLINT      NULL,
    [SDM74]                     SMALLINT      NULL,
    [SDM75]                     SMALLINT      NULL,
    [SDM76]                     SMALLINT      NULL,
    [SDM77]                     SMALLINT      NULL,
    [SDM79]                     SMALLINT      NULL,
    [SDM80]                     SMALLINT      NULL,
    [SDM81]                     SMALLINT      NULL,
    [SDM82]                     SMALLINT      NULL,
    [SDM83]                     SMALLINT      NULL,
    [SDM85]                     SMALLINT      NULL,
    [SDM86]                     SMALLINT      NULL,
    [SDM87]                     SMALLINT      NULL,
    [SDM88]                     SMALLINT      NULL,
    [SDM89]                     SMALLINT      NULL,
    [SDM90]                     SMALLINT      NULL,
    [neglect_raw]               SMALLINT      NULL,
    [abuse_raw]                 SMALLINT      NULL,
    [neglect_level]             SMALLINT      NULL,
    [abuse_level]               SMALLINT      NULL,
    [scored_level]              SMALLINT      NULL,
    [scored_risk]               NVARCHAR (13) NULL,
    [SDM_SCORE_OVERRD_FLG]      NVARCHAR (1)  NULL,
    [SDM_SCORE_OVERRD_CODE]     NVARCHAR (1)  NULL,
    [OVERRIDE_RISK]             NVARCHAR (13) NULL,
    [SDM_SCORE_OVERRD_CODE_NUM] SMALLINT      NULL,
    [final_scored_level]        SMALLINT      NULL,
    [final_scored_risk]         NVARCHAR (13) NULL,
    [SDM_SCORE_OVERRD_RSN_CODE] NVARCHAR (1)  NULL,
    [SDM_SA_INDCTD_RESP_CODE]   NVARCHAR (1)  NULL,
    [SDM_SA_MULT_INDCTD_CODE]   NVARCHAR (1)  NULL,
    [SDM_SA_RSLT_CODE]          NVARCHAR (1)  NULL,
    [SDM_CHLD_PLCD_FLG]         NVARCHAR (1)  NULL,
    [SDM_PAPER_RISK_ASSESS_FLG] NVARCHAR (1)  NULL,
    [SDM_NO_SRVS_RSN_CODE]      NVARCHAR (1)  NULL,
    [SDM_SW_TYPE_CODE]          NVARCHAR (1)  NULL,
    [SDM_SRVS_BEYOND_CA_FLG]    NVARCHAR (1)  NULL
);

