CREATE TABLE [camis].[tblCAMISReferrals] (
    [CY]        FLOAT (53)    NULL,
    [FY]        FLOAT (53)    NULL,
    [refid]     FLOAT (53)    NOT NULL,
    [recdate]   DATETIME      NULL,
    [persnid]   FLOAT (53)    NOT NULL,
    [risktag]   FLOAT (53)    NULL,
    [risk3_5]   NVARCHAR (5)  NULL,
    [invstand]  NVARCHAR (3)  NULL,
    [resptime]  NVARCHAR (3)  NULL,
    [region]    FLOAT (53)    NULL,
    [cnty]      FLOAT (53)    NULL,
    [wrkoff]    FLOAT (53)    NULL,
    [unit]      FLOAT (53)    NULL,
    [zip]       NVARCHAR (9)  NULL,
    [ira_id]    FLOAT (53)    NULL,
    [comdate]   DATETIME      NULL,
    [overallr]  NVARCHAR (1)  NULL,
    [dispcode]  NVARCHAR (20) NULL,
    [dispdet]   NVARCHAR (60) NULL,
    [sa_id]     FLOAT (53)    NULL,
    [app_date]  DATETIME      NULL,
    [sacompdt]  DATETIME      NULL,
    [locate]    NVARCHAR (8)  NULL,
    [nallfnd]   FLOAT (53)    NULL,
    [nallinc]   FLOAT (53)    NULL,
    [nallunf]   FLOAT (53)    NULL,
    [FandI]     FLOAT (53)    NULL,
    [IandU]     FLOAT (53)    NULL,
    [FandU]     FLOAT (53)    NULL,
    [FIandU]    FLOAT (53)    NULL,
    [invsfind]  FLOAT (53)    NULL,
    [nallsa]    FLOAT (53)    NULL,
    [nallpa]    FLOAT (53)    NULL,
    [nallpn]    FLOAT (53)    NULL,
    [nallmn]    FLOAT (53)    NULL,
    [nallea]    FLOAT (53)    NULL,
    [nallothr]  FLOAT (53)    NULL,
    [saonly]    FLOAT (53)    NULL,
    [paonly]    FLOAT (53)    NULL,
    [pnonly]    FLOAT (53)    NULL,
    [mnonly]    FLOAT (53)    NULL,
    [eaonly]    FLOAT (53)    NULL,
    [othronly]  FLOAT (53)    NULL,
    [invsttab]  FLOAT (53)    NULL,
    [FATALREF]  NVARCHAR (1)  NULL,
    [race1c]    FLOAT (53)    NULL,
    [race2c]    FLOAT (53)    NULL,
    [race3c]    FLOAT (53)    NULL,
    [race4c]    FLOAT (53)    NULL,
    [race5c]    FLOAT (53)    NULL,
    [race6c]    FLOAT (53)    NULL,
    [DEATHFLG]  NVARCHAR (1)  NULL,
    [DEATHDT]   DATETIME      NULL,
    [dob]       DATETIME      NULL,
    [AGEY]      FLOAT (53)    NULL,
    [agec]      FLOAT (53)    NULL,
    [gender]    NVARCHAR (8)  NULL,
    [singlrace] FLOAT (53)    NULL,
    [anyafram]  NVARCHAR (3)  NULL,
    [anynatam]  NVARCHAR (3)  NULL,
    [hispanic]  NVARCHAR (3)  NULL,
    [age]       NVARCHAR (15) NULL,
    PRIMARY KEY CLUSTERED ([persnid] ASC, [refid] ASC)
);

