CREATE TABLE [camis].[tblFamLinkOutJan2011] (
    [ID_REMOVAL_EPISODE_FACT]               FLOAT (53)     NULL,
    [ID_EPSD]                               FLOAT (53)     NULL,
    [ID_CASE_DIM]                           FLOAT (53)     NULL,
    [ID_LOCATION_DIM]                       FLOAT (53)     NULL,
    [ID_LOCATION_DIM_REMOVAL]               FLOAT (53)     NULL,
    [ID_LOCATION_DIM_WORKER]                FLOAT (53)     NULL,
    [ID_PEOPLE_DIM_CHILD]                   FLOAT (53)     NULL,
    [ID_PLACEMENT_CARE_AUTH_DIM]            FLOAT (53)     NULL,
    [FL_AAFC]                               FLOAT (53)     NULL,
    [FL_ABANDONMENT]                        FLOAT (53)     NULL,
    [FL_ABUSE]                              FLOAT (53)     NULL,
    [FL_CARETAKER_INABILITY_COPE]           FLOAT (53)     NULL,
    [FL_CHILD_ABUSE_ALCOHOL]                FLOAT (53)     NULL,
    [FL_CHILD_ABUSES_DRUG]                  FLOAT (53)     NULL,
    [FL_CHILD_BEHAVIOR_PROBLEMS]            FLOAT (53)     NULL,
    [FL_CHILD_CLINICALLY_DIAGNOSED]         FLOAT (53)     NULL,
    [FL_INADEQUATE_HOUSNG]                  FLOAT (53)     NULL,
    [FL_NEGLECT]                            FLOAT (53)     NULL,
    [FL_PARENT_ABUSE_ALCOHOL]               FLOAT (53)     NULL,
    [FL_PARENT_DEATH]                       FLOAT (53)     NULL,
    [FL_PARENT_DRUG_ABUSE]                  FLOAT (53)     NULL,
    [FL_PARENT_INCARCERATION]               FLOAT (53)     NULL,
    [FL_PHYSICAL_ABUSE]                     FLOAT (53)     NULL,
    [FL_RELINQUISHMENT]                     FLOAT (53)     NULL,
    [FL_SEX_ABUSE]                          FLOAT (53)     NULL,
    [CHILD_AGE_REMOVAL_BEGIN]               FLOAT (53)     NULL,
    [CD_CNTY]                               NVARCHAR (4)   NULL,
    [TX_CNTY]                               NVARCHAR (200) NULL,
    [CD_OFFICE]                             FLOAT (53)     NULL,
    [TX_OFFICE]                             NVARCHAR (200) NULL,
    [CD_REGION]                             FLOAT (53)     NULL,
    [TX_REGION]                             NVARCHAR (200) NULL,
    [TX_TOWN]                               NVARCHAR (40)  NULL,
    [CD_STATE]                              NVARCHAR (2)   NULL,
    [CD_ZIP]                                NVARCHAR (9)   NULL,
    [ID_PRSN]                               FLOAT (53)     NULL,
    [DT_BIRTH]                              DATETIME       NULL,
    [CD_GNDR]                               NVARCHAR (1)   NULL,
    [TX_GNDR]                               NVARCHAR (200) NULL,
    [GENDER]                                FLOAT (53)     NULL,
    [CD_RACE]                               FLOAT (53)     NULL,
    [TX_RACE]                               NVARCHAR (200) NULL,
    [CD_RACE_TWO]                           FLOAT (53)     NULL,
    [CD_RACE_THREE]                         FLOAT (53)     NULL,
    [CD_RACE_FOUR]                          FLOAT (53)     NULL,
    [CD_RACE_FIVE]                          FLOAT (53)     NULL,
    [CD_HSPNC]                              NVARCHAR (1)   NULL,
    [TX_HSPNC]                              NVARCHAR (200) NULL,
    [HISPANIC]                              FLOAT (53)     NULL,
    [ageatplc]                              FLOAT (53)     NULL,
    [place_age_compare]                     FLOAT (53)     NULL,
    [singlrac]                              FLOAT (53)     NULL,
    [CAMIS_Placement_Episode_End_RAW]       DATETIME       NULL,
    [CAMIS_Placement_Result_RAW]            NVARCHAR (2)   NULL,
    [CAMIS_LOS_RAW]                         FLOAT (53)     NULL,
    [CAMIS_PLACEMENT_EPISODE_END_PROCESSED] DATETIME       NULL,
    [CAMIS_PLACEMENT_RESULT_PROCESSED]      NVARCHAR (2)   NULL,
    [CAMIS_LOS_PROCESSED]                   FLOAT (53)     NULL,
    [CY]                                    FLOAT (53)     NULL,
    [ENTRY_MO]                              FLOAT (53)     NULL,
    [ENTRY_QT]                              FLOAT (53)     NULL,
    [ep_begin]                              DATETIME       NULL,
    [ep_end]                                DATETIME       NULL,
    [LENGTH_OF_STAY]                        FLOAT (53)     NULL,
    [first_ep_begin]                        DATETIME       NULL,
    [firstrmvl]                             FLOAT (53)     NULL,
    [plcm_dschtype]                         FLOAT (53)     NULL,
    [new_ep_end]                            DATETIME       NULL,
    [new_end_result]                        FLOAT (53)     NULL,
    [reunified]                             FLOAT (53)     NULL,
    [new_los]                               FLOAT (53)     NULL
);

