CREATE TABLE [camis].[tblIRA_SDM_CAMIS] (
    [ID]                        INT            IDENTITY (1, 1) NOT NULL,
    [DCFREF_ID]                 INT            NULL,
    [ASSESS_ID]                 INT            NULL,
    [ASSESS_DATE]               DATETIME       NULL,
    [REC_CREAT_DATE]            DATETIME       NULL,
    [ASSESS_BASELINE_RSK_RATE]  NVARCHAR (255) NULL,
    [ASSESS_OVRALL_RSK_RATE]    NVARCHAR (255) NULL,
    [ASSESS_CMPLT_DATE]         DATETIME       NULL,
    [dispcode]                  NVARCHAR (255) NULL,
    [dispdet]                   NVARCHAR (255) NULL,
    [rate_max2030]              NVARCHAR (255) NULL,
    [rate_max2040]              NVARCHAR (255) NULL,
    [rate_max4020]              NVARCHAR (255) NULL,
    [rate_max4030]              NVARCHAR (255) NULL,
    [rate_max4040]              NVARCHAR (255) NULL,
    [rate_max4050]              NVARCHAR (255) NULL,
    [rate_max4060]              NVARCHAR (255) NULL,
    [rate_max4070]              NVARCHAR (255) NULL,
    [rate_max4080]              NVARCHAR (255) NULL,
    [rate_max4090]              NVARCHAR (255) NULL,
    [rate_max40100]             NVARCHAR (255) NULL,
    [rate_max6010]              NVARCHAR (255) NULL,
    [rate_max6030]              NVARCHAR (255) NULL,
    [rate_max6040]              NVARCHAR (255) NULL,
    [rate_max6050]              NVARCHAR (255) NULL,
    [SDM1_A]                    INT            NULL,
    [SDM2_N]                    NVARCHAR (255) NULL,
    [SDM3_N]                    NVARCHAR (255) NULL,
    [SDM3_A]                    NVARCHAR (255) NULL,
    [SDM4_N]                    NVARCHAR (255) NULL,
    [SDM4_A]                    NVARCHAR (255) NULL,
    [SDM5_N]                    NVARCHAR (255) NULL,
    [SDM5_A]                    NVARCHAR (255) NULL,
    [SDM6_N]                    NVARCHAR (255) NULL,
    [SDM6_A]                    NVARCHAR (255) NULL,
    [SDM7_N]                    NVARCHAR (255) NULL,
    [SDM7_A]                    NVARCHAR (255) NULL,
    [SDMQ2_N]                   INT            NULL,
    [SDMQ2_A]                   INT            NULL,
    [SDM8_N]                    NVARCHAR (255) NULL,
    [SDM8_A]                    NVARCHAR (255) NULL,
    [SDM9_N]                    NVARCHAR (255) NULL,
    [SDM9_A]                    NVARCHAR (255) NULL,
    [SDM10_N]                   INT            NULL,
    [SDM11_N]                   NVARCHAR (255) NULL,
    [SDM12_A]                   NVARCHAR (255) NULL,
    [SDM13_A]                   NVARCHAR (255) NULL,
    [SDM14_N]                   NVARCHAR (255) NULL,
    [SDM15_N]                   NVARCHAR (255) NULL,
    [SDM16_N]                   NVARCHAR (255) NULL,
    [SDM16_A]                   NVARCHAR (255) NULL,
    [SDM17_N]                   NVARCHAR (255) NULL,
    [SDM17_A]                   NVARCHAR (255) NULL,
    [SDM18_N]                   NVARCHAR (255) NULL,
    [SDM18_A]                   NVARCHAR (255) NULL,
    [SDM19_N]                   NVARCHAR (255) NULL,
    [SDM19_A]                   NVARCHAR (255) NULL,
    [SDM20_N]                   NVARCHAR (255) NULL,
    [SDM20_A]                   NVARCHAR (255) NULL,
    [SDM21_N]                   NVARCHAR (255) NULL,
    [SDM21_A]                   NVARCHAR (255) NULL,
    [SDM22_N]                   NVARCHAR (255) NULL,
    [SDM22_A]                   NVARCHAR (255) NULL,
    [SDM18_19_N]                NVARCHAR (255) NULL,
    [SDMQ7_N]                   INT            NULL,
    [SDMQ7_A]                   INT            NULL,
    [SDM23]                     NVARCHAR (255) NULL,
    [SDM24]                     NVARCHAR (255) NULL,
    [SDM25]                     NVARCHAR (255) NULL,
    [SDM26]                     NVARCHAR (255) NULL,
    [SDM27]                     NVARCHAR (255) NULL,
    [SDM28_A]                   NVARCHAR (255) NULL,
    [SDM29_A]                   NVARCHAR (255) NULL,
    [SDM30_A]                   NVARCHAR (255) NULL,
    [SDMQ9_A]                   INT            NULL,
    [SDM31_N]                   NVARCHAR (255) NULL,
    [SDM32_N]                   NVARCHAR (255) NULL,
    [SDM33_A]                   NVARCHAR (255) NULL,
    [SDM34_A]                   NVARCHAR (255) NULL,
    [SDM35_A]                   NVARCHAR (255) NULL,
    [SDM36_A]                   NVARCHAR (255) NULL,
    [SDM37_A]                   NVARCHAR (255) NULL,
    [SDM38_A]                   NVARCHAR (255) NULL,
    [SDM39_A]                   NVARCHAR (255) NULL,
    [SDM40]                     NVARCHAR (255) NULL,
    [SDM41]                     NVARCHAR (255) NULL,
    [SDM42]                     NVARCHAR (255) NULL,
    [SDM43]                     NVARCHAR (255) NULL,
    [SDM44]                     NVARCHAR (255) NULL,
    [SDM45]                     NVARCHAR (255) NULL,
    [SDM46]                     NVARCHAR (255) NULL,
    [SDMQ11_A]                  INT            NULL,
    [SDM47_N]                   NVARCHAR (255) NULL,
    [SDM48_N]                   NVARCHAR (255) NULL,
    [SDM49_N]                   NVARCHAR (255) NULL,
    [SDM50]                     NVARCHAR (255) NULL,
    [SDM51]                     NVARCHAR (255) NULL,
    [SDM52]                     NVARCHAR (255) NULL,
    [SDMQ12_N]                  INT            NULL,
    [SDM53_N]                   NVARCHAR (255) NULL,
    [SDM54_N]                   NVARCHAR (255) NULL,
    [SDM55_N]                   NVARCHAR (255) NULL,
    [SDM56_N]                   NVARCHAR (255) NULL,
    [SDM57_N]                   NVARCHAR (255) NULL,
    [SDM58_A]                   NVARCHAR (255) NULL,
    [SDM59_A]                   NVARCHAR (255) NULL,
    [SDM60_A]                   NVARCHAR (255) NULL,
    [SDM61_A]                   NVARCHAR (255) NULL,
    [SDM62_A]                   NVARCHAR (255) NULL,
    [SDM54_55_N]                NVARCHAR (255) NULL,
    [SDM56_57_N]                NVARCHAR (255) NULL,
    [SDMQ13_N]                  INT            NULL,
    [SDMQ13_A]                  INT            NULL,
    [SDM63_A]                   NVARCHAR (255) NULL,
    [SDM64_A]                   NVARCHAR (255) NULL,
    [SDM65]                     NVARCHAR (255) NULL,
    [SDM66]                     NVARCHAR (255) NULL,
    [SDM67_A]                   NVARCHAR (255) NULL,
    [SDM68_A]                   NVARCHAR (255) NULL,
    [SDM69_A]                   NVARCHAR (255) NULL,
    [SDM70_N]                   NVARCHAR (255) NULL,
    [SDM71_N]                   NVARCHAR (255) NULL,
    [SDM72_N]                   NVARCHAR (255) NULL,
    [SDMQ16_N]                  INT            NULL,
    [SDM73]                     NVARCHAR (255) NULL,
    [SDM74]                     NVARCHAR (255) NULL,
    [SDM75]                     NVARCHAR (255) NULL,
    [SDM76]                     NVARCHAR (255) NULL,
    [SDM77]                     NVARCHAR (255) NULL,
    [SDM79]                     NVARCHAR (255) NULL,
    [SDM80]                     NVARCHAR (255) NULL,
    [SDM81]                     NVARCHAR (255) NULL,
    [SDM82]                     NVARCHAR (255) NULL,
    [SDM83]                     NVARCHAR (255) NULL,
    [SDM85]                     NVARCHAR (255) NULL,
    [SDM86]                     NVARCHAR (255) NULL,
    [SDM87]                     NVARCHAR (255) NULL,
    [SDM88]                     NVARCHAR (255) NULL,
    [SDM89]                     NVARCHAR (255) NULL,
    [SDM90]                     NVARCHAR (255) NULL,
    [neglect_raw]               INT            NULL,
    [abuse_raw]                 INT            NULL,
    [neglect_level]             INT            NULL,
    [abuse_level]               INT            NULL,
    [scored_level]              INT            NULL,
    [scored_risk]               NVARCHAR (255) NULL,
    [SDM_SCORE_OVERRD_FLG]      NVARCHAR (255) NULL,
    [SDM_SCORE_OVERRD_CODE]     NVARCHAR (255) NULL,
    [OVERRIDE_RISK]             NVARCHAR (255) NULL,
    [SDM_SCORE_OVERRD_CODE_NUM] NVARCHAR (255) NULL,
    [final_scored_level]        INT            NULL,
    [final_scored_risk]         NVARCHAR (255) NULL,
    [SDM_SCORE_OVERRD_RSN_CODE] NVARCHAR (255) NULL,
    [SDM_SA_INDCTD_RESP_CODE]   INT            NULL,
    [SDM_SA_MULT_INDCTD_CODE]   NVARCHAR (255) NULL,
    [SDM_SA_RSLT_CODE]          NVARCHAR (255) NULL,
    [SDM_CHLD_PLCD_FLG]         NVARCHAR (255) NULL,
    [SDM_PAPER_RISK_ASSESS_FLG] NVARCHAR (255) NULL,
    [SDM_NO_SRVS_RSN_CODE]      NVARCHAR (255) NULL,
    [SDM_SW_TYPE_CODE]          NVARCHAR (255) NULL,
    [SDM_SRVS_BEYOND_CA_FLG]    NVARCHAR (255) NULL
);

