CREATE TABLE [base].[rptIntake_children] (
    [TableKey]                                INT           NULL,
    [ID_ACCESS_REPORT]                        INT           NOT NULL,
    [DT_ACCESS_RCVD]                          DATETIME      NULL,
    [YEAR_DT_ACCESS_RCVD]                     VARCHAR (200) NULL,
    [YEAR_NAME_DT_ACCESS_RCVD]                VARCHAR (200) NULL,
    [MONTH_NAME_DT_ACCESS_RCVD]               VARCHAR (200) NULL,
    [STATE_FISCAL_YEAR_NAME_DT_ACCESS_RCVD]   VARCHAR (200) NULL,
    [FEDERAL_FISCAL_YEAR_NAME_DT_ACCESS_RCVD] VARCHAR (200) NULL,
    [CPS_YESNO]                               VARCHAR (3)   NULL,
    [INTAKE_TYPE]                             VARCHAR (200) NULL,
    [CD_NON_CPS]                              NVARCHAR (10) NULL,
    [SCREEN_DCSN]                             VARCHAR (200) NULL,
    [CD_REASON]                               INT           NULL,
    [REASON]                                  VARCHAR (200) NULL,
    [RESPONSE_TIME]                           VARCHAR (20)  NULL,
    [MAJOR_CAN]                               INT           NULL,
    [PHYSICAL_ABUSE]                          INT           NULL,
    [SEXUAL_ABUSE]                            INT           NULL,
    [NEGLECT]                                 INT           NULL,
    [SEXUAL_EXPLOIT]                          INT           NULL,
    [ABANDONED]                               INT           NULL,
    [OTHER]                                   INT           NULL,
    [ID_CASE]                                 INT           NULL,
    [ID_PRVD_ORG_INTAKE]                      INT           NULL,
    [REGION]                                  VARCHAR (200) NULL,
    [INTAKE_REGION]                           VARCHAR (200) NULL,
    [CD_INTAKE_REGION]                        INT           NULL,
    [INTAKE_OFFICE]                           VARCHAR (200) NULL,
    [CD_INTAKE_OFFICE]                        INT           NULL,
    [INTAKE_UNIT]                             NVARCHAR (20) NULL,
    [CASE_REGION]                             VARCHAR (200) NULL,
    [CD_CASE_REGION]                          INT           NULL,
    [CASE_OFFICE]                             VARCHAR (200) NULL,
    [CD_CASE_OFFICE]                          INT           NULL,
    [PRIMARY_WRKR]                            INT           NULL,
    [WRKR_REGION]                             VARCHAR (200) NULL,
    [CD_WRKR_REGION]                          INT           NULL,
    [WORKER_OFFICE]                           VARCHAR (200) NULL,
    [CD_WORKER_OFFICE]                        INT           NULL,
    [WORKER_UNIT]                             NVARCHAR (20) NULL,
    [COUNTY]                                  VARCHAR (200) NULL,
    [INTAKE_ZIP]                              NVARCHAR (10) NULL,
    [IA_WRKR_ID]                              NVARCHAR (10) NULL,
    [WRKR_NAME]                               VARCHAR (200) NULL,
    [IA_REGION]                               VARCHAR (200) NULL,
    [IA_OFFICE]                               VARCHAR (200) NULL,
    [IA_UNIT]                                 NVARCHAR (20) NULL,
    [VICS_ID_CHILDREN]                        INT           NULL,
    [CD_GNDR]                                 CHAR (1)      NULL,
    [AGE]                                     NVARCHAR (10) NULL,
    [AGE_GRP]                                 VARCHAR (200) NULL,
    [SINGLE_RACE]                             VARCHAR (200) NULL,
    [TX_BRAAM_RACE]                           VARCHAR (200) NULL,
    [CD_ALLEGATION]                           NVARCHAR (10) NULL,
    [TX_ALLEGATION]                           VARCHAR (200) NULL,
    [INVST_CMPLTD]                            CHAR (1)      NULL,
    [IA_CMPLTD_DT]                            NVARCHAR (20) NULL,
    [IA_CMPLTN_DAYS]                          INT           NULL,
    [IA_SCREEN_OUT]                           VARCHAR (3)   NULL,
    [IA_EFSS_REF]                             NVARCHAR (20) NULL,
    [REFRESH_DT]                              DATETIME      NULL,
    [TX_INDIAN_RESERVATION]                   VARCHAR (200) NULL,
    [TX_MEMBER]                               VARCHAR (200) NULL,
    [TX_NATIVE]                               VARCHAR (200) NULL,
    [TX_WARD_TRIBAL_COURT]                    VARCHAR (200) NULL,
    [TX_INVEST_DISP]                          VARCHAR (200) NULL,
    [dv_threat_intake]                        VARCHAR (200) NULL,
    [TX_GNDR]                                 VARCHAR (200) NULL,
    [CD_HSPNC]                                CHAR (1)      NULL,
    [TX_HSPNC]                                VARCHAR (200) NULL,
    [FL_DEATH_SERIOUS_INJURY]                 CHAR (1)      NULL,
    [FL_NEAR_DEATH_INJURY]                    CHAR (1)      NULL,
    [Month_DT_ACCESS_RCVD]                    DATETIME      NULL,
    [Quarter_DT_ACCESS_RCVD]                  DATETIME      NULL,
    [Quarter_Name]                            VARCHAR (200) NULL,
    [TX_MULTI_RACE_ETHNICITY]                 VARCHAR (200) NULL,
    [CD_MULTI_RACE_ETHNICITY]                 INT           NULL,
    [ANY_FOUNDED]                             CHAR (3)      NULL,
    [INTAKE_WORKER]                           INT           NULL,
    [INTAKE_AA]                               INT           NULL,
    [INTAKE_SUP]                              INT           NULL
);

