use CA_ODS
go

ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_id_calendar_dim_founded] FOREIGN KEY([ID_CALENDAR_DIM_FOUNDED])
REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM])
GO

ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_id_calendar_dim_founded]
GO

ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_CALENDAR_DIM_INCIDENT] FOREIGN KEY([ID_CALENDAR_DIM_INCIDENT])
REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM])
GO

ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_CALENDAR_DIM_INCIDENT]
GO

ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_CALENDAR_DIM_REFERRED] FOREIGN KEY([ID_CALENDAR_DIM_REFERRED])
REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM])
GO

ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_CALENDAR_DIM_REFERRED]
GO

ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_CASE_DIM] FOREIGN KEY([ID_CASE_DIM])
REFERENCES [dbo].[CASE_DIM] ([ID_CASE_DIM])
GO

ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_CASE_DIM]
GO

ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_LOCATION_DIM_INCIDENT] FOREIGN KEY([ID_LOCATION_DIM_INCIDENT])
REFERENCES [dbo].[LOCATION_DIM] ([ID_LOCATION_DIM])
GO

ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_LOCATION_DIM_INCIDENT]
GO

ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_LOCATION_DIM_INTAKE_WORKER] FOREIGN KEY([ID_LOCATION_DIM_INTAKE_WORKER])
REFERENCES [dbo].[LOCATION_DIM] ([ID_LOCATION_DIM])
GO

ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_LOCATION_DIM_INTAKE_WORKER]
GO

ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_LOCATION_DIM_PRIMARY_WORKER] FOREIGN KEY([ID_LOCATION_DIM_PRIMARY_WORKER])
REFERENCES [dbo].[LOCATION_DIM] ([ID_LOCATION_DIM])
GO

ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_LOCATION_DIM_PRIMARY_WORKER]
GO

ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_PEOPLE_DIM_VICTIM] FOREIGN KEY([ID_PEOPLE_DIM_VICTIM])
REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM])
GO

ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_PEOPLE_DIM_VICTIM]
GO

ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_PLACEMENT_TYPE_DIM] FOREIGN KEY([ID_PLACEMENT_TYPE_DIM])
REFERENCES [dbo].[PLACEMENT_TYPE_DIM] ([ID_PLACEMENT_TYPE_DIM])
GO

ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_PLACEMENT_TYPE_DIM]
GO

ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_PROVIDER_DIM] FOREIGN KEY([ID_PROVIDER_DIM])
REFERENCES [dbo].[PROVIDER_DIM] ([ID_PROVIDER_DIM])
GO

ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_PROVIDER_DIM]
GO

ALTER TABLE [dbo].[ABUSE_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_WORKER_DIM_PRIMARY] FOREIGN KEY([ID_WORKER_DIM_PRIMARY])
REFERENCES [dbo].[WORKER_DIM] ([ID_WORKER_DIM])
GO

ALTER TABLE [dbo].[ABUSE_FACT] CHECK CONSTRAINT [fk_ID_WORKER_DIM_PRIMARY]
GO



ALTER TABLE [dbo].[ADOPTION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_af_ID_CASE_DIM] FOREIGN KEY([ID_CASE_DIM])
REFERENCES [dbo].[CASE_DIM] ([ID_CASE_DIM])
GO

ALTER TABLE [dbo].[ADOPTION_FACT] CHECK CONSTRAINT [fk_af_ID_CASE_DIM]
GO

ALTER TABLE [dbo].[ADOPTION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_af_ID_PEOPLE_DIM_CHILD] FOREIGN KEY([ID_PEOPLE_DIM_CHILD])
REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM])
GO

ALTER TABLE [dbo].[ADOPTION_FACT] CHECK CONSTRAINT [fk_af_ID_PEOPLE_DIM_CHILD]
GO

ALTER TABLE [dbo].[ADOPTION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_ADOPTION_STATUS_DIM] FOREIGN KEY([ID_ADOPTION_STATUS_DIM])
REFERENCES [dbo].[ADOPTION_STATUS_DIM] ([ID_ADOPTION_STATUS_DIM])
GO

ALTER TABLE [dbo].[ADOPTION_FACT] CHECK CONSTRAINT [fk_ID_ADOPTION_STATUS_DIM]
GO

ALTER TABLE [dbo].[ADOPTION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_CALENDAR_DIM_COMPLETE] FOREIGN KEY([ID_CALENDAR_DIM_COMPLETE])
REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM])
GO

ALTER TABLE [dbo].[ADOPTION_FACT] CHECK CONSTRAINT [fk_ID_CALENDAR_DIM_COMPLETE]
GO

ALTER TABLE [dbo].[ADOPTION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_CALENDAR_DIM_EFFECTIVE_ELIGIBLE] FOREIGN KEY([ID_CALENDAR_DIM_EFFECTIVE_ELIGIBLE])
REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM])
GO

ALTER TABLE [dbo].[ADOPTION_FACT] CHECK CONSTRAINT [fk_ID_CALENDAR_DIM_EFFECTIVE_ELIGIBLE]
GO

ALTER TABLE [dbo].[ADOPTION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ID_CALENDAR_DIM_TERMINATED] FOREIGN KEY([ID_CALENDAR_DIM_TERMINATED])
REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM])
GO

ALTER TABLE [dbo].[ADOPTION_FACT] CHECK CONSTRAINT [fk_ID_CALENDAR_DIM_TERMINATED]
GO

ALTER TABLE [dbo].[ALLEGATION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ALLEGATION_FACT_ID_ABUSE_TYPE_DIM] FOREIGN KEY([ID_ABUSE_TYPE_DIM])
REFERENCES [dbo].[ABUSE_TYPE_DIM] ([ID_ABUSE_TYPE_DIM])
GO

ALTER TABLE [dbo].[ALLEGATION_FACT] CHECK CONSTRAINT [fk_ALLEGATION_FACT_ID_ABUSE_TYPE_DIM]
GO

ALTER TABLE [dbo].[ALLEGATION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ALLEGATION_FACT_ID_CASE_DIM] FOREIGN KEY([ID_CASE_DIM])
REFERENCES [dbo].[CASE_DIM] ([ID_CASE_DIM])
GO

ALTER TABLE [dbo].[ALLEGATION_FACT] CHECK CONSTRAINT [fk_ALLEGATION_FACT_ID_CASE_DIM]
GO

ALTER TABLE [dbo].[ALLEGATION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ALLEGATION_FACT_ID_FINDINGS_DIM] FOREIGN KEY([ID_FINDINGS_DIM])
REFERENCES [dbo].[FINDINGS_DIM] ([ID_FINDINGS_DIM])
GO

ALTER TABLE [dbo].[ALLEGATION_FACT] CHECK CONSTRAINT [fk_ALLEGATION_FACT_ID_FINDINGS_DIM]
GO

ALTER TABLE [dbo].[ALLEGATION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ALLEGATION_FACT_ID_INTAKE_FACT] FOREIGN KEY([ID_INTAKE_FACT])
REFERENCES [dbo].[INTAKE_FACT] ([ID_INTAKE_FACT])
GO

ALTER TABLE [dbo].[ALLEGATION_FACT] CHECK CONSTRAINT [fk_ALLEGATION_FACT_ID_INTAKE_FACT]
GO

ALTER TABLE [dbo].[ALLEGATION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ALLEGATION_FACT_ID_INVESTIGATION_ASSESSMENT_FACT] FOREIGN KEY([ID_INVESTIGATION_ASSESSMENT_FACT])
REFERENCES [dbo].[INVESTIGATION_ASSESSMENT_FACT] ([ID_INVESTIGATION_ASSESSMENT_FACT])
GO

ALTER TABLE [dbo].[ALLEGATION_FACT] CHECK CONSTRAINT [fk_ALLEGATION_FACT_ID_INVESTIGATION_ASSESSMENT_FACT]
GO

ALTER TABLE [dbo].[ALLEGATION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ALLEGATION_FACT_ID_PEOPLE_DIM_SUBJECT] FOREIGN KEY([ID_PEOPLE_DIM_SUBJECT])
REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM])
GO

ALTER TABLE [dbo].[ALLEGATION_FACT] CHECK CONSTRAINT [fk_ALLEGATION_FACT_ID_PEOPLE_DIM_SUBJECT]
GO

ALTER TABLE [dbo].[ALLEGATION_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ALLEGATION_FACT_ID_RELATIONSHIP_DIM] FOREIGN KEY([ID_RELATIONSHIP_DIM])
REFERENCES [dbo].[RELATIONSHIP_DIM] ([ID_RELATIONSHIP_DIM])
GO

ALTER TABLE [dbo].[ALLEGATION_FACT] CHECK CONSTRAINT [fk_ALLEGATION_FACT_ID_RELATIONSHIP_DIM]
GO

ALTER TABLE [dbo].[ASSIGNMENT_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ASSIGNMENT_FACT_ID_ASSIGNMENT_ATTRIBUTE_DIM] FOREIGN KEY([ID_ASSIGNMENT_ATTRIBUTE_DIM])
REFERENCES [dbo].[ASSIGNMENT_ATTRIBUTE_DIM] ([ID_ASSIGNMENT_ATTRIBUTE_DIM])
GO

ALTER TABLE [dbo].[ASSIGNMENT_FACT] CHECK CONSTRAINT [fk_ASSIGNMENT_FACT_ID_ASSIGNMENT_ATTRIBUTE_DIM]
GO

ALTER TABLE [dbo].[ASSIGNMENT_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_BEGIN] FOREIGN KEY([ID_CALENDAR_DIM_BEGIN])
REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM])
GO

ALTER TABLE [dbo].[ASSIGNMENT_FACT] CHECK CONSTRAINT [fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_BEGIN]
GO

ALTER TABLE [dbo].[ASSIGNMENT_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_END] FOREIGN KEY([ID_CALENDAR_DIM_END])
REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM])
GO

ALTER TABLE [dbo].[ASSIGNMENT_FACT] CHECK CONSTRAINT [fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_END]
GO

ALTER TABLE [dbo].[ASSIGNMENT_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ASSIGNMENT_FACT_ID_CASE_DIM] FOREIGN KEY([ID_CASE_DIM])
REFERENCES [dbo].[CASE_DIM] ([ID_CASE_DIM])
GO

ALTER TABLE [dbo].[ASSIGNMENT_FACT] CHECK CONSTRAINT [fk_ASSIGNMENT_FACT_ID_CASE_DIM]
GO

ALTER TABLE [dbo].[ASSIGNMENT_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ASSIGNMENT_FACT_ID_LOCATION_DIM] FOREIGN KEY([ID_LOCATION_DIM])
REFERENCES [dbo].[LOCATION_DIM] ([ID_LOCATION_DIM])
GO

ALTER TABLE [dbo].[ASSIGNMENT_FACT] CHECK CONSTRAINT [fk_ASSIGNMENT_FACT_ID_LOCATION_DIM]
GO

ALTER TABLE [dbo].[ASSIGNMENT_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ASSIGNMENT_FACT_ID_PEOPLE_DIM] FOREIGN KEY([ID_PEOPLE_DIM])
REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM])
GO

ALTER TABLE [dbo].[ASSIGNMENT_FACT] CHECK CONSTRAINT [fk_ASSIGNMENT_FACT_ID_PEOPLE_DIM]
GO

ALTER TABLE [dbo].[ASSIGNMENT_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ASSIGNMENT_FACT_ID_PROVIDER_DIM] FOREIGN KEY([ID_PROVIDER_DIM])
REFERENCES [dbo].[PROVIDER_DIM] ([ID_PROVIDER_DIM])
GO

ALTER TABLE [dbo].[ASSIGNMENT_FACT] CHECK CONSTRAINT [fk_ASSIGNMENT_FACT_ID_PROVIDER_DIM]
GO

ALTER TABLE [dbo].[ASSIGNMENT_FACT]  WITH CHECK ADD  CONSTRAINT [fk_ASSIGNMENT_FACT_ID_WORKER_DIM] FOREIGN KEY([ID_WORKER_DIM])
REFERENCES [dbo].[WORKER_DIM] ([ID_WORKER_DIM])
GO

ALTER TABLE [dbo].[ASSIGNMENT_FACT] CHECK CONSTRAINT [fk_ASSIGNMENT_FACT_ID_WORKER_DIM]
GO



alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_AUTHORIZATION_DIM FOREIGN KEY ( ID_AUTHORIZATION_DIM )
references dbo.AUTHORIZATION_DIM(ID_AUTHORIZATION_DIM)
go
alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_AUTH_BEGIN FOREIGN KEY ( ID_CALENDAR_DIM_AUTH_BEGIN )
references dbo.calendar_dim(ID_CALENDAR_DIM)

go
alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_AUTH_END FOREIGN KEY ( ID_CALENDAR_DIM_AUTH_END )
references dbo.calendar_dim(ID_CALENDAR_DIM)
go

alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_AUTH_END FOREIGN KEY ( ID_CALENDAR_DIM_AUTH_END )
references dbo.calendar_dim(ID_CALENDAR_DIM)
go
alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_SERVICE_BEGIN FOREIGN KEY ( ID_CALENDAR_DIM_SERVICE_BEGIN )
references dbo.calendar_dim(ID_CALENDAR_DIM)
go
alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_SERVICE_END FOREIGN KEY ( ID_CALENDAR_DIM_SERVICE_END )
references dbo.calendar_dim(ID_CALENDAR_DIM)
go
alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_CASE_DIM FOREIGN KEY ( ID_CASE_DIM )
references dbo.case_dim(ID_CASE_DIM)
go
alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_CHART_OF_ACCOUNTS_DIM FOREIGN KEY ( ID_CHART_OF_ACCOUNTS_DIM )
references dbo.CHART_OF_ACCOUNTS_DIM(ID_CHART_OF_ACCOUNTS_DIM)
go
alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_LOCATION_DIM FOREIGN KEY ( ID_LOCATION_DIM )
references dbo.LOCATION_DIM(ID_LOCATION_DIM)
go
alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY ( ID_PEOPLE_DIM_CHILD )
references dbo.people_dim(id_people_dim)
go

alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_PEOPLE_DIM_CLIENT FOREIGN KEY ( ID_PEOPLE_DIM_CLIENT )
references dbo.people_dim(id_people_dim)
go
alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_PLACEMENT_CARE_AUTH_DIM FOREIGN KEY ( ID_PLACEMENT_CARE_AUTH_DIM )
references dbo.PLACEMENT_CARE_AUTH_DIM(ID_PLACEMENT_CARE_AUTH_DIM)
go

alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_IID_PLACEMENT_TYPE_DIM FOREIGN KEY ( ID_PLACEMENT_TYPE_DIM )
references dbo.PLACEMENT_TYPE_DIM(ID_PLACEMENT_TYPE_DIM)
go
alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_PROVIDER_DIM_PAYEE FOREIGN KEY ( ID_PROVIDER_DIM_PAYEE )
references dbo.PROVIDER_DIM(ID_PROVIDER_DIM)
go
alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_PROVIDER_DIM_SERVICE FOREIGN KEY ( ID_PROVIDER_DIM_SERVICE )
references dbo.PROVIDER_DIM(ID_PROVIDER_DIM)
go
alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_SERVICE_TYPE_DIME FOREIGN KEY ( ID_SERVICE_TYPE_DIM )
references dbo.SERVICE_TYPE_DIM(ID_SERVICE_TYPE_DIM)

alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_SOURCE_FUNDS_DIM FOREIGN KEY ( ID_SOURCE_FUNDS_DIM )
references dbo.SOURCE_FUNDS_DIM(ID_SOURCE_FUNDS_DIM)
go
alter table AUTHORIZATION_FACT
add constraint fk_AUTHORIZATION_FACT_ID_WORKER_DIM FOREIGN KEY ( ID_WORKER_DIM )
references dbo.worker_dim(ID_WORKER_DIM)
go
-- case_dim
alter table CASE_DIM
add constraint fk_CASE_DIM_ID_LOCATION_DIM FOREIGN KEY ( ID_LOCATION_DIM )
references dbo.LOCATION_DIM(ID_LOCATION_DIM)
go
alter table CASE_DIM
add constraint fk_CASE_DIM_ID_CALENDAR_DIM_LAST_ACTIVITY FOREIGN KEY ( ID_CALENDAR_DIM_LAST_ACTIVITY )
references dbo.calendar_dim(ID_CALENDAR_DIM)
go

alter table CASE_NOTE_FACT
add constraint fk_CASE_NOTE_FACT_ID_LEGAL_STATUS_DIM FOREIGN KEY ( ID_LEGAL_STATUS_DIM )
references dbo.LEGAL_STATUS_DIM(ID_LEGAL_STATUS_DIM)
go
alter table CASE_NOTE_FACT
add constraint fk_CASE_NOTE_FACT_ID_PEOPLE_DIM FOREIGN KEY ( ID_PEOPLE_DIM )
references dbo.PEOPLE_DIM(ID_PEOPLE_DIM)
go
alter table CASE_NOTE_FACT
add constraint fk_CASE_NOTE_FACT_ID_WORKER_DIM FOREIGN KEY ( ID_WORKER_DIM )
references dbo.WORKER_DIM(ID_WORKER_DIM)
go
alter table CASE_NOTE_FACT
add constraint fk_CASE_NOTE_FACT_ID_CASE_NOTE_TYPE_DIM FOREIGN KEY ( ID_CASE_NOTE_TYPE_DIM )
references dbo.CASE_NOTE_TYPE_DIM(ID_CASE_NOTE_TYPE_DIM)
go
alter table CASE_NOTE_FACT
add constraint fk_CASE_NOTE_FACT_ID_CASE_DIM FOREIGN KEY ( ID_CASE_DIM )
references dbo.case_dim(ID_CASE_DIM)
go
alter table CASE_NOTE_FACT
add constraint fk_CASE_NOTE_FACT_ID_LOCATION_DIM FOREIGN KEY ( ID_LOCATION_DIM )
references dbo.LOCATION_DIM(ID_LOCATION_DIM)
go
alter table CASE_NOTE_FACT
add constraint fk_CASE_NOTE_FACT_ID_CALENDAR_DIM_OCCURRED FOREIGN KEY ( ID_CALENDAR_DIM_OCCURRED )
references dbo.calendar_dim(ID_CALENDAR_DIM)
go
alter table CASE_NOTE_FACT
add constraint fk_CASE_NOTE_FACT_ID_CALENDAR_DIM_PRIOR_VISIT FOREIGN KEY ( ID_CALENDAR_DIM_PRIOR_VISIT )
references dbo.calendar_dim(ID_CALENDAR_DIM)
go

alter table DLR_RISK_ASSESSMENT_FACT
add constraint fk_DLR_RISK_ASSESSMENT_FACT_ID_CALENDAR_DIM_COMPLETED FOREIGN KEY ( ID_CALENDAR_DIM_COMPLETED )
references dbo.calendar_dim(ID_CALENDAR_DIM)
go

alter table DLR_RISK_ASSESSMENT_FACT
add constraint fk_DLR_RISK_ASSESSMENT_FACT_ID_PROVIDER_DIM FOREIGN KEY ( ID_PROVIDER_DIM )
references dbo.PROVIDER_DIM(ID_PROVIDER_DIM)
go


alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_EDUCATION_DIM FOREIGN KEY ( ID_EDUCATION_DIM )
references dbo.EDUCATION_DIM(ID_EDUCATION_DIM)
go
alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_CALENDAR_DIM_CREATED FOREIGN KEY ( ID_CALENDAR_DIM_CREATED )
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)
go
alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_CALENDAR_DIM_EARNED_DIPLOMA FOREIGN KEY (ID_CALENDAR_DIM_EARNED_DIPLOMA )
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)
go
alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_CALENDAR_DIM_ENROLLED FOREIGN KEY (ID_CALENDAR_DIM_ENROLLED )
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)
go
alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_CALENDAR_DIM_ENROLLMENT_END FOREIGN KEY (ID_CALENDAR_DIM_ENROLLMENT_END )
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)
go
alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_LOCATION_DIM_CASE FOREIGN KEY (ID_LOCATION_DIM_CASE )
references dbo.LOCATION_DIM(ID_LOCATION_DIM)
go
alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_LOCATION_DIM_CHILD FOREIGN KEY (ID_LOCATION_DIM_CHILD )
references dbo.LOCATION_DIM(ID_LOCATION_DIM)
go
alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY (ID_PEOPLE_DIM_CHILD )
references dbo.PEOPLE_DIM(ID_PEOPLE_DIM)
go
alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_SCHOOL_DIM FOREIGN KEY (ID_SCHOOL_DIM )
references dbo.school_dim(ID_SCHOOL_DIM)
go
alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_WORKER_DIM_CASE FOREIGN KEY (ID_WORKER_DIM_CASE )
references dbo.worker_dim(ID_WORKER_DIM)
go
alter table EDUCATION_FACT
add constraint fk_EDUCATION_FACT_ID_WORKER_DIM_CHILD FOREIGN KEY (ID_WORKER_DIM_CHILD )
references dbo.worker_dim(ID_WORKER_DIM)
go
alter table EDUCATION_PLAN_FACT
add constraint fk_EDUCATION_PLAN_FACT_ID_EDUCATION_PLAN_DIM FOREIGN KEY ( ID_EDUCATION_PLAN_DIM )
references dbo.EDUCATION_PLAN_DIM(ID_EDUCATION_PLAN_DIM)
go

alter table EDUCATION_PLAN_FACT
add constraint fk_EDUCATION_PLAN_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY ( ID_PEOPLE_DIM_CHILD )
references dbo.PEOPLE_DIM(ID_PEOPLE_DIM)
go

alter table EDUCATION_PLAN_FACT
add constraint fk_EDUCATION_PLAN_FACT_ID_CALENDAR_DIM_PLAN_DATE FOREIGN KEY ( ID_CALENDAR_DIM_PLAN_DATE )
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)
go




alter table EDUCATION_RECORDS_REQUEST_REFERRAL_FACT
add constraint fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_EDUCATION_RECORDS_REQUEST_REFERRAL_DIM
FOREIGN KEY ( ID_EDUCATION_RECORDS_REQUEST_REFERRAL_DIM )
references dbo.EDUCATION_RECORDS_REQUEST_REFERRAL_DIM(ID_EDUCATION_RECORDS_REQUEST_REFERRAL_DIM)
go
alter table EDUCATION_RECORDS_REQUEST_REFERRAL_FACT
add constraint fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_CALENDAR_DIM_REQUESTED FOREIGN KEY ( ID_CALENDAR_DIM_REQUESTED )
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)
go
alter table EDUCATION_RECORDS_REQUEST_REFERRAL_FACT
add constraint fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_CALENDAR_DIM_RECEIVED FOREIGN KEY ( ID_CALENDAR_DIM_RECEIVED )
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)
go
alter table EDUCATION_RECORDS_REQUEST_REFERRAL_FACT
add constraint fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_CALENDAR_DIM_REFERRAL FOREIGN KEY ( ID_CALENDAR_DIM_REFERRAL )
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)
go
alter table ELIG_EPISODE_FACT
add constraint fk_ELIG_EPISODE_FACT_ID_CALENDAR_DIM_END FOREIGN KEY(ID_CALENDAR_DIM_END)
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)
go
alter table ELIG_EPISODE_FACT
add constraint fk_ELIG_EPISODE_FACT_ID_CALENDAR_DIM_BEGIN FOREIGN KEY(ID_CALENDAR_DIM_BEGIN)
references dbo.CALENDAR_DIM(ID_CALENDAR_DIM)
go
alter table ELIG_EPISODE_FACT
add constraint fk_ELIG_EPISODE_FACT_ID_CASE_DIM FOREIGN KEY(ID_CASE_DIM)
references dbo.CASE_DIM(ID_CASE_DIM)
go
alter table ELIG_EPISODE_FACT
add constraint fk_ELIG_EPISODE_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY(ID_PEOPLE_DIM_CHILD)
references dbo.PEOPLE_DIM(ID_PEOPLE_DIM)
go

alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_COMPLETE FOREIGN KEY (ID_CALENDAR_DIM_COMPLETE )
references dbo.calendar_dim(ID_CALENDAR_DIM)
go
alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_COMPLETE FOREIGN KEY (ID_CALENDAR_DIM_ELIGIBILITY_COMPLETE )
references dbo.calendar_dim(ID_CALENDAR_DIM)
go
alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_EFFECTIVE FOREIGN KEY (ID_CALENDAR_DIM_ELIGIBILITY_EFFECTIVE)
references dbo.calendar_dim(ID_CALENDAR_DIM)
go
alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_END FOREIGN KEY (ID_CALENDAR_DIM_ELIGIBILITY_END)
references dbo.calendar_dim(ID_CALENDAR_DIM)
go
alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_VPA_CTW FOREIGN KEY (ID_CALENDAR_DIM_ELIGIBILITY_VPA_CTW)
references dbo.calendar_dim(ID_CALENDAR_DIM)
go


alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY (ID_PEOPLE_DIM_CHILD)
references dbo.PEOPLE_DIM(ID_PEOPLE_DIM)
go
alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_WORKER_DIM FOREIGN KEY (ID_WORKER_DIM)
references dbo.WORKER_DIM(ID_WORKER_DIM)
go


alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_ELIGIBILITY_REMOVAL_HOME_DIM FOREIGN KEY (ID_ELIGIBILITY_REMOVAL_HOME_DIM)
references dbo.ELIGIBILITY_REMOVAL_HOME_DIM(ID_ELIGIBILITY_REMOVAL_HOME_DIM)
go
alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_ELIGIBILITY_STATUS_DIM FOREIGN KEY (ID_ELIGIBILITY_STATUS_DIM)
references dbo.ELIGIBILITY_STATUS_DIM(ID_ELIGIBILITY_STATUS_DIM)
go
alter table ELIGIBILITY_FACT
add constraint fk_ELIGIBILITY_FACT_ID_ELIGIBILITY_DIM FOREIGN KEY (ID_ELIGIBILITY_DIM)
references dbo.ELIGIBILITY_DIM(ID_ELIGIBILITY_DIM)
go

alter table HEALTH_ACTIVITY_FACT
add constraint fk_HEALTH_ACTIVITY_FACT_ID_CALENDAR_DIM_ACTIVITY_END foreign key (ID_CALENDAR_DIM_ACTIVITY_END)
references dbo.calendar_dim(id_calendar_dim)
go
alter table HEALTH_ACTIVITY_FACT
add constraint fk_HEALTH_ACTIVITY_FACT_ID_CALENDAR_DIM_ACTIVITY_START foreign key (ID_CALENDAR_DIM_ACTIVITY_START)
references dbo.calendar_dim(id_calendar_dim)
go
alter table HEALTH_ACTIVITY_FACT
add constraint fk_HEALTH_ACTIVITY_FACT_ID_HEALTH_ACTIVITY_TYPE_DIM foreign key (ID_HEALTH_ACTIVITY_TYPE_DIM)
references dbo.HEALTH_ACTIVITY_TYPE_DIM(ID_HEALTH_ACTIVITY_TYPE_DIM)
go
alter table HEALTH_ACTIVITY_FACT
add constraint fk_HEALTH_ACTIVITY_FACT_ID_MENTAL_HEALTH_EVAL_DIM foreign key (ID_MENTAL_HEALTH_EVAL_DIM)
references dbo.MENTAL_HEALTH_EVAL_DIM(ID_MENTAL_HEALTH_EVAL_DIM)
go
alter table HEALTH_ACTIVITY_FACT
add constraint fk_HEALTH_ACTIVITY_FACT_ID_PEOPLE_DIM_CHILD foreign key (ID_PEOPLE_DIM_CHILD)
references dbo.PEOPLE_DIM(ID_PEOPLE_DIM)
go
alter table HEALTH_CAT_ATTRIBUTE_BRIDGE_FACT
add constraint fk_HEALTH_CAT_ATTRIBUTE_BRIDGE_FACT_ID_HEALTH_ACTIVITY_FACT foreign key (ID_HEALTH_ACTIVITY_FACT)
references dbo.HEALTH_ACTIVITY_FACT(ID_HEALTH_ACTIVITY_FACT)
go

alter table IL_ANSELL_CASEY_ASSESSMENT_FACT
add constraint fk_IL_ANSELL_CASEY_ASSESSMENT_FACT_ID_INDEPENDENT_LIVING_FACT foreign key(ID_INDEPENDENT_LIVING_FACT)
references dbo.independent_living_fact(ID_INDEPENDENT_LIVING_FACT);
go

alter table IL_NYTD_QUESTIONS_FACT
add constraint fk_IL_NYTD_QUESTIONS_FACT_ID_INDEPENDENT_LIVING_FACT foreign key(ID_INDEPENDENT_LIVING_FACT)
references dbo.INDEPENDENT_LIVING_FACT(ID_INDEPENDENT_LIVING_FACT)
go
alter table IL_NYTD_QUESTIONS_FACT
add constraint fk_IL_NYTD_QUESTIONS_FACT_ID_IL_NYTD_QUESTIONS_ATTRIBUTE_DIM foreign key(ID_IL_NYTD_QUESTIONS_ATTRIBUTE_DIM)
references dbo.IL_NYTD_QUESTIONS_ATTRIBUTE_DIM(ID_IL_NYTD_QUESTIONS_ATTRIBUTE_DIM)
go
alter table IL_NYTD_QUESTIONS_FACT
add constraint fk_IL_NYTD_QUESTIONS_FACT_ID_CALENDAR_DIM_SURVEY_COMPLETED foreign key(ID_CALENDAR_DIM_SURVEY_COMPLETED)
references dbo.calendar_dim(id_calendar_dim)
go
alter table INDEPENDENT_LIVING_FACT
add constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_ANTICIPATED_OUT_CARE foreign key(ID_CALENDAR_DIM_ANTICIPATED_OUT_CARE)
references dbo.calendar_dim(id_calendar_dim)
go
alter table INDEPENDENT_LIVING_FACT
add constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_BEGAN foreign key(ID_CALENDAR_DIM_BEGAN)
references dbo.calendar_dim(id_calendar_dim)
go
alter table INDEPENDENT_LIVING_FACT
add constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_IL_PLAN_COMPLETED foreign key(ID_CALENDAR_DIM_IL_PLAN_COMPLETED)
references dbo.calendar_dim(id_calendar_dim)
go
alter table INDEPENDENT_LIVING_FACT
add constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_INITIAL_IL_REFERRAL foreign key(ID_CALENDAR_DIM_INITIAL_IL_REFERRAL)
references dbo.calendar_dim(id_calendar_dim)
go
alter table INDEPENDENT_LIVING_FACT
add constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_REFERRED foreign key(ID_CALENDAR_DIM_REFERRED)
references dbo.calendar_dim(id_calendar_dim)
go
alter table INDEPENDENT_LIVING_FACT
add constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_YOUTH_NOT_PARTICIPATING foreign key(ID_CALENDAR_DIM_YOUTH_NOT_PARTICIPATING)
references dbo.calendar_dim(id_calendar_dim)
go
alter table INDEPENDENT_LIVING_FACT
add constraint fk_INDEPENDENT_LIVING_FACT_ID_PEOPLE_DIM foreign key(ID_PEOPLE_DIM)
references dbo.PEOPLE_DIM(ID_PEOPLE_DIM)
go
alter table intake_fact
add constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_ACCESS_RCVD foreign key (ID_CALENDAR_DIM_ACCESS_RCVD)
references calendar_dim(id_calendar_dim);
go
alter table intake_fact
add constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_CPS_SPVR_DSCN foreign key (ID_CALENDAR_DIM_CPS_SPVR_DSCN)
references calendar_dim(id_calendar_dim);
go
alter table intake_fact
add constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_INCD foreign key (ID_CALENDAR_DIM_INCD)
references calendar_dim(id_calendar_dim);
go
alter table intake_fact
add constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_SPVR_DSCN foreign key (ID_CALENDAR_DIM_SPVR_DSCN)
references calendar_dim(id_calendar_dim);
go
alter table intake_fact
add constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_WRKR_DSCN foreign key (ID_CALENDAR_DIM_WRKR_DSCN)
references calendar_dim(id_calendar_dim);
go
alter table intake_fact
add constraint fk_INTAKE_FACT_ID_CASE_DIM foreign key (ID_CASE_DIM)
references case_dim(id_case_dim);
go
alter table intake_fact
add constraint fk_INTAKE_FACT_ID_INTAKE_ATTRIBUTE_DIM foreign key (ID_INTAKE_ATTRIBUTE_DIM)
references INTAKE_ATTRIBUTE_DIM(ID_INTAKE_ATTRIBUTE_DIM);
go
alter table intake_fact
add constraint fk_INTAKE_FACT_ID_INTAKE_TYPE_DIM foreign key (ID_INTAKE_TYPE_DIM)
references INTAKE_TYPE_DIM(ID_INTAKE_TYPE_DIM);
go
alter table intake_fact
add constraint fk_INTAKE_FACT_ID_LOCATION_DIM_INTAKE_WORKER foreign key (ID_LOCATION_DIM_INTAKE_WORKER)
references location_dim(id_location_dim);
go

alter table intake_fact
add constraint fk_INTAKE_FACT_ID_PROVIDER_DIM_INTAKE foreign key(ID_PROVIDER_DIM_INTAKE)
references provider_dim(ID_PROVIDER_DIM)
go

alter table intake_fact
add constraint fk_INTAKE_FACT_ID_RESPONSE_TIME_EXP_DIM foreign key(ID_RESPONSE_TIME_EXP_DIM)
references  RESPONSE_TIME_EXP_DIM(ID_RESPONSE_TIME_EXP_DIM)
go

alter table intake_fact
add constraint fk_INTAKE_FACT_ID_WORKER_DIM_CPS_SUPERVISOR  foreign key(ID_WORKER_DIM_CPS_SUPERVISOR)
references worker_dim(id_worker_dim);
go
alter table intake_fact
add constraint fk_INTAKE_FACT_ID_WORKER_DIM_INTAKE  foreign key(ID_WORKER_DIM_INTAKE)
references worker_dim(ID_WORKER_DIM);
go
alter table intake_fact
add constraint fk_INTAKE_FACT_ID_WORKER_DIM_INTAKE_SUPERVISOR  foreign key(ID_WORKER_DIM_INTAKE_SUPERVISOR)
references worker_dim(ID_WORKER_DIM);
go
alter table INTAKE_PARTICIPANT_FACT
add constraint fk_INTAKE_PARTICIPANT_FACT_ID_INTAKE_PARTICIPANT_ROLES_DIM foreign key (ID_INTAKE_PARTICIPANT_ROLES_DIM)
references INTAKE_PARTICIPANT_ROLES_DIM(ID_INTAKE_PARTICIPANT_ROLES_DIM)
go
alter table INTAKE_PARTICIPANT_FACT
add constraint fk_INTAKE_PARTICIPANT_FACT_ID_PEOPLE_DIM_CHILD foreign key (ID_PEOPLE_DIM_CHILD)
references PEOPLE_DIM(ID_PEOPLE_DIM)
go
alter table INTAKE_SERVICE_BRIDGE_FACT
add constraint fk_INTAKE_SERVICE_BRIDGE_FACT_ID_INTAKE_FACT foreign key (ID_INTAKE_FACT)
references intake_fact(id_intake_fact);
go
alter table INTAKE_SERVICE_BRIDGE_FACT
add constraint fk_INTAKE_SERVICE_BRIDGE_FACT_ID_SERVICE_REFERRAL_DIM foreign key (ID_SERVICE_REFERRAL_DIM)
references SERVICE_REFERRAL_DIM(ID_SERVICE_REFERRAL_DIM);
go
alter table INTAKE_VICTIM_FACT
add constraint fk_INTAKE_VICTIM_FACT_ID_INTAKE_FACT foreign key (ID_INTAKE_FACT)
references intake_fact(id_intake_fact);
go