
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_WORKER_DIM_PRIMARY]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_WORKER_DIM_PRIMARY]
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_PROVIDER_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_PROVIDER_DIM]
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_PLACEMENT_TYPE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_PLACEMENT_TYPE_DIM]
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_PEOPLE_DIM_VICTIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_PEOPLE_DIM_VICTIM]
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_LOCATION_DIM_PRIMARY_WORKER]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_LOCATION_DIM_PRIMARY_WORKER]
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_LOCATION_DIM_INTAKE_WORKER]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_LOCATION_DIM_INTAKE_WORKER]
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_LOCATION_DIM_INCIDENT]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_LOCATION_DIM_INCIDENT]
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_CASE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_CASE_DIM]
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_CALENDAR_DIM_REFERRED]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_CALENDAR_DIM_REFERRED]
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_CALENDAR_DIM_INCIDENT]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_ID_CALENDAR_DIM_INCIDENT]
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_id_calendar_dim_founded]')
   AND parent_object_id = OBJECT_ID(N'dbo.ABUSE_FACT')
)
ALTER TABLE [dbo].[ABUSE_FACT] DROP CONSTRAINT [fk_id_calendar_dim_founded]
GO

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_CALENDAR_DIM_TERMINATED]')
   AND parent_object_id = OBJECT_ID(N'dbo.adoption_fact')
)
ALTER TABLE dbo.ADOPTION_FACT DROP CONSTRAINT fk_ID_CALENDAR_DIM_TERMINATED
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_CALENDAR_DIM_EFFECTIVE_ELIGIBLE]')
   AND parent_object_id = OBJECT_ID(N'dbo.adoption_fact')
)
ALTER TABLE dbo.ADOPTION_FACT DROP CONSTRAINT fk_ID_CALENDAR_DIM_EFFECTIVE_ELIGIBLE
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_CALENDAR_DIM_COMPLETE]')
   AND parent_object_id = OBJECT_ID(N'dbo.adoption_fact')
)
ALTER TABLE dbo.ADOPTION_FACT DROP CONSTRAINT fk_ID_CALENDAR_DIM_COMPLETE
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ID_ADOPTION_STATUS_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.adoption_fact')
)
ALTER TABLE dbo.ADOPTION_FACT DROP CONSTRAINT fk_ID_ADOPTION_STATUS_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_af_ID_PEOPLE_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.adoption_fact')
)
ALTER TABLE dbo.ADOPTION_FACT DROP CONSTRAINT fk_af_ID_PEOPLE_DIM_CHILD
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_af_ID_CASE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.adoption_fact')
)
ALTER TABLE dbo.ADOPTION_FACT DROP CONSTRAINT fk_af_ID_CASE_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ALLEGATION_FACT_ID_RELATIONSHIP_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ALLEGATION_FACT')
)
ALTER TABLE dbo.ALLEGATION_FACT DROP CONSTRAINT fk_ALLEGATION_FACT_ID_RELATIONSHIP_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ALLEGATION_FACT_ID_PEOPLE_DIM_SUBJECT]')
   AND parent_object_id = OBJECT_ID(N'dbo.ALLEGATION_FACT')
)
ALTER TABLE dbo.ALLEGATION_FACT DROP CONSTRAINT fk_ALLEGATION_FACT_ID_PEOPLE_DIM_SUBJECT
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ALLEGATION_FACT_ID_INVESTIGATION_ASSESSMENT_FACT]')
   AND parent_object_id = OBJECT_ID(N'dbo.ALLEGATION_FACT')
)
ALTER TABLE dbo.ALLEGATION_FACT DROP CONSTRAINT fk_ALLEGATION_FACT_ID_INVESTIGATION_ASSESSMENT_FACT
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ALLEGATION_FACT_ID_INTAKE_FACT]')
   AND parent_object_id = OBJECT_ID(N'dbo.ALLEGATION_FACT')
)
ALTER TABLE dbo.ALLEGATION_FACT DROP CONSTRAINT fk_ALLEGATION_FACT_ID_INTAKE_FACT
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ALLEGATION_FACT_ID_FINDINGS_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ALLEGATION_FACT')
)
ALTER TABLE dbo.ALLEGATION_FACT DROP CONSTRAINT fk_ALLEGATION_FACT_ID_FINDINGS_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ALLEGATION_FACT_ID_CASE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ALLEGATION_FACT')
)
ALTER TABLE dbo.ALLEGATION_FACT DROP CONSTRAINT fk_ALLEGATION_FACT_ID_CASE_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ALLEGATION_FACT_ID_ABUSE_TYPE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ALLEGATION_FACT')
)
ALTER TABLE dbo.ALLEGATION_FACT DROP CONSTRAINT fk_ALLEGATION_FACT_ID_ABUSE_TYPE_DIM
GO

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ASSIGNMENT_FACT_ID_WORKER_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ASSIGNMENT_FACT')
)
ALTER TABLE dbo.ASSIGNMENT_FACT DROP CONSTRAINT fk_ASSIGNMENT_FACT_ID_WORKER_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ASSIGNMENT_FACT_ID_PROVIDER_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ASSIGNMENT_FACT')
)
ALTER TABLE dbo.ASSIGNMENT_FACT DROP CONSTRAINT fk_ASSIGNMENT_FACT_ID_PROVIDER_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ASSIGNMENT_FACT_ID_PEOPLE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ASSIGNMENT_FACT')
)
ALTER TABLE dbo.ASSIGNMENT_FACT DROP CONSTRAINT fk_ASSIGNMENT_FACT_ID_PEOPLE_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ASSIGNMENT_FACT_ID_LOCATION_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ASSIGNMENT_FACT')
)
ALTER TABLE dbo.ASSIGNMENT_FACT DROP CONSTRAINT fk_ASSIGNMENT_FACT_ID_LOCATION_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ASSIGNMENT_FACT_ID_CASE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ASSIGNMENT_FACT')
)
ALTER TABLE dbo.ASSIGNMENT_FACT DROP CONSTRAINT fk_ASSIGNMENT_FACT_ID_CASE_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_END]')
   AND parent_object_id = OBJECT_ID(N'dbo.ASSIGNMENT_FACT')
)
ALTER TABLE dbo.ASSIGNMENT_FACT DROP CONSTRAINT fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_END
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_BEGIN]')
   AND parent_object_id = OBJECT_ID(N'dbo.ASSIGNMENT_FACT')
)
ALTER TABLE dbo.ASSIGNMENT_FACT DROP CONSTRAINT fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_BEGIN
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ASSIGNMENT_FACT_ID_ASSIGNMENT_ATTRIBUTE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ASSIGNMENT_FACT')
)
ALTER TABLE dbo.ASSIGNMENT_FACT DROP CONSTRAINT fk_ASSIGNMENT_FACT_ID_ASSIGNMENT_ATTRIBUTE_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_IID_PLACEMENT_TYPE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
 ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_IID_PLACEMENT_TYPE_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_WORKER_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_WORKER_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_SOURCE_FUNDS_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_SOURCE_FUNDS_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_SERVICE_TYPE_DIME]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_SERVICE_TYPE_DIME
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_PROVIDER_DIM_SERVICE]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_PROVIDER_DIM_SERVICE
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_PROVIDER_DIM_PAYEE]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_PROVIDER_DIM_PAYEE
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_PLACEMENT_CARE_AUTH_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_PLACEMENT_CARE_AUTH_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_PEOPLE_DIM_CLIENT]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_PEOPLE_DIM_CLIENT
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_PEOPLE_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_PEOPLE_DIM_CHILD
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_LOCATION_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_LOCATION_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_CHART_OF_ACCOUNTS_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_CHART_OF_ACCOUNTS_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_CASE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_CASE_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_SERVICE_END]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_SERVICE_END
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_SERVICE_BEGIN]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_SERVICE_BEGIN
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_AUTH_END]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_AUTH_END
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_AUTH_BEGIN]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_CALENDAR_DIM_AUTH_BEGIN
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_AUTHORIZATION_FACT_ID_AUTHORIZATION_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.AUTHORIZATION_FACT')
)
ALTER TABLE dbo.AUTHORIZATION_FACT DROP CONSTRAINT fk_AUTHORIZATION_FACT_ID_AUTHORIZATION_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_DIM_ID_LOCATION_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_DIM')
)
ALTER TABLE dbo.CASE_DIM DROP CONSTRAINT fk_CASE_DIM_ID_LOCATION_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_DIM_ID_CALENDAR_DIM_LAST_ACTIVITY]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_DIM')
)
ALTER TABLE dbo.CASE_DIM DROP CONSTRAINT fk_CASE_DIM_ID_CALENDAR_DIM_LAST_ACTIVITY
GO

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_NOTE_FACT_ID_WORKER_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_NOTE_FACT')
)
ALTER TABLE dbo.CASE_NOTE_FACT DROP CONSTRAINT fk_CASE_NOTE_FACT_ID_WORKER_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_NOTE_FACT_ID_PEOPLE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_NOTE_FACT')
)
ALTER TABLE dbo.CASE_NOTE_FACT DROP CONSTRAINT fk_CASE_NOTE_FACT_ID_PEOPLE_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_NOTE_FACT_ID_LOCATION_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_NOTE_FACT')
)
ALTER TABLE dbo.CASE_NOTE_FACT DROP CONSTRAINT fk_CASE_NOTE_FACT_ID_LOCATION_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_NOTE_FACT_ID_LEGAL_STATUS_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_NOTE_FACT')
)
ALTER TABLE dbo.CASE_NOTE_FACT DROP CONSTRAINT fk_CASE_NOTE_FACT_ID_LEGAL_STATUS_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_NOTE_FACT_ID_CASE_NOTE_TYPE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_NOTE_FACT')
)
ALTER TABLE dbo.CASE_NOTE_FACT DROP CONSTRAINT fk_CASE_NOTE_FACT_ID_CASE_NOTE_TYPE_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_NOTE_FACT_ID_CASE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_NOTE_FACT')
)
ALTER TABLE dbo.CASE_NOTE_FACT DROP CONSTRAINT fk_CASE_NOTE_FACT_ID_CASE_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_NOTE_FACT_ID_CALENDAR_DIM_PRIOR_VISIT]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_NOTE_FACT')
)
ALTER TABLE dbo.CASE_NOTE_FACT DROP CONSTRAINT fk_CASE_NOTE_FACT_ID_CALENDAR_DIM_PRIOR_VISIT
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_CASE_NOTE_FACT_ID_CALENDAR_DIM_OCCURRED]')
   AND parent_object_id = OBJECT_ID(N'dbo.CASE_NOTE_FACT')
)
ALTER TABLE dbo.CASE_NOTE_FACT DROP CONSTRAINT fk_CASE_NOTE_FACT_ID_CALENDAR_DIM_OCCURRED
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_DLR_RISK_ASSESSMENT_FACT_ID_PROVIDER_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.DLR_RISK_ASSESSMENT_FACT')
)
alter table DLR_RISK_ASSESSMENT_FACT
drop constraint fk_DLR_RISK_ASSESSMENT_FACT_ID_PROVIDER_DIM
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_DLR_RISK_ASSESSMENT_FACT_ID_CALENDAR_DIM_COMPLETED]')
   AND parent_object_id = OBJECT_ID(N'dbo.DLR_RISK_ASSESSMENT_FACT')
)
alter table DLR_RISK_ASSESSMENT_FACT
drop constraint fk_DLR_RISK_ASSESSMENT_FACT_ID_CALENDAR_DIM_COMPLETED
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_WORKER_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_WORKER_DIM_CHILD
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_WORKER_DIM_CASE]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_WORKER_DIM_CASE
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_SCHOOL_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_SCHOOL_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_PEOPLE_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_PEOPLE_DIM_CHILD
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_LOCATION_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_LOCATION_DIM_CHILD
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_LOCATION_DIM_CASE]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_LOCATION_DIM_CASE
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_EDUCATION_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_EDUCATION_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_CALENDAR_DIM_ENROLLMENT_END]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_CALENDAR_DIM_ENROLLMENT_END
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_CALENDAR_DIM_ENROLLED]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_CALENDAR_DIM_ENROLLED
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_CALENDAR_DIM_EARNED_DIPLOMA]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_CALENDAR_DIM_EARNED_DIPLOMA
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_FACT_ID_CALENDAR_DIM_CREATED]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_FACT')
)
ALTER TABLE dbo.EDUCATION_FACT DROP CONSTRAINT fk_EDUCATION_FACT_ID_CALENDAR_DIM_CREATED
GO

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_PLAN_FACT_ID_PEOPLE_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_PLAN_FACT')
)
ALTER TABLE [dbo].[EDUCATION_PLAN_FACT] DROP CONSTRAINT [fk_EDUCATION_PLAN_FACT_ID_PEOPLE_DIM_CHILD]
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_PLAN_FACT_ID_EDUCATION_PLAN_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_PLAN_FACT')
)
ALTER TABLE [dbo].[EDUCATION_PLAN_FACT] DROP CONSTRAINT [fk_EDUCATION_PLAN_FACT_ID_EDUCATION_PLAN_DIM]
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_PLAN_FACT_ID_CALENDAR_DIM_PLAN_DATE]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_PLAN_FACT')
)
ALTER TABLE [dbo].[EDUCATION_PLAN_FACT] DROP CONSTRAINT fk_EDUCATION_PLAN_FACT_ID_CALENDAR_DIM_PLAN_DATE
GO

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_EDUCATION_RECORDS_REQUEST_REFERRAL_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_RECORDS_REQUEST_REFERRAL_FACT')
)
ALTER TABLE dbo.EDUCATION_RECORDS_REQUEST_REFERRAL_FACT 
DROP CONSTRAINT fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_EDUCATION_RECORDS_REQUEST_REFERRAL_DIM
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_CALENDAR_DIM_REQUESTED]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_RECORDS_REQUEST_REFERRAL_FACT')
)
ALTER TABLE dbo.EDUCATION_RECORDS_REQUEST_REFERRAL_FACT DROP CONSTRAINT fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_CALENDAR_DIM_REQUESTED
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_CALENDAR_DIM_REFERRAL]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_RECORDS_REQUEST_REFERRAL_FACT')
)
ALTER TABLE dbo.EDUCATION_RECORDS_REQUEST_REFERRAL_FACT DROP CONSTRAINT fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_CALENDAR_DIM_REFERRAL
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_CALENDAR_DIM_RECEIVED]')
   AND parent_object_id = OBJECT_ID(N'dbo.EDUCATION_RECORDS_REQUEST_REFERRAL_FACT')
)
ALTER TABLE dbo.EDUCATION_RECORDS_REQUEST_REFERRAL_FACT DROP CONSTRAINT fk_EDUCATION_RECORDS_REQUEST_REFERRAL_FACT_ID_CALENDAR_DIM_RECEIVED
GO
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIG_EPISODE_FACT_ID_CALENDAR_DIM_END]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIG_EPISODE_FACT')
)
alter table ELIG_EPISODE_FACT
drop constraint fk_ELIG_EPISODE_FACT_ID_CALENDAR_DIM_END 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIG_EPISODE_FACT_ID_CALENDAR_DIM_BEGIN]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIG_EPISODE_FACT')
)
alter table ELIG_EPISODE_FACT
drop constraint fk_ELIG_EPISODE_FACT_ID_CALENDAR_DIM_BEGIN 

go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIG_EPISODE_FACT_ID_CASE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIG_EPISODE_FACT')
)
alter table ELIG_EPISODE_FACT
drop constraint fk_ELIG_EPISODE_FACT_ID_CASE_DIM 

go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIG_EPISODE_FACT_ID_PEOPLE_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIG_EPISODE_FACT')
)
alter table ELIG_EPISODE_FACT
drop constraint fk_ELIG_EPISODE_FACT_ID_PEOPLE_DIM_CHILD
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_COMPLETE]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_COMPLETE 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_COMPLETE]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_COMPLETE 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_EFFECTIVE]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_EFFECTIVE 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_END]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_END 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_VPA_CTW]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_CALENDAR_DIM_ELIGIBILITY_VPA_CTW 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_PEOPLE_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_PEOPLE_DIM_CHILD 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_WORKER_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_WORKER_DIM 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_ELIGIBILITY_REMOVAL_HOME_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_ELIGIBILITY_REMOVAL_HOME_DIM 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_ELIGIBILITY_STATUS_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_ELIGIBILITY_STATUS_DIM 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_ELIGIBILITY_FACT_ID_ELIGIBILITY_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.ELIGIBILITY_FACT')
)
alter table ELIGIBILITY_FACT
drop constraint fk_ELIGIBILITY_FACT_ID_ELIGIBILITY_DIM 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_HEALTH_ACTIVITY_FACT_ID_CALENDAR_DIM_ACTIVITY_END]')
   AND parent_object_id = OBJECT_ID(N'dbo.HEALTH_ACTIVITY_FACT')
)
alter table HEALTH_ACTIVITY_FACT
drop constraint fk_HEALTH_ACTIVITY_FACT_ID_CALENDAR_DIM_ACTIVITY_END 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_HEALTH_ACTIVITY_FACT_ID_CALENDAR_DIM_ACTIVITY_START]')
   AND parent_object_id = OBJECT_ID(N'dbo.HEALTH_ACTIVITY_FACT')
)
alter table HEALTH_ACTIVITY_FACT
drop constraint fk_HEALTH_ACTIVITY_FACT_ID_CALENDAR_DIM_ACTIVITY_START
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_HEALTH_ACTIVITY_FACT_ID_HEALTH_ACTIVITY_TYPE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.HEALTH_ACTIVITY_FACT')
)
alter table HEALTH_ACTIVITY_FACT
drop constraint fk_HEALTH_ACTIVITY_FACT_ID_HEALTH_ACTIVITY_TYPE_DIM 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_HEALTH_ACTIVITY_FACT_ID_MENTAL_HEALTH_EVAL_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.HEALTH_ACTIVITY_FACT')
)
alter table HEALTH_ACTIVITY_FACT
drop constraint fk_HEALTH_ACTIVITY_FACT_ID_MENTAL_HEALTH_EVAL_DIM 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_HEALTH_ACTIVITY_FACT_ID_PEOPLE_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.HEALTH_ACTIVITY_FACT')
)
alter table HEALTH_ACTIVITY_FACT
drop constraint fk_HEALTH_ACTIVITY_FACT_ID_PEOPLE_DIM_CHILD 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_HEALTH_CAT_ATTRIBUTE_BRIDGE_FACT_ID_HEALTH_ACTIVITY_FACT]')
   AND parent_object_id = OBJECT_ID(N'dbo.HEALTH_CAT_ATTRIBUTE_BRIDGE_FACT')
)
alter table HEALTH_CAT_ATTRIBUTE_BRIDGE_FACT
drop constraint fk_HEALTH_CAT_ATTRIBUTE_BRIDGE_FACT_ID_HEALTH_ACTIVITY_FACT
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_IL_ANSELL_CASEY_ASSESSMENT_FACT_ID_INDEPENDENT_LIVING_FACT]')
   AND parent_object_id = OBJECT_ID(N'dbo.IL_ANSELL_CASEY_ASSESSMENT_FACT')
)
alter table IL_ANSELL_CASEY_ASSESSMENT_FACT
drop constraint fk_IL_ANSELL_CASEY_ASSESSMENT_FACT_ID_INDEPENDENT_LIVING_FACT 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_IL_NYTD_QUESTIONS_FACT_ID_INDEPENDENT_LIVING_FACT]')
   AND parent_object_id = OBJECT_ID(N'dbo.IL_NYTD_QUESTIONS_FACT')
)
alter table IL_NYTD_QUESTIONS_FACT
drop constraint fk_IL_NYTD_QUESTIONS_FACT_ID_INDEPENDENT_LIVING_FACT 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_IL_NYTD_QUESTIONS_FACT_ID_IL_NYTD_QUESTIONS_ATTRIBUTE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.IL_NYTD_QUESTIONS_FACT')
)
alter table IL_NYTD_QUESTIONS_FACT
drop constraint fk_IL_NYTD_QUESTIONS_FACT_ID_IL_NYTD_QUESTIONS_ATTRIBUTE_DIM 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_IL_NYTD_QUESTIONS_FACT_ID_CALENDAR_DIM_SURVEY_COMPLETED]')
   AND parent_object_id = OBJECT_ID(N'dbo.IL_NYTD_QUESTIONS_FACT')
)
alter table IL_NYTD_QUESTIONS_FACT
drop constraint fk_IL_NYTD_QUESTIONS_FACT_ID_CALENDAR_DIM_SURVEY_COMPLETED 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_ANTICIPATED_OUT_CARE]')
   AND parent_object_id = OBJECT_ID(N'dbo.INDEPENDENT_LIVING_FACT')
)
alter table INDEPENDENT_LIVING_FACT
drop constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_ANTICIPATED_OUT_CARE 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_BEGAN]')
   AND parent_object_id = OBJECT_ID(N'dbo.INDEPENDENT_LIVING_FACT')
)
alter table INDEPENDENT_LIVING_FACT
drop constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_BEGAN 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_IL_PLAN_COMPLETED]')
   AND parent_object_id = OBJECT_ID(N'dbo.INDEPENDENT_LIVING_FACT')
)
alter table INDEPENDENT_LIVING_FACT
drop constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_IL_PLAN_COMPLETED 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_INITIAL_IL_REFERRAL]')
   AND parent_object_id = OBJECT_ID(N'dbo.INDEPENDENT_LIVING_FACT')
)
alter table INDEPENDENT_LIVING_FACT
drop constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_INITIAL_IL_REFERRAL
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_REFERRED]')
   AND parent_object_id = OBJECT_ID(N'dbo.INDEPENDENT_LIVING_FACT')
)
alter table INDEPENDENT_LIVING_FACT
drop constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_REFERRED
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_YOUTH_NOT_PARTICIPATING]')
   AND parent_object_id = OBJECT_ID(N'dbo.INDEPENDENT_LIVING_FACT')
)
alter table INDEPENDENT_LIVING_FACT
drop constraint fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_YOUTH_NOT_PARTICIPATING 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INDEPENDENT_LIVING_FACT_ID_PEOPLE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.INDEPENDENT_LIVING_FACT')
)
alter table INDEPENDENT_LIVING_FACT
drop constraint fk_INDEPENDENT_LIVING_FACT_ID_PEOPLE_DIM 
go

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_CALENDAR_DIM_ACCESS_RCVD]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_ACCESS_RCVD 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_CALENDAR_DIM_CPS_SPVR_DSCN]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_CPS_SPVR_DSCN 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_CALENDAR_DIM_INCD]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_INCD
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_CALENDAR_DIM_SPVR_DSCN]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_SPVR_DSCN 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_CALENDAR_DIM_WRKR_DSCN]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_CALENDAR_DIM_WRKR_DSCN 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_CASE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_CASE_DIM
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_INTAKE_ATTRIBUTE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_INTAKE_ATTRIBUTE_DIM 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_INTAKE_TYPE_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_INTAKE_TYPE_DIM 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_LOCATION_DIM_INTAKE_WORKER]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_LOCATION_DIM_INTAKE_WORKER 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_PROVIDER_DIM_INTAKE]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_PROVIDER_DIM_INTAKE
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_RESPONSE_TIME_EXP_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_RESPONSE_TIME_EXP_DIM 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_WORKER_DIM_CPS_SUPERVISOR]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_WORKER_DIM_CPS_SUPERVISOR 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_WORKER_DIM_INTAKE]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_WORKER_DIM_INTAKE 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_FACT_ID_WORKER_DIM_INTAKE_SUPERVISOR]')
   AND parent_object_id = OBJECT_ID(N'dbo.intake_fact')
)
alter table intake_fact
drop constraint fk_INTAKE_FACT_ID_WORKER_DIM_INTAKE_SUPERVISOR  
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_PARTICIPANT_FACT_ID_INTAKE_PARTICIPANT_ROLES_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.INTAKE_PARTICIPANT_FACT')
)
alter table INTAKE_PARTICIPANT_FACT
drop constraint fk_INTAKE_PARTICIPANT_FACT_ID_INTAKE_PARTICIPANT_ROLES_DIM 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_PARTICIPANT_FACT_ID_PEOPLE_DIM_CHILD]')
   AND parent_object_id = OBJECT_ID(N'dbo.INTAKE_PARTICIPANT_FACT')
)
alter table INTAKE_PARTICIPANT_FACT
drop constraint fk_INTAKE_PARTICIPANT_FACT_ID_PEOPLE_DIM_CHILD 
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_SERVICE_BRIDGE_FACT_ID_INTAKE_FACT]')
   AND parent_object_id = OBJECT_ID(N'dbo.INTAKE_SERVICE_BRIDGE_FACT')
)
alter table INTAKE_SERVICE_BRIDGE_FACT
drop constraint fk_INTAKE_SERVICE_BRIDGE_FACT_ID_INTAKE_FACT ;
go
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.[fk_INTAKE_SERVICE_BRIDGE_FACT_ID_SERVICE_REFERRAL_DIM]')
   AND parent_object_id = OBJECT_ID(N'dbo.INTAKE_SERVICE_BRIDGE_FACT')
)
alter table INTAKE_SERVICE_BRIDGE_FACT
drop constraint fk_INTAKE_SERVICE_BRIDGE_FACT_ID_SERVICE_REFERRAL_DIM ;
go