CREATE TABLE [rodis].[birth_child_intake_placement] (
	[id_birth] [bigint] NOT NULL,
	[id_child] [int] NOT NULL,
	[id_intake] [int] NOT NULL,
	[id_placement] [int] NOT NULL,
	[record_source] [varchar](23) NULL,
	[intake_date] [datetime] NULL,
	[intake_office] [varchar](200) NULL,
	[intake_reporter_type] [varchar](200) NULL,
	[intake_reporter_mandate] [varchar](50) NULL,
	[screen_decision] [varchar](200) NULL,
	[alleged_phys_abuse] [varchar](20) NULL,
	[alleged_sex_abuse] [varchar](20) NULL,
	[alleged_phys_or_sex_abuse] [varchar](20) NULL,
	[alleged_neglect] [varchar](20) NULL,
	[alleged_emotional_abuse] [varchar](20) NULL,
	[any_allegation] [varchar](20) NULL,
	[any_investigation] [varchar](20) NULL,
	[overall_findings] [varchar](28) NULL,
	[simple_findings] [varchar](31) NULL,
	[ihs_provided] [varchar](7) NULL,
	[ihs_start_date] [datetime] NULL,
	[ooh_provided] [varchar](3) NULL,
	[ooh_start_date] [datetime] NULL,
	[overall_services] [varchar](26) NULL,
	[simple_services] [varchar](26) NULL,
	[child_CA_birth_date] [datetime] NULL,
	[child_census_race] [varchar](200) NULL,
	[child_census_ethnicity] [varchar](13) NULL,
	[child_simple_race_ethnicity] [varchar](22) NULL,
	[placement_outcome] [varchar](25) NULL,
	[birth_record_link] [varchar](22) NULL,
	[child_birth_date] [datetime] NULL,
	[child_birth_weight] [int] NULL,
	[child_birth_weight_category] [varchar](7) NULL,
	[child_birth_sex] [varchar](50) NULL,
	[any_congenital_abnormality] [varchar](13) NULL,
	[prenatal_care_start_month] [smallint] NULL,
	[prenatal_care_start_trimester] [varchar](25) NULL,
	[birth_order] [varchar](24) NULL,
	[birth_payment_category] [varchar](25) NULL,
	[paternity_established] [varchar](11) NULL,
	[maternal_age] [int] NULL,
	[maternal_age_category] [varchar](30) NULL,
	[maternal_census_race] [varchar](50) NULL,
	[maternal_census_ethnicity] [varchar](50) NULL,
	[maternal_simple_race_ethnicity] [varchar](22) NULL,
	[maternal_residence] [varchar](50) NULL,
	[maternal_raw_education] [varchar](255) NULL,
	[maternal_simple_education] [varchar](26) NULL,
	[mandatory_reporter_fl] [int] NULL,
	[screen_in_fl] [int] NULL,
	[alleged_phys_abuse_fl] [int] NULL,
	[alleged_sex_abuse_fl] [int] NULL,
	[alleged_neglect_fl] [int] NULL,
	[any_allegation_fl] [int] NULL,
	[any_investigation_fl] [int] NULL,
	[any_substantiated_fl] [int] NULL,
	[ihs_provided_fl] [int] NULL,
	[ooh_provided_fl] [int] NULL,
	[still_in_care_fl] [int] NULL,
	[birth_record_link_fl] [int] NOT NULL,
	CONSTRAINT [pk_birth_child_intake_placement] PRIMARY KEY CLUSTERED (
		[id_birth] ASC,
		[id_child] ASC,
		[id_intake] ASC,
		[id_placement] ASC
		)
	)
