CREATE TABLE [dbo].[ALLEGATION_FACT] (
    [ID_ALLEGATION_FACT]               INT      NOT NULL,
    [ID_ALGT]                          INT      NULL,
    [ID_CPS]                           INT      NULL,
    [ID_INTAKE_FACT]                   INT      NULL,
    [ID_INVESTIGATION_ASSESSMENT_FACT] INT      NULL,
    [ID_ABUSE_TYPE_DIM]                INT      NULL,
    [ID_CASE_DIM]                      INT      NULL,
    [ID_FINDINGS_DIM]                  INT      NULL,
    [ID_PEOPLE_DIM_SUBJECT]            INT      NULL,
    [ID_PEOPLE_DIM_VICTIM]             INT      NULL,
    [ID_RELATIONSHIP_DIM]              INT      NULL,
    [FL_FATALITY]                      TINYINT  NULL,
    [FL_FATALITY_INVS]                 TINYINT  NULL,
    [FL_INVS]                          TINYINT  NULL,
    [CHILD_AGE]                        TINYINT  NULL,
    [FL_EXPUNGED]                      CHAR (1) NULL,
    [ID_PRSN_SUBJECT]                  INT      NULL,
    [ID_PRSN_VICTIM]                   INT      NULL,
    [ID_CASE]                          INT      NULL,
    CONSTRAINT [PK_ID_ALLEGATION_FACT] PRIMARY KEY CLUSTERED ([ID_ALLEGATION_FACT] ASC),
    CONSTRAINT [fk_ALLEGATION_FACT_ID_ABUSE_TYPE_DIM] FOREIGN KEY ([ID_ABUSE_TYPE_DIM]) REFERENCES [dbo].[ABUSE_TYPE_DIM] ([ID_ABUSE_TYPE_DIM]),
    CONSTRAINT [fk_ALLEGATION_FACT_ID_CASE_DIM] FOREIGN KEY ([ID_CASE_DIM]) REFERENCES [dbo].[CASE_DIM] ([ID_CASE_DIM]),
    CONSTRAINT [fk_ALLEGATION_FACT_ID_FINDINGS_DIM] FOREIGN KEY ([ID_FINDINGS_DIM]) REFERENCES [dbo].[FINDINGS_DIM] ([ID_FINDINGS_DIM]),
    CONSTRAINT [fk_ALLEGATION_FACT_ID_INTAKE_FACT] FOREIGN KEY ([ID_INTAKE_FACT]) REFERENCES [dbo].[INTAKE_FACT] ([ID_INTAKE_FACT]),
    CONSTRAINT [fk_ALLEGATION_FACT_ID_INVESTIGATION_ASSESSMENT_FACT] FOREIGN KEY ([ID_INVESTIGATION_ASSESSMENT_FACT]) REFERENCES [dbo].[INVESTIGATION_ASSESSMENT_FACT] ([ID_INVESTIGATION_ASSESSMENT_FACT]),
    CONSTRAINT [fk_ALLEGATION_FACT_ID_PEOPLE_DIM_SUBJECT] FOREIGN KEY ([ID_PEOPLE_DIM_SUBJECT]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM]),
    CONSTRAINT [fk_ALLEGATION_FACT_ID_RELATIONSHIP_DIM] FOREIGN KEY ([ID_RELATIONSHIP_DIM]) REFERENCES [dbo].[RELATIONSHIP_DIM] ([ID_RELATIONSHIP_DIM])
);


GO
CREATE NONCLUSTERED INDEX [idx_id_cps_victim]
    ON [dbo].[ALLEGATION_FACT]([ID_CPS] ASC, [ID_PEOPLE_DIM_VICTIM] ASC)
    INCLUDE([ID_ABUSE_TYPE_DIM], [ID_RELATIONSHIP_DIM], [ID_PRSN_VICTIM]);


GO
CREATE NONCLUSTERED INDEX [idx_id_intake_fact]
    ON [dbo].[ALLEGATION_FACT]([ID_INTAKE_FACT] ASC);

