CREATE TABLE [dbo].[EDUCATION_DIM] (
    [ID_EDUCATION_DIM]           INT           NOT NULL,
    [CD_CHANGE_REASON]           INT           NULL,
    [TX_CHANGE_REASON]           VARCHAR (200) NULL,
    [CD_CMPLTN_STAT]             INT           NULL,
    [TX_CMPLTN_STAT]             VARCHAR (200) NULL,
    [CD_EFFORT_MADE]             INT           NULL,
    [TX_EFFORT_MADE]             VARCHAR (200) NULL,
    [CD_GRADE]                   INT           NULL,
    [TX_GRADE]                   VARCHAR (200) NULL,
    [CD_MAINTAIN_EFFORTS]        INT           NULL,
    [TX_MAINTAIN_EFFORTS]        VARCHAR (200) NULL,
    [CD_PRGM_TYPE]               INT           NULL,
    [TX_PRGM_TYPE]               VARCHAR (200) NULL,
    [CD_REASON_NOT_ENROLLED]     INT           NULL,
    [TX_REASON_NOT_ENROLLED]     VARCHAR (200) NULL,
    [CD_SCHL_TYPE]               INT           NULL,
    [TX_SCHL_TYPE]               VARCHAR (200) NULL,
    [CD_SPECIAL_EDUCATION_LEVEL] INT           NULL,
    [TX_SPECIAL_EDUCATION_LEVEL] VARCHAR (200) NULL,
    [CD_SPECIAL_REASON]          INT           NULL,
    [TX_SPECIAL_REASON]          VARCHAR (200) NULL,
    [CD_WASL_MATH]               INT           NULL,
    [TX_WASL_MATH]               VARCHAR (200) NULL,
    [CD_WASL_READING]            INT           NULL,
    [TX_WASL_READING]            VARCHAR (200) NULL,
    [CD_WASL_SCIENCE]            INT           NULL,
    [TX_WASL_SCIENCE]            VARCHAR (200) NULL,
    [CD_WASL_WRITING]            INT           NULL,
    [TX_WASL_WRITING]            VARCHAR (200) NULL,
    [DT_ROW_BEGIN]               DATETIME      NULL,
    [DT_ROW_END]                 DATETIME      NULL,
    [ID_CYCLE]                   INT           NULL,
    [IS_CURRENT]                 INT           NULL,
    CONSTRAINT [PK_ID_EDUCATION_DIM] PRIMARY KEY CLUSTERED ([ID_EDUCATION_DIM] ASC)
);

