CREATE TABLE [dbo].[EDUCATION_PLAN_DIM] (
    [ID_EDUCATION_PLAN_DIM] INT           NOT NULL,
    [CD_ACADEM_GOALS]       INT           NULL,
    [TX_ACADEM_GOALS]       VARCHAR (200) NULL,
    [CD_ACADEM_PROGRESS]    INT           NULL,
    [TX_ACADEM_PROGRESS]    VARCHAR (200) NULL,
    [CD_ED_ROLE]            INT           NULL,
    [TX_ED_ROLE]            VARCHAR (200) NULL,
    [CD_ISSUES_PROGRESS]    INT           NULL,
    [TX_ISSUES_PROGRESS]    VARCHAR (200) NULL,
    [CD_PLAN_CREDITS]       INT           NULL,
    [TX_PLAN_CREDITS]       VARCHAR (200) NULL,
    [CD_PREP_POST_ED]       INT           NULL,
    [TX_PREP_POST_ED]       VARCHAR (200) NULL,
    [CD_PROVIDED_BY]        INT           NULL,
    [TX_PROVIDED_BY]        VARCHAR (200) NULL,
    [CD_RES_ROLE]           INT           NULL,
    [TX_RES_ROLE]           VARCHAR (200) NULL,
    [CD_SERVICES_NEEDED]    INT           NULL,
    [TX_SERVICES_NEEDED]    VARCHAR (200) NULL,
    [CD_TRANSPORT]          INT           NULL,
    [TX_TRANSPORT]          VARCHAR (200) NULL,
    [DT_ROW_BEGIN]          DATETIME      NULL,
    [DT_ROW_END]            DATETIME      NULL,
    [ID_CYCLE]              INT           NULL,
    [IS_CURRENT]            INT           NULL,
    CONSTRAINT [PK_ID_EDUCATION_PLAN_DIM] PRIMARY KEY CLUSTERED ([ID_EDUCATION_PLAN_DIM] ASC)
);

