CREATE TABLE [dbo].[ELIG_EPISODE_FACT] (
    [ID_ELIG_EPISODE_FACT]  INT           NULL,
    [ID_ELIG]               INT           NULL,
    [ID_EPSD]               INT           NULL,
    [ID_CALENDAR_DIM_BEGIN] INT           NULL,
    [ID_CALENDAR_DIM_END]   INT           NULL,
    [ID_CASE_DIM]           INT           NULL,
    [ID_PEOPLE_DIM_CHILD]   INT           NULL,
    [CD_ELIG]               CHAR (1)      NULL,
    [TX_ELIG]               VARCHAR (200) NULL,
    [FL_APPLICABLE]         TINYINT       NULL,
    [FL_LCNS_VRFD]          TINYINT       NULL,
    [FL_REIMB]              TINYINT       NULL,
    CONSTRAINT [fk_ELIG_EPISODE_FACT_ID_CALENDAR_DIM_BEGIN] FOREIGN KEY ([ID_CALENDAR_DIM_BEGIN]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_ELIG_EPISODE_FACT_ID_CALENDAR_DIM_END] FOREIGN KEY ([ID_CALENDAR_DIM_END]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_ELIG_EPISODE_FACT_ID_CASE_DIM] FOREIGN KEY ([ID_CASE_DIM]) REFERENCES [dbo].[CASE_DIM] ([ID_CASE_DIM]),
    CONSTRAINT [fk_ELIG_EPISODE_FACT_ID_PEOPLE_DIM_CHILD] FOREIGN KEY ([ID_PEOPLE_DIM_CHILD]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM])
);

