CREATE TABLE [dbo].[ELIGIBILITY_STATUS_DIM] (
    [ID_ELIGIBILITY_STATUS_DIM] INT           NOT NULL,
    [CD_ELIGIBILITY_STATUS]     INT           NULL,
    [TX_ELIGIBILITY_STATUS]     VARCHAR (200) NULL,
    [DT_ROW_BEGIN]              DATETIME      NULL,
    [DT_ROW_END]                DATETIME      NULL,
    [ID_CYCLE]                  INT           NULL,
    [IS_CURRENT]                INT           NULL,
    CONSTRAINT [PK_ELIGIBILITY_STATUS_DIM] PRIMARY KEY CLUSTERED ([ID_ELIGIBILITY_STATUS_DIM] ASC)
);

