CREATE TABLE [dbo].[INDEPENDENT_LIVING_FACT] (
    [ID_INDEPENDENT_LIVING_FACT]              INT NOT NULL,
    [ID_INDEPENDENT_LIVING]                   INT NULL,
    [ID_PRSN]                                 INT NULL,
    [ID_CALENDAR_DIM_ANTICIPATED_OUT_CARE]    INT NULL,
    [ID_CALENDAR_DIM_BEGAN]                   INT NULL,
    [ID_CALENDAR_DIM_IL_PLAN_COMPLETED]       INT NULL,
    [ID_CALENDAR_DIM_INITIAL_IL_REFERRAL]     INT NULL,
    [ID_CALENDAR_DIM_REFERRED]                INT NULL,
    [ID_CALENDAR_DIM_YOUTH_NOT_PARTICIPATING] INT NULL,
    [ID_PEOPLE_DIM]                           INT NULL,
    [FL_YOUTH_REFERRED]                       INT NULL,
    [FL_YOUTH_RECEIVING]                      INT NULL,
    [FL_YOUTH_NOT_PARTICIPATING]              INT NULL,
    PRIMARY KEY CLUSTERED ([ID_INDEPENDENT_LIVING_FACT] ASC),
    CONSTRAINT [fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_ANTICIPATED_OUT_CARE] FOREIGN KEY ([ID_CALENDAR_DIM_ANTICIPATED_OUT_CARE]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_BEGAN] FOREIGN KEY ([ID_CALENDAR_DIM_BEGAN]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_IL_PLAN_COMPLETED] FOREIGN KEY ([ID_CALENDAR_DIM_IL_PLAN_COMPLETED]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_INITIAL_IL_REFERRAL] FOREIGN KEY ([ID_CALENDAR_DIM_INITIAL_IL_REFERRAL]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_REFERRED] FOREIGN KEY ([ID_CALENDAR_DIM_REFERRED]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_YOUTH_NOT_PARTICIPATING] FOREIGN KEY ([ID_CALENDAR_DIM_YOUTH_NOT_PARTICIPATING]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_INDEPENDENT_LIVING_FACT_ID_PEOPLE_DIM] FOREIGN KEY ([ID_PEOPLE_DIM]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM])
);

