CREATE TABLE [dbo].[INTAKE_ATTRIBUTE_DIM] (
    [ID_INTAKE_ATTRIBUTE_DIM]              INT           NOT NULL,
    [ID_ACCESS_REPORT]                     INT           NULL,
    [CD_ALLEGATION_ABUSE]                  CHAR (1)      NULL,
    [TX_ALLEGATION_ABUSE]                  VARCHAR (200) NULL,
    [CD_BEHAVIORAL_PROBLEMS]               CHAR (1)      NULL,
    [TX_BEHAVIORAL_PROBLEMS]               VARCHAR (200) NULL,
    [CD_BENEFIT_TREATMENT]                 CHAR (1)      NULL,
    [TX_BENEFIT_TREATMENT]                 VARCHAR (200) NULL,
    [CD_CHILD_ASLTD_IN_DOMESTIC_VIOLENCE]  INT           NULL,
    [TX_CHILD_ASLTD_IN_DOMESTIC_VIOLENCE]  VARCHAR (200) NULL,
    [CD_CHRONICITY]                        CHAR (1)      NULL,
    [TX_CHRONICITY]                        VARCHAR (200) NULL,
    [CD_COMPLAINTS_HYGIENE]                CHAR (1)      NULL,
    [TX_COMPLAINTS_HYGIENE]                VARCHAR (200) NULL,
    [CD_CONTACT_OTHERS]                    INT           NULL,
    [TX_CONTACT_OTHERS]                    VARCHAR (200) NULL,
    [TX_CPS_SPVR_RSN]                      VARCHAR (200) NULL,
    [CD_DCF_WRK_INV]                       CHAR (1)      NULL,
    [TX_DCF_WRK_INV]                       VARCHAR (200) NULL,
    [CD_DEVELOPMENTAL_DISABILITY]          CHAR (1)      NULL,
    [TX_DEVELOPMENTAL_DISABILITY]          VARCHAR (200) NULL,
    [CD_DNGR_TO_CHLD_IN_DOMESTIC_VIOLENCE] INT           NULL,
    [TX_DNGR_TO_CHLD_IN_DOMESTIC_VIOLENCE] VARCHAR (200) NULL,
    [CD_DRUG_ABUSE]                        CHAR (1)      NULL,
    [TX_DRUG_ABUSE]                        VARCHAR (200) NULL,
    [CD_DSCN_OVERRIDE]                     INT           NULL,
    [TX_DSCN_OVERRIDE]                     VARCHAR (200) NULL,
    [CD_FAILURE_BASIC_NEEDS]               CHAR (1)      NULL,
    [TX_FAILURE_BASIC_NEEDS]               VARCHAR (200) NULL,
    [CD_FAILURE_CLOTHING]                  CHAR (1)      NULL,
    [TX_FAILURE_CLOTHING]                  VARCHAR (200) NULL,
    [CD_FAILURE_SUPERVISE]                 CHAR (1)      NULL,
    [TX_FAILURE_SUPERVISE]                 VARCHAR (200) NULL,
    [CD_FAILURE_TREATMENT]                 CHAR (1)      NULL,
    [TX_FAILURE_TREATMENT]                 VARCHAR (200) NULL,
    [CD_FEAR_AFRAID]                       CHAR (1)      NULL,
    [TX_FEAR_AFRAID]                       VARCHAR (200) NULL,
    [CD_HAZARDOUS_CONDITIONS]              CHAR (1)      NULL,
    [TX_HAZARDOUS_CONDITIONS]              VARCHAR (200) NULL,
    [CD_IMMEDIATE_CPS_RESPONSE]            CHAR (1)      NULL,
    [TX_IMMEDIATE_CPS_RESPONSE]            VARCHAR (200) NULL,
    [CD_IMMEDIATE_MEDICAL]                 CHAR (1)      NULL,
    [TX_IMMEDIATE_MEDICAL]                 VARCHAR (200) NULL,
    [CD_INDIAN_RESERVATION]                INT           NULL,
    [TX_INDIAN_RESERVATION]                VARCHAR (200) NULL,
    [CD_LANG]                              INT           NULL,
    [TX_LANG]                              VARCHAR (200) NULL,
    [CD_LOCO_PARENTIS]                     INT           NULL,
    [TX_LOCO_PARENTIS]                     VARCHAR (200) NULL,
    [CD_MEDICAL_NEGLECT]                   CHAR (1)      NULL,
    [TX_MEDICAL_NEGLECT]                   VARCHAR (200) NULL,
    [CD_MEET_WAC]                          INT           NULL,
    [TX_MEET_WAC]                          VARCHAR (200) NULL,
    [CD_MEMBER]                            INT           NULL,
    [TX_MEMBER]                            VARCHAR (200) NULL,
    [CD_MTHD]                              INT           NULL,
    [TX_MTHD]                              VARCHAR (200) NULL,
    [CD_NATIVE]                            INT           NULL,
    [TX_NATIVE]                            VARCHAR (200) NULL,
    [CD_OVERRIDE_REASON]                   INT           NULL,
    [TX_OVERRIDE_REASON]                   VARCHAR (200) NULL,
    [CD_PHYSICAL_HARM]                     CHAR (1)      NULL,
    [TX_PHYSICAL_HARM]                     VARCHAR (200) NULL,
    [CD_PHYSICAL_SEXUAL_ABUSE]             CHAR (1)      NULL,
    [TX_PHYSICAL_SEXUAL_ABUSE]             VARCHAR (200) NULL,
    [CD_POOR_JUDGMENT]                     CHAR (1)      NULL,
    [TX_POOR_JUDGMENT]                     VARCHAR (200) NULL,
    [CD_PREVIOUS_FOUNDED]                  CHAR (1)      NULL,
    [TX_PREVIOUS_FOUNDED]                  VARCHAR (200) NULL,
    [CD_PRNT_KILLED_BY_PERPETRATOR]        INT           NULL,
    [TX_PRNT_KILLED_BY_PERPETRATOR]        VARCHAR (200) NULL,
    [CD_RPTR_DSCR]                         INT           NULL,
    [TX_RPTR_DSCR]                         VARCHAR (200) NULL,
    [CD_RTM_DSGNTN]                        INT           NULL,
    [TX_RTM_DSGNTN]                        VARCHAR (200) NULL,
    [CD_SERIOUS_INJURIES]                  CHAR (1)      NULL,
    [TX_SERIOUS_INJURIES]                  VARCHAR (200) NULL,
    [CD_SPVR_RSN]                          INT           NULL,
    [TX_SPVR_RSN]                          VARCHAR (200) NULL,
    [CD_THREAT_LIFE]                       CHAR (1)      NULL,
    [TX_THREAT_LIFE]                       VARCHAR (200) NULL,
    [CD_THREAT_PHSCL_FRC_AGNST_ADLT]       INT           NULL,
    [TX_THREAT_PHSCL_FRC_AGNST_ADLT]       VARCHAR (200) NULL,
    [CD_UNDER_AGE]                         INT           NULL,
    [TX_UNDER_AGE]                         VARCHAR (200) NULL,
    [CD_UNREALISTIC_EXPECTATION]           CHAR (1)      NULL,
    [TX_UNREALISTIC_EXPECTATION]           VARCHAR (200) NULL,
    [CD_WARD_TRIBAL_COURT]                 INT           NULL,
    [TX_WARD_TRIBAL_COURT]                 VARCHAR (200) NULL,
    [CD_WRKR_RSN]                          INT           NULL,
    [TX_WRKR_RSN]                          VARCHAR (200) NULL,
    [FL_AFTER_HOURS]                       CHAR (1)      NULL,
    [FL_CIA]                               CHAR (1)      NULL,
    [FL_EFFS]                              CHAR (1)      NULL,
    [FL_INTERP]                            CHAR (1)      NULL,
    [FL_INVS]                              CHAR (1)      NULL,
    [FL_MNDREP]                            CHAR (1)      NULL,
    [FL_NTC_GEN]                           CHAR (1)      NULL,
    [FL_OTHR]                              CHAR (1)      NULL,
    [FL_PCKT]                              CHAR (1)      NULL,
    [FL_POLICE]                            CHAR (1)      NULL,
    [FL_PRVD_ASSOCIATED]                   CHAR (1)      NULL,
    [FL_REFERRER_REQ_CONFIDENTIALITY]      CHAR (1)      NULL,
    [FL_RESPONSE_COMPLETE]                 CHAR (1)      NULL,
    [FL_RPT_ADDRSS]                        CHAR (1)      NULL,
    [FL_RSPNS_DSCN_OVERRIDE]               CHAR (1)      NULL,
    [FL_RTM_TIME]                          CHAR (1)      NULL,
    [FL_SER_INCD_RPT_GNRTD]                CHAR (1)      NULL,
    [FL_WRKR_SFTY_CONCERNS]                CHAR (1)      NULL,
    [DT_ROW_BEGIN]                         DATETIME      NULL,
    [DT_ROW_END]                           DATETIME      NULL,
    [ID_CYCLE]                             INT           NULL,
    [IS_CURRENT]                           INT           NULL,
    [FL_DELETED]                           CHAR (1)      NULL,
    [FL_EXPUNGED]                          CHAR (1)      NULL,
    [CD_INTAKE_TYPE_DERIVED]               INT           NULL,
    [TX_INTAKE_TYPE_DERIVED]               VARCHAR (200) NULL,
    CONSTRAINT [PK_ID_INTAKE_ATTRIBUTE_DIM] PRIMARY KEY CLUSTERED ([ID_INTAKE_ATTRIBUTE_DIM] ASC)
);

