CREATE TABLE [dbo].[INTAKE_SERVICE_BRIDGE_FACT] (
    [ID_INTAKE_SERVICE_BRIDGE_FACT] INT NOT NULL,
    [ID_INTAKE_FACT]                INT NULL,
    [ID_SERVICE_REFERRAL_DIM]       INT NULL,
    CONSTRAINT [PK_ID_INTAKE_SERVICE_BRIDGE_FACT] PRIMARY KEY CLUSTERED ([ID_INTAKE_SERVICE_BRIDGE_FACT] ASC),
    CONSTRAINT [fk_INTAKE_SERVICE_BRIDGE_FACT_ID_INTAKE_FACT] FOREIGN KEY ([ID_INTAKE_FACT]) REFERENCES [dbo].[INTAKE_FACT] ([ID_INTAKE_FACT]),
    CONSTRAINT [fk_INTAKE_SERVICE_BRIDGE_FACT_ID_SERVICE_REFERRAL_DIM] FOREIGN KEY ([ID_SERVICE_REFERRAL_DIM]) REFERENCES [dbo].[SERVICE_REFERRAL_DIM] ([ID_SERVICE_REFERRAL_DIM])
);

