CREATE TABLE [dbo].[INTAKE_PARTICIPANT_FACT] (
    [ID_INTAKE_PARTICIPANT_FACT]      INT           NOT NULL,
    [CD_INTK_TYPE]                    INT           NULL,
    [ID_INTK]                         INT           NULL,
    [TS_CR]                           DATETIME      NULL,
    [ID_INTAKE_FACT]                  INT           NULL,
    [ID_INTAKE_PARTICIPANT_ROLES_DIM] INT           NULL,
    [ID_PEOPLE_DIM_CHILD]             INT           NULL,
    [TX_INTK_TYPE]                    VARCHAR (200) NULL,
    [FL_EXPUNGED]                     VARCHAR (1)   NULL,
    [ID_PRSN_CHILD]                   INT           NULL,
    CONSTRAINT [pk_id_INTAKE_PARTICIPANT_FACT] PRIMARY KEY CLUSTERED ([ID_INTAKE_PARTICIPANT_FACT] ASC),
    CONSTRAINT [fk_INTAKE_PARTICIPANT_FACT_ID_INTAKE_PARTICIPANT_ROLES_DIM] FOREIGN KEY ([ID_INTAKE_PARTICIPANT_ROLES_DIM]) REFERENCES [dbo].[INTAKE_PARTICIPANT_ROLES_DIM] ([ID_INTAKE_PARTICIPANT_ROLES_DIM]),
    CONSTRAINT [fk_INTAKE_PARTICIPANT_FACT_ID_PEOPLE_DIM_CHILD] FOREIGN KEY ([ID_PEOPLE_DIM_CHILD]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM])
);


GO
CREATE NONCLUSTERED INDEX [idx_id_intake_fact_incl_roles_dim_child]
    ON [dbo].[INTAKE_PARTICIPANT_FACT]([ID_INTAKE_FACT] ASC)
    INCLUDE([ID_INTAKE_PARTICIPANT_ROLES_DIM], [ID_PEOPLE_DIM_CHILD]);

