CREATE TABLE [dbo].[LEGAL_FACT] (
    [ID_LEGAL_FACT]                            INT      NOT NULL,
    [ID_CRT_DISP]                              INT      NULL,
    [ID_CALENDAR_DIM_EFFECTIVE]                INT      NULL,
    [ID_CALENDAR_DIM_HEARING]                  INT      NULL,
    [ID_CASE_DIM]                              INT      NULL,
    [ID_LEGAL_ACTION_DIM]                      INT      NULL,
    [ID_LEGAL_JURISDICTION_DIM]                INT      NULL,
    [ID_LEGAL_RESULT_DIM]                      INT      NULL,
    [ID_LEGAL_STATUS_DIM]                      INT      NULL,
    [ID_PEOPLE_DIM]                            INT      NULL,
    [ID_WORKER_DIM]                            INT      NULL,
    [FL_REASONABLE_EFFORT_FINALIZE_PERMANENCY] TINYINT  NULL,
    [FL_REASONABLE_EFFORT_PREVENT_REMOVAL]     TINYINT  NULL,
    [TS_UP]                                    DATETIME NULL,
    [ID_PRSN]                                  INT      NULL,
    [ID_CASE]                                  INT      NULL,
    CONSTRAINT [PK_ID_LEGAL_FACT] PRIMARY KEY CLUSTERED ([ID_LEGAL_FACT] ASC),
    CONSTRAINT [fk_LEGAL_FACT_ID_CALENDAR_DIM_EFFECTIVE] FOREIGN KEY ([ID_CALENDAR_DIM_EFFECTIVE]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_LEGAL_FACT_ID_CALENDAR_DIM_HEARING] FOREIGN KEY ([ID_CALENDAR_DIM_HEARING]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_LEGAL_FACT_ID_CASE_DIM] FOREIGN KEY ([ID_CASE_DIM]) REFERENCES [dbo].[CASE_DIM] ([ID_CASE_DIM]),
    CONSTRAINT [fk_LEGAL_FACT_ID_LEGAL_ACTION_DIM] FOREIGN KEY ([ID_LEGAL_ACTION_DIM]) REFERENCES [dbo].[LEGAL_ACTION_DIM] ([ID_LEGAL_ACTION_DIM]),
    CONSTRAINT [fk_LEGAL_FACT_ID_LEGAL_JURISDICTION_DIM] FOREIGN KEY ([ID_LEGAL_JURISDICTION_DIM]) REFERENCES [dbo].[LEGAL_JURISDICTION_DIM] ([ID_LEGAL_JURISDICTION_DIM]),
    CONSTRAINT [fk_LEGAL_FACT_ID_LEGAL_RESULT_DIM] FOREIGN KEY ([ID_LEGAL_RESULT_DIM]) REFERENCES [dbo].[LEGAL_RESULT_DIM] ([ID_LEGAL_RESULT_DIM]),
    CONSTRAINT [fk_LEGAL_FACT_ID_LEGAL_STATUS_DIM] FOREIGN KEY ([ID_LEGAL_STATUS_DIM]) REFERENCES [dbo].[LEGAL_STATUS_DIM] ([ID_LEGAL_STATUS_DIM]),
    CONSTRAINT [fk_LEGAL_FACT_ID_PEOPLE_DIM] FOREIGN KEY ([ID_PEOPLE_DIM]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM]),
    CONSTRAINT [fk_LEGAL_FACT_ID_WORKER_DIM] FOREIGN KEY ([ID_WORKER_DIM]) REFERENCES [dbo].[WORKER_DIM] ([ID_WORKER_DIM])
);


GO
CREATE NONCLUSTERED INDEX [idx_id_legal_result_dim]
    ON [dbo].[LEGAL_FACT]([ID_LEGAL_RESULT_DIM] ASC)
    INCLUDE([ID_CALENDAR_DIM_EFFECTIVE], [ID_LEGAL_ACTION_DIM], [ID_LEGAL_STATUS_DIM], [ID_PRSN]);


GO
CREATE NONCLUSTERED INDEX [idx_id_prsn_legal_fact_incl_eff_hearing_status]
    ON [dbo].[LEGAL_FACT]([ID_PRSN] ASC)
    INCLUDE([ID_CALENDAR_DIM_EFFECTIVE], [ID_CALENDAR_DIM_HEARING], [ID_LEGAL_STATUS_DIM]);


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20140326-102159]
    ON [dbo].[LEGAL_FACT]([ID_LEGAL_ACTION_DIM] ASC, [ID_LEGAL_RESULT_DIM] ASC, [ID_LEGAL_STATUS_DIM] ASC)
    INCLUDE([ID_CALENDAR_DIM_EFFECTIVE], [ID_CALENDAR_DIM_HEARING]);


GO
CREATE NONCLUSTERED INDEX [idx_legal_fact_ID_LEGAL_RESULT_DIM_INCL]
    ON [dbo].[LEGAL_FACT]([ID_LEGAL_RESULT_DIM] ASC)
    INCLUDE([ID_CALENDAR_DIM_EFFECTIVE], [ID_CALENDAR_DIM_HEARING], [ID_LEGAL_ACTION_DIM], [ID_LEGAL_STATUS_DIM], [ID_PRSN], [ID_CASE]);


GO
CREATE NONCLUSTERED INDEX [idx_legal_fact_id_legal_result_dim]
    ON [dbo].[LEGAL_FACT]([ID_LEGAL_RESULT_DIM] ASC)
    INCLUDE([ID_LEGAL_FACT], [ID_CALENDAR_DIM_EFFECTIVE], [ID_LEGAL_JURISDICTION_DIM], [ID_PRSN]);

