CREATE TABLE [dbo].[LEGAL_TPR_REFERRAL_FACT] (
    [ID_LEGAL_TPR_REFERRAL_FACT]             INT NOT NULL,
    [ID_LEGAL_TPR_REFERRAL]                  INT NULL,
    [ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT] INT NULL,
    [ID_CALENDAR_DIM_TPR_REFERRAL]           INT NULL,
    [ID_RELATIONSHIP_DIM_TPR]                INT NULL,
    [ID_PEOPLE_DIM_TPR_PARENT]               INT NULL,
    [ID_PRSN_TPR_PARENT]                     INT NULL,
    CONSTRAINT [pk_ID_LEGAL_TPR_REFERRAL_FACT] PRIMARY KEY CLUSTERED ([ID_LEGAL_TPR_REFERRAL_FACT] ASC),
    CONSTRAINT [fk_LEGAL_TPR_REFERRAL_FACT_ID_CALENDAR_DIM_TPR_REFERRAL] FOREIGN KEY ([ID_CALENDAR_DIM_TPR_REFERRAL]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_LEGAL_TPR_REFERRAL_FACT_ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT] FOREIGN KEY ([ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT]) REFERENCES [dbo].[LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT] ([ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT]),
    CONSTRAINT [fk_LEGAL_TPR_REFERRAL_FACT_ID_PEOPLE_DIM_TPR_PARENT] FOREIGN KEY ([ID_PEOPLE_DIM_TPR_PARENT]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM]),
    CONSTRAINT [fk_LEGAL_TPR_REFERRAL_FACT_ID_RELATIONSHIP_DIM_TPR] FOREIGN KEY ([ID_RELATIONSHIP_DIM_TPR]) REFERENCES [dbo].[RELATIONSHIP_DIM] ([ID_RELATIONSHIP_DIM])
);

