CREATE TABLE [dbo].[MEETING_TYPE_DIM] (
    [ID_MEETING_TYPE_DIM] NVARCHAR (50) NULL,
    [CD_TYPE]             NVARCHAR (50) NULL,
    [TX_TYPE]             NVARCHAR (50) NULL,
    [DT_ROW_BEGIN]        NVARCHAR (50) NULL,
    [DT_ROW_END]          NVARCHAR (50) NULL,
    [ID_CYCLE]            NVARCHAR (50) NULL,
    [IS_CURRENT]          NVARCHAR (50) NULL
);

