CREATE TABLE [dbo].[PAYMENT_DETAIL_DIM] (
    [ID_PAYMENT_DETAIL_DIM] INT         NOT NULL,
    [TX_ALLOCATION]         VARCHAR (4) NULL,
    [TX_APPROPRIATION]      VARCHAR (3) NULL,
    [TX_FUND]               VARCHAR (3) NULL,
    [TX_PROGRAM_INDEX]      VARCHAR (5) NULL,
    [TX_SUB_OBJECT]         VARCHAR (2) NULL,
    [TX_SUB_SUB_OBJECT]     VARCHAR (4) NULL,
    [SERVICE_YEAR_MONTH]    INT         NULL,
    [DT_ROW_BEGIN]          DATETIME    NULL,
    [DT_ROW_END]            DATETIME    NULL,
    [ID_CYCLE]              INT         NULL,
    [IS_CURRENT]            INT         NULL,
    CONSTRAINT [PK_ID_PAYMENT_DETAIL_DIM] PRIMARY KEY CLUSTERED ([ID_PAYMENT_DETAIL_DIM] ASC)
);

