CREATE TABLE [dbo].[PERMANENCY_FACT] (
    [ID_PERMANENCY_FACT]            INT NOT NULL,
    [ID_CRT_DISP]                   INT NULL,
    [ID_CALENDAR_DIM_HEARING]       INT NULL,
    [ID_CALENDAR_DIM_ORDER_ENTERED] INT NULL,
    [ID_CASE_DIM]                   INT NULL,
    [ID_LEGAL_JURISDICTION_DIM]     INT NULL,
    [ID_LEGAL_STATUS_DIM]           INT NULL,
    [ID_PEOPLE_DIM]                 INT NULL,
    [ID_PERMANENCY_PLAN_DIM]        INT NULL,
    [CHILD_AGE]                     INT NULL,
    [ID_PRSN]                       INT NULL,
    [ID_CASE]                       INT NULL,
    CONSTRAINT [PK_ID_PERMANENCY_FACT] PRIMARY KEY CLUSTERED ([ID_PERMANENCY_FACT] ASC),
    CONSTRAINT [fk_PERMANENCY_FACT_ID_CALENDAR_DIM_HEARING] FOREIGN KEY ([ID_CALENDAR_DIM_HEARING]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_PERMANENCY_FACT_ID_CALENDAR_DIM_ORDER_ENTERED] FOREIGN KEY ([ID_CALENDAR_DIM_ORDER_ENTERED]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_PERMANENCY_FACT_ID_CASE_DIM] FOREIGN KEY ([ID_CASE_DIM]) REFERENCES [dbo].[CASE_DIM] ([ID_CASE_DIM]),
    CONSTRAINT [fk_PERMANENCY_FACT_ID_LEGAL_JURISDICTION_DIM] FOREIGN KEY ([ID_LEGAL_JURISDICTION_DIM]) REFERENCES [dbo].[LEGAL_JURISDICTION_DIM] ([ID_LEGAL_JURISDICTION_DIM]),
    CONSTRAINT [fk_PERMANENCY_FACT_ID_LEGAL_STATUS_DIM] FOREIGN KEY ([ID_LEGAL_STATUS_DIM]) REFERENCES [dbo].[LEGAL_STATUS_DIM] ([ID_LEGAL_STATUS_DIM]),
    CONSTRAINT [fk_PERMANENCY_FACT_ID_PEOPLE_DIM] FOREIGN KEY ([ID_PEOPLE_DIM]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM]),
    CONSTRAINT [fk_PERMANENCY_FACT_ID_PERMANENCY_PLAN_DIM] FOREIGN KEY ([ID_PERMANENCY_PLAN_DIM]) REFERENCES [dbo].[PERMANENCY_PLAN_DIM] ([ID_PERMANENCY_PLAN_DIM])
);

