CREATE TABLE [dbo].[PLACEMENT_CARE_AUTH_FACT] (
    [ID_PLACEMENT_CARE_AUTH_FACT] INT     NOT NULL,
    [ID_PLCMNT_CARE_AUTHORITY]    INT     NULL,
    [ID_CALENDAR_DIM_BEGIN]       INT     NULL,
    [ID_CALENDAR_DIM_END]         INT     NULL,
    [ID_PEOPLE_DIM]               INT     NULL,
    [ID_PLACEMENT_CARE_AUTH_DIM]  INT     NULL,
    [FL_COMPLETE]                 TINYINT NULL,
    [FL_VOID]                     TINYINT NULL,
    [ID_PRSN]                     INT     NULL,
    CONSTRAINT [PK_ID_PLACEMENT_CARE_AUTH_FACT] PRIMARY KEY CLUSTERED ([ID_PLACEMENT_CARE_AUTH_FACT] ASC),
    CONSTRAINT [fk_PLACEMENT_CARE_AUTH_FACT_ID_CALENDAR_DIM_BEGIN] FOREIGN KEY ([ID_CALENDAR_DIM_BEGIN]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_PLACEMENT_CARE_AUTH_FACT_ID_CALENDAR_DIM_END] FOREIGN KEY ([ID_CALENDAR_DIM_END]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_PLACEMENT_CARE_AUTH_FACT_ID_PEOPLE_DIM] FOREIGN KEY ([ID_PEOPLE_DIM]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM]),
    CONSTRAINT [fk_PLACEMENT_CARE_AUTH_FACT_ID_PLACEMENT_CARE_AUTH_DIM] FOREIGN KEY ([ID_PLACEMENT_CARE_AUTH_DIM]) REFERENCES [dbo].[PLACEMENT_CARE_AUTH_DIM] ([ID_PLACEMENT_CARE_AUTH_DIM])
);

