CREATE TABLE [dbo].[PRIMARY_ASSIGNMENT_FACT] (
    [ID_PRIMARY_ASSIGNMENT_FACT] INT      NOT NULL,
    [ID_CASE]                    INT      NULL,
    [ID_WORKER]                  INT      NULL,
    [ID_CALENDAR_DIM_BEGIN]      INT      NULL,
    [ID_CALENDAR_DIM_END]        INT      NULL,
    [ID_CASE_DIM]                INT      NULL,
    [ID_LOCATION_DIM]            INT      NULL,
    [ID_WORKER_DIM]              INT      NULL,
    [ID_WORKER_DIM_CURRENT]      INT      NULL,
    [CD_ASGN_ROLE]               INT      NULL,
    [DT_BEGIN]                   DATETIME NULL,
    [DT_END]                     DATETIME NULL,
    [FL_EXPUNGED]                CHAR (1) NULL,
    CONSTRAINT [PK_ID_PRIMARY_ASSIGNMENT_FACT] PRIMARY KEY CLUSTERED ([ID_PRIMARY_ASSIGNMENT_FACT] ASC),
    CONSTRAINT [fk_PRIMARY_ASSIGNMENT_FACT_ID_CALENDAR_DIM_BEGIN] FOREIGN KEY ([ID_CALENDAR_DIM_BEGIN]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_PRIMARY_ASSIGNMENT_FACT_ID_CALENDAR_DIM_END] FOREIGN KEY ([ID_CALENDAR_DIM_END]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_PRIMARY_ASSIGNMENT_FACT_ID_CASE_DIM] FOREIGN KEY ([ID_CASE_DIM]) REFERENCES [dbo].[CASE_DIM] ([ID_CASE_DIM]),
    CONSTRAINT [fk_PRIMARY_ASSIGNMENT_FACT_ID_LOCATION_DIM] FOREIGN KEY ([ID_LOCATION_DIM]) REFERENCES [dbo].[LOCATION_DIM] ([ID_LOCATION_DIM]),
    CONSTRAINT [fk_PRIMARY_ASSIGNMENT_FACT_ID_WORKER_DIM] FOREIGN KEY ([ID_WORKER_DIM]) REFERENCES [dbo].[WORKER_DIM] ([ID_WORKER_DIM]),
    CONSTRAINT [fk_PRIMARY_ASSIGNMENT_FACT_ID_WORKER_DIM_CURRENT] FOREIGN KEY ([ID_WORKER_DIM_CURRENT]) REFERENCES [dbo].[WORKER_DIM] ([ID_WORKER_DIM])
);

