CREATE TABLE [dbo].[PROVIDER_PART_FACT] (
    [ID_PROVIDER_PART_FACT]     INT           NOT NULL,
    [ID_BSNS]                   INT           NULL,
    [ID_PRSN]                   INT           NULL,
    [ID_PRVD_ORG]               INT           NULL,
    [ID_CALENDAR_DIM_END]       INT           NULL,
    [ID_CALENDAR_DIM_START]     INT           NULL,
    [ID_PEOPLE_DIM]             INT           NULL,
    [ID_PROVIDER_DIM_CAREGIVER] INT           NULL,
    [CD_ROLE]                   INT           NULL,
    [TX_ROLE]                   VARCHAR (200) NULL,
    [CD_RSN_END]                INT           NULL,
    [TX_RSN_END]                VARCHAR (200) NULL,
    [CD_RSN_START]              INT           NULL,
    [TX_RSN_START]              VARCHAR (200) NULL,
    [TS_CR]                     DATETIME      NULL,
    CONSTRAINT [PK_ID_PROVIDER_PART_FACT] PRIMARY KEY CLUSTERED ([ID_PROVIDER_PART_FACT] ASC),
    CONSTRAINT [fk_PROVIDER_PART_FACT_ID_CALENDAR_DIM_END] FOREIGN KEY ([ID_CALENDAR_DIM_END]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_PROVIDER_PART_FACT_ID_CALENDAR_DIM_START] FOREIGN KEY ([ID_CALENDAR_DIM_START]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_PROVIDER_PART_FACT_ID_PEOPLE_DIM] FOREIGN KEY ([ID_PEOPLE_DIM]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM]),
    CONSTRAINT [fk_PROVIDER_PART_FACT_ID_PROVIDER_DIM_CAREGIVER] FOREIGN KEY ([ID_PROVIDER_DIM_CAREGIVER]) REFERENCES [dbo].[PROVIDER_DIM] ([ID_PROVIDER_DIM])
);

