CREATE TABLE [dbo].[PROVIDER_SERVICE_LICENSE_FACT] (
    [ID_PROVIDER_SERVICE_LICENSE_FACT] INT NOT NULL,
    [ID_BSNS]                          INT NULL,
    [ID_LCNS]                          INT NULL,
    [ID_PRVD_ORG]                      INT NULL,
    [ID_LICENSE_FACT]                  INT NULL,
    [ID_PROVIDER_DIM]                  INT NULL,
    [ID_SERVICE_TYPE_DIM]              INT NULL,
    [CD_SRVC]                          INT NULL,
    [QT_LCNS_CAP]                      INT NULL,
    CONSTRAINT [PK_ID_PROVIDER_SERVICE_LICENSE_FACT] PRIMARY KEY CLUSTERED ([ID_PROVIDER_SERVICE_LICENSE_FACT] ASC),
    CONSTRAINT [fk_PROVIDER_SERVICE_LICENSE_FACT_ID_LICENSE_FACT] FOREIGN KEY ([ID_LICENSE_FACT]) REFERENCES [dbo].[LICENSE_FACT] ([ID_LICENSE_FACT]),
    CONSTRAINT [fk_PROVIDER_SERVICE_LICENSE_FACT_ID_PROVIDER_DIM] FOREIGN KEY ([ID_PROVIDER_DIM]) REFERENCES [dbo].[PROVIDER_DIM] ([ID_PROVIDER_DIM]),
    CONSTRAINT [fk_PROVIDER_SERVICE_LICENSE_FACT_ID_SERVICE_TYPE_DIM] FOREIGN KEY ([ID_SERVICE_TYPE_DIM]) REFERENCES [dbo].[SERVICE_TYPE_DIM] ([ID_SERVICE_TYPE_DIM])
);

