CREATE TABLE [dbo].[qa_dcfs_cnt_null] (
    [qry_type]                               INT      NOT NULL,
    [date_type]                              INT      NULL,
    [start_date]                             DATETIME NULL,
    [bin_dep_cd]                             INT      NOT NULL,
    [max_bin_los_cd]                         INT      NULL,
    [bin_placement_cd]                       INT      NULL,
    [bin_ihs_svc_cd]                         INT      NULL,
    [cd_reporter_type]                       INT      NOT NULL,
    [fl_cps_invs]                            INT      NOT NULL,
    [fl_cfws]                                INT      NOT NULL,
    [fl_risk_only]                           INT      NOT NULL,
    [fl_alternate_intervention]              INT      NOT NULL,
    [fl_frs]                                 INT      NOT NULL,
    [fl_phys_abuse]                          INT      NOT NULL,
    [fl_sexual_abuse]                        INT      NOT NULL,
    [fl_neglect]                             INT      NOT NULL,
    [fl_any_legal]                           INT      NOT NULL,
    [fl_founded_phys_abuse]                  INT      NOT NULL,
    [fl_founded_sexual_abuse]                INT      NOT NULL,
    [fl_founded_neglect]                     INT      NOT NULL,
    [fl_found_any_legal]                     INT      NOT NULL,
    [fl_family_focused_services]             INT      NOT NULL,
    [fl_child_care]                          INT      NOT NULL,
    [fl_therapeutic_services]                INT      NOT NULL,
    [fl_mh_services]                         INT      NOT NULL,
    [fl_receiving_care]                      INT      NOT NULL,
    [fl_family_home_placements]              INT      NOT NULL,
    [fl_behavioral_rehabiliation_services]   INT      NOT NULL,
    [fl_other_therapeutic_living_situations] INT      NOT NULL,
    [fl_specialty_adolescent_services]       INT      NOT NULL,
    [fl_respite]                             INT      NOT NULL,
    [fl_transportation]                      INT      NOT NULL,
    [fl_clothing_incidentals]                INT      NOT NULL,
    [fl_sexually_aggressive_youth]           INT      NOT NULL,
    [fl_adoption_support]                    INT      NOT NULL,
    [fl_various]                             INT      NOT NULL,
    [fl_medical]                             INT      NOT NULL,
    [fl_budget_C12]                          INT      NOT NULL,
    [fl_budget_C14]                          INT      NOT NULL,
    [fl_budget_C15]                          INT      NOT NULL,
    [fl_budget_C16]                          INT      NOT NULL,
    [fl_budget_C18]                          INT      NOT NULL,
    [fl_budget_C19]                          INT      NOT NULL,
    [fl_uncat_svc]                           INT      NOT NULL,
    [age_grouping_cd]                        INT      NULL,
    [cd_race]                                INT      NULL,
    [census_hispanic_latino_origin_cd]       INT      NULL,
    [pk_gndr]                                INT      NOT NULL,
    [init_cd_plcm_setng]                     INT      NULL,
    [long_cd_plcm_setng]                     INT      NULL,
    [county_cd]                              INT      NULL,
    [int_match_param_key]                    BIGINT   NULL,
    [cnt_ooh]                                INT      NULL,
    [cnt_entries]                            INT      NULL,
    [cnt_exits]                              INT      NULL,
    [cnt_dcfs_ooh]                           INT      NULL,
    [cnt_dcfs_entries]                       INT      NULL,
    [cnt_dcfs_exits]                         INT      NULL
);

