CREATE TABLE [dbo].[TRAINING_FACT] (
    [ID_TRAINING_FACT]                   INT      NOT NULL,
    [ID_PRSN_TRAINING]                   INT      NULL,
    [ID_CALENDAR_DIM_COMPLETION]         INT      NULL,
    [ID_CALENDAR_DIM_EXPIRATION]         INT      NULL,
    [ID_PEOPLE_DIM_TRAINING_PARTICIPANT] INT      NULL,
    [ID_TRAINING_TYPE_DIM]               INT      NULL,
    [FL_MEETS_REQUIREMENT]               INT      NULL,
    [QT_HOURS]                           INT      NULL,
    [FL_EXPUNGED]                        CHAR (1) NULL,
    [ID_PRSN]                            INT      NULL,
    PRIMARY KEY CLUSTERED ([ID_TRAINING_FACT] ASC),
    CONSTRAINT [fk_TRAINING_FACT_ID_CALENDAR_DIM_COMPLETION] FOREIGN KEY ([ID_CALENDAR_DIM_COMPLETION]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_TRAINING_FACT_ID_CALENDAR_DIM_EXPIRATION] FOREIGN KEY ([ID_CALENDAR_DIM_EXPIRATION]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_TRAINING_FACT_ID_PEOPLE_DIM_TRAINING_PARTICIPANT] FOREIGN KEY ([ID_PEOPLE_DIM_TRAINING_PARTICIPANT]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM]),
    CONSTRAINT [fk_TRAINING_FACT_ID_TRAINING_TYPE_DIM] FOREIGN KEY ([ID_TRAINING_TYPE_DIM]) REFERENCES [dbo].[TRAINING_TYPE_DIM] ([ID_TRAINING_TYPE_DIM])
);

