CREATE TABLE [dbo].[TRIBE_ATTRIBUTE_DIM] (
    [ID_TRIBE_ATTRIBUTE_DIM] INT           NOT NULL,
    [CD_PRSN_TRB_RESPONSE]   INT           NULL,
    [TX_PRSN_TRB_RESPONSE]   VARCHAR (200) NULL,
    [CD_PRSN_TRB_STATUS]     INT           NULL,
    [TX_PRSN_TRB_STATUS]     VARCHAR (200) NULL,
    [DT_ROW_BEGIN]           DATETIME      NULL,
    [DT_ROW_END]             DATETIME      NULL,
    [ID_CYCLE]               INT           NULL,
    [IS_CURRENT]             INT           NULL,
    CONSTRAINT [PK_TRIBE_ATTRIBUTE_DIM] PRIMARY KEY CLUSTERED ([ID_TRIBE_ATTRIBUTE_DIM] ASC)
);

