CREATE TABLE [dbo].[TRIBE_FACT] (
    [ID_TRIBE_FACT]           INT      NULL,
    [ID_PRSN_TRIBE]           INT      NULL,
    [ID_TRIBE]                INT      NULL,
    [ID_CALENDAR_DIM_ENTERED] INT      NULL,
    [ID_PEOPLE_DIM]           INT      NULL,
    [ID_TRIBE_ATTRIBUTE_DIM]  INT      NULL,
    [ID_TRIBE_DIM]            INT      NULL,
    [FL_EXPUNGED]             CHAR (1) NULL,
    CONSTRAINT [fk_TRIBE_FACT_ID_CALENDAR_DIM_ENTERED] FOREIGN KEY ([ID_CALENDAR_DIM_ENTERED]) REFERENCES [dbo].[CALENDAR_DIM] ([ID_CALENDAR_DIM]),
    CONSTRAINT [fk_TRIBE_FACT_ID_PEOPLE_DIM] FOREIGN KEY ([ID_PEOPLE_DIM]) REFERENCES [dbo].[PEOPLE_DIM] ([ID_PEOPLE_DIM]),
    CONSTRAINT [fk_TRIBE_FACT_ID_TRIBE_ATTRIBUTE_DIM] FOREIGN KEY ([ID_TRIBE_ATTRIBUTE_DIM]) REFERENCES [dbo].[TRIBE_ATTRIBUTE_DIM] ([ID_TRIBE_ATTRIBUTE_DIM]),
    CONSTRAINT [fk_TRIBE_FACT_ID_TRIBE_DIM] FOREIGN KEY ([ID_TRIBE_DIM]) REFERENCES [dbo].[TRIBE_DIM] ([ID_TRIBE_DIM])
);

