CREATE TABLE [prtl].[ooh_key_filter_id] (
    [key_filter_id]       BIGINT       NOT NULL,
    [bin_dep_cd]          INT          NULL,
    [bin_los_cd]          INT          NULL,
    [bin_placement_cd]    INT          NULL,
    [bin_ihs_svc_cd]      INT          NULL,
    [cd_reporter_type]    INT          NULL,
    [cd_access_type]      INT          NULL,
    [cd_allegation]       INT          NULL,
    [cd_finding]          INT          NULL,
    [cd_subctgry_poc_frc] INT          NULL,
    [cd_budget_poc_frc]   INT          NULL,
    [age_grouping_cd]     INT          NULL,
    [cd_race]             INT          NULL,
    [pk_gndr]             INT          NULL,
    [init_cd_plcm_setng]  INT          NULL,
    [long_cd_plcm_setng]  INT          NULL,
    [county_cd]           INT          NULL,
    [int_hash_key]        DECIMAL (22) NULL,
    PRIMARY KEY CLUSTERED ([key_filter_id] ASC),
    CONSTRAINT [ooh_key_filter_id_bin_dep_cd_FK] FOREIGN KEY ([bin_dep_cd]) REFERENCES [dbo].[ref_filter_dependency] ([bin_dep_cd]),
    CONSTRAINT [ooh_key_filter_id_bin_ihs_svc_cd_FK] FOREIGN KEY ([bin_ihs_svc_cd]) REFERENCES [dbo].[ref_filter_ihs_services] ([bin_ihs_svc_cd]),
    CONSTRAINT [ooh_key_filter_id_bin_los_cd_FK] FOREIGN KEY ([bin_los_cd]) REFERENCES [dbo].[ref_filter_los] ([bin_los_cd]),
    CONSTRAINT [ooh_key_filter_id_bin_placement_cd_FK] FOREIGN KEY ([bin_placement_cd]) REFERENCES [dbo].[ref_filter_nbr_placement] ([bin_placement_cd]),
    CONSTRAINT [ooh_key_filter_id_cd_access_type] FOREIGN KEY ([cd_access_type]) REFERENCES [dbo].[ref_filter_access_type] ([cd_access_type]),
    CONSTRAINT [ooh_key_filter_id_cd_allegation] FOREIGN KEY ([cd_allegation]) REFERENCES [dbo].[ref_filter_allegation] ([cd_allegation]),
    CONSTRAINT [ooh_key_filter_id_cd_budget_poc_frc] FOREIGN KEY ([cd_budget_poc_frc]) REFERENCES [dbo].[ref_service_cd_budget_poc_frc] ([cd_budget_poc_frc]),
    CONSTRAINT [ooh_key_filter_id_cd_finding] FOREIGN KEY ([cd_finding]) REFERENCES [dbo].[ref_filter_finding] ([cd_finding]),
    CONSTRAINT [ooh_key_filter_id_cd_race_FK] FOREIGN KEY ([cd_race]) REFERENCES [dbo].[ref_lookup_ethnicity_census] ([cd_race_census]),
    CONSTRAINT [ooh_key_filter_id_cd_reporter_type_FK] FOREIGN KEY ([cd_reporter_type]) REFERENCES [dbo].[ref_filter_reporter_type] ([cd_reporter_type]),
    CONSTRAINT [ooh_key_filter_id_cd_subctgry_poc_frc] FOREIGN KEY ([cd_subctgry_poc_frc]) REFERENCES [dbo].[ref_service_cd_subctgry_poc_old] ([cd_subctgry_poc_frc]),
    CONSTRAINT [ooh_key_filter_id_county_cd_FK] FOREIGN KEY ([county_cd]) REFERENCES [dbo].[ref_lookup_county] ([county_cd]),
    CONSTRAINT [ooh_key_filter_id_init_cd_plcm_setng_FK] FOREIGN KEY ([init_cd_plcm_setng]) REFERENCES [dbo].[ref_lookup_plcmnt] ([cd_plcm_setng]),
    CONSTRAINT [ooh_key_filter_id_long_cd_plcm_setng_FK] FOREIGN KEY ([long_cd_plcm_setng]) REFERENCES [dbo].[ref_lookup_plcmnt] ([cd_plcm_setng]),
    CONSTRAINT [ooh_key_filter_id_pk_gndr_FK] FOREIGN KEY ([pk_gndr]) REFERENCES [dbo].[ref_lookup_gender] ([pk_gndr])
);

