
CREATE PROCEDURE [loading].[Load_WORKER_DIM_HISTORY] 
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @HistoryRecords INT = (SELECT COUNT(*) FROM dbo.WORKER_DIM_HISTORY);

	IF @HistoryRecords = 0
	BEGIN
		INSERT dbo.WORKER_DIM_HISTORY
			(ID_WORKER_DIM, ID_PRSN, ID_PRSN_SPRV, ID_RMTS_GROUP_COORD, ID_LOCATION_DIM_WORKER, ID_WORKER_DIM_SUPERVISOR, CD_JOB_CLS, TX_JOB_CLS,
			CD_RMTS_WRKR_TYP, TX_RMTS_WRKR_TYP, CD_STAT, TX_STAT, CD_UNT, QT_WRK_MEASURE, DT_BRTH, DT_END, DT_START, DT_ROW_BEGIN, DT_ROW_END,
			ID_CYCLE, IS_CURRENT, LOAD_DATE)
		SELECT
			LWDH.ID_WORKER_DIM
			,LWDH.ID_PRSN
			,LWDH.ID_PRSN_SPRV
			,LWDH.ID_RMTS_GROUP_COORD
			,LWDH.ID_LOCATION_DIM_WORKER
			,LWDH.ID_WORKER_DIM_SUPERVISOR
			,LWDH.CD_JOB_CLS
			,LWDH.TX_JOB_CLS
			,LWDH.CD_RMTS_WRKR_TYP
			,LWDH.TX_RMTS_WRKR_TYP
			,LWDH.CD_STAT
			,LWDH.TX_STAT
			,LWDH.CD_UNT
			,LWDH.QT_WRK_MEASURE
			,LWDH.DT_BRTH
			,LWDH.DT_END
			,LWDH.DT_START
			,LWDH.DT_ROW_BEGIN
			,LWDH.DT_ROW_END
			,LWDH.ID_CYCLE
			,LWDH.IS_CURRENT
			,LWDH.LOAD_DATE
		FROM loading.WORKER_DIM_HISTORY LWDH;

		UPDATE WDH
		SET ID_WORKER_DIM_HISTORY_SUPERVISOR = WDHS.ID_WORKER_DIM_HISTORY
		--SELECT WDH.ID_WORKER_DIM_HISTORY, WDH.ID_WORKER_DIM_SUPERVISOR, WDHS.ID_WORKER_DIM [ID_WORKER_DIM_HISTORY_SUPERVISOR]
		FROM dbo.WORKER_DIM_HISTORY WDH
		INNER JOIN dbo.WORKER_DIM_HISTORY WDHS ON
			WDHS.ID_WORKER_DIM = WDH.ID_WORKER_DIM_SUPERVISOR;
	END

	ELSE
	BEGIN
		;WITH WorkerChanges AS (
		SELECT TOP 100 PERCENT
			LWDH.ID_WORKER_DIM
			,MR.ID_PRSN
			,LWDH.ID_RMTS_GROUP_COORD
			,IIF(WDH.ID_RMTS_GROUP_COORD != LWDH.ID_RMTS_GROUP_COORD
					OR (WDH.ID_RMTS_GROUP_COORD IS NULL AND LWDH.ID_RMTS_GROUP_COORD IS NOT NULL)
					OR (WDH.ID_RMTS_GROUP_COORD IS NOT NULL AND LWDH.ID_RMTS_GROUP_COORD IS NULL)
				, 1, 0
			) [Change_ID_RMTS_GROUP_COORD]
			,LWDH.ID_LOCATION_DIM_WORKER
			,IIF(WDH.ID_LOCATION_DIM_WORKER != LWDH.ID_LOCATION_DIM_WORKER
					OR (WDH.ID_LOCATION_DIM_WORKER IS NULL AND LWDH.ID_LOCATION_DIM_WORKER IS NOT NULL)
					OR (WDH.ID_LOCATION_DIM_WORKER IS NOT NULL AND LWDH.ID_LOCATION_DIM_WORKER IS NULL)
				, 1, 0
			) [Change_ID_LOCATION_DIM_WORKER]
			,LWDH.ID_PRSN_SPRV
			,IIF(WDH.ID_PRSN_SPRV != LWDH.ID_PRSN_SPRV
					OR (WDH.ID_PRSN_SPRV IS NULL AND LWDH.ID_PRSN_SPRV IS NOT NULL)
					OR (WDH.ID_PRSN_SPRV IS NOT NULL AND LWDH.ID_PRSN_SPRV IS NULL)
				, 1, 0
			) [Change_ID_PRSN_SPRV]
			,LWDH.ID_WORKER_DIM_SUPERVISOR
			,IIF(WDH.ID_WORKER_DIM_SUPERVISOR != LWDH.ID_WORKER_DIM_SUPERVISOR
					OR (WDH.ID_WORKER_DIM_SUPERVISOR IS NULL AND LWDH.ID_WORKER_DIM_SUPERVISOR IS NOT NULL)
					OR (WDH.ID_WORKER_DIM_SUPERVISOR IS NOT NULL AND LWDH.ID_WORKER_DIM_SUPERVISOR IS NULL)
				, 1, 0
			) [Change_ID_WORKER_DIM_SUPERVISOR]
			,LWDH.CD_JOB_CLS
			,IIF(WDH.CD_JOB_CLS != LWDH.CD_JOB_CLS
					OR (WDH.CD_JOB_CLS IS NULL AND LWDH.CD_JOB_CLS IS NOT NULL)
					OR (WDH.CD_JOB_CLS IS NOT NULL AND LWDH.CD_JOB_CLS IS NULL)
				, 1, 0
			) [Change_CD_JOB_CLS]
			,LWDH.TX_JOB_CLS
			,IIF(WDH.TX_JOB_CLS != LWDH.TX_JOB_CLS
					OR (WDH.TX_JOB_CLS IS NULL AND LWDH.TX_JOB_CLS IS NOT NULL)
					OR (WDH.TX_JOB_CLS IS NOT NULL AND LWDH.TX_JOB_CLS IS NULL)
				, 1, 0
			) [Change_TX_JOB_CLS]
			,LWDH.CD_RMTS_WRKR_TYP
			,IIF(WDH.CD_RMTS_WRKR_TYP != LWDH.CD_RMTS_WRKR_TYP
					OR (WDH.CD_RMTS_WRKR_TYP IS NULL AND LWDH.CD_RMTS_WRKR_TYP IS NOT NULL)
					OR (WDH.CD_RMTS_WRKR_TYP IS NOT NULL AND LWDH.CD_RMTS_WRKR_TYP IS NULL)
				, 1, 0
			) [Change_CD_RMTS_WRKR_TYP]
			,LWDH.TX_RMTS_WRKR_TYP
			,IIF(WDH.TX_RMTS_WRKR_TYP != LWDH.TX_RMTS_WRKR_TYP
					OR (WDH.TX_RMTS_WRKR_TYP IS NULL AND LWDH.TX_RMTS_WRKR_TYP IS NOT NULL)
					OR (WDH.TX_RMTS_WRKR_TYP IS NOT NULL AND LWDH.TX_RMTS_WRKR_TYP IS NULL)
				, 1, 0
			) [Change_TX_RMTS_WRKR_TYP]
			,LWDH.CD_STAT
			,IIF(WDH.CD_STAT != LWDH.CD_STAT
					OR (WDH.CD_STAT IS NULL AND LWDH.CD_STAT IS NOT NULL)
					OR (WDH.CD_STAT IS NOT NULL AND LWDH.CD_STAT IS NULL)
				, 1, 0
			) [Change_CD_STAT]
			,LWDH.TX_STAT
			,IIF(WDH.TX_STAT != LWDH.TX_STAT
					OR (WDH.TX_STAT IS NULL AND LWDH.TX_STAT IS NOT NULL)
					OR (WDH.TX_STAT IS NOT NULL AND LWDH.TX_STAT IS NULL)
				, 1, 0
			) [Change_TX_STAT]
			,LWDH.CD_UNT
			,IIF(WDH.CD_UNT != LWDH.CD_UNT
					OR (WDH.CD_UNT IS NULL AND LWDH.CD_UNT IS NOT NULL)
					OR (WDH.CD_UNT IS NOT NULL AND LWDH.CD_UNT IS NULL)
				, 1, 0
			) [Change_CD_UNT]
			,LWDH.QT_WRK_MEASURE
			,IIF(WDH.QT_WRK_MEASURE != LWDH.QT_WRK_MEASURE
					OR (WDH.QT_WRK_MEASURE IS NULL AND LWDH.QT_WRK_MEASURE IS NOT NULL)
					OR (WDH.QT_WRK_MEASURE IS NOT NULL AND LWDH.QT_WRK_MEASURE IS NULL)
				, 1, 0
			) [Change_QT_WRK_MEASURE]
			,LWDH.DT_BRTH
			,IIF(WDH.DT_BRTH != LWDH.DT_BRTH
					OR (WDH.DT_BRTH IS NULL AND LWDH.DT_BRTH IS NOT NULL)
					OR (WDH.DT_BRTH IS NOT NULL AND LWDH.DT_BRTH IS NULL)
				, 1, 0
			) [Change_DT_BRTH]
			,LWDH.DT_START
			,IIF(WDH.DT_START != LWDH.DT_START
					OR (WDH.DT_START IS NULL AND LWDH.DT_START IS NOT NULL)
					OR (WDH.DT_START IS NOT NULL AND LWDH.DT_START IS NULL)
				, 1, 0
			) [Change_DT_START]
			,LWDH.DT_END
			,IIF(WDH.DT_END != LWDH.DT_END
					OR (WDH.DT_END IS NULL AND LWDH.DT_END IS NOT NULL)
					OR (WDH.DT_END IS NOT NULL AND LWDH.DT_END IS NULL)
				, 1, 0
			) [Change_DT_END]
			,LWDH.DT_ROW_BEGIN
			,LWDH.DT_ROW_END
			,LWDH.ID_CYCLE
			,LWDH.IS_CURRENT
			,LWDH.LOAD_DATE
			,WDH.ID_CYCLE [ID_CYCLE_PREV]
		FROM (
			SELECT
				WDH.ID_PRSN
				,MAX(WDH.ID_WORKER_DIM) [Max_ID_WORKER_DIM]
				,MAX(WDH.ID_WORKER_DIM_HISTORY) [Max_ID_WORKER_DIM_HISTORY]
			FROM dbo.WORKER_DIM_HISTORY WDH
			GROUP BY WDH.ID_PRSN
		) MR
		INNER JOIN dbo.WORKER_DIM_HISTORY WDH ON
			WDH.ID_WORKER_DIM_HISTORY = MR.Max_ID_WORKER_DIM_HISTORY
		INNER JOIN loading.WORKER_DIM_HISTORY LWDH ON
			LWDH.ID_WORKER_DIM = WDH.ID_WORKER_DIM
		)

		INSERT dbo.WORKER_DIM_HISTORY
			(ID_WORKER_DIM, ID_PRSN, ID_PRSN_SPRV, ID_RMTS_GROUP_COORD, ID_LOCATION_DIM_WORKER, ID_WORKER_DIM_SUPERVISOR, CD_JOB_CLS, TX_JOB_CLS,
			CD_RMTS_WRKR_TYP, TX_RMTS_WRKR_TYP, CD_STAT, TX_STAT, CD_UNT, QT_WRK_MEASURE, DT_BRTH, DT_END, DT_START, DT_ROW_BEGIN, DT_ROW_END,
			ID_CYCLE, IS_CURRENT, LOAD_DATE)
		SELECT
			WC.ID_WORKER_DIM
			,WC.ID_PRSN
			,WC.ID_PRSN_SPRV
			,WC.ID_RMTS_GROUP_COORD
			,WC.ID_LOCATION_DIM_WORKER
			,WC.ID_WORKER_DIM_SUPERVISOR
			,WC.CD_JOB_CLS
			,WC.TX_JOB_CLS
			,WC.CD_RMTS_WRKR_TYP
			,WC.TX_RMTS_WRKR_TYP
			,WC.CD_STAT
			,WC.TX_STAT
			,WC.CD_UNT
			,WC.QT_WRK_MEASURE
			,WC.DT_BRTH
			,WC.DT_END
			,WC.DT_START
			,WC.DT_ROW_BEGIN
			,WC.DT_ROW_END
			,WC.ID_CYCLE
			,WC.IS_CURRENT
			,WC.LOAD_DATE
		FROM WorkerChanges WC
		WHERE 1 IN (
			WC.Change_ID_LOCATION_DIM_WORKER
			,WC.Change_ID_RMTS_GROUP_COORD
			,WC.Change_ID_PRSN_SPRV
			,WC.Change_ID_WORKER_DIM_SUPERVISOR
			,WC.Change_CD_JOB_CLS
			,WC.Change_TX_JOB_CLS
			,WC.Change_CD_RMTS_WRKR_TYP
			,WC.Change_TX_RMTS_WRKR_TYP
			,WC.Change_CD_STAT
			,WC.Change_TX_STAT
			,WC.Change_CD_UNT
			,WC.Change_QT_WRK_MEASURE
			,WC.Change_DT_BRTH
			,WC.Change_DT_START
			,WC.Change_DT_END
		);

		--SELECT * FROM dbo.WORKER_DIM_HISTORY WDH INNER JOIN loading.WORKER_DIM_HISTORY LWDH ON LWDH.ID_WORKER_DIM = WDH.ID_WORKER_DIM AND (LWDH.DT_ROW_BEGIN != WDH.DT_ROW_BEGIN OR LWDH.DT_ROW_END != WDH.DT_ROW_END OR LWDH.ID_CYCLE != WDH.ID_CYCLE OR LWDH.IS_CURRENT != WDH.IS_CURRENT);

		DECLARE @LoadDate INT = (SELECT MAX(LOAD_DATE) FROM loading.WORKER_DIM_HISTORY);
		
		--DECLARE @LoadDate INT = (SELECT MAX(LOAD_DATE) FROM loading.WORKER_DIM_HISTORY);
		UPDATE WDH
		SET DT_ROW_END = DATEADD(MILLISECOND, -3, STUFF(STUFF(CONVERT(VARCHAR, @LoadDate), 7, 0, '/'), 5, 0, '/'))
		/*DECLARE @LoadDate INT = (SELECT MAX(LOAD_DATE) FROM loading.WORKER_DIM_HISTORY);
		SELECT WDH.ID_WORKER_DIM_HISTORY, WDH.ID_WORKER_DIM, WDH.DT_ROW_END, WDHN.ID_WORKER_DIM_HISTORY, DATEADD(MILLISECOND, -3, STUFF(STUFF(CONVERT(VARCHAR, @LoadDate), 7, 0, '/'), 5, 0, '/')) [NEW_DT_ROW_END], WDH.LOAD_DATE--*/
		FROM dbo.WORKER_DIM_HISTORY WDH
		INNER JOIN dbo.WORKER_DIM_HISTORY WDHN ON
			WDHN.ID_WORKER_DIM = WDH.ID_WORKER_DIM
				AND WDHN.LOAD_DATE = @LoadDate
		WHERE WDH.LOAD_DATE != @LoadDate;

		--DECLARE @LoadDate INT = (SELECT MAX(LOAD_DATE) FROM loading.WORKER_DIM_HISTORY);
		UPDATE dbo.WORKER_DIM_HISTORY
		SET DT_ROW_BEGIN = CONVERT(DATETIME, STUFF(STUFF(CONVERT(VARCHAR, @LoadDate), 7, 0, '/'), 5, 0, '/'))
		/*DECLARE @LoadDate INT = (SELECT MAX(LOAD_DATE) FROM loading.WORKER_DIM_HISTORY);
		SELECT *, CONVERT(DATETIME, STUFF(STUFF(CONVERT(VARCHAR, @LoadDate), 7, 0, '/'), 5, 0, '/')) [NEW_DT_ROW_BEGIN] FROM dbo.WORKER_DIM_HISTORY--*/
		WHERE LOAD_DATE = @LoadDate;

		INSERT dbo.WORKER_DIM_HISTORY
			(ID_WORKER_DIM, ID_PRSN, ID_PRSN_SPRV, ID_RMTS_GROUP_COORD, ID_LOCATION_DIM_WORKER, ID_WORKER_DIM_SUPERVISOR, CD_JOB_CLS, TX_JOB_CLS,
			CD_RMTS_WRKR_TYP, TX_RMTS_WRKR_TYP, CD_STAT, TX_STAT, CD_UNT, QT_WRK_MEASURE, DT_BRTH, DT_END, DT_START, DT_ROW_BEGIN, DT_ROW_END,
			ID_CYCLE, IS_CURRENT, LOAD_DATE)
		SELECT
			LWDH.ID_WORKER_DIM
			,LWDH.ID_PRSN
			,LWDH.ID_PRSN_SPRV
			,LWDH.ID_RMTS_GROUP_COORD
			,LWDH.ID_LOCATION_DIM_WORKER
			,LWDH.ID_WORKER_DIM_SUPERVISOR
			,LWDH.CD_JOB_CLS
			,LWDH.TX_JOB_CLS
			,LWDH.CD_RMTS_WRKR_TYP
			,LWDH.TX_RMTS_WRKR_TYP
			,LWDH.CD_STAT
			,LWDH.TX_STAT
			,LWDH.CD_UNT
			,LWDH.QT_WRK_MEASURE
			,LWDH.DT_BRTH
			,LWDH.DT_END
			,LWDH.DT_START
			,LWDH.DT_ROW_BEGIN
			,LWDH.DT_ROW_END
			,LWDH.ID_CYCLE
			,LWDH.IS_CURRENT
			,LWDH.LOAD_DATE
		FROM loading.WORKER_DIM_HISTORY LWDH
		WHERE NOT EXISTS (
			SELECT WDH.ID_WORKER_DIM_HISTORY
			FROM dbo.WORKER_DIM_HISTORY WDH
			WHERE WDH.ID_WORKER_DIM = LWDH.ID_WORKER_DIM
		);

		--DECLARE @LoadDate INT = (SELECT MAX(LOAD_DATE) FROM loading.WORKER_DIM_HISTORY);
		UPDATE WDH
		SET DT_ROW_END = DATEADD(MILLISECOND, -3, WDHN.Min_DT_ROW_BEGIN)
			,IS_CURRENT = 0
		/*DECLARE @LoadDate INT = (SELECT MAX(LOAD_DATE) FROM loading.WORKER_DIM_HISTORY);
		SELECT WDH.ID_WORKER_DIM, WDH.DT_ROW_END, DATEADD(MILLISECOND, -3, WDHN.Min_DT_ROW_BEGIN) [NEW_DT_ROW_END]--*/
		FROM dbo.WORKER_DIM_HISTORY WDH
		INNER JOIN (
			--DECLARE @LoadDate INT = (SELECT MAX(LOAD_DATE) FROM loading.WORKER_DIM_HISTORY);
			SELECT
				ID_PRSN
				,MIN(DT_ROW_BEGIN) [Min_DT_ROW_BEGIN]
			FROM dbo.WORKER_DIM_HISTORY
			WHERE LOAD_DATE = @LoadDate
			GROUP BY ID_PRSN
		) WDHN ON
			WDHN.ID_PRSN = WDH.ID_PRSN
		WHERE WDH.LOAD_DATE != @LoadDate
			AND WDH.DT_ROW_END = '12/31/9999'

		--DECLARE @LoadDate INT = (SELECT MAX(LOAD_DATE) FROM loading.WORKER_DIM_HISTORY);
		UPDATE WDH
		SET ID_WORKER_DIM_HISTORY_SUPERVISOR = WDHS.ID_WORKER_DIM_HISTORY_SUPERVISOR
		/*DECLARE @LoadDate INT = (SELECT MAX(LOAD_DATE) FROM loading.WORKER_DIM_HISTORY);
		SELECT WDH.ID_WORKER_DIM_HISTORY, WDH.ID_WORKER_DIM, WDH.ID_WORKER_DIM_SUPERVISOR, WDHS.ID_WORKER_DIM_HISTORY_SUPERVISOR--*/
		FROM dbo.WORKER_DIM_HISTORY WDH
		INNER JOIN (
			SELECT
				ID_WORKER_DIM
				,MAX(ID_WORKER_DIM_HISTORY) [ID_WORKER_DIM_HISTORY_SUPERVISOR]
			FROM dbo.WORKER_DIM_HISTORY
			GROUP BY ID_WORKER_DIM
		) WDHS ON
			WDHS.ID_WORKER_DIM = WDH.ID_WORKER_DIM_SUPERVISOR
		WHERE WDH.ID_WORKER_DIM_HISTORY_SUPERVISOR IS NULL
			AND WDH.LOAD_DATE = @LoadDate
	END
END
